### ISSUE TITLE
Pod install Error

### ISSUE THREAD

**Issue by kansaraprateek** [highcharts/highcharts-ios#1]
I am trying to install highcharts within my iOS app using cocoapods and I am getting this error. 

"Unable to find a specification for 'HighCharts' "

Have you pushed the code version to pod trunk??

**Comment by ratka6** [comment]
Would you mind checking again?

**Comment by kansaraprateek** [comment]
@ratka6  : Still not working. Same error

**Comment by ratka6** [comment]
Please paste me your podfile

**Comment by kansaraprateek** [comment]
There is no issue with the pod file, since only this pod was not installing. I just checked you have update the pod name from 'HighCharts' to 'Highcharts'. 
It's working now. Thanks!
