### ISSUE TITLE
API / Documentation problems

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-ios#10]
1. On top / initial level of API options the `series` is doubled and clicking any of them opens the first one.
http://api.highcharts.com/highcharts-ios/

2. In than option none of the series types are possible to open - e.g. http://api.highcharts.com/highcharts-ios/series%3Carea%3E, or you could try opening any of the series types in here: http://api.highcharts.com/highcharts-ios/series

**Comment by ratka6** [comment]
Thanks, I will report that bug.

**Comment by ihnatmoisieiev** [comment]
@KacperMadej, it is fixed. 
[https://api.highcharts.com/ios/](https://api.highcharts.com/ios/)

**Comment by ihnatmoisieiev** [comment]
@KacperMadej can I close this issue?

**Comment by KacperMadej** [comment]
@ihnatmoisieiev Yes.

(I can do it too, but didn't want to create to much chaos - you can add "close if resolved" or something like that next time in a comment and I will close if you want.)
