### ISSUE TITLE
Want to get tap event on bar chart in iOS 

### ISSUE THREAD

**Issue by tripathishivam35** [highcharts/highcharts-ios#100]
related with #44 
I tried to use this provided code 
[HIFunction * function = [[HIFunction alloc] initWithClosure:^(HIChartContext *context) {
        NSLog(@"Y value: %@", [context getProperty:@"y"]);
        NSLog(@"Index: %@", [context getProperty:@"index"]);
        NSLog(@"Category: %@", [context getProperty:@"category"]);
} properties:@[@"y", @"index", @"category"]];
point.events.click = function;]

But Xcode throwing error that no function available with this name. Is thing got changed or Updated?

**Comment by ihnatmoisieiev** [comment]
@tripathishivam35 no, nothing changed. Do you use the latest version?

Your code doesn't compile for me. This function works:

```
HIFunction *function = [[HIFunction alloc] initWithClosure:^(HIChartContext *context) {
        NSLog(@"Y value: %@", [context getProperty:@"y"]);
        NSLog(@"Index: %@", [context getProperty:@"index"]);
        NSLog(@"Category: %@", [context getProperty:@"category"]);
    } properties:@[@"y", @"index", @"category"]];
```

**Comment by tripathishivam35** [comment]
@ihnatmoisieiev Thanks for helping out.
It was the pods issue. i was using older version(6.0.2). I updated to new one(6.1.0). Its resolved now.

Could U add that how to add Gesture Recognizer to HighChartView. 
I am normally able to add gesture Recognizer to ParentView(UIView). When I add to HighChartView , control didn't move to selector function.

    UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self
                                                                          action:@selector(gestureHandlerMethod:)];
    [self.ReshipPieChart addGestureRecognizer:tap];
   where  ReshipPieChart is HighChartView.


-(void)gestureHandlerMethod:(UITapGestureRecognizer*)sender {
  
            HIFunction *function = [[HIFunction alloc] initWithClosure:^(HIChartContext *context) {
                NSLog(@"Y value: %@", [context getProperty:@"y"]);
                NSLog(@"Index: %@", [context getProperty:@"index"]);
                NSLog(@"Category: %@", [context getProperty:@"category"]);
            } properties:@[@"y", @"index", @"category"]];
            HIPoint *point = [[HIPoint alloc]init];
            point.events.click = function;
    }

**Comment by ihnatmoisieiev** [comment]
@tripathishivam35 you don't need adding a gesture recognizer to HighChartView. If you want to get tap event on point, add above function as a click event to point object in plotOptions, e.g.

```
HIPlotOptions *plotOptions = [[HIPlotOptions alloc] init];
plotOptions.series = [[HISeries alloc] init];
plotOptions.series.point = [[HIPoint alloc] init];
plotOptions.series.point.events = [[HIEvents alloc] init];
plotOptions.series.point.events.click = function;
options.plotOptions = plotOptions;
```

**Comment by tripathishivam35** [comment]
Great.. Thanks for sharing your knowledge.

**Comment by chandanvarma009** [comment]
@tripathishivam35 Bro can you plz share how can you add detect a tap event in my view controller?

**Comment by tripathishivam35** [comment]
@chandanvarma009 If u are talking about HighChart .  Then above mentioned comments are proper and with the help of that U can detect tap event. Let me know if there is any issue u are facing.

**Comment by chandanvarma009** [comment]
Yes man, I am implementing highchart wordcloud and want to detect the word which i tapped, currently it shows the occurances of the word. I just want the word on which i tapped.

I followed this example : https://www.highcharts.com/ios/demo/wordcloud

**Comment by sebastianbochan** [comment]
Hi @chandanvarma009,
Let's talk about your issue here: https://github.com/highcharts/highcharts-ios/issues/103#issuecomment-397552415, as a result we will keep all in one place, instead of mixing.

**Comment by barotbhavesh** [comment]
Hello Boss,
I am using Highcharts 
**@IBOutlet weak var viewChart      : HIChartView!**
i want to tab in my chart 

**let chart = HIChart()
 chart.type = "column"**

**HIPlotOptions *plotOptions = [[HIPlotOptions alloc] init];
plotOptions.series = [[HISeries alloc] init];
plotOptions.series.point = [[HIPoint alloc] init];
plotOptions.series.point.events = [[HIEvents alloc] init];
plotOptions.series.point.events.click = function;
options.plotOptions = plotOptions;**

or also 

**UITapGestureRecognizer**

not working for me please help me how to get **Tap** in my chart

Thank you so much for help in advance
