### ISSUE TITLE
HighCharts graph loading time issue in iOS

### ISSUE THREAD

**Issue by vnanaware** [highcharts/highcharts-ios#101]
HighChart takes more time to display graph. I display spinner for loading and stoped in below delegate method.

 func chartViewDidLoad(_ chart: HIChartView!)
    {
        dismissSpinner()
    }

Even controller comes in this method loader will stop, then also it takes few time to load graph. 
is there any solution?

**Comment by ihnatmoisieiev** [comment]
Hi @vnanaware,
I've checked it and for me it works perfectly. 
Did you set up `HIChartViewDelegate` for your view controller? (`chartView.delegate = self`)
Did you add your spinner to `HIChartView` and hide it in the delegate method?

**Comment by vnanaware** [comment]
yes I have added HIChartViewDelegate
Also added spinner, and stopped spinner in 
chartViewDidLoad delegate.  It occures only at first time graph loading, second time works fine.

**Comment by ihnatmoisieiev** [comment]
![spinner](https://user-images.githubusercontent.com/11294008/40961056-c25e022a-68a1-11e8-92c9-150a5ff681d8.gif)

This is first time graph loading.

**Comment by vnanaware** [comment]
let yaxis=HIYAxis()
yaxis.labels.formatter=HIFunction.init(jsFunction:"function() { if (this.value / 10000000) return this.value / 10000000 + 'Cr'; else if (this.value / 100000) return this.value / 100000 + 'Lac'; else if (this.value / 1000) return this.value / 1000 + 'K'; }")

is it correct above function.  Still facing for this issue.

**Comment by ihnatmoisieiev** [comment]
@vnanaware it is not connecting with this issue.

**Comment by vnanaware** [comment]
yes

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev i face this issue for the first time loading alone. I load 2 charts with say Chart1 with 4 series and Chart2 with 2 series. Between chart construction completion and chart loading, I get a wait time of 35 to 45 seconds. It is usually 38 seconds. Once the chart is loaded, the app becomes unresponsive too, though not every time the app becomes unresponsive. 
For the same chart values, the wait time between chart construction complete and chart loading is 0 to few milliseconds. Can you please suggest me a solution for this?
I am testing on Simulator - 12.1 OS

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi send me please options for your charts. When does it appear? Are you using a `UITableView`? Do you have some dome?

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev Sorry, I don't have a demo project. But here is my sample code (ViewController class), which is also taking more than 40seconds to load the charts. 
UITableView - YES. I have used few table views in my real project, but the below sample code project did not use any table views.
The slowness appear only when the chart is loaded for the first time. After one or more selection in the uitableviews, I reload the chart with a new data set, which happens within 3 to 5 seconds.


    import UIKit
    import Highcharts

    class ViewController: UIViewController {  

    @IBOutlet weak var chart_1: HIChartView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        print("~~~~~~~~~~~~~~~~~~~\(Date())-View did load")
        fnRefreshCharts()
    }
    
    func fnRefreshCharts() {
        print("~~~~~~~~~~~~~~~~~~~\(Date())-inside fnrefreshcharts")
        let labels_x = HILabels()
        labels_x.rotation = 270
        labels_x.step = 2
        labels_x.y = 8
        labels_x.x = 0
        
        //Define x axis label style
        let label_x_Style = HIStyle()
        label_x_Style.fontWeight = "bold"
        label_x_Style.fontSize = GetDeviceSize.shared.xAxis_Label_Font_size
        label_x_Style.fontFamily = "Arial"
        label_x_Style.color = "black"
        labels_x.style = label_x_Style
        
        let xAxis_Crosshair = HICrosshair()
        
        let xAxis = HIXAxis()
        let dateToDisplay = ["Sun", "Mon", "Tue", "Wed", "Thu"]
        xAxis.categories = dateToDisplay
        xAxis.alignTicks = true
        xAxis.tickmarkPlacement = "off"
        xAxis.startOnTick = true
        xAxis.endOnTick = true
        xAxis.showLastLabel = true
        xAxis.labels = labels_x
        xAxis.crosshair = xAxis_Crosshair
        
        let labels_y = HILabels()
        labels_y.enabled = false
        
        let title_y = HITitle()
        title_y.text = EMPTY_STRING
        
        let yAxis = HIYAxis()
        yAxis.labels = labels_y
        yAxis.title = title_y
        yAxis.gridLineDashStyle = "dash"
        yAxis.gridLineWidth = 0.5
        yAxis.gridLineColor = HIColor(hexValue: "d9d9d9")
        let tickPosition = "function () { var positions = []; var maxtick, mintick; " +
            "if (this.dataMax < 1) { maxtick = (this.dataMax + this.dataMax * 0.25); mintick = (this.dataMin - this.dataMin * 0.15); }" +
            "else { maxtick = Math.ceil(this.dataMax + this.dataMax * 0.25); mintick = (this.dataMin - this.dataMin * 0.15); }" +
            "if (mintick < 0) { mintick = mintick; } " + "increment = (maxtick - mintick) / 5.0; " +
            "if (increment == 0) { positions.push(0); positions.push(maxtick); }" +
            "else if (this.maxtick !== null && this.mintick !== null) { " +
            "for (mintick; mintick <= maxtick; mintick += increment) { positions.push(mintick); }" +
        "positions.push(maxtick); } return positions; }"
        
        yAxis.tickPositioner = HIFunction(jsFunction: tickPosition)
        
        let plotlines = self.PlotLines([0,2,4], ["Sun", "Tue", "Thu"])
        
        let titleStyle = HIStyle()
        titleStyle.position = "absolute"
        titleStyle.color = "navy"
        titleStyle.fontFamily = "Lucida Sans"
        titleStyle.fontSize = "10px"
        titleStyle.fontWeight = "bold"
        
        let dataLabel = HIDataLabels()
        dataLabel.rotation = 270
        dataLabel.align = "center"
        dataLabel.y = -20
        dataLabel.overflow = false
        dataLabel.allowOverlap = true
        dataLabel.crop = false
        dataLabel.enabled = true
        dataLabel.useHTML = true
        dataLabel.color = HIColor(hexValue: "000")
        
        let dataLabelStyle = HIStyle()
        dataLabelStyle.fontSize = "9px"
        dataLabelStyle.fontFamily = "Helvetica"
        dataLabelStyle.fontWeight = "semibold"
        
        dataLabel.style = dataLabelStyle
        
        let options1 = HIOptions()
        let line11 = HILine()
        line11.data = [2342,2423,4364,3453,5677,3456,6768,1234,5645]
        line11.name = "Data"
        line11.allowPointSelect = true
        line11.showInLegend = true
        line11.dataLabels = dataLabel
        
        let line12 = HILine()
        line12.data = []
        line12.name = "Avg"
        line12.showInLegend = true
        
        let chart1 = HIChart()
        let title1 = HITitle()
        
        title1.text = "Main1"
        title1.align = "center"
        title1.useHTML = true
        title1.style = titleStyle
        
        let _jsFunc = "function() { if (this.y < 10) {return '<span>' + Highcharts.numberFormat(this.y, 2) + '</span>';} else if (this.y < 100) {return '<span>' + Highcharts.numberFormat(this.y, 1) + '</span>';} else if (this.y > 999) {return '<span>' + Highcharts.numberFormat(this.y, 0, ',', ',') + '</span>';} else {return '<span>' + this.y + '</span>'}}"
        let _labelFormatter = HIFunction(jsFunction: _jsFunc)
        dataLabel.formatter = _labelFormatter
        
        let legend = HILegend()
        legend.align = "right"
        legend.layout = "horizontal"
        legend.itemMarginTop = -12
        legend.itemDistance = 7
        legend.itemMarginBottom = -15
        legend.symbolPadding = 2
        legend.verticalAlign = "bottom"
        legend.enabled = true
        
        let legend_ItemStyle = HIItemStyle()
        legend_ItemStyle.color = "404040"
        legend_ItemStyle.fontSize = "0.7em"
        legend.itemStyle = legend_ItemStyle
        
        let toolTip = HITooltip()
        toolTip.enabled = true
        toolTip.useHTML = true
        toolTip.formatter = HIFunction(jsFunction: "function() {return false;}")
        toolTip.shared = true
        
        let x_0_PlotLines = HIPlotLines()
        x_0_PlotLines.dashStyle = "ShortDash"
        x_0_PlotLines.color = HIColor(hexValue: "c5c8cc")
        x_0_PlotLines.width = 1
        x_0_PlotLines.value = 0
        
        let _exporting = HIExporting()
        _exporting.enabled = false
        
        let chartFunction = HIFunction(closure: { (context) in
            
            let xIndex = context!.getProperty("this.x") as! Int
            options1.tooltip = toolTip
            print(xIndex)
        }, properties: ["this.x"])
        
        let chartFunction1: HIClosure = { context in
            let xValue = context!.getProperty("event.xAxis[0].value") as! Double
            var intValue = Int(xValue)
            let d : Double = xValue - Double(intValue)
            if d > 0.5 {
                intValue += 1
            }
        }
        
        let plotOptions = HIPlotOptions()
        plotOptions.series = HISeries()
        plotOptions.series.point = HIPoint()
        plotOptions.series.point.events = HIEvents()
        plotOptions.series.point.events.click = chartFunction
        
        chart1.events = HIEvents()
        chart1.events.click = HIFunction(closure: chartFunction1, properties: ["event.xAxis[0].value"])
        
        options1.chart = chart1
        options1.title = title1
        options1.xAxis = [xAxis]
        options1.yAxis = [yAxis]
        options1.series = [line11, line12]
        options1.credits.enabled = false
        options1.tooltip = toolTip
        options1.legend = legend
        options1.exporting = _exporting
        options1.plotOptions = plotOptions
        print("~~~~~~~~~~~~~~~~~~~\(Date())-options1 construction complete")
        
        self.chart_1.delegate = self
        self.chart_1.options = options1
        
        print("~~~~~~~~~~~~~~~~~~~\(Date())-show chart views")
        self.chart_1.isHidden = false
    }
    
    func PlotLine(_ index: Int,_ month: String) -> HIPlotLines {
        let plotLine = HIPlotLines()
        plotLine.dashStyle = "ShortDash"
        plotLine.color = HIColor(hexValue: "c5c8cc")
        plotLine.width = 1
        plotLine.value = index as NSNumber
        
        let plotLineLabel = HILabel()
        plotLineLabel.text = month
        plotLineLabel.x = -2
        plotLineLabel.y = -2
        plotLineLabel.verticalAlign = "bottom"
        plotLineLabel.rotation = 270
        
        let plotLineStyle = HIStyle()
        plotLineStyle.fontSize = "10px"
        plotLineStyle.color = "black"
        plotLineStyle.fontFamily = "Helvetica"
        plotLineStyle.fontWeight = "semibold"
        
        plotLineLabel.style = plotLineStyle
        plotLine.label = plotLineLabel
        
        return plotLine
    }
    
    func PlotLines(_ index: Array<Int>,_ day: Array<String>) -> Array<HIPlotLines> {
        var plotLines = Array<HIPlotLines>()
        for i in 0..<index.count {
            plotLines.append(PlotLine(index[i], day[i]))
        }
        return plotLines
    }
    }

    extension ViewController: HIChartViewDelegate {
     func chartViewDidLoad(_ chart: HIChartView!) {
        print("~~~~~~~~~~~~~~~~~~~\(Date())-chart did load")
     }
     }

The response log is 
~~~~~~~~~~~~~~~~~~~2019-01-28 17:19:28 +0000-View did load
~~~~~~~~~~~~~~~~~~~2019-01-28 17:19:28 +0000-inside fnrefreshcharts
~~~~~~~~~~~~~~~~~~~2019-01-28 17:19:28 +0000-options1 construction complete
~~~~~~~~~~~~~~~~~~~2019-01-28 17:19:28 +0000-show chart views
~~~~~~~~~~~~~~~~~~~2019-01-28 17:20:15 +0000-chart did load

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi I have tested your example many times on iPhone 8 (12.1) simulator and had the next worst result:

```
~~~~~~~~~~~~~~~~~~~2019-01-29 08:06:15 +0000-View did load
~~~~~~~~~~~~~~~~~~~2019-01-29 08:06:15 +0000-inside fnrefreshcharts
~~~~~~~~~~~~~~~~~~~2019-01-29 08:06:15 +0000-options1 construction complete
~~~~~~~~~~~~~~~~~~~2019-01-29 08:06:15 +0000-show chart views
~~~~~~~~~~~~~~~~~~~2019-01-29 08:06:16 +0000-chart did load
```

Did you add `HIChartView.preload()` in your AppDelegate method `didFinishLaunchingWithOptions` ?
It speeds up the first time chart loads.

Did you try to run your example on the device?

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev I added HIChartView.preload() in my App Delegate and here is the log for that
The response is similar in 2 difference MacBook Pros simulator 
~~~~~~~~~~~~~~~~~~~2019-01-29 09:01:39 +0000-View did load
~~~~~~~~~~~~~~~~~~~2019-01-29 09:01:39 +0000-inside fnrefreshcharts
~~~~~~~~~~~~~~~~~~~2019-01-29 09:01:39 +0000-options1 construction complete
~~~~~~~~~~~~~~~~~~~2019-01-29 09:01:39 +0000-show chart views
~~~~~~~~~~~~~~~~~~~2019-01-29 09:02:26 +0000-chart did load

However when I run the same example in iPhone 6s, I get the following log

~~~~~~~~~~~~~~~~~~~2019-01-29 11:56:53 +0000-View did load
~~~~~~~~~~~~~~~~~~~2019-01-29 11:56:53 +0000-inside fnrefreshcharts
~~~~~~~~~~~~~~~~~~~2019-01-29 11:56:53 +0000-options1 construction complete
~~~~~~~~~~~~~~~~~~~2019-01-29 11:56:53 +0000-show chart views
~~~~~~~~~~~~~~~~~~~2019-01-29 11:56:54 +0000-chart did load

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi so, I suppose the problem with the simulator.

**Comment by arunavasumathi** [comment]
must be. but it happened with all simulators i tried and even in my other Mac simulators too.

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi try the latest `7.0.2` version.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev 
this is the time log for 7.0.2

~~~~~~~~~~~~~~~~~~~2019-02-04 09:04:12 +0000-View did load
~~~~~~~~~~~~~~~~~~~2019-02-04 09:04:12 +0000-inside fnrefreshcharts
~~~~~~~~~~~~~~~~~~~2019-02-04 09:04:12 +0000-options1 construction complete
~~~~~~~~~~~~~~~~~~~2019-02-04 09:04:12 +0000-show chart views
~~~~~~~~~~~~~~~~~~~2019-02-04 09:05:05 +0000-chart did load

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi so, the problem with your simulators.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev should be. thank you for your support in identifying my problem. 👍
