### ISSUE TITLE
Hide a HIPlotLine when a HISeries is hidden

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#102]
How can I toggle the visibility of a HIPlotLine if I toggle the visibility of a HISeries?

Thanks.

**Comment by skuske** [comment]
I alfready tried something like that:

```
HIEvents *event_series_1 = [[HIEvents alloc] init];
event_series_1.hide = [[HIFunction alloc] initWithJSFunction:@"function () { chart.xAxis[0].removePlotLine('line1'); }"];
series.events=event_series_1;
```

but that does not work. Any working sample would be highly appreciated! :o)

**Comment by skuske** [comment]
Just got it working.

**Comment by skuske** [comment]
I re-open the issue as I still cannot get this done properly. 

What I want to do is this: once the user (de)selects a series from the legend, I want to hide/show a specific HIPlotLine on the Y-Axis. Instead of removing the HIPlotLine from the chart I would like to set its width to 0, which would make it invisible. Next time the series is shown again, the line's width should be set to 1 again.

How can I do that? I tried HIFunctions on show/hide events for a series, but I cannot access the HIPlotLine and modify its width without re-drawing the whole chart. 

Thanks for any help.

**Comment by sebastianbochan** [comment]
@ihnatmoisieiev

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

try to add `legendItemClick` event to your series with this example js function: 
```
this.chart.series[1].visible ? this.chart.series[1].hide() : this.chart.series[1].show();
```
where `1` is the index of your `HIPlotLine`.

**Comment by skuske** [comment]
Hello @ihnatmoisieiev 

no, that hides one of the series, but I want to hide a HIPlotLine once a series is hidden.

**Comment by skuske** [comment]
I tried this, but it does not work:

`function () { if (this.chart.yAxis.plotLines[1].width==0){  this.chart.yAxis.plotLines[1].width=1;} else { this.chart.yAxis.plotLines[1].width=0;} }`

**Comment by skuske** [comment]
@ihnatmoisieiev 

Finally got it working with this:

`function () { if (this.chart.yAxis[0].options.plotLines[0].width==0){  this.chart.yAxis[0].options.plotLines[0].width=1;this.chart.yAxis[0].update();} else { this.chart.yAxis[0].options.plotLines[0].width=0;this.chart.yAxis[0].update();} }`
