### ISSUE TITLE
Can i get a tap event on highchart wordcloud?

### ISSUE THREAD

**Issue by chandanvarma009** [highcharts/highcharts-ios#103]
I tried HIFunction closure but its crashing. Is there any other alternative method so that i can get the word on which i tapped?

Thanks in Advance :)

**Comment by ihnatmoisieiev** [comment]
Hello @chandanvarma009,

can you show a piece of your code with `HIFunction`?

**Comment by chandanvarma009** [comment]
Yes man, I am implementing highchart wordcloud and want to detect the word which i tapped, currently it shows the occurances of the word. I just want the word on which i tapped in my View controller.

I followed this example : https://www.highcharts.com/ios/demo/wordcloud

**Comment by sebastianbochan** [comment]
@chandanvarma009,
Could you paste a code with declaration of `HIFunction`? It will allow us to check your chart's configuration.

**Comment by ihnatmoisieiev** [comment]
@chandanvarma009 did you resolve your question?

**Comment by chandanvarma009** [comment]
No man, I am out of town. Will post the code this Monday.

**Comment by ihnatmoisieiev** [comment]
@chandanvarma009 see:
[https://github.com/highcharts/highcharts-ios/issues/100](https://github.com/highcharts/highcharts-ios/issues/100)
[https://github.com/highcharts/highcharts-ios/issues/44](https://github.com/highcharts/highcharts-ios/issues/44)
[https://github.com/highcharts/highcharts-ios/issues/77](https://github.com/highcharts/highcharts-ios/issues/77)
