### ISSUE TITLE
Highcharts-tooltip-delay

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#104]
I would like to delay the display of tooltips and found this on GitHub:

http://rudovjan.github.io/highcharts-tooltip-delay/

Is there any way I can use that with the iOS wrapper?

Thanks.

**Comment by skuske** [comment]
Anybody? Is it possible to call functions from an external .js file? Thanks.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
there is no way to add an external plugin to the wrapper at the moment.
