### ISSUE TITLE
x-axis issue on iPads

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#105]
We see a pretty strange issue on iPads, mostly with iOS 9, some with iOS 10, but not on iOS 11. On timedate x-axis, on some devices the whole chart is broken, where **exactly the same data** does not cause any trouble on devices with iOS 11 installed, or if running in the Xcode simulator. Also: only iPads seem to be affected, we never got a similar issue reported from iPhones.

![xaxiserror](https://user-images.githubusercontent.com/12996815/42684797-780649ae-8691-11e8-8721-d73c228cd0ed.jpg)

**Important: the series data is exactly the same all the time.** That means that it works on iOS 11, but not on iOS 9 or 10.

Any idea what might be causing this?

The data series is an array of approximately 150 arrays, where the first value is a regular timestamp, and the second value is the Y-axis value.

**Comment by skuske** [comment]
Here's an additional screenshot of a more larger scaled graph showing that all values are actually there, but in one line, and that the x-axis is broken:

![ipad-issue1](https://user-images.githubusercontent.com/12996815/42689840-4edaa956-86a2-11e8-96b8-1f64d3def135.jpg)

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
thank you for your question. I will report it. It could be connected to [https://github.com/highcharts/highcharts-ios/issues/92](https://github.com/highcharts/highcharts-ios/issues/92).

**Comment by skuske** [comment]
@ihnatmoisieiev 

I can also provide the CSV data of the above chart if that helps.

**Comment by ihnatmoisieiev** [comment]
@skuske yes, please paste it there.

**Comment by skuske** [comment]
export
 1531393380
1531393681
1531393982
1531394284
1531394586
1531394888
1531395190
1531395492
1531395792
1531396094
1531396397
1531396699
1531397001
1531397303
1531397605
1531397906
1531398208
1531398510
1531398811
1531399113
1531399415
1531399716
1531400017
1531400319
1531400621
1531400923
1531401225
1531401526
1531401828
1531402130
1531402431
1531402733
1531403036
1531403338
1531403640
1531403942
1531404244
1531404546
1531404848
1531405150
1531405452
1531405754
1531406056
1531406357
1531406659
1531406961
1531407261
1531407563
1531407867
1531408169
1531408470
1531408772
1531409074
1531409376
1531409678
1531409980
1531410282
1531410584
1531410886
1531411188
1531411490
1531411792
1531412095
1531412398
1531412700
1531413002
1531413304
1531413606
1531413908
1531414210
1531414512
1531414814
1531415116
1531415418
1531415721
1531416023
1531416326
1531416628
1531416930
1531417232
1531417534
1531417835
1531418137
1531418439
1531418741
1531419044
1531419345
1531419647
1531419949
1531420251
1531420552
1531420854
1531421157
1531421459
1531421761
1531422063
1531422364
1531422666
1531422968
1531423270
1531423572
1531423874
1531424176
1531424478
1531424779
1531425081
1531425383
1531425685
1531425987
1531426289
1531426591
1531426893
1531427194
1531427496
1531427798
1531428100
1531428402
1531428704
1531429005
1531429307
1531429609
1531429911
1531430212
1531430514
1531430816
1531431118
1531431420
1531431721
1531432023
1531432325
1531432625
1531432927
1531433230
1531433532
1531433833
1531434135
1531434436
1531434738
1531435041
1531435343
1531435643
1531435946
1531436248
1531436549
1531436850
1531437151
1531437454
1531437756
1531438057
1531438359
1531438660
1531438962
1531439264
1531439566
1531439868
1531440169
1531440470
1531440772
1531441074
1531441376
1531441677
1531441978
1531442281
1531442582
1531442883
1531443185
1531443487
1531443788
1531444090
1531444391
1531444693
1531444994
1531445296
1531445598
1531445899
1531446201
1531446503
1531446804
1531447106
1531447408
1531447709
1531448010
1531448312
1531448613
1531448915
1531449216
1531449517
1531449819
1531450120
1531450421
1531450724
1531451025
1531451326
1531451628
1531451929
1531452232
1531452534
1531452835
1531453136
1531453438
1531453739
1531454041
1531454343
1531454644
1531454946
1531455247
1531455549
1531455850
1531456151
1531456453
1531456754
1531457056
1531457356
1531457658
1531457960
1531458262
1531458562
1531458864
1531459166
1531459468
1531459768
1531460069
1531460370
1531460671
1531460973
1531461275
1531461578
1531461879
1531462180
1531462481
1531462782
1531463084
1531463385
1531463687
1531463987
1531464289
1531464592
1531464893
1531465195
1531465497
1531465797
1531466099
1531466402
1531466703
1531467004
1531467306
1531467607
1531467909
1531468210
1531468512
1531468813
1531469115
1531469416
1531469718
1531470019
1531470321
1531470623
1531470925
1531471226
1531471528
1531471830
1531472131
1531472432
1531472734
1531473037
1531473339
1531473639
1531473941
1531474242
1531474544
1531474846
1531475147
1531475449
1531475751
1531476052
1531476354
1531476655
1531476957
1531477258
1531477560
1531477862
1531478163
1531478465
1531478767
1531479068
1531479370
1531479672
1531479973
1531480275
1531480576
1531480877
1531481179
24
24 24,1 24 24,1 24,1 24,1 24,1 24,1 24,1 24,1 24,1 24,1 24,1 24,1 24,1 24,1 24,1 24,2 24,2 24,2 24,2 24,2 24,3 24,3 24,3 24,4 24,5 24,6 24,6 24,7 24,7 24,8 24,8 24,8 24,9 24,9 25 25,1 25,1 25,1 25,1 25,1 25,1 25,1 25,1 25,2 25,2 25,3 25,3 25,4 25,4 25,5 25,5 25,5 25,5 25,5 25,4 25,5 25,4 25,4 25,4 25,4 25,4 25,4 25,4 25,4 25,4 25,4 25,3 25,3 25,3 25,2 25,2 25,1 25,1 25 25 25 24,9 24,9 24,9 24,8 24,8 24,8 24,7 24,7 24,7 24,8 24,8 24,8 24,8 24,8 24,8 24,9 24,8 24,9 24,8 24,8 24,8 24,8 24,7 24,7 24,6 24,6 24,6 24,6 24,6 24,6 24,5 24,5 24,5 24,5 24,5 24,5 24,5 24,6 24,5 24,5 24,5 24,5 24,5 24,5
24,5 24,4 24,3 24,3 24,3 24,3 24,3 24,2 24,2 24,2 24,2 24,1 24,1 24,1 24,1 24,1 24,1
  24
  24
  24
  24
  24
  24
  24
  24
23,9 24 23,9 23,9 23,9 23,9 23,9 23,9 23,9 23,9 23,9 23,9 23,9 23,9 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,8 23,7 23,8 23,7 23,7 23,6 23,5 23,5 23,4 23,4 23,3 23,3 23,2 23,2 23,2 23,1 23,1 23,1 23 23 23 22,9 22,9 22,9 22,9 22,8 22,8 22,8 22,7 22,5 22,4 22,4 22,3 22,3 22,3 22,2 22,2 22,2 22,2 22,3 22,4 22,5 22,6 22,7 22,9 23 23,1 23,2 23,3 23,4 23,5 23,6 23,7 23,7 23,7 23,7 23,8 23,8 23,8 23,8 23,9 23,9 23,9 23,9 23,9 23,9 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24,1 24 24,1 24,1 24,1 24,1 24,1 23,9 23,8 23,8 23,8 23,8 23,8 23,8 23,9 23,9 23,9 23,9 24 24 24,1 24,1 24,2 24,2 24,2 24,3 24,3 24,3 24,3 24,4 24,5 24,6
   24,5

**Comment by skuske** [comment]
@ihnatmoisieiev

Timestamps must be multiplied by 1000.

**Comment by skuske** [comment]
@ihnatmoisieiev

Find the data attached as a zipped CSV file. That's better than the above, I think.

[export.csv.zip](https://github.com/highcharts/highcharts-ios/files/2193344/export.csv.zip)

**Comment by sebastianbochan** [comment]
Hi @skuske,
Are you able to replicate the bug in native Highcharts without wrapper ?

**Comment by skuske** [comment]
@sebastianbochan 

No, we even cannot reproduce that on any of our devices, neither in the Xcode Simulator. However, there are quite a few users of our app reporting the issue.

**Comment by sebastianbochan** [comment]
Hi @skuske,
Please try to gather as much informations as you can and if you will be able to replicate it as live demo, then we will be debug and fix the problem. Unfortunately at this moment we do not have enough informations for debugging.

**Comment by pawelfus** [comment]
I'm just curious: could you show a screenshot how the chart **should** look like?

**Comment by skuske** [comment]
@sebastianbochan 

Hmmm - that will be difficult as what kind of data could I gather beside the series data? I am sure that this issue is iPad related as at the same time the chart works fine on an iPhone with the same data...

**Comment by skuske** [comment]
@pawelfus 

It should look like the screenshot below. Note that the screenshot below shows different data and not the data from above:

![img_3793](https://user-images.githubusercontent.com/12996815/42770361-ebc8893e-8924-11e8-9a57-3d09f341c1fb.jpg)

**Comment by pawelfus** [comment]
Thanks! I am really curious why both screenshots above use exactly the same x-value (`22:31:12.647` - very specific one!). I have access to iPad with iOS v9.3.5, so when you will be able to recreate the issue let me know, I will test it. Are you sure that datasets are exactly the same? As long as x-values are passed as Numbers (timestamps) then this shouldn't be a problem..

**Comment by skuske** [comment]
@pawelfus 

Do you also have an iPad with iOS 10 installed? The issue above appears on iOS 10 and we have actually stopped supporting iOS 9.3.5 due to the WebKit crashes I reported [here](url
https://github.com/highcharts/highcharts-ios/issues/92).

So, if you have an iPad with iOS 10 installed, then you could download our app from the AppStore. I could send you access data so that the app can access real data and the issue might appear on your machine. We do actually  not have an iOS 10 device here, which makes it impossible for us to debug the issue. It works fine in iOS Simulator...

**Comment by pawelfus** [comment]
Unfortunately, real device only with v9.3.5 (no update to v10). The remaining versions I have in iOS Simulator..

**Comment by skuske** [comment]
@pawelfus 

OK, our app no longer supports iOS 9.3.5 due to the issue mentioned in #92 

Anyway - from your point of view: is this more an x-axis issue, or do you have any other idea what might causing this? The x-value as visible on the screenshot is indeed very specific, and I have no idea where it actually comes from. All x-axis values we pass along to Highcharts are correct (as you can see in the CSV data). Maybe this is more a `xaxis.type=@"datetime"` issue

We construct our x-axis like this:

```
HIXAxis *xaxis = [[HIXAxis alloc]init];
xaxis.type=@"datetime";
xaxis.tickmarkPlacement=@"on";
xaxis.tickInterval=@(4 * 3600 * 1000);
xaxis.lineWidth=@0.5;
xaxis.lineColor=[[HIColor alloc]initWithHexValue:@"B0B6BB"];
xaxis.gridLineColor=[[HIColor alloc]initWithHexValue:@"B0B6BB"];
xaxis.showEmpty=[[NSNumber alloc] initWithBool:false];
xaxis.gridLineWidth=@0.5;
xaxis.dateTimeLabelFormats=@"%H:%M";
```

Is there something in there that looks strange in your eyes, or that might be the cause for the issue?

The strangest thing is that the issue only appears on iPads, not sure if limited to iOS 10. It might also appear on iOS 11, but we never received a report from iOS 11 users until now.

**Comment by pawelfus** [comment]
@skuske 

That's a very strange issue. If that would happen **always** on iPad + iOS 10, then I would expect bug in the OS. Your setting for `dateTimeLabelFormats` looks wrong. For me (from JS perspective), it looks like a problem with data, all points (different screenshots) share exactly the same x-value. I see you have in chart's title dates `from` -> `to`. Maybe workaround as `xaxis.min` and `xaxis.max` could help? But if it's problem with data, then it won't change anything.

**Comment by skuske** [comment]
@sebastianbochan 

I do not know which Safari version is bundled with iOS 10. I doubt you can find that out as there's no way to even update Safari exclusively on iOS. Maybe Apple can tell you the exact version of Safari on iOS 10, but I cannot. Sorry.

**Comment by skuske** [comment]
@sebastianbochan 

> Finding the Safari Version Number on an IOS Device
> Because Safari is part of the iOS operating system, its version is the same as the iOS. To see the iOS version currently running on the iPad, iPhone or iPod touch, tap Settings > General > Software Update. For example, if your iPhone is running iOS 11.2.6, it is running Safari 11.

https://www.lifewire.com/check-the-version-number-of-safari-446563

**Comment by skuske** [comment]
@sebastianbochan 

I am just wondering: the Highcharts iOS wrapper is based on Webkit - maybe the version of Webkit is more important that the version of Safari... ???

**Comment by pawelfus** [comment]
@skuske 

Could share your config? All of the options, including data-processing? Does it break when you load for example this dataset: https://www.highcharts.com/demo/line-time-series ?

**Comment by skuske** [comment]
@pawelfus 

Thanks for your reply. :-)

See my options below. Data as CSV see above in a previous reply. The data actually does not matter: the problem is the same with any other data, too, although the data structure is the same. Data is not further processed - it is passed to Highcharts as an array of arrays, exactly as listed as the CSV above:

One measurement array looks like this:

> First element: timestamp in milliseconds
> Second element: Temperature

I cannot test the dataset you mentioned as we do not have an iPad with iOS 10 here - we only get reports from our users about this issue, but we cannot test that here.

Options:

```
    HIOptions *options = [[HIOptions alloc]init];
    HIChart *chart = [[HIChart alloc]init];
    chart.type = @"areaspline";
    chart.spacingBottom=@2;
    chart.spacingTop=@4;
    chart.spacingRight=@0;
    chart.spacingLeft=@0;
    chart.backgroundColor = [[HIColor alloc]initWithRGBA:0 green:0 blue:0 alpha:0.0];
    options.chart = chart;
    options.credits.enabled=@0;
    
    HITitle *title = [[HITitle alloc]init];
    title.text = @"";
    options.title = title;
    
    HIAreaspline *series = [[HIAreaspline alloc]init];
    series.keys=@[@"x", @"y"];
    series.data=arrayModuleMeasurementArrays;
    series.connectNulls=[[NSNumber alloc] initWithBool:true];
    series.lineWidth=@1;
    series.fillOpacity=@0.5;
    options.series = @[series];
      
    HILang *lang = [[HILang alloc]init];
    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
    lang.weekdays=[dateFormatter weekdaySymbols];
    lang.shortWeekdays=[dateFormatter shortWeekdaySymbols];
    
    HIExporting *exporting = [[HIExporting alloc] init];
    exporting.enabled = [[NSNumber alloc] initWithBool:false];
    options.exporting=exporting;
        
    HILegend *legend = [[HILegend alloc] init];
    legend.enabled = [[NSNumber alloc] initWithBool:false];
    options.legend=legend;
    
    HICrosshair *crosshair = [[HICrosshair alloc] init];
    crosshair.width=@0.5;
    crosshair.color=[[HIColor alloc]initWithHexValue:@"2c3e50"];
    crosshair.dashStyle=@"solid";
    
    HIXAxis *xaxis = [[HIXAxis alloc]init];
    xaxis.tickmarkPlacement=@"on";
	xaxis.type=@"datetime";
    xaxis.tickmarkPlacement=@"on";
    xaxis.tickInterval=@(4 * 3600 * 1000);

    NSNumber *numXaxis_min=[[arrayModuleMeasurementArrays firstObject] objectAtIndex:0];
    NSNumber *numXaxis_max=[[arrayModuleMeasurementArrays lastObject] objectAtIndex:0];
    xaxis.min=numXaxis_min;
    xaxis.max=numXaxis_max;
        
    xaxis.lineWidth=@0.5;
    xaxis.lineColor=[[HIColor alloc]initWithHexValue:@"B0B6BB"];
    xaxis.gridLineColor=[[HIColor alloc]initWithHexValue:@"B0B6BB"];
    xaxis.showEmpty=[[NSNumber alloc] initWithBool:false];
    xaxis.gridLineWidth=@0.5;
    xaxis.crosshair=crosshair;
    
    HIDateTimeLabelFormats *dateTimeFormat=[[HIDateTimeLabelFormats alloc] init];
    dateTimeFormat.hour=@"%H:%M";
    dateTimeFormat.day=@"%d.%m.";

    xaxis.dateTimeLabelFormats=dateTimeFormat;
    
    HILabels *labels_x = [[HILabels alloc] init];
    labels_x.style = [[HIStyle alloc] init];
    labels_x.style.fontSize = @"10px"];
    labels_x.style.fontWeight = @"regular";
    labels_x.style.color=@"#2c3e50";
    xaxis.labels = labels_x;
    
    HIYAxis *yaxis = [[HIYAxis alloc]init];
    yaxis.showEmpty=[[NSNumber alloc] initWithBool:false];
    yaxis.gridLineWidth=@0.5;
    yaxis.lineColor=[[HIColor alloc]initWithHexValue:@"B0B6BB"];
    yaxis.gridLineColor=[[HIColor alloc]initWithHexValue:@"B0B6BB"];
    yaxis.crosshair=crosshair;
    yaxis.alternateGridColor=[[HIColor alloc]initWithHexValue:@"F5F5F5"];
            
    HIPlotLines *averageLine = [[HIPlotLines alloc]init];
    averageLine.color = [[HIColor alloc]initWithHexValue:@"2c3e50"];
    averageLine.dashStyle = @"dash";
    averageLine.width = @1;
    averageLine.value = [self AverageValue];
    averageLine.zIndex = @5;
        
    HIPlotLines *maxLine = [[HIPlotLines alloc]init];
    maxLine.color = [[HIColor alloc]initWithHexValue:@"E84D3C"];
    maxLine.dashStyle = @"dash";
    maxLine.width = @1;
    maxLine.value = numMaxInGraph;
    maxLine.zIndex = @5;
        
    HIPlotLines *minLine = [[HIPlotLines alloc]init];
    minLine.color = [[HIColor alloc]initWithHexValue:@"5065A0"];
    minLine.dashStyle = @"dash";
    minLine.width = @1;
    minLine.value = numMinInGraph;
    minLine.zIndex = @5;
    
    HILabel *labelAverage = [[HILabel alloc] init];        
    labelAverage.text=[cellNumberFormatter stringFromNumber:[self AverageValue]];
    labelAverage.style = [[HIStyle alloc] init];
    labelAverage.style.fontSize = [NSString stringWithFormat:@"%ld%@", (long)intLabelSize, @"px"];
    labelAverage.style.fontWeight = @"bold";
    labelAverage.style.color=@"#2c3e50";
    labelAverage.x=@(5);
    averageLine.label=labelAverage;
    
    HILabel *labelMax = [[HILabel alloc] init];
    labelMax.text=[cellNumberFormatter stringFromNumber:numMaxInGraph];
    labelMax.style = [[HIStyle alloc] init];
    labelMax.style.fontSize = [NSString stringWithFormat:@"%ld%@", (long)intLabelSize, @"px"];
    labelMax.style.fontWeight = @"bold";
    labelMax.style.color=@"#2c3e50";
    labelMax.x=@(5);
    maxLine.label=labelMax;
    
    HILabel *labelMin = [[HILabel alloc] init];
    labelMin.text=[cellNumberFormatter stringFromNumber:numMinInGraph];
    labelMin.style = [[HIStyle alloc] init];
    labelMin.style.fontSize = [NSString stringWithFormat:@"%ld%@", (long)intLabelSize, @"px"];
    labelMin.style.fontWeight = @"bold";
    labelMin.style.color=@"#2c3e50";
    labelMin.x=@(5);
    minLine.label=labelMin;
            
    yaxis.plotLines = [NSMutableArray arrayWithObjects:averageLine,maxLine,minLine,nil];
     
    HILabels *labels_y = [[HILabels alloc] init];
    labels_y.style = [[HIStyle alloc] init];
    labels_y.style.fontSize =  @"10px"];
    labels_y.style.fontWeight = @"regular";
    labels_y.style.color=@"#2c3e50";
    yaxis.labels = labels_y;
    
    HITitle *titleYaxis = [[HITitle alloc]init];
    titleYaxis.text=@"";
    
    yaxis.title=titleYaxis;
    
    options.xAxis = [NSMutableArray arrayWithObjects:xaxis, nil];
    options.yAxis = [NSMutableArray arrayWithObjects:yaxis, nil];
        
    HIPlotOptions *plotOptions = [[HIPlotOptions alloc] init];
    plotOptions.series=[[HISeries alloc] init];
    plotOptions.series.animation = [[HIAnimation alloc] init];
    plotOptions.series.animation.duration=@0;

    options.plotOptions=plotOptions;
    
    HIPane *pane = [[HIPane alloc]init];
    pane.size = @"80%";
    options.pane=pane;
    
    HIChartView_MainModule.lang=lang;
    HIChartView_MainModule.options = options;
```

**Comment by skuske** [comment]
On iPads with < iOS 11 we are now using a categorized x-axis with all timestamps converted to readable dates in order to get this working. That works fine.

However, this is just a workaround as the categorized x-axis is not the perfect way to go... We would prefert to offer datetime x-axis on iOS 10 iPads, too, but since that does not work for us, we needed to prepare a quick workaround.

**Comment by pawelfus** [comment]
Thanks for sharing the workaround! And yes, sorry, I'm still forgetting that only your clients can recreate this issue.

Your code looks right, maybe a few things:

- is HIPane necessary in your config? It's a line series ([API](https://api.highcharts.com/highcharts/pane):  `The pane serves as a container for axes and backgrounds for circular gauges and polar charts.`)
- `series.keys=@[@"x", @"y"];` shouldn't be necessary (it's kind of a default setting)
- `series.data=arrayModuleMeasurementArrays;` - can you share how `arrayModuleMeasurementArrays` is created? What's inside? I'm still convinced that either it's data issue, or bug in the webkit. We didn't get any similar report for iOS with Safari (sharing the same webkit engine as native apps, correct me if I'm wrong) so I'm biased toward data error.. CSV you shared doesn't mean the same is passed to the chart.

**Comment by skuske** [comment]
@pawelfus 

Thanks for your reply. As I tried to explain before, the data array looks like this:

It is an array of arrays, and the arrays are like this:

```
First element: timestamp in milliseconds
Second element: Temperature
```

See the CSV data I attached further above.

Example:

```
<__NSArrayM 0x1c4641830>(
<__NSArrayI 0x1c4432f60>(
1533038447000,
26.9
)
,
<__NSArrayI 0x1c4432f80>(
1533038751000,
26.9
)
,
<__NSArrayI 0x1c4432fa0>(
1533039054000,
26.9
)
,
<__NSArrayI 0x1c4432fe0>(
1533039358000,
26.9
)
.
.
.
.
.
)
```

This is the whole array exported to a text file:

[array.txt](https://github.com/highcharts/highcharts-ios/files/2250051/array.txt)

Hope that helps.

I doubt that this is a data issue, as the same data works fine on an iPhone with iOS 10. The issue only appears on iPads, same data, just a different device type. Both iOS 10.

**Comment by pawelfus** [comment]
I'm out of ideas. Everything (except my bullet points above) looks fine. @ihnatmoisieiev - what do you think?

**Comment by skuske** [comment]
@pawelfus 

> I'm out of ideas. Everything (except my bullet points above) looks fine.

I know how that feels. LOL.

I'll change the points you mentioned above, but I doubt that it will make a difference, as it works fine on iPhones.

I just found that the affected iPads are all older devices with a 32bit CPU. Newer ones come with a 64bit CPU. I am pretty sure that the issue is related to the timestamp values, and that something breaks during x-axis generation. The 32bit - 64bit CPUs don't make a difference here, do they?

**Comment by ihnatmoisieiev** [comment]
The data array and chart's config seem to be ok. I suppose it could be a bug in WebKit on old iPads as @skuske writes above (32 bit CPU).

**Comment by pawelfus** [comment]
Of course, following our conversation: https://github.com/highcharts/highcharts-ios/issues/105#issuecomment-405919533 you had this options:

```
HIXAxis *xaxis = [[HIXAxis alloc]init];
xaxis.type=@"datetime";
xaxis.tickmarkPlacement=@"on";
xaxis.tickInterval=@(4 * 3600 * 1000);
xaxis.lineWidth=@0.5;
xaxis.lineColor=[[HIColor alloc]initWithHexValue:@"B0B6BB"];
xaxis.gridLineColor=[[HIColor alloc]initWithHexValue:@"B0B6BB"];
xaxis.showEmpty=[[NSNumber alloc] initWithBool:false];
xaxis.gridLineWidth=@0.5;
xaxis.dateTimeLabelFormats=@"%H:%M";
```
So this part:

```
xaxis.dateTimeLabelFormats=@"%H:%M";
```

Looks wrong :) Later you said have this config:

```
    HIDateTimeLabelFormats *dateTimeFormat=[[HIDateTimeLabelFormats alloc] init];
    dateTimeFormat.hour=@"%H:%M";
    dateTimeFormat.day=@"%d.%m.";

    xaxis.dateTimeLabelFormats=dateTimeFormat;
```
 Which looks correct. I hope we are clear now.

**Comment by skuske** [comment]
@pawelfus 

Uups. Sorry, my mistake. The `.dateTimeLabelFormats` I was using in the production code was correct. Don't know how `xaxis.dateTimeLabelFormats=@"%H:%M";` made it in here...

**Comment by skuske** [comment]
Update on this issue: Heatmaps (even the iOS heatmap sample you provide), do not work at all if x-axis type = datetime. iOS 10 affect only so far.

**Comment by ihnatmoisieiev** [comment]
@skuske can I close it?

**Comment by skuske** [comment]
@ihnatmoisieiev  Yes, sure. :o) Closed.
