### ISSUE TITLE
Unable to remove highCharts watermark and button at top right corner

### ISSUE THREAD

**Issue by karthikShiva1997** [highcharts/highcharts-ios#107]
Hey ! How  do I remove the 'HighCharts' watermark and the menu button on top right corner . Do I have to purchase , to remove them ?

**Comment by ihnatmoisieiev** [comment]
Hi @karthikShiva1997,

see [docs](https://api.highcharts.com/ios/highcharts/) for more info.

You can hide a credits label and exporting button, e.g.

```
let credits = HICredits()
credits.enabled = false
options.credits = credits

let exporting = HIExporting()
exporting.enabled = false
options.exporting = exporting
```

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 can I close this issue?
