### ISSUE TITLE
HIColor 'string' property missing in new release

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#109]
Xcode reports this for the new release of the wrapper:

`Property 'string' not found on object of type 'HIColor *'`

**Comment by ihnatmoisieiev** [comment]
@skuske I don't have this error. Please, write more info. Do you use Cocoapods/Carthage or binary framework? When this error occurs?

**Comment by skuske** [comment]
@ihnatmoisieiev 

No, I don't use Cocoapods/Carthage. I do everything manually. Before updating to the new version of the wrapper, I was using the `HIColor.string` property, but after updating the wrapper, Xcode no longer sees the 'String' property of HIColor. I must now init a HIColor using '`initWithHexValue`'

I cleaned the project, but no luck: '`string`' property is gone.

**Comment by skuske** [comment]
Binary framework used.

**Comment by skuske** [comment]
@ihnatmoisieiev 

![bildschirmfoto 2018-07-23 um 14 53 08](https://user-images.githubusercontent.com/12996815/43077577-2dbe0f0e-8e88-11e8-8d53-c8a46d19439a.png)

**Comment by ihnatmoisieiev** [comment]
@skuske yes, there are some small changes in HIColor. You may use `initWithHexValue ` instead of `string`.

**Comment by skuske** [comment]
No problem. Will do that. However, the changelog should reflect that, as well as the iOS api docs.

**Comment by ihnatmoisieiev** [comment]
The iOS api docs will be updated soon. Thanks for remark.
