### ISSUE TITLE
Problem with datetime line charts

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#11]
Hi,

I'm drawing a line chart, with a datetime xaxis.
I give data for 2 dates : 2017-05-11 and 2017-05-10
Timestamps for these dates are 1494453600 and 1494367200

As you can see on the screenshots, data displayed are really strange:

<img width="597" alt="screen shot 2017-06-21 at 14 51 23" src="https://user-images.githubusercontent.com/726972/27384959-33869652-5691-11e7-8beb-dac5263db02c.png">
<img width="615" alt="screen shot 2017-06-21 at 14 51 15" src="https://user-images.githubusercontent.com/726972/27384958-33815fca-5691-11e7-8935-eff51728ff49.png">

Any idea of what can be wrong with my data or with the chart?

Regards,
Alexandre

**Comment by ratka6** [comment]
Is it possible for you to provide your chart options?

**Comment by AlexandreMinard** [comment]
you need all data and all options?

**Comment by ratka6** [comment]
data is not so important as the chart options - what objects you include, especially chart type

**Comment by AlexandreMinard** [comment]
okay, here is my code so you can see my options:
I made it from this sample: https://www.highcharts.com/ios/demo/spline-irregular-time

`
let chart = HIChart()
        chart.type = "spline"
let xaxis = HIXAxis()
        xaxis.type = "datetime"
        
        let yaxis = HIYAxis()
        yaxis.title = HIYAxisTitle()
        yaxis.title.text = "ventes".localized
        yaxis.min = 0

        let tooltip = HITooltip()
        tooltip.headerFormat = "<b>{series.name}</b><br>";
        tooltip.pointFormat = "{point.x:%e. %b}: {point.y:.2f} m";
        
        let legend = HILegend()
        legend.enabled = false
        
        let plotoptions = HIPlotOptions()
        plotoptions.spline = HIPlotOptionsSpline()
        plotoptions.spline.marker = HIPlotOptionsSplineMarker()
        plotoptions.spline.marker.enabled = true
        plotoptions.spline.showInLegend = true
        
        let exporting = HIExporting()
        exporting.enabled = false
        
        let credits = HICredits()
        credits.enabled = false
        
        let options = HIOptions()
options.series = []

// for loop to fill the series
let data = HISpline()
        options.series.append(data)
// end of for loop

options.chart = chart
        options.credits = credits
        options.exporting = exporting
        options.title = title
        options.subtitle = subtitle
        options.xAxis = [xaxis]
        options.yAxis = [yaxis]
        options.tooltip = tooltip
        options.plotOptions = plotoptions
        options.legend = legend
`

**Comment by ratka6** [comment]
I believe there is a problem with adding data to options. First of all you need to create data structure like this (objc but it's easy to read):
`
HISpline *spline = [[HISpline alloc]init]; //initialize the data object
        spline1.name = @"some name";
        spline1.data = [@1016, //some random data
                        @1016,
                        @1015.9,
                        @1015.5,
                        @1012.3,
                        @1009.5,
                        @1009.6,
                        @1010.2,
                        @1013.1,
                        @1016.9,
                        @1018.2,
                        @1016.7, nil];
`
after that you can add it to options:
`
options.series = [spline];
`
Please let me know if it helped

**Comment by AlexandreMinard** [comment]
Here is how I add data:

```
let s1 = HISpline()
s1.name = "data 1"
s1.data = []

for stats in myArray {
     let d = stats.date
     let val = stats.value

    s1.data.append([Int(d.timeIntervalSince1970*1000), val])
}

options.series.append(s1)

```

**Comment by ratka6** [comment]
It is difficult for me to recreate this bug. Are you sure that options.series isn't an nil object?

**Comment by AlexandreMinard** [comment]
Here is the code to add data on my series:

```
for cpt in 0...1 {
    let s1 = HISpline()
    s1.name = "data 1"
    s1.data = []

    if cpt == 0 {
                    s1.data.append([1494367200000,176.176])
                    s1.data.append([1494453600000,25.25])
                }
                else if cpt == 1 {
                    s1.data.append([1494367200000,1517.17])
                    s1.data.append([1494453600000,111.11])
                }

    options.series.append(s1)
}
```
And here is what I get:

<img width="584" alt="screen shot 2017-06-21 at 20 05 21" src="https://user-images.githubusercontent.com/726972/27399425-0163c902-56bd-11e7-9553-c78b651dbb98.png">
<img width="602" alt="screen shot 2017-06-21 at 20 05 16" src="https://user-images.githubusercontent.com/726972/27399426-016ac95a-56bd-11e7-8205-5373c7da5eb9.png">

**Comment by ratka6** [comment]
I see no problem here - you have exactly what you put in code: Two splines with two points

**Comment by AlexandreMinard** [comment]
really you don't see the problem?
check the tooltip...

9 May for value 176.18 is wrong
and 10 May for value 111.111 is wrong too

the dates (1494367200000 and 1494453600000)are 10 may and 11 may, not 9 and 10 may

and why the string "11 may" not displayed on xaxis?

**Comment by ratka6** [comment]
These are 9th and 10th of May using GMT time - that is currently the only timezone we can use. We are working to add another set of options to adapt to users locale.

**Comment by AlexandreMinard** [comment]
OK I got that.
Hope you'll do that quickly.

Thanks a lot for your support!!!

**Comment by ratka6** [comment]
Thanks for your feedback!

**Comment by AlexandreMinard** [comment]
Due to that, I've another issue now...

In France (yes I'm leaving in France), we are now on GMT+2, that's summer time.
But in winter, we're GMT+1.

I can detect that on iOS, so I can add the corresponding time to my timestamp, but will that work on the charts?

I really need to have the exact date, with time 00:00 and not 01:00

Good luck for that one :)

**Comment by ratka6** [comment]
I am not sure what you are asking for.

**Comment by AlexandreMinard** [comment]
for get about that please :)
