### ISSUE TITLE
Programmatically select a column

### ISSUE THREAD

**Issue by DarrenAndes** [highcharts/highcharts-ios#110]
Is there a way to programmatically select a column and have it highlight visually as if you tapped on the column itself.

Example is I select a table cell of data underneath the column chart and want to have the chart highlight as a result to match.

**Comment by ihnatmoisieiev** [comment]
Hello @DarrenAndes,
it is not possible at the moment.

**Comment by ihnatmoisieiev** [comment]
@DarrenAndes can I close it?

**Comment by DarrenAndes** [comment]
Hello... it's been a while, curious if it's now possible to programmatically select a column with later versions of the HighChart framework?

Or better yet, is there now a built-in feature added which allows taps above a bar to highlight/select the entire column (as if you tapped directly on the bar itself)?

**Comment by ihnatmoisieiev** [comment]
@DarrenAndes this feature has been added in the latest release. Can I close it?

**Comment by chriszrc** [comment]
@ihnatmoisieiev  Can you point us to how to accomplish this?

**Comment by kliffy** [comment]
@ihnatmoisieiev or if you've already figured it out @chriszrc. Can anyone share how to programmatically select a point? I can't seem to figure it out

**Comment by chriszrc** [comment]
@kliffy this worked for me:

https://stackoverflow.com/a/28986506/228369

**Comment by kliffy** [comment]
@chriszrc Thank you!
