### ISSUE TITLE
Support for Grouped categories plugin

### ISSUE THREAD

**Issue by merdok** [highcharts/highcharts-ios#112]
Hi,

can i currently use the [Grouped categories](https://www.highcharts.com/products/plugin-registry/single/11/Grouped-Categories) plugin?
If not is there a plan to adding this?

**Comment by KacperMadej** [comment]
Hi @merdok 

Have you tried and ended up with some errors or problems? or are you asking about license?

**Comment by merdok** [comment]
I don't see the grouped categories plugin as part of the package. On mobile it just gives me [object Object] as labels.

**Comment by KacperMadej** [comment]
Grouped categories plugin is not a module, so it's not a part of Highcharts or it's modules. Other plugins are listed here: https://www.highcharts.com/products/plugin-registry

Those could be third party, community made and are not a part of Highcharts.
Grouped categories plugin doesn't have any special documentation for loading as anything else than JavaScript, so it might not work with highcharts-ios.

You could report this problem in the grouped categories plugin GitHub repository - https://github.com/blacklabel/grouped_categories/issues Currently there's no plan to add support for iOS in the plugin nor [in the highcharts-ios](https://github.com/highcharts/highcharts-ios/issues/104#issuecomment-404090311)
