### ISSUE TITLE
Two SPLine on same y axis not show properly

### ISSUE THREAD

**Issue by saurabhjain6853** [highcharts/highcharts-ios#113]
Hello,

I am working on multi axes chart. I add two spline on same axes with different color but the  line show in same color and join two each other. See the image
![screen shot 2018-07-27 at 12 05 50 pm](https://user-images.githubusercontent.com/21302249/43305571-eb0748d6-9195-11e8-8ddd-27a13f5c0951.png)

My code is :     
```
let options = HIOptions()   
var dataSets = [HISpline]()
 for i in 0 ..< 2 {
 var color = HIColor()
 color = HIColor(uiColor: getRandomColor())
 let speedLine = HISpline()
                speedLine.data = speedData
                speedLine.yAxis = 0
                speedLine.color = color
                speedLine.name = "Speed"
                dataSets.append(speedLine)
}

        options.chart = chart
        options.xAxis = [getTimeXAxis()]
        options.yAxis = arrYAxis
        options.tooltip = tooltip
        options.legend = legend
        options.title = title
        options.credits = credits
        options.exporting = exporting
        options.series = dataSets
        options.plotOptions = plotOptions
        graphViews.options = options
```

Why this happen on multi axes chart?
Please help

**Comment by ihnatmoisieiev** [comment]
Hello @saurabhjain6853,
I guess maybe `getRandomColor()` return the same color.

**Comment by saurabhjain6853** [comment]
No Sir, I checked It return different RGB value

```
func getRandomColor() -> UIColor{
        let randomRed:CGFloat = CGFloat(drand48())
        let randomGreen:CGFloat = CGFloat(drand48())
        let randomBlue:CGFloat = CGFloat(drand48())
        return UIColor(red: randomRed, green: randomGreen, blue: randomBlue, alpha: 1.0)
    }
```

**Comment by saurabhjain6853** [comment]
And Why this graph join (continuous) with each other.. this are two different graph

**Comment by sebastianbochan** [comment]
Hi @saurabhjain6853,
Could you send me a json your you data ?

**Comment by saurabhjain6853** [comment]
the graph data come from server..Sir

**Comment by saurabhjain6853** [comment]
For two user graph show two SPLine, but the last selected color set on line

**Comment by saurabhjain6853** [comment]
```
 {
        "acc_calc" = "5.347";
        "acc_on" = 1;
        "accel_x" = "-0.03";
        "accel_y" = "0.28";
        "accel_z" = "-0.13";
        "brake_calc" = 0;
        "brake_on" = 0;
        dist = "170.253";
        lat = "2.76071474";
        lng = "101.73677784";
        row = 11135;
        speed = "200.660";
        time = "2.868";
    }

```
This type multiple data come from server

**Comment by ihnatmoisieiev** [comment]
It seems that you add the same data (`speedData `) for each speedLine in your for-in loop. As a result you have two identical `HISpline` series. Try to add legend to your chart:

```
let legend = HILegend()
legend.enabled = true
options.legend = legend
```
and check it.

**Comment by saurabhjain6853** [comment]
I add the legend see the screenshot:

![screen shot 2018-07-27 at 2 06 12 pm](https://user-images.githubusercontent.com/21302249/43310841-583ad732-91a6-11e8-984e-653e3ba2c4c6.png)

**Comment by ihnatmoisieiev** [comment]
Please, hide the first series by clicking the first "Speed" label and share screenshot.

**Comment by saurabhjain6853** [comment]
Please see the screenshot:
![screen shot 2018-07-27 at 2 06 12 pm](https://user-images.githubusercontent.com/21302249/43311410-fd223294-91a7-11e8-8b2b-4b4940d12285.png)

**Comment by saurabhjain6853** [comment]
Please see the screenshot:

![screen shot 2018-07-27 at 2 18 07 pm](https://user-images.githubusercontent.com/21302249/43311441-1ae5d7e0-91a8-11e8-8593-1d8c6de906a5.png)

**Comment by saurabhjain6853** [comment]
Thank you, 
I got the solution and resolved the issue, you can close the issue.
Thank you so much :)
