### ISSUE TITLE
HIFunction Implementation in Highcharts iOS libary to 6.1.1

### ISSUE THREAD

**Issue by ShreeramGWL** [highcharts/highcharts-ios#114]
I have implemented HIFunction in **Highcharts iOS library 6.0.7** as below and it was working fine, Once after upgrading **Highcharts iOS libary to 6.1.1** it doesnt work as expected. Let me know what exactly has to be done in the below code. Thanks in advance.

         let plotOptions = HIPlotOptions()

         let chartFunction: HIFunction? = HIFunction(closure: { context in
             print("Y value: \(String(describing: context?.getProperty("y")))")
         },properties:["y"])
        
        let chartSeries = HISeries()
        plotOptions.series = chartSeries
        
        let chartPoint = HIPoint()
        plotOptions.series.point = chartPoint
        
        let chartEvents = HIEvents()
        plotOptions.series.point.events = chartEvents
        
        plotOptions.series.point.events.click = chartFunction

**Comment by ihnatmoisieiev** [comment]
Hi @ShreeramGWL,
thank you for your question. 

There are small changes in `HIFunction`. In your example it will be:

```
let chartFunction: HIFunction? = HIFunction(closure: { context in
         print("Y value: \(String(describing: context?.getProperty("this.y")))")
},properties:["this.y"])
```

**Comment by ShreeramGWL** [comment]
Hi @ihnatmoisieiev 
            Your code dosen't work for me. HIFunction is triggered only when i remove properties and getProperty returns nil for y. 
Actually i am trying to get the value of the point clicked in the chart.

        let chartFunction: HIFunction? = HIFunction(closure: { context in
            print("Y value: \(String(describing: context?.getProperty("this.y")))")
        })

**Comment by ihnatmoisieiev** [comment]
Properties array must contain a list of all properties you want to get from the context. In this example, it is `["this.y"]`. 

Try:
```
let chartFunction = HIFunction(closure: { (context) in
            print("Clicked x: \(context!.getProperty("this.x")), y: \(context!.getProperty("this.y"))")
}, properties: ["this.x", "this.y"])
```

This function works perfectly for me.

**Comment by ihnatmoisieiev** [comment]
In this case, only one change: `y` -> `this.y`. 

Try this example in **6.1.1**:

```
let options = HIOptions()
        
let chart = HIChart()
chart.type = "column"
options.chart = chart
        
let title = HITitle()
title.text = "Demo chart"
options.title = title
        
let plotOptions = HIPlotOptions()
        
let chartFunction = HIFunction(closure: { (context) in
            print("Clicked x: \(context!.getProperty("this.x")), y: \(context!.getProperty("this.y"))")
}, properties: ["this.x", "this.y"])
        
let chartSeries = HISeries()
plotOptions.series = chartSeries
        
let chartPoint = HIPoint()
plotOptions.series.point = chartPoint
        
let chartEvents = HIEvents()
plotOptions.series.point.events = chartEvents
plotOptions.series.point.events.click = chartFunction
        
options.plotOptions = plotOptions

let series = HIColumn()
series.data = [49.9, 71.5, 106.4, 129.2, 144, 176, 203.4, 177.4, 155.4, 122.2, 95.6, 54.4]
options.series = [series]
```

**Comment by ShreeramGWL** [comment]
Thanks @ihnatmoisieiev  it worked. I have removed and added the pod once again with the changes you have mentioned.
