### ISSUE TITLE
Can't add a point from objective C

### ISSUE THREAD

**Issue by nkphuong** [highcharts/highcharts-ios#116]
Hi Highchart Team,

First, thanks for your great job. 

For now,  i have an issue with the dynamic chart. 

I have an NSArray that automatic updated data for every seconds. My problem is i cant call the function "addPoint" when the array is updated. 
Could you please show me how to do that? 
For now i could only update the chart options which i think the chart will be redraw.
I only want add new point every time the array receive new data

Thanks
Regard

**Comment by ihnatmoisieiev** [comment]
Hi @nkphuong,
thank you for your question.

You can update the chart's series to achieve this.  After array updated try e.g.:

```
let series = HISeries()
series.data = updatedDataArray
self.chartView.options.series = [series]
```

**Comment by nkphuong** [comment]
Hi @ihnatmoisieiev,
thanks, you save my day.

After updated, the chart work fine. But it's not scroll left.
Here is my code:
`- (HIOptions*)provideForChart:(NSMutableArray*)tempData
{
    HIOptions *hioptions = [[HIOptions alloc]init];
    
    HIChart *chart = [[HIChart alloc]init];
    chart.type = @"spline";
    chart.animation = @"Highcharts.svg"; // don't animate in old IE
    chart.marginRight = @10;
    

    HIXAxis *xaxis = [[HIXAxis alloc]init];
    xaxis.type = @"datetime";
    xaxis.tickPixelInterval = @10;
    
    HIYAxis *yaxis = [[HIYAxis alloc]init];
    yaxis.title = [[HITitle alloc] init];
    yaxis.title.text = @"Value";
    
    HIPlotLines *plotLines = [[HIPlotLines alloc] init];
    plotLines.value = @0;
    plotLines.width = @1;
    plotLines.color = [[HIColor alloc] initWithHexValue:@"808080"];
    yaxis.plotLines = [NSMutableArray arrayWithObjects:plotLines, nil];
    
    
    HITitle *title = [[HITitle alloc] init];
    title.text = @"Temp Chart";
    
    HISpline *spline = [[HISpline alloc] init];
    spline.name = @"Temp data";
    spline.data = tempData;
    
    hioptions.title = title;
    hioptions.chart = chart;
    hioptions.xAxis = [NSMutableArray arrayWithObjects:xaxis, nil];
    hioptions.yAxis = [NSMutableArray arrayWithObjects:yaxis, nil];
    hioptions.series = [NSMutableArray arrayWithObjects:spline,  nil];
    
    
    return hioptions;
}`

Did i do anything wrong?? Please help me !!

Thanks,
Regard

**Comment by ihnatmoisieiev** [comment]
@nkphuong you need to set up chart's `scrollablePlotArea` param.

**Comment by nkphuong** [comment]
@ihnatmoisieiev thanks for your very quick answer.
It's work perfectly.

There is a problem about the X-axis
I generate x value by:
` ([[NSDate date] timeIntervalSince1970]) `

Then how could i display X-axis label as format "HH:mm:ss" ?

I tried:

` HIDateTimeLabelFormats *dateTimeFormat=[[HIDateTimeLabelFormats alloc] init];
    dateTimeFormat.second=@"%H:%M:%S"; `

but it's seem not work

Thanks
Regard

**Comment by ihnatmoisieiev** [comment]
@nkphuong try `dateTimeFormat.day = @"%H:%M:%S";`. 
See [docs](https://api.highcharts.com/ios/highcharts/) for more info.

**Comment by nkphuong** [comment]
Many thanks @ihnatmoisieiev  
I got it. 

I'll close this question.

Regards
