### ISSUE TITLE
Is there any way to change the chart custom font?

### ISSUE THREAD

**Issue by nkphuong** [highcharts/highcharts-ios#117]
Hi Highchart Team,

First, thanks for your great job.

I have a question:

Is there any way that i could change the chart font by using custom fonts are included within the app??

Thanks
Regard

**Comment by ihnatmoisieiev** [comment]
Hi @nkphuong,
you can change the chart font by setting chart `style` param, e.g.
```
chart.style = ["fontFamily" : "serif"]
```
but unfortunately, you can't use your own font from iOS.

**Comment by nkphuong** [comment]
OK @ihnatmoisieiev,

Is there any plan in future to support that? And a function to addPoint (like JS) also?


thanks for your support

**Comment by ihnatmoisieiev** [comment]
@nkphuong no. You can update your `series` and achieve the same effect.

**Comment by nkphuong** [comment]
@ihnatmoisieiev it's look flickery when i add 4 points for every 4s. Or there's a way to make it's smooth like https://www.highcharts.com/ios/demo/dynamic-update/sand-signika ?

Thank you

**Comment by ihnatmoisieiev** [comment]
@nkphuong you can write a JS function as in above demo.

**Comment by nkphuong** [comment]
@ihnatmoisieiev can you give me an example? the data will be update for every 4s, so how could i make i from Objective-C to JS function?

Thanks

**Comment by ihnatmoisieiev** [comment]
@nkphuong ok, you haven't written about updated data from iOS. In this case, there is one way at the moment - update your `series` object.

**Comment by nkphuong** [comment]
thank @ihnatmoisieiev . I hope there will be a way to addPoint, and using custom font in near future.
 Many thank!!!

**Comment by speedoholic** [comment]
> Hi @nkphuong,
> you can change the chart font by setting chart `style` param, e.g.
> 
> ```
> chart.style = ["fontFamily" : "serif"]
> ```
> but unfortunately, you can't use your own font from iOS.

Thanks for sharing this @ihnatmoisieiev, What did you mean bt _you can't use your own font_? Can we use the **fontFamily** as per the fonts available in iOS devices by default?

**Comment by ihnatmoisieiev** [comment]
@speedoholic no, only default fonts from Highcharts.
