### ISSUE TITLE
HiFunction in Combination Chart

### ISSUE THREAD

**Issue by ShreeramGWL** [highcharts/highcharts-ios#119]
I am able to implement HiFunction in Line,Area,Bar and Column.How to implement HiFunction in Combination charts like **LineLine**,**Line Column**..etc?

**Comment by ihnatmoisieiev** [comment]
Hello @ShreeramGWL,
can you write more info about your problem? 
I suppose you can do it the same way.

**Comment by ShreeramGWL** [comment]
Hi @ihnatmoisieiev,
I have used below code to add HIFunction to my chart. when any point is selected i will trigger a print function. It works fine for  Line,Area,Bar and Column, for combination chart such as LineLine,LineColumn it do not  print any value in the console.

            let chartFunction = HIFunction(closure: { (chartContext) in
                print("Point Clicked")
            }, properties: ["this.x", "this.y","this.index","this.category"])
            
            let chartSeries = HISeries()
            plotOptions.series = chartSeries
            
            let chartPoint = HIPoint()
            plotOptions.series.point = chartPoint
            
            let chartEvents = HIEvents()
            plotOptions.series.point.events = chartEvents
            
            plotOptions.series.point.events.click = chartFunction

**Comment by ihnatmoisieiev** [comment]
@ShreeramGWL it should be worked. Can you share your chart options config? 
Try to change your `chartFunction ` to: 
```
let chartFunction = HIFunction(closure: { (chartContext) in
    print("Point Clicked")
})
```
and check it again.

**Comment by ihnatmoisieiev** [comment]
@ShreeramGWL did it resolve your problem? Can I close it?

**Comment by ihnatmoisieiev** [comment]
@ShreeramGWL can you share your char options?

**Comment by ihnatmoisieiev** [comment]
@ShreeramGWL does it work for you? Can I close the issue?
