### ISSUE TITLE
Disabled All animation

### ISSUE THREAD

**Issue by nkphuong** [highcharts/highcharts-ios#120]
Hi Team,

I read the documentation, but i couldn't disabled the animation when the chart is drawn. Could you pls show me how to disable it?

Thanks

**Comment by ihnatmoisieiev** [comment]
Hi @nkphuong,
you can disable animation by setting series `animation` param to **false** of `plotOptions`, e.g.:
```
let plotOptions = HIPlotOptions()
plotOptions.series = HISeries()
let animation = HIAnimation()
animation.duration = 0
plotOptions.series.animation = animation
options.plotOptions = plotOptions
```
