### ISSUE TITLE
Detect Zoom

### ISSUE THREAD

**Issue by nkphuong** [highcharts/highcharts-ios#121]
Hi team,

I have a situation:

1. For default, the chart display as 2 minutes per X-axis  tick
2. When zoom in, the chart display as 1 minutes per X-axis tick
3. When zoom out, the chart display as 5 minutes per X-axis tick

My chart will be updated data for every second. X-axis is datetime type.
Is there a way that i could do that? Or Could i redraw the chart when zoom detected? 
How could i detect when user zoom on chart? How set the chart is scrollable when zoomed in?

Thanks,
Regard

**Comment by sebastianbochan** [comment]
Hi @nkphuong,
You can use two events:
- setExtremes
- afterSetExtremes
which detects zooming / change extremes on any exis.

Docs:
- https://api.highcharts.com/ios/highcharts/

Reference to `HIEvents Class Reference`.

I hope that will help.

**Comment by ihnatmoisieiev** [comment]
@nkphuong did you resolve your problem? Can I close it?

**Comment by nkphuong** [comment]
@ihnatmoisieiev 
Thanks for your support, but i couldn't resolve it for now.
Anyway i gonna close it now.
