### ISSUE TITLE
How to let the tick of axis begin from the leftmost position after setting the X axis categories ?

### ISSUE THREAD

**Issue by AAChartModel** [highcharts/highcharts-ios#122]
<img width="467" alt="2803346c-653f-4f52-95b7-3648003dcdde" src="https://user-images.githubusercontent.com/16357599/44719668-95668200-aaf6-11e8-9b2b-98b5f22e0447.png">

In highcharts, if I setted the  X axis categories,and the tickmarkPlacement is equal "on",the tick of axis will not begin from the zero position, how to set the tick begin from the axis origin position???

**Comment by ihnatmoisieiev** [comment]
Hello @AAChartModel,
thanks for your question. 
Did you try to set `pointStart` param in `plotOptions` or `min` param in `xAxis `?

**Comment by AAChartModel** [comment]
the pointStart i equal to 0, and mini in xAxis is equal to 0, however, the tick still can not begin from the axis origin position. configuration as follow

```js
{
		title: {
			text: 'Chart reflow is set to true'
		},
		subtitle: {
			text: 'When resizing the window or the frame, the chart should resize'
		},
		xAxis: {
			categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
			,
			min:0,
			tickmarkPlacement: 'on',
		},
		plotOptions: {
			series: {
				pointStart: 0
			}
		},
		series: [{
			data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
		}]
	}
```

**Comment by AAChartModel** [comment]
Thanks for your suggestion, but if I configure the  formatter function of xAxis labels as you said ,it will lead to the another problem that the tittle of tooltip cannot show the categories element content, Just like this
example :http://jsfiddle.net/stepday/yVG7R/

as you can see, at this time, the tittle of tooltip just show the sequence  number  rather than the categories element.  is there any way to solve this problem? 😊(*￣︶￣)

**Comment by pawelfus** [comment]
Hi @AAChartModel 

That's not a problem, simple formatter will resolve the issue: http://jsfiddle.net/BlackLabel/yVG7R/187/

Snippet:

```javascript
    tooltip: {
      formatter: function() {
        return categories[this.point.x] + '<br><span style="color:' + this.point.color + '">\u25CF</span> ' + this.point.series.name + ': <b>' + this.point.y + '</b><br/>''
      }
    },
```

**Comment by ihnatmoisieiev** [comment]
@AAChartModel does it work? Can I close the issue?

**Comment by AAChartModel** [comment]
It work perfectly, thanks!😊
