### ISSUE TITLE
Y-axis is disapear

### ISSUE THREAD

**Issue by nkphuong** [highcharts/highcharts-ios#123]
Hi team,

My chart is updated for every second.

My config of scrollablePlotArea with minWidth is 700

I'm using

HISpline *spline1 = [[HISpline alloc] init];
spline1.data = [self.temperatureArray copy];
HISpline *spline2 = [[HISpline alloc] init];
spline2.data = [self.customTemperatureArray copy];
self.chartView.options.series =  [NSMutableArray arrayWithObjects:spline1, spline2, nil];

When the chart updated, the Y-axis stick to the chart left side. Is there any way that i could stick it on the screen left side?

Thanks, 
Regard

**Comment by ihnatmoisieiev** [comment]
Hello @nkphuong,
can you attach a screenshot and mark on the chart what do you mean exactly?

**Comment by nkphuong** [comment]
When at the right side
![img_0255](https://user-images.githubusercontent.com/5858327/44773214-2e9aa480-ab9a-11e8-87fb-31122924e6de.jpg)
When at the leftside
![img_0256](https://user-images.githubusercontent.com/5858327/44773215-2f333b00-ab9a-11e8-9647-53d03d3de706.jpg)

**Comment by ihnatmoisieiev** [comment]
@nkphuong ok, but what do you want to achieve?

**Comment by nkphuong** [comment]
@ihnatmoisieiev 

My chart will be updated data for every seconds.

I want the yaxis is always display on absolute position (here is left device screen), even when chart scrolling (it happen when i redraw the hold chart)

 As you can see, now it display below the "white panel", and it only display on the left side of the chart

**Comment by ihnatmoisieiev** [comment]
Hello @nkphuong,
I have reported the issue [https://github.com/highcharts/highcharts/issues/8862](https://github.com/highcharts/highcharts/issues/8862).
Thank you.
