### ISSUE TITLE
want to get  a tap action from a chart in ios swift

### ISSUE THREAD

**Issue by venkateshr8849** [highcharts/highcharts-ios#124]

**Comment by venkateshr8849** [comment]
want to get  a tap action from a chart in ios swift . i saw some examples in objective-c..so i change that code to swift.. but i am not able to get a tap action

**Comment by ihnatmoisieiev** [comment]
Hi @venkateshr8849,
see [https://github.com/highcharts/highcharts-ios/issues/114](https://github.com/highcharts/highcharts-ios/issues/114).

**Comment by ihnatmoisieiev** [comment]
@venkateshr8849 can I close this issue?

**Comment by venkateshr8849** [comment]
heyyy..... how to get ChartView from the HIFunction closure..

**Comment by ihnatmoisieiev** [comment]
It's not possible, because you have your charView locally.

**Comment by ihnatmoisieiev** [comment]
@venkateshr8849 Can I close the issue?

**Comment by ihnatmoisieiev** [comment]
@venkateshr8849 can you give more info and one describe what do you want to achieve (maybe some screenshots). Do you have UIButton or highchart's button? And what do you want to hide?

**Comment by venkateshr8849** [comment]
i want to hide that expand button(red circle) that is UIbutton. By click a chart i wanna to show that button . so chartview and uibuttons are subviews of uiView..
<img width="380" alt="screen shot 2018-09-17 at 2 19 11 pm" src="https://user-images.githubusercontent.com/13820137/45617288-7ae94e00-ba8f-11e8-820c-fcf6157d6223.png">

**Comment by venkateshr8849** [comment]
wherever click in the HIChartView i wanna to perform a action

\

**Comment by ihnatmoisieiev** [comment]
@venkateshr8849 ok, in this case, you can add tap gesture recognizer to `HIChartView` or add click event to `chart` : 
```
let chart = HIChart()
let closure: HIClosure = { context in
   print("Chart clicked!")
}
chart.events = HIEvents()
chart.events.click = HIFunction(closure: closure)
options.chart = chart
```

**Comment by ihnatmoisieiev** [comment]
@venkateshr8849 did it resolve your problem?
