### ISSUE TITLE
Is High chart available in swift?

### ISSUE THREAD

**Issue by prince0210** [highcharts/highcharts-ios#125]
Hi,

I want to know whether the given repository of high charts is available in swift language or not?

If it's not available, then how will I merge this in my swift project?

Thanks in advanced.

**Comment by ihnatmoisieiev** [comment]
Hello @prince0210,
you can use Highcharts framework with your Swift project. See [blog article](https://www.highcharts.com/blog/tutorials/highcharts-ios-library-in-swift/).
