### ISSUE TITLE
v6.1.2?

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#127]
When can we expect v6.1.2 to be released? Thanks.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
v6.1.2 will be released today.

**Comment by skuske** [comment]
Thank you.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Another two days passed now... Any update? We are waiting for v6.1.2 as it fixes an issue some of our users complained about. Tahnks.
