### ISSUE TITLE
How to hide HiColumnRange name

### ISSUE THREAD

**Issue by saminyasar** [highcharts/highcharts-ios#128]
How can i hide column range name ? I have tried to set name using an empty string like  - 

`HIColumnRange *series =[ [HIColumnRange alloc] init];
[series setName:@""];`

But it shows "Series 1" (please see attached screenshot).
![simulator screen shot - iphone 8 - 2018-09-14 at 17 44 48](https://user-images.githubusercontent.com/3470367/45548407-0a9bbc00-b846-11e8-93b6-312787254527.png)

**Comment by ihnatmoisieiev** [comment]
Hello @saminyasar,
try `series.showInLegend = [[NSNumber alloc] initWithBool:false];`.

**Comment by saminyasar** [comment]
@ihnatmoisieiev yes. I was looking for this exact behaviour. Thanks for your reply.
