### ISSUE TITLE
Columns tooltip problem

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#129]
If you have a column chart and if you touch one column, the tooltip appears. That's fine. 

But: If you then move the finger on the chart, the tooltip follows the finger, but the tooltip does not update and it does not show value of the column the finger touches - it still shows the value of the column I touched before.

You must remove the finger and touch a new column in order to force the tooltip to draw again with the current columns value.

Question: how can I get the tooltip to constantly update itself with the value of the column the finger points to, just like it works with any other chart type?

It works with line charts, and I want the tooltip to behave exactly like in line charts, i.e. it should update itslef according to the finger's position.

Thanks.

**Comment by skuske** [comment]
You can reproduce this behavior in the HighFit sample app >>> Calories (Burned) chart: the tooltip follows the finger, but it does not update according to the column below the finger.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
thank you for the reporting. I will check it as soon as possible.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thank you.

Also:

`tooltip.followTouchMove=[[NSNumber alloc] initWithBool:true];`

`true` or `false` does not make a difference. The tooltip always follows the touch, no matter if `true` or `false`.

**Comment by ihnatmoisieiev** [comment]
@skuske issue have been reopened on the main repo: [https://github.com/highcharts/highcharts/issues/7484](https://github.com/highcharts/highcharts/issues/7484). Thank you!

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thank you.

When can we expect this to be finally resolved? I am asking this since we are waiting for this bug to be resolved for months now, and we thought that v6.1.2 would fix it and we postponed an update of our app in order to include v6.1.2 of the wrapper. When v6.1.2 was released we were extremely disappointed that things actually got worse due to the fact that the tooltip does not update at all once displayed. Therefore we had to go back to v6.1.1.

So, simple question: when will this be fixed?

**Comment by ihnatmoisieiev** [comment]
@skuske the answers are on the main repo: [https://github.com/highcharts/highcharts/issues/7484](https://github.com/highcharts/highcharts/issues/7484).

**Comment by ihnatmoisieiev** [comment]
@skuske I hope today.

**Comment by skuske** [comment]
@ihnatmoisieiev 

The updated wrapper fixes it. Many thanks! :o)
