### ISSUE TITLE
Tooltip format

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#13]
Hi,

Is there a way to get the formatted strings of a date in a tooltip in French?
Right now, when displaying my tooltip with the format  "{point.x:%e %b}"
I get the month in English ('May').

I need to get it in French ('Mai').

My iPhone locale is French.

```
        let tooltip = HITooltip()
        tooltip.headerFormat = "<b>{series.name}</b><br>"
        tooltip.pointFormat = "{point.x:%e %b}: {point.y:.2f} €"
```

Regards,
Alexandre

**Comment by AlexandreMinard** [comment]
anyone?

**Comment by mll** [comment]
Hi @AlexandreMinard. We will give you a detailed response soon. Thank you for your patience.

**Comment by AlexandreMinard** [comment]
Happy to see some life here :)

**Comment by AlexandreMinard** [comment]
so, anything new?

**Comment by sebastianbochan** [comment]
Hi @AlexandreMinard
I apologize for late reply. The issue will be resolved until 20th July.

**Comment by AlexandreMinard** [comment]
We're the 20th July now, any update?

**Comment by mll** [comment]
Hi @AlexandreMinard we are close to publishing a new version that fixes the issue.

**Comment by AlexandreMinard** [comment]
Any update?

**Comment by AlexandreMinard** [comment]
Anything new?

**Comment by mll** [comment]
Formatter functions are now working. We use javascript functions at this stage. Please refer to the javascript docs on info how to use them.

**Comment by TorsteinHonsi** [comment]
@mll  The OP question is about [tooltip.headerFormat](http://api.highcharts.com/highcharts/tooltip.headerFormat) and `tooltip.pointFormat`, which are string configurations and should not be confused with the `tooltip.formatter` callback.

In Highcharts JS, the solution is to set the `lang`, which will be applied to the `pointFormat`: http://jsfiddle.net/3765Lbph/.

It is a general pattern in Highcharts that formatter callbacks are accompanied by _format_ strings. The reason for this is that is precisely that formatters are difficult to replicate in wrappers, GUIs etc. So whenever a formatter callback is used, you should ask if a format string can be used instead. Does this work equally in Highcharts iOS?

**Comment by mll** [comment]
@TorsteinHonsi We have full support for format strings as well as formatter functions. See: 

https://github.com/highcharts/highcharts-ios/blob/master/development/Highcharts.framework/Headers/HITooltip.h 

I understand that I have introduced confusion on formatters vs format strings. To clarify - we now support both.
