### ISSUE TITLE
Disable Initial Animation [Swift 4]

### ISSUE THREAD

**Issue by learner25** [highcharts/highcharts-ios#131]
I tried the following:
```
 let s_animation = HIAnimation()
 s_animation.duration =  2000
plotOptions.series.animation = s_animation 
```

late this one : 
`   plotOptions.series.animation= false // incompitable type`
and 
`   plotOptions.series.animation.duration = 0 // the app crashes` 

get stuck for several hours. Is there any solution

**Comment by ihnatmoisieiev** [comment]
Hello @learner25,
see [https://github.com/highcharts/highcharts-ios/issues/120](https://github.com/highcharts/highcharts-ios/issues/120).
