### ISSUE TITLE
Dynamic ToolTip ! Unable to get swift variables into JS code ! 

### ISSUE THREAD

**Issue by karthikShiva1997** [highcharts/highcharts-ios#133]
var labelDict = [12:"Apple",14:"Orange"]
        var yValue = Int()
        var mappedLabelValue = String()
        
        let hiFunc = HIFunction(closure: { (context) in
            
            guard let context = context else { return }
            yValue = context.getProperty("y") as! Int
            mappedLabelValue = labelDict[yValue] ?? "defaultLabel"
            
        }, properties: ["y"])
    
        
        let jsfunc = "function() { var i = \(mappedLabelValue) ;return i; }"
        
        let funcDaw = HIFunction(jsFunction: jsfunc)
        
        bullet.tooltip.pointFormatter = funcDaw

**Comment by ihnatmoisieiev** [comment]
Hi @karthikShiva1997,
try to change your `hiFunc` to:

```
let hiFunc = HIFunction(closure: { (context) in
        
        guard let context = context else { return }
        yValue = context.getProperty("this.y") as! Int
        mappedLabelValue = labelDict[yValue] ?? "defaultLabel"
        
    }, properties: ["this.y"])
```

**Comment by karthikShiva1997** [comment]
@ihnatmoisieiev Thanks for responding !  But , it still doesn't work ! This is the code that I am trying to get it work !  I am able to successfully get the values on tap event and mappedLabelValue gets updated ! But, the problem is with the Javascript function . It refuses to return the swift variable ! :(

        var labelDict = [275:"Apple",344:"Orange"]

        var yValue = Int()
        var mappedLabelValue = String()

         bullet.point = HIPoint()
         bullet.point.events = HIEvents()
         bullet.point.events.click = HIFunction(closure: { (context) in

            
            guard let context = context else { return }
            yValue = context.getProperty("this.y") as! Int
            mappedLabelValue = labelDict[yValue] ?? "defaultLabel"
        }, properties: ["this.y"])
    

        let jsfunc = "function() { return '\(mappedLabelValue)' + 'is a fruit'; }"

        let funcDaw = HIFunction(jsFunction: jsfunc)

        bullet.tooltip.pointFormatter = funcDaw

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 in this case, you don't need `click` function. You need to add your `labelDict` to js context:

```
let jsfunc = "function () { var labelDict = { 275 :"Apple", 344:"Orange" }; var mappedLabelValue = labelDict[this.y] || 'defaultLabel'; return mappedLabelValue + ' is a fruit'; }"

let funcDaw = HIFunction(jsFunction: jsfunc)

bullet.tooltip.pointFormatter = funcDaw
```

**Comment by karthikShiva1997** [comment]
@ihnatmoisieiev Unfortunately I cannot do that ! labelDict is a dictionary which i get as JSON from the server and it keeps changing . I somehow need to get the swift variables into the JS function or achieve the same through HIFunction or HIClosure ! I don't understand why IOS developers are being forced to write JS code here ! Why am I not able to return anything from HIClosure ?? Please help us out !!

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 Highcharts iOS is only wrapper of HighchartsJS for iOS. Unfortunately, it is impossible to **return** Swift variables from `HIClosure` to `JS`, but you can get values from `JS` to Swift.  The way to resolve the problem is adding your dictionary from the server to `jsFunction` and return values as I've written above. And after it has been updated, you can set new `HIFunction` for `pointFormatter` object.

**Comment by karthikShiva1997** [comment]
@ihnatmoisieiev It didn't work :(   Before using the dictionary from JSON , I gave it a shot with a variable . Reassigning the pointFormatter object with a new instance of HIFunction doesn't seem to update the pointFormatter function. Can you please provide me a tested solution ? . I would very much appreciate it !


var jsFuncString: String = {
            
            return "function() { var i = 'Papaya'; return i + 'is a fruit'; }"
            
        }()

         bullet.point = HIPoint()
         bullet.point.events = HIEvents()
         bullet.point.events.click = HIFunction(closure: { (context) in

            
            guard let context = context else { return }
            yValue = context.getProperty("this.y") as! Int
            mappedLabelValue = labelDict[yValue] ?? "defaultLabel"
       
            jsFuncString = "function() { var i = '\(mappedLabelValue)'; return i + 'is a fruit'; }"
            
           // jsFuncString = "function() { var i = 'mango'; return i + 'is a fruit'; }"

            bullet.tooltip.pointFormatter = HIFunction(jsFunction: jsFuncString)
            

        }, properties: ["this.y"])
        

        
        let jsfunc = jsFuncString

        let funcDaw = HIFunction(jsFunction: jsfunc)

        bullet.tooltip.pointFormatter = funcDaw

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 
it works perfect for me:

```
let jsfunc = "function () { var labelDict = { 275 :"Apple", 344:"Orange" }; var mappedLabelValue = labelDict[this.y] || 'defaultLabel'; return mappedLabelValue + ' is a fruit'; }"

let funcDaw = HIFunction(jsFunction: jsfunc)

bullet.tooltip.pointFormatter = funcDaw
```

As I've written you don't need click event.

**Comment by karthikShiva1997** [comment]
As you had commented "The way to resolve the problem is adding your dictionary from the server to jsFunction" . How do I accomplish this ? . In any case it has to swift variable inside JS function

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 ok, the simplest example: 

```
var labelDict = [275: "Apple", 344: "Orange"]
        
var labelDictStringValues = ""
        
labelDict.forEach { (key, value) in
    labelDictStringValues += "\(key) : '\(value)',"
}
        
let jsfunc = "function () { var labelDict = { \(labelDictStringValues.dropLast()) }; var mappedLabelValue = labelDict[this.y] || 'defaultLabel'; return mappedLabelValue + ' is a fruit'; }"
        
let funcDaw = HIFunction(jsFunction: jsfunc)
        
tooltip.pointFormatter = funcDaw
```

**Comment by karthikShiva1997** [comment]
@ihnatmoisieiev Thanks a lot man !  It worked !  I was trying to return a simple variable instead of a swift dictionary and It never worked . I must have messed up the JS code !
