### ISSUE TITLE
Annotation won't show up in ios

### ISSUE THREAD

**Issue by maxydey** [highcharts/highcharts-ios#135]
I'm trying to crate chart with annotation. on web demo it works as expected
https://jsfiddle.net/2ys86h3p/2/

But on iOS annotation won't show up. hiOptions object is identical. I suspect it is due to annotation module isn't enabled. Can't find documentation entry on how to enable modules.

**Comment by ihnatmoisieiev** [comment]
Hello @maxydey,
yes, you have to enable `annotation` module:
```
chartView.plugins = ["annotations"]
```

**Comment by maxydey** [comment]
Thanks @ihnatmoisieiev it worked. I'd say this info is worth mentioning in readMe:)

**Comment by ihnatmoisieiev** [comment]
@maxydey ok, thank you for your attention.

**Comment by ihnatmoisieiev** [comment]
@maxydey the readme has been updated.
