### ISSUE TITLE
Events handlers does not work in the new versions

### ISSUE THREAD

**Issue by YardenTR** [highcharts/highcharts-ios#136]
Hello!
Im using Highcharts iOS for the past few months.
I recently upgraded my pod from '6.0.7' to '6.1.2'
This broke the HIFunction handlers.

example code:
> let areaSeries = HIArea()
>         areaSeries.name = ""
>         areaSeries.data = material.data
>         areaSeries.point = HIPoint()
>         areaSeries.point.events = HIEvents()
>               areaSeries.point.events.mouseOver = HIFunction(closure: { (context) in
>                 let dictionary = ["y": context?.getProperty("y") as? NSNumber, "x": context?.getProperty("x") as? NSNumber]
>                 print(dictionary)
>             }, properties: ["y", "x"])
>         options.series = [areaSeries]

When I removed the properties array -> the callback was called, but we need the properties.

**Comment by ihnatmoisieiev** [comment]
@YardenTR there are some changes in the `HIFunction`from `6.0.7`. If you want to get properties from the current context, you need to get it from `this`:

```
areaSeries.point.events.mouseOver = HIFunction(closure: { (context) in
let dictionary = ["y": context?.getProperty("this.y") as? NSNumber, "x": context?.getProperty("this.x") as? NSNumber]
print(dictionary)
}, properties: ["this.y", "this.x"])
```

**Comment by YardenTR** [comment]
Worked, Thanks a lot!
