### ISSUE TITLE
Bugs in this wrapper

### ISSUE THREAD

**Issue by shivanraptor** [highcharts/highcharts-ios#14]
I'm using the Highcharts iOS v1.0.5 installed via Cocoapods, but I found quite a lot of bugs:

**Bug 1 : Tooltip, Legend, Menu buttons cannot be hidden**

```
// Highchart
self.highchartView = [[HIGChartView alloc] initWithFrame:CGRectMake(0, 0, chartArea.frame.size.width, chartArea.frame.size.height)];

HIOptions *options = [[HIOptions alloc] init];
options.legend.enabled = [NSNumber numberWithBool:NO]; // this does NOT work
options.tooltip.enabled = [NSNumber numberWithBool:NO]; // this does NOT work
options.credits.enabled = [NSNumber numberWithBool:NO]; // this works
options.exporting.enabled = [NSNumber numberWithBool:NO]; // this does NOT work
options.navigation.buttonOptions.enabled = [NSNumber numberWithBool:NO]; // this does NOT work
self.highchartView.options = options;
```

The elements are still there even when I disable them. 
p.s. the `enabled` property should be in `BOOL` instead of `NSNumber`, which is very weird.

**Bug 2 : Unable to find a correct formatter for Y axis labels**
The API document explained I can use `yAxis.label.formatter` to format the Y axis label, in my case I would like to have 6 decimal places, but the example only provides unrelated JS functions. 

What is the expected value for the formatter ? It requires `NSString`. Tried `{.6f}` but nothing changed (the actual value is `0.000006` but it's displayed as `0`)

**Comment by mll** [comment]
Hi @shivanraptor. We are working on the issue, thank you for your patience.

**Comment by mll** [comment]
Hi @shivanraptor. You have to create objects that you manipulate on, for example like this:
options.tooltip = [HITooltip new];
before you use its properties. This is because all the subobjects are nil by default. 

The formatters currently do not work. We are close to releasing an updated version where they do work, then it would look like this:

yAxis.labels.formatter = @"function () { return 'aaa'; }";

**Comment by mll** [comment]
Function support was introduced in v 1.1.0.
