### ISSUE TITLE
Highlight a single data point - iOS

### ISSUE THREAD

**Issue by arunavasumathi** [highcharts/highcharts-ios#142]
Hi,

I use 4 HILine() data values and on selection - click anywhere inside chart, I want to show markers on all 4 lines in the chart only at that **context!.getProperty("event.xAxis[0].value")** point. How can i achieve this? Please help.

**Comment by ihnatmoisieiev** [comment]
Hello @arunavasumathi,
can you give more info what do you want to show after the click? 
Thank you.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev Hi, after click event, I want to show markers on all the lines for clicked x axis value, irrespective of y data value of the lines.

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi try to set tooltip `shared` param to `true`.

See [demo](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/shared-true/).

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev thank you it worked. Is there a way I can set marker at specific points of lines other than highlighting? For instance, I want marker to be displayed only on the 4th y value of 2nd series and I want another marker on 5th y value of 3rd series?

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi yes, for example:

```
let plotOptions = HIPlotOptions()
plotOptions.series = HISeries()
plotOptions.series.point = HIPoint()
plotOptions.series.point.events = HIEvents()
plotOptions.series.point.events.click = HIFunction(jsFunction: "function () { var chart = this.series.chart; chart.series[0].data[0].select(true, true); chart.series[1].data[0].select(true, true); chart.series[2].data[0].select(true, true); }")
options.plotOptions = plotOptions
```

Also you can use `setState` method instead of `select`. See [docs](https://api.highcharts.com/class-reference/Highcharts.Point#setState).

**Comment by arunavasumathi** [comment]
Hi @ihnatmoisieiev  
I just modified the line below because I use only 2 lines.
`plotOptions.series.point.events.click = HIFunction(jsFunction: "function () { var chart = this.series.chart; chart.series[0].data[0].setState(true, true); chart.series[1].data[1].setState(true, true); chart.series[0].data[4].setState(true, true); }")`
What happens is when I click on the chart or the line, the market at first position of series[0] is enabled, but I don't see any marker on the second series.

**Comment by arunavasumathi** [comment]
Also, I have an array of colours for the markers of one of the series. I want the colours to be displayed like first marker colour of the series should be first index in colours array, second marker colour of the series should be second index of the colours array. Please let me know how to achieve this.

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi see [docs](https://api.highcharts.com/class-reference/Highcharts.Point#setState) for `setState` function. 
The first param is `string`, e.g.:
```
chart.series[0].data[0].setState('select');
chart.series[0].data[0].setState('hover');
```
or
```
chart.series[0].data[0].select(true, true);
```

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev thank you. it works, but when i have clicked on the points i have given to select. can you please let me know how to make it selected by default, while loading the chart.

lets say i have 1 line and 2 column, on chart loading, i want to highlight the middle point of all the data series.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev thank you. it works, but when i have clicked on the points i have given to select. can you please let me know how to make it selected by default, while loading the chart.

lets say i have 1 line and 2 column, on chart loading, i want to highlight the middle point of all the data series.

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi add your function to `chart.events. load` and remove from `plotOptions.series.point.events.click`.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev i tried this and see no change. please help.

```let chart = HIChart()
        chart.events = HIEvents()
        chart.events.click = HIFunction(jsFunction: "my function")
        chart.events.load = HIFunction(jsFunction: "function () { var chart = this.series.chart; chart.series[0].data[2].setState('select'); chart.series[1].data[4].setState('select'); }")

...
        hiOptions.chart = chart```

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev it worked. thank you. but please tell me why is the markers are different than the usual halo marker?

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev i want the selection to like normal chart selection with crosshair options too.

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi in this case, you need to change state from `'select'` to `'hover'`,
```
function () { this.series[0].data[2].setState('hover'); this.series[1].data[4].setState('hover'); }
```
I have written about it above.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev this code selects the point, lets say FIRST_POINT as expected, but after selecting another point, say SECOND_POINT using click event, the halo in the FIRST_POINT disappears, but the FIRST_POINT still stays selected. only if i select the FIRST_POINT again and go on selecting SECOND_POINT or THIRD_POINT, the FIRST_POINT becomes normal. this happens only if the series has markers enables. 
please guide me.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev 

1. FIRST_POINT remains selected (default) while chart loading
2. SECOND_POINT is selected, FIRST_POINT remains selected or highlighted without halo but with increased marker size. Two points (FIRST_POINT without halo and SECOND_POINT with halo) are selected
3. FIRST_POINT is selected, SECOND_POINT becomes normal or unselected
4. SECOND_POINT (or THIRD_POINT) is selected, FIRST_POINT becomes normal or unselected

This scenario happens only with series that has marker enabled.
I also have another series in the same chart without marker on which this **setState('hover')** works fine like below:

1. FIRST_POINT remains selected (default) while chart loading
2. SECOND_POINT is selected, FIRST_POINT becomes normal or unselected

**Comment by sebastianbochan** [comment]
Hi @arunavasumathi,
Due to the christmas time it will take some time until we are able to look into a solution.
Thank you for your patience.

**Comment by sebastianbochan** [comment]
Hi @arunavasumathi,
I will try to help to you and @ihnatmoisieiev to understand the problem and find a solution. 

At the beginning let's focus on a really simple demo (in JS) to have complex scenario.
- https://jsfiddle.net/BlackLabel/vz9xm03p/)

1. The FIRST_POINT is selected by default
2. Click on the SECOND_POINT, is selected
3. When hover on the FIRST_POINT, select state is missing, which is wrong. It should be still selected until click again on the FIRST POINT

Please analyze my demo and let me know if all points from above are correct in the understanding the problem. If we agree, then we @ihnatmoisieiev code it to iOS platform.

**Comment by arunavasumathi** [comment]
Hi @sebastianbochan ,

In the demo which you gave,
1. The FIRST_POINT is selected by default
2. Click on SECOND_POINT. Now SECOND_POINT is selected, FIRST_POINT is not deselected. 

This is my requirement: When SECOND_POINT is clicked, SECOND_POINT should be selected, FIRST_POINT should be deselected or FIRST_POINT should be normal marker.

**Comment by sebastianbochan** [comment]
Hi @arunavasumathi,
Thank you for the feedback.

I prepared updated demo:
- https://jsfiddle.net/BlackLabel/w5gc2uz4/

Please let me know if it is correct with your final concept.

**Comment by arunavasumathi** [comment]
@sebastianbochan Thanks! Behaves as expected. Please let me know the iOS changes.

**Comment by ihnatmoisieiev** [comment]
Thank you for your help @sebastianbochan !

@arunavasumathi I prepared this demo in Swift:

```
let options = HIOptions()
        
let chart = HIChart()
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: "function() { var chart = this; this.series[0].data[0].setState('select'); }")
        
let plotOptions = HIPlotOptions()
plotOptions.series = HISeries()
plotOptions.series.allowPointSelect = true
plotOptions.series.point = HIPoint()
plotOptions.series.point.events = HIEvents()
plotOptions.series.point.events.select = HIFunction(jsFunction: "function() { var currentPoint = this; this.series.data.forEach(function (point) { if (point !== currentPoint) { point.setState(''); } }); }")
        
let series = HISeries()
series.data = [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]
        
options.chart = chart
options.plotOptions = plotOptions
options.series = [series]
```

Please try it.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev 

What happens is:
1. FIRST_POINT selected by default.
2. SECOND_POINT is clicked, SECOND_POINT gets selected but FIRST_POINT is unchanged (FIRST_POINT still remains selected)
3. SECOND_POINT or any other point clicked, FIRST_POINT becomes normal.

Please help.

Also i want the same behaviour for **chart.events.select** function too.

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi thank you for the reporting. It is a bug related with [https://github.com/highcharts/highcharts/issues/6817](https://github.com/highcharts/highcharts/issues/6817). I will provide a solution soon.

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi it will be fixed in the next release.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev thank you for the update. meanwhile, could you please let me know how to achieve the same with chart events?

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi yes, of course. Try:
```
chart1.events.load = HIFunction(closure: chartLoadFn, jsFunction: "function () { this.series.forEach(function(serie) { serie.data[serie.data.length - 1].setState('hover'); }); }")
```

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi did you try it? Can I close the issue?

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev thank you so much. it works. 👍

**Comment by arunavasumathi** [comment]
Hi @ihnatmoisieiev 

Could you please tell me how to achieve this with chart events?

I already have a click event with which I get the x-Axis value to do further manipulations:

       let chartFunction1: HIClosure = { context in
            let xValue = context!.getProperty("event.xAxis[0].value") as! Double
            
            var intValue = Int(xValue)
            let d : Double = xValue - Double(intValue)
            if d > 0.5 {
                intValue += 1
            }
            self.delegate?.....<my delegate function>
        }

**Comment by ihnatmoisieiev** [comment]
Hello @arunavasumathi,

what do you want to achieve with chart events?

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev 
1. On chart load - default points to be selected
2. On chart click or selection event, the Y points corresponding to X value of the click event, should be highlighted.


Chart click or select event that will behave the same way as the point event provided 

    plotOptions.series.point.events.select` = HIFunction(jsFunction: "function() { var currentPoint = this; this.series.data.forEach(function (point) { if (point !== currentPoint) { point.setState(''); } }); }")

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi ok, try this:
1. `chart.events.load = HIFunction(closure: chartLoadFn, jsFunction: "function () { this.series.forEach(function(serie) { serie.data[serie.data.length - 1].select(); }); }")`
2. `chart.events.click = HIFunction(jsFunction: "function (event) { var selectedPoints = this.getSelectedPoints(); var x = Math.round(event.xAxis[0].value); selectedPoints.forEach(function(point) { point.select(false); }); this.series.forEach(function(serie) { serie.data[x].setState('hover'); }); }")`
