### ISSUE TITLE
BorderWidth not functioning properly

### ISSUE THREAD

**Issue by DarrenAndes** [highcharts/highcharts-ios#143]
I have been trying to remove the borderWidth and haven't had any luck.. nothing works regardless of where I set borderWidth. I am using a column chart with stacking set to "normal"

Looking at "HISeries.h" I found this code... should the borderWidth property be an "NSNumber" instead of an "id"? I see it used to be an NSNumber but was recently changed...
```@property(nonatomic, readwrite) id borderWidth;```

https://github.com/highcharts/highcharts-ios/blob/2cd692413561bddc6c2fa747636f1b896b0b0762/release/Highcharts.framework/Headers/HISeries.h#L515

If not... what should be passed instead of a number?

**Comment by ihnatmoisieiev** [comment]
Hi @DarrenAndes,
thank you for the reporting. It will be fixed.
