### ISSUE TITLE
Hiding a Series from outside the ChartView

### ISSUE THREAD

**Issue by DarrenAndes** [highcharts/highcharts-ios#144]
Is it possible to hide / show a series on the chart from a native iOS button?

I see there is a hide() and show() function is Javascript, but not sure if this is part of the highcharts-ios library. Thanks...

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/members/series-hide/

**Comment by ihnatmoisieiev** [comment]
Hi @DarrenAndes,
unfortunately you can't use `hide()` and `show()` functions from `JS` at the moment, but you can update `series` object from `HIOptions`. Set `visible` param to `false` before update, e.g.:

```
let newSeries = HISeries()
newSeries.visible = false
...


self.chartView.options.series = [newSeries]
```

**Comment by DarrenAndes** [comment]
Please make this a feature request.... thank you.

**Comment by ihnatmoisieiev** [comment]
@DarrenAndes this feature has been added in the latest 7.0.2 release. Can I close it?
