### ISSUE TITLE
Please update the API docs!

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#146]
v6.2.0 includes so many API changes, but they are still undocumented in the docs. Please update the docs asap. HIHour, HIDay, HICSSObject for example: all missing.

**Comment by ihnatmoisieiev** [comment]
@skuske thank you for the remark! Docs will be updated soon.

**Comment by skuske** [comment]
@ihnatmoisieiev 

That was quick. Mayn thanks! :o)
