### ISSUE TITLE
In the iOS8 system, including Chinese will cause the chart to not display

### ISSUE THREAD

**Issue by xiongoahc** [highcharts/highcharts-ios#15]
for example：the DataSources.json like this
[
    {
        "title": "你好",
        "subtitle": "",
        "source": "DataSteps",
        "unit": "steps",
        "chartType": "area",
        "icon": "ic_directions_walk",
        "exporting": false
    },
    {
        "title": "我爱中国",
        "subtitle": "",
        "source": "DataCaloriesOut",
        "unit": "kcal",
        "chartType": "column",
        "icon": "ic_whatshot",
        "exporting": false
     },
     {
         "title": "Calories (Eaten)",
         "subtitle": "",
         "source": "DataCaloriesIn",
         "unit": "kcal",
         "chartType": "spline",
         "icon": "ic_local_dining",
         "exporting": false
     }
 ]

**Comment by sebastianbochan** [comment]
Hi @xiongoahc 
Thank you for the reporting. We will investigate the issue as soon as possible.

**Comment by ihnatmoisieiev** [comment]
@xiongoahc, it is fixed in the newest release.

**Comment by ihnatmoisieiev** [comment]
@xiongoahc can I close it?

**Comment by xiongoahc** [comment]
Of course,Thanks
