### ISSUE TITLE
Include of non-modular header inside framework module 'Highcharts'

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#150]
Hello,

First of all thanks for such library. I am using:

    Highcharts : 7.0.1
    xcode : 10.1
    swift : 4.2
    cocoapods : 1.5.3

Podfile : (partial)

    platform` :ios, '9.3'
    use_modular_headers!
    inhibit_all_warnings!
    
    source 'https://github.com/CocoaPods/Specs.git'
    
    def XXX_pods
        pod 'Highcharts', '~> 7.0.1'
    ...

I am getting this error when trying to compile my project after adding Highcharts pod definition into my podfile :

    XXX/Pods/Highcharts/development/Highcharts.framework/Headers/Highcharts.h:18:9: Include of non-modular header inside framework module 'Highcharts': 'XXX/Pods/Headers/Public/Highcharts/Highcharts/HIGChartView.h'
    
    XXX/Pods/Highcharts/development/Highcharts.framework/Headers/Highcharts.h:20:9: Include of non-modular header inside framework module 'Highcharts': 'XXX/Pods/Headers/Public/Highcharts/Highcharts/HIChartView.h'
    
    XXX/Pods/Highcharts/development/Highcharts.framework/Headers/Highcharts.h:22:9: Include of non-modular header inside framework module 'Highcharts': 'XXX/Pods/Headers/Public/Highcharts/Highcharts/UIColor+HIG.h'
    
    XXX/Pods/Highcharts/development/Highcharts.framework/Headers/Highcharts.h:23:9: Include of non-modular header inside framework module 'Highcharts': 'XXX/Pods/Headers/Public/Highcharts/Highcharts/UIImage+HIG.h'
    
    XXX/Pods/Highcharts/development/Highcharts.framework/Headers/Highcharts.h:25:9: Include of non-modular header inside framework module 'Highcharts': 'XXX/Pods/Headers/Public/Highcharts/Highcharts/HIBridge.h'
    
    XXX/YYY/Controllers/MMFPad/MMFPadViewController.swift:12:8: Could not build Objective-C module 'Highcharts'

Best

**Comment by ergunkocak** [comment]
I forked to see if i can fix on my own and make a pull request but it is not possible :) So can this be the source of problem? https://medium.com/@florentmorin/integrating-swift-framework-with-non-modular-libraries-d18098049e18

**Comment by ihnatmoisieiev** [comment]
Hello @ergunkocak,
thank you for choosing Highcharts!

I have just tried the following Podfile:
```
platform :ios, '9.3'
use_modular_headers!
inhibit_all_warnings!

target 'XXX' do
  pod 'Highcharts', '~> 7.0.1'
end
```

and I haven't got these errors. 

Could you provide some additional info about your `Podfile`?

**Comment by ihnatmoisieiev** [comment]
@ergunkocak I guess it is not a source of the problem. Did you try to set `Allow Non-modular Includes in Framework Modules` to `YES`?

**Comment by ergunkocak** [comment]
Yes in main main target it is set to yes. I will change it and inform you about the result.

**Comment by ergunkocak** [comment]
Setting it to false in main target did not change anything. After rereading your comment you already suggested setting it to YES :) so in the second attempt set main project build settings and set it to YES. Checked all targets and their respective settings became yes as well. Deleted Cleaned project, "Derived Data", removed "Pods" folder and "Podfile.lock" reinstalled pods. Same result :(

**Comment by ergunkocak** [comment]
I created an empty project with a single view application. Everything compiled until i allowed "Allow Non-modular Includes in Framework Modules" to "YES".

Even i changed it back the error did not go away. I can send the sample project as a zip so you can investigate further? We have license by the way shall i contact support instead?

**Comment by ihnatmoisieiev** [comment]
@ergunkocak ok, please send me your new project here.

**Comment by ergunkocak** [comment]
[highcharts-test.zip](https://github.com/highcharts/highcharts-ios/files/2772429/highcharts-test.zip)

**Comment by ergunkocak** [comment]
I removed "Pods" folder to reduce size. fyi

**Comment by ihnatmoisieiev** [comment]
@ergunkocak I have found the problem. You are using a `use_modular_headers!` for static libraries, but `Highcharts` is dynamic. 
Please, uncomment `use_frameworks!` and delete `use_modular_headers!` from your `Podfile`. I hope it should work and help you.

**Comment by ergunkocak** [comment]
@ihnatmoisieiev First of all thanks very much for fast and to the point responses. The problem is we use pods as static libraries on purpose. It reduces the app launch time and also reduces the APK size. We did not have any issues with this approach since today. As you can see more than 30 libraries we use (including Google, Firebase, Facebook and Reactive) has no problems with static libraries. And we dont want to change our approach which will cause our app to open slower and become larger. We will  be really glad if you can find a solution to this problem.

King Regards

**Comment by ihnatmoisieiev** [comment]
@ergunkocak, in this case, I can only suggest you add the following to your `Podfile` to choosing between dynamic or static linking:

```
use_frameworks!
...
dynamic_frameworks = ['Highcharts']

target 'XXX' do
   pod 'Highcharts', '~> 7.0.1'
   ...
end

# make all the other frameworks into static frameworks
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !dynamic_frameworks.include?(pod.name)
      def pod.static_framework?;
        true
      end
    end
  end
end
```

Please, let me know if this solution is acceptable.

**Comment by ergunkocak** [comment]
@ihnatmoisieiev I tried the solution you suggested. But if i analyzed correctly it has no difference than using just "use_frameworks!" ? Am i missing something? I am saying this because i could not see any static includes after applying this.

**Comment by ergunkocak** [comment]
As an alternative i tried manually including the "Highcharts.framework" file in "https://github.com/highcharts/highcharts-ios/tree/master/release/" but i got this error while compiling : 

    ld: warning: ignoring file /XXX/Library/Highcharts/Highcharts.framework/Highcharts, missing required architecture x86_64 in file /XXX/Library/Highcharts/Highcharts.framework/Highcharts (3 slices)
    Undefined symbols for architecture x86_64

**Comment by ihnatmoisieiev** [comment]
@ergunkocak I have found the above solution here [https://github.com/CocoaPods/CocoaPods/issues/7428#issuecomment-377864948](https://github.com/CocoaPods/CocoaPods/issues/7428#issuecomment-377864948). It should compile all libraries (except `Highcharts`) as static. Have you tried to run `pod deintegrate` ?

There are two builds: [development](https://github.com/highcharts/highcharts-ios/tree/master/development) and [release](https://github.com/highcharts/highcharts-ios/tree/master/release). If you run in a simulator, you have to use development version.

**Comment by ergunkocak** [comment]
"Embedded Binaries" and development version solved the issues. Now i am looking for a way to automate this. Like; if app is running in debug mode use the framework for development otherwise use the framework for release. If you implemented such thing before your directions are more than welcome :)

**Comment by ihnatmoisieiev** [comment]
@ergunkocak, unfortunately, I haven't implemented it yet.

**Comment by ergunkocak** [comment]
Thanks. I can use this way and try to find a solution for automation. Do you know when "use_modular_headers!" will be supported?

**Comment by ihnatmoisieiev** [comment]
@ergunkocak I suppose that static library won't be supported in the near future.

**Comment by ergunkocak** [comment]
With all the respect, why not? Does it take too much development time? or is it not possible without exposing the code?

**Comment by ihnatmoisieiev** [comment]
@ergunkocak thank you for your attention. You can add it to [UserVoice](https://highcharts.uservoice.com/forums/55896-general) for Highcharts iOS and maybe it will be added to the iOS wrapper.

**Comment by ergunkocak** [comment]
Added to user voice : https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/36562006-static-library-support 

To developers who experience the same; please upvote it :)

**Comment by mll** [comment]
Hi @ergunkocak! This is a side note, but to my knowledge the *dynamic* frameworks allow the app to load faster as the dynamic part is loaded during runtime hence can be delayed until needed (https://www.ca.com/en/blog-developers/dynamic-versus-static-framework-in-ios.html). Could you please reference some resources that demonstrate your point of getting faster loading and smaller footprint using *static* libraries?

**Comment by ergunkocak** [comment]
Hi @mll, As of cocoapods 1.50 they supported this feature because of performance: http://blog.cocoapods.org/CocoaPods-1.5.0/ . Also we experienced a 30 percent size shrink in our app because of switching to static libraries. I also remember a wwdc video explaining the performance differences. I will share that as well as soon as i have time to look for it.
