### ISSUE TITLE
Variable Pie in Swift

### ISSUE THREAD

**Issue by AndrewGOlson33** [highcharts/highcharts-ios#151]
I am trying to make a variable pie chart in swift.

https://github.com/highcharts/highcharts-ios/issues/61

I am referencing this issue but I cant figure it out. I was seeing if anyone would figure out what exactly I was doing wrong :)

`self.chartView = HIChartView(frame: self.view.bounds)
        
        let options = HIOptions()
        let chart = HIChart()
        let exporting = HIExporting()
        exporting.enabled = false
        
        chart.type = "variablepie"
        options.chart = chart
        
        let title = HITitle()
        title.text = "stuff"
        let subtitle = HISubtitle()
        
        subtitle.text = "more stuff"
        options.title = title
        options.subtitle = subtitle
        
        let plotoptions = HIPlotOptions()
        plotoptions.variablepie = HIVariablepie()
        plotoptions.variablepie.minPointSize = 10
        plotoptions.variablepie.innerSize = "20%"
        plotoptions.variablepie.zMin = 0
        plotoptions.variablepie.name = "name"
        plotoptions.variablepie.data = [
            ["name": "Microsoft Internet Explorer","x": 56.33, "y": 56.33],
            ["name": "Chrome","x": 24.03, "y": 24.03],
            ["name": "Firefox","x": 14.03, "y": 10.38],
            ["name": "Safari","x": 4.03, "y": 4.77],
            ["name": "Opera","x": 1.03, "y": 0.91],
            ["name": "Proprietary or Undetectable","x": 0.3, "y": 0.2]]
        
        print(plotoptions.variablepie.data)
        options.series = [plotoptions.variablepie]
        
        self.chartView.options = options
        self.view.addSubview(self.chartView)`

**Comment by AndrewGOlson33** [comment]
I just used a objective c to swift conveter and got it

**Comment by ergunkocak** [comment]
@AndrewGOlson33 Would you share the working version if you manage to make it work? Best
