### ISSUE TITLE
Unable to get series object inside tap event closure !!

### ISSUE THREAD

**Issue by karthikShiva1997** [highcharts/highcharts-ios#154]
pie.point = HIPoint()
        pie.point.events = HIEvents()
        pie.point.events.click = HIFunction(closure: { (context)  in
            guard let context = context else {return}
            print("Point Object ->>",context.getProperty("this.series") as? HISeries)
        }, properties: ["this.series"])
        

    Hey, I am looking to retrieve the series object associated with the tapped point but it doesn't seem           to work !!

**Comment by ihnatmoisieiev** [comment]
Hello @karthikShiva1997,
it is impossible. You only can get some `Series` properties like index, name, etc. Try:

```
pie.point = HIPoint()
pie.point.events = HIEvents()
pie.point.events.click = HIFunction(closure: { (context)  in
        guard let context = context else {return}
        print("Series index ->>", context.getProperty("this.series.index"))
}, properties: ["this.series.index"])
```

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 can I close the issue?
