### ISSUE TITLE
Legends scrolling and border !

### ISSUE THREAD

**Issue by karthikShiva1997** [highcharts/highcharts-ios#155]
The Legends currently scroll up and down on clicking the navigation buttons ! Is it possible to make it scroll without the use of these navigation buttons ? And the buttons sometimes feel unresponsive to touches !

Also, I am looking for a way to get a border between the chart and the legends ?
Are the above possible ?

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 
1) it isn't possible to scroll the legends without using navigation buttons. Give me please more info when it doesn't work. 

2) Could you send your `HIChartView` options? We need to see your chart.

**Comment by karthikShiva1997** [comment]
The following is my HIOptions Configuration ! Also for some reason, the legend maxHeight does        not take effect !
        highCharts.chartPlotOptions.series.dataLabels = HIDataLabels()
        highCharts.chartPlotOptions.series.dataLabels.enabled = false
        
        highCharts.chartPlotOptions.pie = HIPie()
        highCharts.chartPlotOptions.pie.showInLegend = true

        highCharts.chartOptions.legend = HILegend()
        highCharts.chartOptions.legend.maxHeight = 10
![image 2019-01-28 04_23_37 11 pm png](https://user-images.githubusercontent.com/41145258/51832185-fdc1c580-2319-11e9-9fce-86415c71942a.jpeg)

        highCharts.chart.events = HIEvents()
        highCharts.chart.events.load = HIFunction(jsFunction: "function () { var chart = this, r = chart.renderer, legend = chart.legend.group, y = legend.translateY; r.path(['M', 0, y, 'L', chart.plotLeft + chart.plotWidth, y]) .attr({ 'stroke-width': 0.5, stroke: '#2f2f2f', zIndex: 1 }) .add() }")

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 it isn't possible at the moment, but you could add it to [UserVoice](https://highcharts.uservoice.com/forums/55896-general).
