### ISSUE TITLE
HIColor outputs the wrong color !

### ISSUE THREAD

**Issue by karthikShiva1997** [highcharts/highcharts-ios#156]
I have an  UIColor(red:0.95, green:0.95, blue:0.96, alpha:1.0) object ! When i use the UIColor init() for HIColor, I get a deep black color instead of what was supposed to be pale grey ! But, I get the right color when I use HexColor init() of HIColor.

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 thank you for the reporting a bug. We will investigate it as soon as possible.

**Comment by ihnatmoisieiev** [comment]
@karthikShiva1997 the bug will be fixed in the next release.
