### ISSUE TITLE
Dynamic Data Animation and xAxis scroll

### ISSUE THREAD

**Issue by DmitriyLupych** [highcharts/highcharts-ios#157]
Hello!

First of all, thank you for a great library! 

I'm trying to create spline chart with several lines and dynamic data using Swift. For example, server push new part of data - and I want to redraw chart with it.

For this purpose I'm currently using update method something like this: self.chartView.options.series = [spline1, spline2, spline3, spline4, spline5]

**Problem:** This code adds new data to chart but it redraws itself without any animation. Also, chart scales after every new point added. I want graph to move along xAxis from right to left while adding new points, and animate drawing of every new point. How can I reach this effect, like on your site? [https://www.highcharts.com/ios/demo/dynamic-update](https://www.highcharts.com/ios/demo/dynamic-update)

**Comment by ihnatmoisieiev** [comment]
Hello @DmitriyLupych,
thank you for choosing Highcharts!

Yes, it redraws itself without animation. But, for example, you can call an `addPoint:` or `setSeriesData:` method from `HISeries` object to add new data with animation. This feature is available from 7.0.2 version. Please, try it and let me know.

**Comment by DmitriyLupych** [comment]
Hello @ihnatmoisieiev , thanks for your response!

Can you please provide some code for example? If I'm not mistaken, addPoint refers to JS (or HiFunction), not to HiSeries class in Swift..

**Comment by ihnatmoisieiev** [comment]
@DmitriyLupych methods from JS have been added to iOS classes in the newest release. Example:

```
let newPoint = HIData()
newPoint.y = 100
self.chartView.options.series[0].addPoint(newPoint, redraw: true, shift: true)
```

**Comment by ihnatmoisieiev** [comment]
@DmitriyLupych try to set up scrollablePlotArea param of chart object, e.g.:

```
let chart = HIChart()
chart.scrollablePlotArea = HIScrollablePlotArea()
chart.scrollablePlotArea.minWidth = 1000
chart.scrollablePlotArea.scrollPositionX = 1
options.chart = chart
```

**Comment by DmitriyLupych** [comment]
@ihnatmoisieiev I've set this [http://prntscr.com/mfafc6](http://prntscr.com/mfafc6), but after adding new points I have this picture: 
normal step: [http://prntscr.com/mfagre](http://prntscr.com/mfagre)
steps shrink: [http://prntscr.com/mfah7a](http://prntscr.com/mfah7a)

How can I prevent this shrinking effect and make step between points constant?

**Comment by ihnatmoisieiev** [comment]
@DmitriyLupych I have tried it and haven't got any shrinking effect. Do you have some sample data to get this?

![test](https://user-images.githubusercontent.com/11294008/52198397-f1ca8c00-2862-11e9-9ac0-eb8612c6f51a.gif)

**Comment by DmitriyLupych** [comment]
@ihnatmoisieiev Hello! Good behavior of chart, that is what i'm trying to achieve!

Here is my test sample project: I have 5 random data streams and they are described on single chart. Maybe, I've missed something?

[https://drive.google.com/open?id=1yBuuk_C7GapURYbjsAQfkXWmIFSoZtAt](https://drive.google.com/open?id=1yBuuk_C7GapURYbjsAQfkXWmIFSoZtAt)

**Comment by ihnatmoisieiev** [comment]
@DmitriyLupych ok, I have debugged your code. Try to remove this line:
```
xaxis.categories = []
```
and set `tickInterval` or `tickPixelInterval` on `xaxis`, e.g.
```
xaxis.tickPixelInterval = 150
```

**Comment by DmitriyLupych** [comment]
@ihnatmoisieiev I've already played with tickPixelInterval/tickInterval - no results( chart shrinks as always.

Maybe the problem is in scroll area - the more points are added, the "shrinker" chart becomes?

**Comment by ihnatmoisieiev** [comment]
@DmitriyLupych after removing `xaxis.categories = []` and setting `xaxis.tickPixelInterval` it isn't 'shrink' for me:

[https://drive.google.com/file/d/1VsDEE5RD1OTlowZqJ-rpkxq-JUMAzVjp/view?usp=sharing](https://drive.google.com/file/d/1VsDEE5RD1OTlowZqJ-rpkxq-JUMAzVjp/view?usp=sharing)

**Comment by DmitriyLupych** [comment]
@ihnatmoisieiev look at the distance between points at start and in the end - it shrinks..

Is there any option, to make it constant? Ideally: by adding new points chart scrolls from right to left and distance between points always is the same

start: [http://prntscr.com/mgg1z7](http://prntscr.com/mgg1z7)
end:   [http://prntscr.com/mgg2je](http://prntscr.com/mgg2je)

**Comment by DmitriyLupych** [comment]
@ihnatmoisieiev thanks a lot! It help in my case! Hope, this thread will help many iOS developers in creating beautiful charts :)
