### ISSUE TITLE
DataLabel color missing in version 7.0.3

### ISSUE THREAD

**Issue by arunavasumathi** [highcharts/highcharts-ios#159]
Hi,

The styles which I set to the data labels using version 7.0.3 is not getting reflected. Earlier I used version 6.1.0 in which the data label styles worked as expected.

This is my style code in which "(in percent)" would be in a different color (e28507). Please let me know if I am missing something while updating the style related objects.

        let dataLabel = HIDataLabels()
        dataLabel.rotation = 270
        dataLabel.align = "center"
        dataLabel.y = -20
        dataLabel.overflow = false
        dataLabel.allowOverlap = true
        dataLabel.crop = false
        dataLabel.enabled = true
        dataLabel.useHTML = true
        dataLabel.color = HIColor(hexValue: "000")
        
        let dataLabelCSS = HICSSObject()
        dataLabelCSS.fontSize = "9px"
        dataLabelCSS.fontFamily = "Helvetica"
        dataLabelCSS.fontWeight = "semibold"
        let _jsFunc = "function() { var yData = this.y; var labelValue; labelValue = '<span style = ' + 'color:#000' + '>'+yData+'</span>'; if (yData == 0) { labelValue += ''; } else { labelValue += '<span style =' + 'color:#e28507' + ';font-weight:bold' + '>' + ' (in percent)' + '</span>'; } return labelValue; }"
        let _labelFormatter = HIFunction(jsFunction: _jsFunc)
        dataLabel.formatter = _labelFormatter
        dataLabel.style = dataLabelCSS

**Comment by ihnatmoisieiev** [comment]
Hello @arunavasumathi,

your style related objects `HIDataLabels` and `HICSSObject` looks ok. 

But I have found some errors in your `_jsFunc`. Try:

```
let _jsFunc = "function() { var yData = this.y; var labelValue = '<span style=\"color:#000\">' + yData + '</span>'; if (yData != 0) { labelValue += '<span style=\"color:#e28507;font-weight:bold\"> (in percent)</span>'; } return labelValue; }"
```

**Comment by arunavasumathi** [comment]
Hi @ihnatmoisieiev 

This is the exact jsfunction which I am using 

    let _jsFunc = "function() { var percentile = Number(((this.y - this.point.prev) / this.point.prev * 100).toFixed(0)); var yData = this.y; if (yData > 100) { yData = Highcharts.numberFormat(yData, 0, ',', ','); } var labelValue; var percent = percentile; labelValue = '<span style = ' + 'color:#000' + '>'+yData+'</span>'; if (yData == 0) { labelValue += ''; } else { labelValue += '<span style =' + 'color:#e28507' + ';font-weight:bold' + '>' + ' : ' + percent + '</span>'; } return labelValue; }"


which works as expected in Highcharts version 6.1.4, whereas the same is not displaying the specified color in version 7.0.3

Here is my HILine object:

       var data_dict = [NSMutableDictionary]()
        var val = [2342,2423,4364,3453,5677,3456,6768,1234,5645]
        var prev = [1233,3431,2212,4223,3345,2334,5322,456,4566]
        for i in 0..<7 {
            let h = NSMutableDictionary()
            h.setValue(val[i], forKey: "y")
            h.setValue(prev[i], forKey: "prev")
            data_dict.append(h)
        }
        let options1 = HIOptions()
        let line11 = HILine()
        line11.data = data_dict
        line11.name = "Data"
        line11.allowPointSelect = true
        line11.showInLegend = true
        line11.dataLabels = dataLabel


Can you please clarify me, what I am missing?

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi you are missing double quotes inside your `<span>` element in `_jsFunc`.
I have changed your `_jsFunc`. Try it:
```
let _jsFunc = "function() { var percentile = Number(((this.y - this.point.prev) / this.point.prev * 100).toFixed(0)); var yData = this.y; if (yData > 100) { yData = Highcharts.numberFormat(yData, 0, ',', ','); } var labelValue = '<span style=\"color:#000\">' + yData + '</span>'; if (yData != 0) { labelValue += '<span style=\"color:#e28507;font-weight:bold\">' + ' : ' + percentile + '</span>'; } return labelValue; }"
```
I hope it will work as expected.

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi have you tried it?

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev yes. it works. thank you. 
i still have a question on the jsFunc. in the jsFunc which you gave, if i include this condition if (yData == 0) { labelValue += ''; } that still doesn't work. Could you please clarify?

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi it should work, but maybe do you have a `tooltip.shared` set to `true`?

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev yes. i do.

        let toolTip = HITooltip()
        toolTip.enabled = true
        toolTip.useHTML = true
        toolTip.formatter = HIFunction(jsFunction: "function() {return false;}")
        toolTip.shared = true

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi ok, I've checked it and it works for me. Try:

```
let _jsFunc = "function() { var percentile = Number(((this.y - this.point.prev) / this.point.prev * 100).toFixed(0)); var yData = this.y; if (yData > 100) { yData = Highcharts.numberFormat(yData, 0, ',', ','); } var labelValue = '<span style=\"color:#000\">' + yData + '</span>'; if (yData === 0) { labelValue += ''; } else { labelValue += '<span style=\"color:#e28507;font-weight:bold\">' + ' : ' + percentile + '</span>'; } return labelValue; }"
```

**Comment by arunavasumathi** [comment]
Thank you @ihnatmoisieiev
