### ISSUE TITLE
Y-axis Line Overlapping on Plotline 

### ISSUE THREAD

**Issue by codal-aabid** [highcharts/highcharts-ios#160]
Hi Team,
I am using the HightChart iOS SDK for the mobile app. I am facing one issue here. Y-axis line is overlapping on plot line (Goal). Actually, the plotline is a solid-dash line but here it looks like the double dash line because of Y-axis grey line overlapping on the goal line.
You can refer the attached screenshot. I highlighted the issue with the **RED BOX** in Image.
Please do needful, How to bring up the plot line.
![img_0222](https://user-images.githubusercontent.com/20509761/52496634-83a30380-2b99-11e9-800b-f2f16a15b445.PNG)

**Comment by ihnatmoisieiev** [comment]
Hello @codal-aabid,
thank you for the reporting!
Did you try adding a `zIndex` to your plotline?

**Comment by codal-aabid** [comment]
Hi @ihnatmoisieiev 
Thanks! for your help
Now I able to change the plotline order by using **zIndex**  
Thanks Once again for your valuable help.
