### ISSUE TITLE
MenuButton

### ISSUE THREAD

**Issue by cherry143** [highcharts/highcharts-ios#161]
Hi this is my code and it does not work, quick answer would be appreciated.  Thanks!

HIExporting* exporting = [[HIExporting alloc] init];
    exporting.enabled = false;
    options.exporting = exporting;

**Comment by ihnatmoisieiev** [comment]
Hello @cherry143,
did you set your view controller to `HIChartView`?
`chartView.viewController = self`

**Comment by ihnatmoisieiev** [comment]
@cherry143 I have noticed that you want to hide the export button. In this case, see [https://github.com/highcharts/highcharts-ios/issues/47](https://github.com/highcharts/highcharts-ios/issues/47) and try:

```
HIExporting *exporting = [[HIExporting alloc] init];
exporting.enabled = [[NSNumber alloc] initWithBool:false];
options.exporting = exporting;
```

**Comment by ihnatmoisieiev** [comment]
@cherry143 did it resolve your problem?

**Comment by cherry143** [comment]
Thanks for your quick response!
