### ISSUE TITLE
Reload/Update Data

### ISSUE THREAD

**Issue by cherry143** [highcharts/highcharts-ios#163]
Hi, 
I have to reload or update array data into the pieChart, but how?
In API method like, 
                                                _pie_ChartData.values=[NSArray arrayWithArray:arr] ;
                                                [_pie_ChartData update];

Written as,
-(void)instanceForPieChart{   
  
//    self.chartView = [[HIChartView alloc] initWithFrame:_view_pieChartBackground.frame];
    HIOptions *options = [[HIOptions alloc]init];
    HIChart *chart = [[HIChart alloc]init];
    chart.type = @"pie"; 
    
    HIExporting *exporting = [[HIExporting alloc] init];
    exporting.enabled = [[NSNumber alloc] initWithBool:false];
    options.exporting = exporting;
    
    //    HIExporting* exporting = [[HIExporting alloc] init];
    //    exporting.enabled = false;
    //    options.exporting = exporting;
    
    options.credits.text = @"";
    
    //    options.exporting.enabled = NO;
    
    HITitle *title = [[HITitle alloc]init];
    title.text = @"Percentage Holdings";
    options.title = title;
    
    HIPie *series = [[HIPie alloc]init];
    _chartView.delegate = self;
    series.innerSize = @[@50,@50];
    series.shadow = [NSNumber numberWithInt:100];
    series.data = @[arr_Consolidata]; //not working 
    options.series = @[series];
    self.chartView.options = options;
    
    [self.chartView updateOptions];
    
//    [self.view addSubview:self.chartView];
}

Expecting quick response. Thanks in advance!

**Comment by ihnatmoisieiev** [comment]
@cherry143,
you have two options:

1. `self.chartView.options.series[0].data = newDataArray;`
2. `[self.chartView.options.series[0] setData: newDataArray];`

**Comment by cherry143** [comment]
Thanks man! That was too quick.

**Comment by cherry143** [comment]
One more i need to ask you that how to change the slice name.

**Comment by ihnatmoisieiev** [comment]
@cherry143 what do you mean by 'slice name' ?

**Comment by cherry143** [comment]
![highcharts pie](https://user-images.githubusercontent.com/42531833/53465469-0bcb4900-3a74-11e9-8c7d-4112df243090.png)

I need to have the same in my application as there are countries (slice)

**Comment by ihnatmoisieiev** [comment]
@cherry143 see this [demo](https://www.highcharts.com/ios/demo/pie-basic).

**Comment by cherry143** [comment]
Thanks buddy! it worked.
