### ISSUE TITLE
Can't make testflight build xcode says signing is failed.

### ISSUE THREAD

**Issue by devidasm** [highcharts/highcharts-ios#164]
When i started to build an archive with xcode for a testflight build  I got an error (See image link below)
[See error screenshot](https://i.imgur.com/y1ew4gZ.png)
Have anyone encountered this issue.
Please help me.

**Comment by ihnatmoisieiev** [comment]
Hello @devidasm,
thank you for choosing Highcharts!

What version of the framework are you using: 
[development](https://github.com/highcharts/highcharts-ios/tree/master/development) or [release](https://github.com/highcharts/highcharts-ios/tree/master/release)?

**Comment by devidasm** [comment]
Version 7.0.3
https://github.com/highcharts/highcharts-ios/releases/download/v7.0.3/Highcharts.framework.zip

I have used the above one.  I didn't used pod, manually added the framework.

**Comment by devidasm** [comment]
> Hello @devidasm,
> thank you for choosing Highcharts!
> 
> What version of the framework are you using: [development](https://github.com/highcharts/highcharts-ios/tree/master/development) or [release](https://github.com/highcharts/highcharts-ios/tree/master/release)?

Version 7.0.3
https://github.com/highcharts/highcharts-ios/releases/download/v7.0.3/Highcharts.framework.zip

I have used the above one. I didn't used pod, manually added the framework.

**Comment by ihnatmoisieiev** [comment]
@devidasm the framework from [release](https://github.com/highcharts/highcharts-ios/tree/master/release) folder should work. Please try one more time and let me know.

**Comment by ihnatmoisieiev** [comment]
@devidasm Can I close the issue?

**Comment by devidasm** [comment]
Yes its working with release framework.
