### ISSUE TITLE
No Data Option

### ISSUE THREAD

**Issue by cherry143** [highcharts/highcharts-ios#165]
Hi

#1
Below code is not working that I want to show if array is equal to zero.

_chartView.lang.noData = @"No Data To Display";

#2 

Want to rotate the Pie Chart, is there any option to use?

Thanks!

**Comment by ihnatmoisieiev** [comment]
Hello @cherry143,

1. Did you set your `lang` object before assigning `options` object, i.e.

```
chartView.lang = [[HILang alloc] init];
chartView.lang.noData = @"No Data To Display";
    
...
    
chartView.options = options;
```
?

2. Yes, you can rotate your Pie Chart by setting `startAngle` param, e.g.:
```
plotoptions.pie.startAngle = @90;
```

**Comment by cherry143** [comment]
Thanks for the quick response!

**Comment by cherry143** [comment]
Not working...

**Comment by cherry143** [comment]
It is not working. 

The rotation is working but I want to rotate by touching

**Comment by ihnatmoisieiev** [comment]
@cherry143 it is impossible, but you can implement it by yourself.

**Comment by cherry143** [comment]
Hello, the below code is not working...!

chartView.lang = [[HILang alloc] init];

chartView.lang.noData = @"No Data To Display";

>>>  I have to hide the chart view, how?

**Comment by ihnatmoisieiev** [comment]
@cherry143 

1. You need to add `no-data-to-display` module. See full example:

```
HIChartView *chartView = [[HIChartView alloc] initWithFrame:self.view.bounds];
chartView.plugins = @[@"no-data-to-display"];

HILang *lang = [[HILang alloc] init];
lang.noData = @"No Data To Display";
    
chartView.lang = lang;

HIOptions *options = [[HIOptions alloc] init];

...

chartView.options = options;
```

![screen](https://user-images.githubusercontent.com/11294008/53718556-d2bc1b80-3e5b-11e9-81b5-17ea4b72ae96.png)

2. `[chartView setHidden:true];`

3. 
```
HITitle *title = [[HITitle alloc] init];
title.text = @"";
```

**Comment by cherry143** [comment]
Thanks buddy, the "No Data To Display" is working.

Still getting  Chart Title at header and I need to hide it. When I put it in hidden even there is data chart is not appearing. I need to hide only the "Chart Title" field. Thanks!

**Comment by ihnatmoisieiev** [comment]
@cherry143 see iOS [docs](https://api.highcharts.com/ios/highcharts/) and JS [docs](https://api.highcharts.com/highcharts/noData) for more info.

You need to set up `noData` object from `options`:

```
HINoData *noData = [[HINoData alloc] init];
noData.style = [[HICSSObject alloc] init];
noData.style.fontSize = @"30px";
options.noData = noData;
```

**Comment by cherry143** [comment]
Thanks dude, done with chart. You helped me a lot!

**Comment by sushil7271** [comment]
@ihnatmoisieiev Thanks, dude it worked
