### ISSUE TITLE
showLastLabel not showing last x-Axis label

### ISSUE THREAD

**Issue by arunavasumathi** [highcharts/highcharts-ios#166]
Hi,

I set xAxis.showLastLabel = true, but in the xAxis the last label is not shown. 
I am also setting label.step = 2 or 1 depending on the chart displayed.
Please help.

**Comment by ihnatmoisieiev** [comment]
Hi @arunavasumathi,
try this example:
```
let options = HIOptions()
        
let xAxis = HIXAxis()
xAxis.endOnTick = true
xAxis.showLastLabel = true
options.xAxis = [xAxis]
        
let series = HISeries()
series.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [series]
```

It works perfect for me.

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev Yes. The example works. But if I give step value like below, the last xAxis label is not showing up. If the step value is 1, I see the last label.

        let labels_x = HILabels()
        labels_x.rotation = 270
        labels_x.step = 2
        
        let label_x_Style = HICSSObject()
        labels_x.style = label_x_Style

       let xAxis = HIXAxis()
        xAxis.categories = ValuesArray
        xAxis.alignTicks = true
        xAxis.tickmarkPlacement = "off"
        xAxis.startOnTick = true
        xAxis.endOnTick = true
        xAxis.showLastLabel = true
        xAxis.labels = labels_x

**Comment by ihnatmoisieiev** [comment]
@arunavasumathi it is correct. The last label can not be displayed for some step values. For example, if I set the step value to 3 in my above example - I don't see the last label, but for 2 or 4 I do.

![zrzut ekranu 2019-03-6 o 08 13 20](https://user-images.githubusercontent.com/11294008/53862473-c95fba00-3fe7-11e9-80cd-237cebef494c.png)

![zrzut ekranu 2019-03-6 o 08 13 40](https://user-images.githubusercontent.com/11294008/53862479-ccf34100-3fe7-11e9-8d87-6ede1c5a4930.png)

```
let options = HIOptions()
        
let xAxis = HIXAxis()
xAxis.labels = HILabels()
xAxis.labels.step = 2
        
xAxis.startOnTick = true
xAxis.endOnTick = true
xAxis.showLastLabel = true
options.xAxis = [xAxis]

let series = HISeries()
series.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [series]
```

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev Thank you for the detail. But we have a website with chart constructed using Highcharts library in which, irrespective of the step count, they display the last x-Axis label. I want to achieve the same in mobile app as well. Please help.

**Comment by sebastianbochan** [comment]
Hi @arunavasumathi,
At this moment @ihnatmoisieiev explains you how it works in app and on desktop (the same core of functionality). The reason of differences is resolution only, but please recreate your "website example" in the jsfiddle.net. It will allow us to compare both scenarios and verify if its a bug or not.

Example of jsfiddle, which can be a good point to start:
- https://jsfiddle.net/BlackLabel/75b1qhdg/

**Comment by arunavasumathi** [comment]
I was able to achieve it using a chart render function, which the website used. Thank you @ihnatmoisieiev @sebastianbochan
