### ISSUE TITLE
DataLabels Font

### ISSUE THREAD

**Issue by cherry143** [highcharts/highcharts-ios#167]
![fullsizeoutput_b0](https://user-images.githubusercontent.com/42531833/53934445-e9b37580-40c8-11e9-8f5c-efe9f32d8b63.jpeg)
Hi below code is not working. I want to change the font size because in iPhone 5s the pie chart is getting smaller and data labels are a bit larger and some data labels missing even there is data, so it seems very disgusting. Thanks in advance!

                plotoptions.pie.dataLabels.style.fontSize = @"5px";

PS:Only on iPhone 5s...

One more problem is that small value dataLabel name not showing.

**Comment by ihnatmoisieiev** [comment]
@cherry143 send me please your chart options. Thanks!

**Comment by cherry143** [comment]
#pragma mark - start of piechart
                HILang*lang=[[HILang alloc]init];
                HIPie*pie_Data=[[HIPie alloc]init];
                HITitle*title=[[HITitle alloc]init];
                HIChart*chart= [[HIChart alloc]init];
                HINoData*noData=[[HINoData alloc]init];
                HITooltip*tooltip=[[HITooltip alloc]init];
                HIOptions*options= [[HIOptions alloc]init];
                HIExporting*exporting=[[HIExporting alloc]init];
                HIPlotOptions*plotoptions=[[HIPlotOptions alloc]init];
                
                noData.style = [[HICSSObject alloc] init];
                noData.style.fontSize = @"10px";
                noData.style.fontFamily = KTGeorgia;
                options.noData = noData;
                _chartView.plugins = @[@"no-data-to-display"];
                lang.noData = @"No Data To Display";
                _chartView.lang = lang;
                chart.type = @"pie";
                exporting.enabled = [[NSNumber alloc] initWithBool:false];
                options.exporting = exporting;
                options.credits.text = @"";
                title.text = @"";
                options.title = title;
                tooltip.pointFormat = @"{series.name}:<b>{point.percentage:.1f}%</b>";
                tooltip.backgroundColor = [[HIColor alloc] initWithUIColor:[UIColor whiteColor]];
                plotoptions.pie = [[HIPie alloc]init];
                plotoptions.pie.allowPointSelect = [[NSNumber alloc] initWithBool:true];
                plotoptions.pie.dataLabels = [[HIDataLabels alloc]init];
                plotoptions.pie.dataLabels.style.fontSize = @"2px";
                plotoptions.pie.dataLabels.enabled = [[NSNumber alloc] initWithBool:true];
                plotoptions.pie.showInLegend = [[NSNumber alloc] initWithBool:false];
                pie_Data.innerSize = @[@50];
                pie_Data.shadow = [NSNumber numberWithInt:20.f];
                options.series = @[pie_Data];
                options.tooltip = tooltip;
                self.chartView.options = options;
                options.plotOptions = plotoptions;
                options.series = [NSMutableArray arrayWithObjects:pie_Data,  nil];
                pie_Data.name = @"Current Value";
                NSMutableArray *arr=[NSMutableArray new];
                for (NSDictionary *dic in arr_ConsoliData) {
                    NSMutableDictionary *mut_dic=[NSMutableDictionary new];
                    [mut_dic setObject:dic[@"AMC"] forKey:@"name"];
                    [mut_dic setObject:dic[@"Current Value"] forKey:@"y"];
                    [arr addObject:mut_dic];
                }
                    pie_Data.data = [NSArray arrayWithArray:arr];
                    _chartView.options =  options;
                    [self.chartView updateOptions];
#pragma mark - end of piechart

**Comment by ihnatmoisieiev** [comment]
Hi @cherry143,

the dataLabel name not showing because there is not enough space to fit it. Try to set the dataLabels font size to smaller. The below demo works perfectly for me on iPhone 5s:

```
    HIChartView *chartView = [[HIChartView alloc] initWithFrame:self.view.bounds];
    
    HIChart *chart = [[HIChart alloc]init];
    chart.type = @"pie";
    chart.plotShadow = [[NSNumber alloc] initWithBool:false];
    
    HITitle *title = [[HITitle alloc]init];
    title.text = @"Browser market shares January, 2015 to May, 2015";
    
    HITooltip *tooltip = [[HITooltip alloc]init];
    tooltip.pointFormat = @"{series.name}: <b>{point.percentage:.1f}%</b>";
    
    HIPlotOptions *plotOptions = [[HIPlotOptions alloc]init];
    plotOptions.pie = [[HIPie alloc]init];
    plotOptions.pie.allowPointSelect = [[NSNumber alloc] initWithBool:true];
    plotOptions.pie.cursor = @"pointer";
    plotOptions.pie.dataLabels = [[HIDataLabels alloc]init];
    plotOptions.pie.dataLabels.enabled = [[NSNumber alloc] initWithBool:true];
    plotOptions.pie.dataLabels.format = @"<b>{point.name}</b>: {point.percentage:.1f} %";
    plotOptions.pie.dataLabels.style = [[HICSSObject alloc] init];
    plotOptions.pie.dataLabels.style.color = @"black";
    plotOptions.pie.dataLabels.style.fontSize = @"15px";
    
    HIPie *pie = [[HIPie alloc]init];
    pie.name = @"Brands";
    pie.data = [NSMutableArray arrayWithObjects:@{
                                                  @"name": @"Microsoft Internet Explorer",
                                                  @"y": @56.33
                                                  },
                @{
                  @"name": @"Chrome",
                  @"y": @24.03,
                  @"sliced": [[NSNumber alloc] initWithBool:true],
                  @"selected": [[NSNumber alloc] initWithBool:true]
                  },
                @{
                  @"name": @"Firefox",
                  @"y": @10.38
                  },
                @{
                  @"name": @"Safari",
                  @"y": @4.77
                  },
                @{
                  @"name": @"Opera",
                  @"y": @0.91
                  },
                @{
                  @"name": @"Proprietary or Undetectable",
                  @"y": @0.2
                  }, nil];
    
    HIOptions *options = [[HIOptions alloc]init];
    options.chart = chart;
    options.title = title;
    options.tooltip = tooltip;
    options.plotOptions = plotOptions;
    options.series = [NSMutableArray arrayWithObjects:pie, nil];
    
    chartView.options = options;
    
    [self.view addSubview:chartView];
```

<img width="504" alt="2019-03-07 19 46 24" src="https://user-images.githubusercontent.com/11294008/53980993-02944900-4112-11e9-8501-3c7f92ce53c1.png">

<img width="504" alt="2019-03-07 19 46 00" src="https://user-images.githubusercontent.com/11294008/53980984-fd36fe80-4111-11e9-93c5-e3032dabf74b.png">

**Comment by cherry143** [comment]
Thanks for the response, but the line is not effecting why? I told you already at my first comment!!

as per the below line, the fontSize has to be changed but nothing happening...seems to be default

                plotoptions.pie.dataLabels.style.fontSize = @"20px";

**Comment by ihnatmoisieiev** [comment]
@cherry143 I have shared the [demo](https://github.com/highcharts/highcharts-ios/issues/167#issuecomment-470647585) where `fontSize` works perfectly for me on iPhone 5s. Please, check your code. Can I close the issue?

**Comment by cherry143** [comment]
Thanks man! Its working...

You can close this but one last issue that dataLabel names are still missing, what should I do? everything okay except this issue... is there  any other way? may be the pointer size...

**Comment by cherry143** [comment]
This is from your demo... see how the dataLabels are missing 


![Screen Shot 2019-03-13 at 3 14 11 PM](https://user-images.githubusercontent.com/42531833/54269396-4cae7c00-45a3-11e9-808f-a96bd617d701.png)

**Comment by cherry143** [comment]
This is from your demo... see how the dataLabels are missing...




![Screen Shot 2019-03-13 at 3 14 11 PM](https://user-images.githubusercontent.com/42531833/54269700-d6f6e000-45a3-11e9-91ec-951c5fb95caf.png)

**Comment by ihnatmoisieiev** [comment]
@cherry143 ok, thank you for the screens. When there is not enough space for dataLabels, the smallest values (`point.y`) are hidden. You can try to slightly increase the space by setting `dataLabels.padding` to `0`:
```
plotOptions.pie.dataLabels.padding = @0;
```
