### ISSUE TITLE
Tooltip jumps to previous point

### ISSUE THREAD

**Issue by marcinmatczuk** [highcharts/highcharts-ios#168]
I'm using Highcharts iOS wrapper 7.0.3 on iOS 12.1.4 and use the wrapper to plot time-series data (XY).

On the chart tooltip displays correctly, but when it follows the touch, upon finger up, most of the time tooltip jumps back to one of previous points or even to the starting point.

My tooltip setup:
```
useHTML = true
shared = true
formatter = // custom formatter, same for both iOS and Android just to format timestamp and use 2 decimal places for value
```
Crosshair has `snap` set to `true`.
The rest of setup is colors, width, etc.

Notes:
1. When tapping on screen, the tooltip displays at correctly place and stays there until dismissed.
2. Not reproducible on Android wrapper.

Possible workaround:
1. Automatically hide tooltip on finger up, but afaik that's not possible currently - am I correct?

There is a similiar issue reported in main JS highcharts repo: [#2870](https://github.com/highcharts/highcharts/issues/2870), but it seems to be abandoned.

**Comment by ihnatmoisieiev** [comment]
@marcinmatczuk thank you for the reporting! I will report it! [#2870](https://github.com/highcharts/highcharts/issues/2870)

**Comment by ihnatmoisieiev** [comment]
[#2870](https://github.com/highcharts/highcharts/issues/2870)

**Comment by marcinmatczuk** [comment]
@ihnatmoisieiev , I'd like to have this issue re-opened, as I've reproduced it on your demo app, HighFit.
You can download all the changes to app and video demonstrating the issue from dropbox: https://www.dropbox.com/s/7m85y90ulss145f/highcharts-ios-issues-168.zip?dl=0

Please see the video and observe as tooltip jump.
Changes to HighFit:
- for month data of calories in, I've copied pasted it three times to have more points in series
- I've disabled scrolling in DataTableViewController as it's easier to reproduce.
Reproducible on 7.0.3

**Comment by ihnatmoisieiev** [comment]
Hi @marcinmatczuk,

please reopen here [#2870](https://github.com/highcharts/highcharts/issues/2870).
