### ISSUE TITLE
How to dismiss/hide tooltip together with crosshair? 

### ISSUE THREAD

**Issue by marcinmatczuk** [highcharts/highcharts-ios#169]
How to programatically hide tooltip together with crosshair? 
In my usecase, after device rotation I'd like to hide them.

**Comment by ihnatmoisieiev** [comment]
Hi @marcinmatczuk,

thank you for your question. First of all, you need to set crosshair width in your chart config.

You have two options to hide tooltip and crosshair:

1. Update feature:
```
self.chartView.options.tooltip.enabled = false
self.chartView.options.xAxis[0].crosshair.width = 0
```

2. Class methods
```
let options = HIOptions()
let tooltip = HITooltip()
tooltip.enabled = false
options.tooltip = tooltip
self.chartView.update(options)
            
let xAxis = HIXAxis()
xAxis.crosshair = HICrosshair()
xAxis.crosshair.width = 0
self.chartView.options.xAxis[0].update(xAxis)
```

**Comment by marcinmatczuk** [comment]
@ihnatmoisieiev , thanks for providing options here. Much appreciated!

What worked for me is the following:
```
self.chartView.options.tooltip.enabled = false
self.chartView.options.xAxis[0].crosshair.width = 0

self.chartView.options.tooltip.enabled = true
self.chartView.options.xAxis[0].crosshair.width = originalWidth

```

Unless above is not recommended, or you do plan to implement "proper" tooltip hiding, I can go with this solution and you can close the issue.

**Comment by ihnatmoisieiev** [comment]
@marcinmatczuk the above two solutions works and are recommended.

**Comment by ihnatmoisieiev** [comment]
@marcinmatczuk Can I close the issue?
