### ISSUE TITLE
Solidgauge - threshold not working/plotOption 'rounded' missing

### ISSUE THREAD

**Issue by ZuzanaBenicko** [highcharts/highcharts-ios#17]
Hello,

Solid-gauge's threshold attribute seems not to work, it makes no change in series start point. It always start where the yAxis.min is set.

Also I would like to ask if I can get rounded series bar as in picture, in plotOption object is no rounded attribute.

Thanks!
<img width="403" alt="snimka obrazovky 2017-07-12 o 16 10 52" src="https://user-images.githubusercontent.com/9416708/28121947-0d50797a-671d-11e7-9851-25f387fe4834.png">

**Comment by pawelfus** [comment]
Hi @ZuzanaBenicko 

Threshold works for me, please take a look: http://jsfiddle.net/gxz17vy1/ - could you recreate issue using my demo?

Regarding bars and rounded corners, you can use this plugin: https://github.com/highcharts/rounded-corners

**Comment by ZuzanaBenicko** [comment]
Hello Pawel,

thank you for Your reply. 
Unfortunately, I am not sure, what I am doing wrong but as you can see in included screenshot threshold is set in code but not in graph. Every attribute is set as in you demo.

Simillary my second question was meant how to set rounded Solid-gouge in Xcode, or at least if there is this opportunity at all.

Thank you for your time and have a nice day,
Zuzana Benickova

**Comment by pawelfus** [comment]
Hi @ZuzanaBenicko 

My apologies, it was my mistake, I thought you reported this issue on Highcharts, not Highcharts iOS. My previous comment was removed.

**Comment by ihnatmoisieiev** [comment]
Hello @ZuzanaBenicko,

we are actually working to add rounded attribute of solidgauge.

**Comment by TorsteinHonsi** [comment]
This option was added in Highcharts v5.0.8: http://api.highcharts.com/highcharts/plotOptions.solidgauge.rounded

**Comment by ihnatmoisieiev** [comment]
@ZuzanaBenicko it is added in the newest release.

**Comment by ihnatmoisieiev** [comment]
@ZuzanaBenicko can I close it?

**Comment by ZuzanaBenicko** [comment]
Yes, thank you.
