### ISSUE TITLE
Graph not showing large dataset

### ISSUE THREAD

**Issue by ezefire** [highcharts/highcharts-ios#172]
When showing a large dataset the chart shows only the "noData"
In the pictures you can see the number of items to show, and the result

<img width="260" alt="Screenshot 2019-03-18 at 11 25 09" src="https://user-images.githubusercontent.com/4618466/54523755-91a22c00-4970-11e9-84b8-4fcef2937a20.png">
<img width="361" alt="Screenshot 2019-03-18 at 11 25 26" src="https://user-images.githubusercontent.com/4618466/54523757-91a22c00-4970-11e9-9ce0-a532040a9366.png">

**Comment by ihnatmoisieiev** [comment]
Hi @ezefire,
did you try to use a `boost` module? Try:
```
let boost = HIBoost()
boost.useGPUTranslations = true
options.boost = boost
```

**Comment by ezefire** [comment]
Hi @ihnatmoisieiev, I tried to use HIBoost but nothing changed

I have done the following changes:

```
        let boost = HIBoost()
        boost.enabled = true
        boost.seriesThreshold = 2 
        boost.useGPUTranslations = true
        options.boost = boost

       let plotOptions = HIPlotOptions()
        ....
        plotOptions.column.boostThreshold = 1000
        ....   
        plotOptions.line.boostThreshold = 1000
        ....
        plotOptions.series.boostThreshold = 1000
        
        
        ....
         chartView.plugins = ["no-data-to-display", "boost"] 
```

**Comment by ihnatmoisieiev** [comment]
Hi @ezefire,
so, it could be too many points to render the chart.
I have one remark, you should set `chartView.plugins` before assigning chart's options.

**Comment by ihnatmoisieiev** [comment]
@ezefire can I close the issue?

**Comment by pruharikantamipara** [comment]
i'm facing same issue is data more than 1000 then it will showing blank view. i done with above solution but i did't get anything can you please help me out @ihnatmoisieiev @ezefire thank you in advance.

- data not showing more than 1000+
- also not showing gradient color i have added code below can you guide if i wrong anywhere.
- aslo crash at - > plotOptions.column.boostThreshold = 1000 and plotOptions.line.boostThreshold = 1000

       `let chartView = HIChartView(frame: view.bounds)
        chartView.plugins = ["no-data-to-display", "boost"]
        
        let options = HIOptions()

        let chart = HIChart()
        chart.type = "area"
        options.chart = chart

        let boost = HIBoost()
        let plotOptions = HIPlotOptions()
        plotOptions.area = HIArea()
        plotOptions.series = HISeries()

        boost.enabled = true
        boost.allowForce = true
        boost.seriesThreshold = 2
        boost.useGPUTranslations = true
        options.boost = boost

       plotOptions.area.boostThreshold = 1000
       plotOptions.column.boostThreshold = 1000
       plotOptions.line.boostThreshold = 1000
       plotOptions.series.boostThreshold = 1000

        options.chart = chart

        let title = HITitle()
        title.text = ""
        options.title = title

        let subtitle = HISubtitle()
        subtitle.text = ""
        options.subtitle = subtitle

        let xaxis = HIXAxis()
        xaxis.labels = HILabels()
        xaxis.labels.formatter = HIFunction(jsFunction: "function () { return Highcharts.dateFormat('%e %b %Y', this.value) }") 
        xaxis.type = "datetime"
        xaxis.dateTimeLabelFormats = HIDateTimeLabelFormats()
        xaxis.dateTimeLabelFormats.month = HIMonth()
        xaxis.dateTimeLabelFormats.month.main = "%b %Y"
        xaxis.dateTimeLabelFormats.year = HIYear()
        xaxis.dateTimeLabelFormats.year.main = "%b"
        xaxis.title = HITitle()
        xaxis.title.text = ""

        let yAxis = HIYAxis()
        yAxis.title = HITitle()
        yAxis.title.text = ""
        yAxis.labels = HILabels()
        yAxis.labels.enabled = false
        yAxis.labels.formatter = HIFunction(jsFunction: "function () { return this.value ; }")

        plotOptions.series.cursor = "pointer"
        plotOptions.series.point = HIPoint()
        plotOptions.series.point.events = HIEvents()

        plotOptions.area.fillColor = HIColor(linearGradient: ["x1": 0, "y1": 0, "x2": 0, "y2": 150], stops: [[0, "rgba(255,255,255, 0.75)"], [1, "rgba(255,255,255, 0.02)"]])

        plotOptions.area.pointStart = NSNumber(value: 9 * 60 + 15)
        plotOptions.area.pointInterval = NSNumber(value: 24 * 3600 * 1000) // one day
        plotOptions.area.marker = HIMarker()
        plotOptions.area.marker.enabled = false
        plotOptions.area.marker.symbol = "circle"
        plotOptions.area.marker.radius = 1
        plotOptions.area.marker.states = HIStates()
        plotOptions.area.marker.states.hover = HIHover()
        plotOptions.area.marker.states.hover.enabled = true

        plotOptions.series.point.events.click = HIFunction(jsFunction: "function (e) { hs.htmlExpand(null, { pageOrigin: { x: e.pageX || e.clientX, y: e.pageY || e.clientY }, headingText: this.series.name, maincontentText: Highcharts.dateFormat('%e %b %Y', this.x) + ':<br/> ' + this.y + ' visits', width: 300 }); }")
        plotOptions.series.marker = HIMarker()
        plotOptions.series.marker.lineWidth = 2

        let usa = HIArea()
        usa.name = ""
        usa.color = HIColor(uiColor: UIColor.orange)
        usa.data = [NSNull()]

        for ii in 0..<self.mutArrBrokingChart[0].count //- 240
        {
            let strDate = self.arrChart[0][ii]["volume"].intValue
            let strPrice = self.arrChart[0][ii]["price"].doubleValue
            usa.data.insert([strDate,strPrice], at: ii)
            print("date price",strDate, strPrice, ii)
        }

        options.xAxis = [xaxis]
        options.yAxis = [yAxis]
        options.plotOptions = plotOptions
        options.series = [usa]
        chartView.options = options

        self.view.addSubview(chartView)`
