### ISSUE TITLE
Crash with HIYAxis getParams on Iphone 5

### ISSUE THREAD

**Issue by ezefire** [highcharts/highcharts-ios#173]
I'm having the following crash when running the app in iPhone 5 with ios 10.3.3

I have made tests in simulators and it crashes on simulator with iPhone 5 and iOS 10.3.1 but it works on iPhone 5s with iOS 10.3.1

<img width="1223" alt="Screenshot 2019-03-18 at 15 49 44" src="https://user-images.githubusercontent.com/4618466/54539075-c4125000-4995-11e9-82ce-7a9e048f3148.png">

**Comment by ihnatmoisieiev** [comment]
Hello @ezefire,
share please your chart config.

**Comment by ezefire** [comment]
Hi @ihnatmoisieiev, 
Yes sure:

`    private func createChart() -> HIChartView{

        let chartView = YChartView(frame: CGRect(x: 0, y: 0, width: 320, height: 500))
        
        let options = HIOptions()
       
        let scrollableArea = HIScrollablePlotArea()
        scrollableArea.minWidth = 1000
        
        let chart = HIChart()
        chart.type = "column"
        chart.scrollablePlotArea = scrollableArea
        options.chart = chart
        
        let title = HITitle()
        title.text = ""
        options.title = title
        
        //Hides a menu that appears
        let exporting = HIExporting()
        exporting.enabled = false
        options.exporting = exporting
        
        //Hides text Tooltip over the columns and points
        let tooltip = HITooltip()
        tooltip.enabled = false
        options.tooltip = tooltip
        
        //xAxis
        let xAxis = HIXAxis()
        options.xAxis = [xAxis]
        
        //yAxis
        let yAxis = HIYAxis()
        yAxis.title = HITitle()
        yAxis.title.text = ""
        
        let stackLabels = HIStackLabels()
        stackLabels.enabled = true
        stackLabels.useHTML = true
        
        yAxis.stackLabels = stackLabels
        options.yAxis = [yAxis]
        
        let legend = HILegend()
        legend.layout = "vertical"
        legend.itemMarginBottom = 5
        options.legend = legend
        
        let noData = HINoData()
        noData.style = HICSSObject()
        noData.style.color = UIColor.textColorDarker()?.toHex
        options.noData = noData
        
        let lang = HILang()
        lang.noData = ToolsRes.getString("no_data_available")
        chartView.lang = lang
        
        
        let plotOptions = HIPlotOptions()
        plotOptions.column = HIColumn()
        plotOptions.column.stacking = "normal"
        plotOptions.column.enableMouseTracking = false
        plotOptions.column.groupPadding = 0.02
        
        plotOptions.line = HILine()
        plotOptions.line.enableMouseTracking = false

        options.plotOptions = plotOptions
        
        
        let events = HIEvents()
        events.click = HIFunction(closure: { [weak self] (context) in
            guard let strongSelf = self, let context = context, let value = context.getProperty("event.xAxis[0].value") as? Double else { return }
            let index = Int(round(value))
            let selectedItem = strongSelf.charts_datas[index]
            
            strongSelf.onCategorySelected(name: selectedItem.key, data: selectedItem.value)
            
            }, properties: ["event.xAxis[0].value"])
        options.chart.events = events
        
        chartView.options = options
        chartView.plugins = ["no-data-to-display"]
        return chartView
    }`

**Comment by ihnatmoisieiev** [comment]
@ezefire thank you for options. The iPhone 5 is not already supported, but we will check what is going on as soon as possible. 
Thanks for the report!

**Comment by ezefire** [comment]
@ihnatmoisieiev Thanks for your help. 
After your response I remembered that I have seen the chart working in that device. So after thinking what changes I have made I downgraded the Highcharts version to 6.2.0 (the previous I was using in app) and now it works on that device. 
So it could be something modified in the last versions.

**Comment by ihnatmoisieiev** [comment]
@ezefire thank you for the info!

**Comment by LaurentKinomap** [comment]
Hi, it seems that this issue is still there. Reproduced on iPad 4 and iPad mini.
Any info on getting the fix in the latest version? We need to stay on version 7.0.1 which is an issue in the long term.
Laurent
