### ISSUE TITLE
Update scrollPositionX after data reloaded

### ISSUE THREAD

**Issue by ezefire** [highcharts/highcharts-ios#174]
How can I update the scrollPositionX property after I change the data in the chart? 

I tried many things but nothing happens. It is ok for the first time the data is showed in the chart but after that nothing happens.

This is what i'm using:

`      let scrollableArea = HIScrollablePlotArea()
        scrollableArea.minWidth = NSNumber(value: contentSize)
        scrollableArea.scrollPositionX =  NSNumber(value: scrollOffset)
        mChart.options.chart!.scrollablePlotArea = scrollableArea   `

where scrollOffset is a value between 0..1 calculated using the index i want to show and contentSize is the size to show all items

**Comment by ihnatmoisieiev** [comment]
@ezefire a quote from the [docs](https://api.highcharts.com/ios/highcharts/):

> **The initial scrolling position** of the scrollable plot area. Ranges from 0 to 1, where 0 aligns the plot area to the left and 1 aligns it to the right. Typically we would use 1 if the chart has right aligned Y axes.

So, you can set it only once before chart init. But you could try set new options (with updated data and scrollableArea):

```
mChart.options = newOptions
```

**Comment by ezefire** [comment]
@ihnatmoisieiev Thanks for your help.
After setting a new HiOptions object it updates the initial scroll correctly. Thanks
