### ISSUE TITLE
Stacked columns show two labels 

### ISSUE THREAD

**Issue by ezefire** [highcharts/highcharts-ios#175]
When one of the series has a negative value, and another serie has a positive value the stacked column is showing two different stacked labels, not only one with the result of the two.

What I need is to show always on top a label with the result of the addition of the showing series.

I'm using:

```
       let plotOptions = HIPlotOptions()
        plotOptions.column = HIColumn()
        plotOptions.column.stacking = "normal"

       .....


        let stackLabels = HIStackLabels()
        stackLabels.enabled = true
        stackLabels.useHTML = true

        yAxis.stackLabels = stackLabels

        .....

         options.yAxis[0].stackLabels.formatter = formatter
```

<img width="607" alt="Screenshot 2019-03-20 at 12 40 38" src="https://user-images.githubusercontent.com/4618466/54681733-656fe200-4b0d-11e9-9822-4244f265749a.png">

**Comment by ihnatmoisieiev** [comment]
@ezefire see [https://github.com/highcharts/highcharts/issues/8843](https://github.com/highcharts/highcharts/issues/8843).
