### ISSUE TITLE
moment.js is not included in the framework bundle

### ISSUE THREAD

**Issue by alpono** [highcharts/highcharts-ios#176]
We are using iOS wrapper for HICharts library (version 7.0.3). Currently, we are facing a problem that we need to draw charts with respect to time zones.

As far as we know, it can be achieved by using “moment-timezone-with-data.js” and “moment.js” plugins. We’ve tried to enable these plugins using such call:

chartsView.plugins = [“no-data-to-display”,
                                   “moment.min”,
                                   “moment-timezone-with-data.min”]

However, the problem is that HiCharts cannot find this module as they are not included in the bundle inside the framework. So every time app draws chart we got this in log output:

[ Highcharts ]: js/modules/moment.min.js, dont exits!
[ Highcharts ]: js/modules/moment-timezone-with-data.min.js, dont exits!

Could you please let us know how correctly add these plugins to our app? Is there a way the framework can reach this plugin without adding them to the framework bundle? Where should we place “moment-timezone-with-data.js” and “moment.js” files so HiCharts can access them? Maybe some additional configuration needed?

**Comment by ihnatmoisieiev** [comment]
Hi @alpono,
there is no way to add additional modules to the framework at the moment. But from what I know, `moment-timezone-with-data.js` and `moment.js` will be added to the wrappers in the next release.

**Comment by marcinmatczuk** [comment]
@ihnatmoisieiev, what's the ETA for next release? I'd appreciate if you provided a specific date rather then "within month", or "next week".

**Comment by ihnatmoisieiev** [comment]
@marcinmatczuk unfortunately, I can't provide the exact date of the next release. But I suppose ETA is end of next week.

**Comment by ihnatmoisieiev** [comment]
@alpono @marcinmatczuk `moment.js` and `moment-timezone-with-data.js` have been added to the latest release.
