### ISSUE TITLE
After a while - HIChart becomes white.

### ISSUE THREAD

**Issue by YardenTR** [highcharts/highcharts-ios#177]
Hi, I encountered to a bug in HighCharts for iOS
In some rare cases the HIChartView just becomes white rectangles after several minutes of regular usage in the app.
I uploaded an image from the app: [https://imgur.com/gRPekzV](url)

It's not happening every time, but it still occurs to some of the users.
I would like to know if you guys are encountered the same bug and maybe have a  solution?

Waiting for you reply.
Thanks a lot.

**Comment by ihnatmoisieiev** [comment]
Hi @YardenTR,
thank you for the reporting.

We have never encountered this issue. Unfortunately, I can't open the image. Does it happen for certain chart options? If yes, could you share these options?

**Comment by YardenTR** [comment]
Try this url: [https://i.ibb.co/QPFK2Yt/image-2018-10-15-11-10-10-889.png](https://i.ibb.co/QPFK2Yt/image-2018-10-15-11-10-10-889.png)

It occur with different charts and options.
Im using HIChartView in UITableView and UICollectionView (reusable scroll views)
Although, I make sure I'm not initialising or setting an already updated chart.

**Comment by ihnatmoisieiev** [comment]
@YardenTR what version of the framework are you using? 
Have you added `HIChartView.preload()` to your AppDelegate `didFinishLaunchingWithOptions` method? Do you have any animations in your charts?

Please note that `HIChartView` loads the chart asynchronously, so you should be careful using charts inside `UITableView` or `UICollectionView`. See related [issue](https://github.com/highcharts/highcharts-ios/issues/138).

**Comment by YardenTR** [comment]
Hi the project has version 6.1.4 of Highcharts.
I didn't have these preload functions (HIChartView.preload()), in AppDelegate class, I will add it.

And actually the image I uploaded is HighChartView in a regular UIView and not in a reusable component.
However I do use in other screens- charts in UITableView or UICollectionView.

Thanks for your quick answer!

**Comment by ihnatmoisieiev** [comment]
@YardenTR did it help you? 

Could you please send your chart options? I'll try to reproduce it.

**Comment by YardenTR** [comment]
Yes, I did.
 And here an example for PieChart:
````
 let chartView = HIChartView.init(frame: frame)
 chartView.isUserInteractionEnabled = false
 let options = HIOptions()
 options.credits = HICredits()
 options.credits.enabled = NSNumber(booleanLiteral: false)
 options.title = HITitle()
 options.title.text = ""
 options.subtitle = HISubtitle()
 options.subtitle.text = ""
 options.legend = HILegend()
 options.legend.enabled = NSNumber(booleanLiteral: false)
 options.plotOptions = HIPlotOptions.init()
 chartView.options = options
 
 let chart = HIChart()
 chart.backgroundColor = HIColor.init(uiColor: .clear)
 chart.type = "pie"
 chartView.options.chart = chart
 chartView.options.time = HITime()
 chartView.options.time.timezoneOffset = NSNumber(integerLiteral: -1 * 3 * 60)
 chartView.options.tooltip = HITooltip()
 chartView.options.tooltip.enabled = NSNumber(booleanLiteral: false)
 chartView.options.exporting = HIExporting()
 chartView.options.exporting.enabled = NSNumber(booleanLiteral: false)
 let pie = HIPie()
 pie.data = pieMaterial.data.map({ return ["", $0.1] })
 pie.colors = pieMaterial.colors.map({ HIColor(hexValue: $0.rawValue.replacingOccurrences(of: "#", with: "")) })
 pie.dataLabels = HIDataLabels()
 pie.dataLabels.enabled = NSNumber(booleanLiteral: false)
 pie.borderColor = HIColor(uiColor: .clear)
 pie.innerSize = "\(pieMaterial.innerSize)%"
 chartView.options.series = [pie]
````

Im updating the chartView (every X minutes) with this code: (I make sure I have new or other data to display)
````
let pie =  chartView.options.series.last as? HIPie
pie?.data = material.data.map({ return ["", $0.1] })
pie?.colors = material.colors.map({ HIColor(hexValue: $0.rawValue.replacingOccurrences(of: "#", with: "")) })
chartView.updateOptions()
````

**Comment by ihnatmoisieiev** [comment]
@YardenTR first of all, your chart config is wrong. You have to set `HIChartView` options object exactly once before rendering a chart. The chart is rendered after setting options object i.e.
 `chartView.options = options`. Any set inside options object causes the chart to redraw, e.g. `chartView.options.chart = chart, chartView.options.time = HITime()`, etc. 

I've modified your options in the right way:

```
let chartView = HIChartView(frame: frame)
chartView.isUserInteractionEnabled = false

let options = HIOptions()

let credits = HICredits()
credits.enabled = false
options.credits = credits

let title = HITitle()
title.text = ""
options.title = title

let subtitle = HISubtitle()
subtitle.text = ""
options.subtitle = subtitle

let legend = HILegend()
legend.enabled = false
options.legend = legend

let plotOptions = HIPlotOptions()
options.plotOptions = plotOptions

let chart = HIChart()
chart.backgroundColor = HIColor.init(uiColor: .clear)
chart.type = "pie"
options.chart = chart

let time = HITime()
time.timezoneOffset = NSNumber(integerLiteral: -1 * 3 * 60)
options.time = time

let tooltip = HITooltip()
tooltip.enabled = false
options.tooltip = tooltip

let exporting = HIExporting()
exporting.enabled = false
options.exporting = exporting

let pie = HIPie()
pie.data = pieMaterial.data.map({ return ["", $0.1] })
pie.colors = pieMaterial.colors.map({ HIColor(hexValue: $0.rawValue.replacingOccurrences(of: "#", with: "")) })
pie.dataLabels = HIDataLabels()
pie.dataLabels.enabled = false
pie.borderColor = HIColor(uiColor: .clear)
pie.innerSize = "\(pieMaterial.innerSize)%"
options.series = [pie]

chartView.options = options
```

I've noticed that you want to modify only a series object. You can do it in two ways:

1.
```
let pie = self.chartView.options.series.last as! HIPie
pie.data = material.data.map({ return ["", $0.1] })
pie.colors = material.colors.map({ HIColor(hexValue: $0.rawValue.replacingOccurrences(of: "#", with: "")) })
```
It's not neccessary to call `chartView.updateOptions()`. The chart will be updated automatically.

2.
```
let updatedPie = HIPie()
updatedPie.data = material.data.map({ return ["", $0.1] })
updatedPie.colors = material.colors.map({ HIColor(hexValue: $0.rawValue.replacingOccurrences(of: "#", with: "")) })

let pie = self.chartView.options.series.last as! HIPie
pie.update(updatedPie)
```

Please, change these things and let me know if it helped!

**Comment by ihnatmoisieiev** [comment]
@YardenTR did it help you? Can I close the issue?

**Comment by YardenTR** [comment]
I think so, I did not encounter this bug in the past 2 weeks.
Thanks a lot!
