### ISSUE TITLE
piechart background

### ISSUE THREAD

**Issue by cherry143** [highcharts/highcharts-ios#179]
Hi,

I need to change background colour of my pie chart, but how?

below codes are not working...

HIChart*chart= [[HIChart alloc]init];

chart.backgroundColor = [HIColor alloc] initWithUIColor:[UIColor whiteColor];

                                                                               OR

chart.backgroundColor = [[HIColor alloc] initWithRGBA:0 green:1 blue:2 alpha:1.0];

**Comment by soommy12** [comment]
Hello @cherry143  ! Did you attach `HIChart` object to your options?

**Comment by cherry143** [comment]
It is showing while am trying to add like this,

chart.options3d????

chart.options = options; 

are you expecting like this?

**Comment by soommy12** [comment]
First of all you need to add `chart` class to your options:
`options.chart = chart;`
when your options are set you should add them to your chart view:
`chartView.options = options;`

**Comment by cherry143** [comment]
Thanks man... it worked!
