### ISSUE TITLE
Issue in uploading to iTunes

### ISSUE THREAD

**Issue by neerajcsa** [highcharts/highcharts-ios#18]
I have embedded Highcharts framework in my iOS app, when i am trying to upload it to on iTunes Connect, i am getting error.
Please see the attached screenshots.
![high-charts](https://user-images.githubusercontent.com/7921708/28418276-c2e43cd4-6d78-11e7-8b7e-b15006ab980f.png)

**Comment by mll** [comment]
Hi @neerajcsa. We are sorry to see this error. We are investigating the issue, will get back to you as soon as we understand what is causing it and have a fix.

**Comment by mll** [comment]
Hi @neerajcsa. We could not reproduce your problem. Please make sure that you have bitcode enabled in your project.

**Comment by mll** [comment]
You are trying to link against a fat binary. Apple does not allow fat binaries in the app store. Please use CocoaPods version or link directly against a framework from the 'release' directory.
