### ISSUE TITLE
HiDataLabels - methods changed with v7.1.1 ???

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#180]
After upgrading to v7.1.1, HIDataLabels no longer have the `'rotation'`, `'y'`, and the `'format`' properties. The API docs still lists them. What's the problem here? The changelog also does not state any changes for HIDataLabels

**Comment by ihnatmoisieiev** [comment]
Hi @skuske,

this has already been reported [https://github.com/highcharts/highcharts/issues/10546](https://github.com/highcharts/highcharts/issues/10546). Thank you for pointing it out!

**Comment by skuske** [comment]
@ihnatmoisieiev 

What exactly does that mean now? Will this be fixed soon, or what changes do we need to apply to our code to make it work with v7.1.1? Thanks.

**Comment by ihnatmoisieiev** [comment]
@skuske this will be fixed in the next release.

**Comment by skuske** [comment]
@ihnatmoisieiev 

OK, when will the next release be available? 

This is a serious critical issue as DataLabels can no longer be configured the way they should be configured. Or is there any other way to configure them in v7.1.1? If so, please post some sample code. Many thanks.

We are not just talking about the docs as mentioned in https://github.com/highcharts/highcharts/issues/10546

This is an API issue, and not just an issue to the docs.

**Comment by ihnatmoisieiev** [comment]
@skuske it would be fixed in v7.1.2. You're right, there is no other correct way to configure datalabels.

**Comment by skuske** [comment]
@ihnatmoisieiev 

When can we expect v7.1.2? We would like to use the new features of v7.1.1, but cannot do so due to the HIDataLabels issues...

**Comment by ihnatmoisieiev** [comment]
@skuske 

we don't know the exact date of releasing v7.1.2. But if you have something very urgent, I can report it.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Well, there is no way to configure HIDataLabels in 7.1.1, and that is an issue that is serious enough for us as there is no way to use 7.1.1 at all. Therefore I am wondering why the release of a fix for such a serious issue takes such a long time.

**Comment by sebastianbochan** [comment]
Hi @skuske,
I apologize for my late reply. We are still preparing and testing v7.1.2, which will be released next week.

Thank you for your patience.

**Comment by ihnatmoisieiev** [comment]
@skuske the issue has been fixed in the latest release.
