### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 211Yang** [highcharts/highcharts-ios#181]
it creshed when i use formatter 

cresh log is
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (HIFunction)'

**Comment by 211Yang** [comment]
when i called [self.aaChartView update:self.options];

**Comment by ihnatmoisieiev** [comment]
Hi @211Yang,
could you please send your chart options?

**Comment by 211Yang** [comment]
- (HIOptions *)options
{
    if (!_options) {
        _options = [[HIOptions alloc] init];
        HIChart *chart = [[HIChart alloc]init];
        _options.chart = chart;
        
        HIExporting *exporting = [[HIExporting alloc]init];
        exporting.enabled = @NO;
        _options.exporting = exporting;
        _options.navigation.enabled = @NO;
    _options.chart.type = @"column";
    _options.colors = self.colors;

        _options.credits.enabled = @NO;

        HITitle *title = [[HITitle alloc]init];
        title.text = @"";
        _options.title = title;

        HIPlotOptions *plotOptions = [[HIPlotOptions alloc]init];
        _options.plotOptions = plotOptions;
        HITooltip *tooltip = [[HITooltip alloc]init];
        tooltip.backgroundColor = [[HIColor alloc] initWithHexValue:@"565656"];
        tooltip.borderColor = [[HIColor alloc] initWithHexValue:@"565656"];
        tooltip.style = [[HICSSObject alloc] init];
        tooltip.style.color = @"rgb(255, 255, 255)";
        tooltip.formatter = [[HIFunction alloc] initWithJSFunction:[NSString stringWithFormat:@"function () {return '<b>' + this.x + '</b><br/>' +Math.floor(this.point.y/60)+'%@'+this.point.y%%60+'%@';}",Localize(@"时"), Localize(@"分")]];
        _options.tooltip = tooltip;

        HIXAxis *xaxis = [[HIXAxis alloc]init];
        xaxis.tickColor = [[HIColor alloc]initWithUIColor:[UIColor clearColor]];
        xaxis.lineColor = [[HIColor alloc]initWithHexValue:@"E9E9E9"];
        xaxis.labels = [[HILabels alloc]init];
        xaxis.labels.style = [[HICSSObject alloc] init];
        xaxis.labels.style.color = @"rgb(177, 177, 177)";
        xaxis.lineWidth = @1;
        xaxis.allowDecimals = @0;

        _options.xAxis = @[xaxis];
        
        HIYAxis *yaxis = [[HIYAxis alloc]init];
        yaxis.lineWidth = @0;
        yaxis.gridLineWidth = @0;
        yaxis.lineColor = [[HIColor alloc]initWithHexValue:@"E9E9E9"];
        yaxis.tickColor = [[HIColor alloc]initWithUIColor:[UIColor clearColor]];
        yaxis.labels = [[HILabels alloc]init];
        yaxis.labels.style = [[HICSSObject alloc] init];
        yaxis.labels.style.color = @"rgb(177, 177, 177)";
//        yaxis.labels.style.textOutline = @"10px Arial";
        yaxis.labels.x = @-5;
        yaxis.title = [[HITitle alloc]init];
        yaxis.title.text = @"";
        yaxis.allowDecimals = @0;
        yaxis.min = @0;

        _options.yAxis = @[yaxis];

    }
    
    return _options;
}

Localize() is defined as follows
#define Localize(key) NSLocalizedString(key,@"")

**Comment by ihnatmoisieiev** [comment]
@211Yang thank you for the reporting! It would be fixed in the next release.

**Comment by 211Yang** [comment]
ok,thanks

but i have other question, dateTimeLabelFormats appears day unit when use hour unit, 

so i checked the HIDateTimeLabelFormats Class Reference 
shows For intermediate values, different units may be used, for example the day unit can be used on midnight and hour unit be used for intermediate values on the same axis

what should i do when i just want to use only hour unit ,help my, thanks!

**Comment by ihnatmoisieiev** [comment]
@211Yang the issue has been fixed in the latest release.
