### ISSUE TITLE
How to auto show tooltip?

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#183]
Is there any way to auto show a specific tooltip after chart generation? I found the following, but that does not seem to work on iOS:

`chart.tooltip.refresh(chart.series[0].data[1]);`

from http://jsfiddle.net/90uafg7a/3

Thanks for any help. :o)

**Comment by ihnatmoisieiev** [comment]
Hi @skuske,

try to add this to the chart `load` event:

```
let chart = HIChart()
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: "function () { this.tooltip.refresh(this.series[0].data[1]); }")
options.chart = chart
```

**Comment by skuske** [comment]
Thanks! :o)
