### ISSUE TITLE
two unit on xaxis

### ISSUE THREAD

**Issue by 211Yang** [highcharts/highcharts-ios#184]
but i have other question, dateTimeLabelFormats appears day unit when use hour unit, 

so i checked the HIDateTimeLabelFormats Class Reference 
shows For intermediate values, different units may be used, for example the day unit can be used on midnight and hour unit be used for intermediate values on the same axis

what should i do when i just want to use only hour unit ,help my, thanks!

**Comment by ihnatmoisieiev** [comment]
Hi @211Yang,

could you please send your chart options? I'll check what is going on.

**Comment by 211Yang** [comment]
sorry, i know what wrong, i forgot to set the hour format. thanks!
