### ISSUE TITLE
Tap Event in bar charts

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#185]
Hello Boss,
I am using Highcharts
@IBOutlet weak var viewChart : HIChartView!
i want to tab in my chart

let chart = HIChart()
chart.type = "column"

*HIPlotOptions plotOptions = [[HIPlotOptions alloc] init];
plotOptions.series = [[HISeries alloc] init];
plotOptions.series.point = [[HIPoint alloc] init];
plotOptions.series.point.events = [[HIEvents alloc] init];
plotOptions.series.point.events.click = function;
options.plotOptions = plotOptions;

or also

UITapGestureRecognizer

not working for me please help me how to get Tap in my chart

Thank you so much for help in advance

**Comment by ihnatmoisieiev** [comment]
Hi @barotbhavesh,

see `HIFunction example` from [README](https://github.com/highcharts/highcharts-ios/blob/master/README.md).
