### ISSUE TITLE
crashed didFailNavigation:Error Domain=NSURLErrorDomain

### ISSUE THREAD

**Issue by 211Yang** [highcharts/highcharts-ios#186]
crashed on wkwebview 

when i click quickly to push a highcharts controller ,some times it will crash

so i hook the  delegate method on 
 - (void)webView:(WKWebView *)webView didFailNavigation:(null_unspecified WKNavigation *)navigation withError:(NSError *)error

and print the error as follows, i confused

didFailNavigation:Error Domain=NSURLErrorDomain Code=-999 "(null)" UserInfo={NSErrorFailingURLKey=file:///var/mobile/Containers/Data/Application/FD98FD35-9D8E-45D2-9417-BFC2EB5C3920/tmp/com.highcharts.charts.bundle/, _WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x174428560>, NSErrorFailingURLStringKey=file:///var/mobile/Containers/Data/Application/FD98FD35-9D8E-45D2-9417-BFC2EB5C3920/tmp/com.highcharts.charts.bundle/}

**Comment by 211Yang** [comment]
sorry, i should say push a controller contains HIChartView , maybe is the wkwebview delegate have not release on the dealloc method cause the cresh

i write a HIChartView category as follows

@implementation HIChartView (Hook)

#pragma mark - Method Swizzling
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
//        Class class = [super class];

        // When swizzling a class method, use the following:
        // Class class = object_getClass((id)self);

        [HIChartView replaceoriginalSelector:@selector(webViewWebContentProcessDidTerminate:) swizzledSelector:@selector(replaced_webViewWebContentProcessDidTerminate:)];
        
        [HIChartView replaceoriginalSelector:@selector(webView:didFinishNavigation:) swizzledSelector:@selector(replaced_webView:didFinishNavigation:)];

        [HIChartView replaceoriginalSelector:@selector(webView:didFailNavigation:withError:) swizzledSelector:@selector(replaced_webView:didFailNavigation:withError:)];

        [HIChartView replaceoriginalSelector:@selector(webView:didFailProvisionalNavigation:withError:) swizzledSelector:@selector(replaced_webView:didFailProvisionalNavigation:withError:)];
        
        
        [HIChartView replaceoriginalSelector:@selector(webView:decidePolicyForNavigationResponse:decisionHandler:) swizzledSelector:@selector(replaced_webView:decidePolicyForNavigationResponse:decisionHandler:)];
        
        [HIChartView replaceoriginalSelector:@selector(webView:didStartProvisionalNavigation:) swizzledSelector:@selector(replaced_webView:didStartProvisionalNavigation:)];
        
        [HIChartView replaceoriginalSelector:@selector(webView:didReceiveServerRedirectForProvisionalNavigation:) swizzledSelector:@selector(replaced_webView:didReceiveServerRedirectForProvisionalNavigation:)];
        
        [HIChartView replaceoriginalSelector:@selector(webView:decidePolicyForNavigationAction:decisionHandler:) swizzledSelector:@selector(replaced_webView:decidePolicyForNavigationAction:decisionHandler:)];


    });
}

+ (void)replaceoriginalSelector:(SEL)originalSelector swizzledSelector:(SEL)swizzledSelector
{
    Method originalMethod = class_getInstanceMethod([super class], originalSelector);
    Method swizzledMethod = class_getInstanceMethod([super class], swizzledSelector);
    
    BOOL didAddMethod =
    class_addMethod([super class],
                    originalSelector,
                    method_getImplementation(swizzledMethod),
                    method_getTypeEncoding(swizzledMethod));
    
    if (didAddMethod) {
        class_replaceMethod([super class],
                            swizzledSelector,
                            method_getImplementation(originalMethod),
                            method_getTypeEncoding(originalMethod));
    } else {
        method_exchangeImplementations(originalMethod, swizzledMethod);
    }

}


- (void)replaced_webView:(WKWebView *)webView didFinishNavigation:(null_unspecified WKNavigation *)navigation
{
    NSLog(@"didFinishNavigation");
    [self replaced_webView:webView didFinishNavigation:navigation];
    
}
- (void)replaced_webViewWebContentProcessDidTerminate:(WKWebView *)webView NS_AVAILABLE(10_11, 9_0){
    
    NSLog(@"进程被终止");
    [webView reload];
//    [self replaced_webViewWebContentProcessDidTerminate:webView];
    
}


- (void)replaced_webView:(WKWebView *)webView didFailProvisionalNavigation:(null_unspecified WKNavigation *)navigation withError:(NSError *)error
{
    NSLog(@"didFailProvisionalNavigation:%@",error);
    [self replaced_webView:webView didFailProvisionalNavigation:navigation withError:error];

}
//
- (void)replaced_webView:(WKWebView *)webView didFailNavigation:(null_unspecified WKNavigation *)navigation withError:(NSError *)error
{
    NSLog(@"didFailNavigation:%@",error);
    [self replaced_webView:webView didFailNavigation:navigation withError:error];
}


- (void)replaced_webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler
{
    NSLog(@"decidePolicyForNavigationAction");
    [self replaced_webView:webView decidePolicyForNavigationAction:navigationAction decisionHandler:decisionHandler];
//    decisionHandler(YES);

}
- (void)replaced_webView:(WKWebView *)webView decidePolicyForNavigationResponse:(WKNavigationResponse *)navigationResponse decisionHandler:(void (^)(WKNavigationResponsePolicy))decisionHandler
{
    NSLog(@"decidePolicyForNavigationResponse");
    
//    (^(WKNavigationResponsePolicy)) handler = decisionHandler;
    [self replaced_webView:webView decidePolicyForNavigationResponse:navigationResponse decisionHandler:decisionHandler];
//    decisionHandler(YES);

}
- (void)replaced_webView:(WKWebView *)webView didStartProvisionalNavigation:(null_unspecified WKNavigation *)navigation
{
    NSLog(@"didStartProvisionalNavigation");
//    [self replaced_webView:webView didStartProvisionalNavigation:navigation];
}
- (void)replaced_webView:(WKWebView *)webView didReceiveServerRedirectForProvisionalNavigation:(null_unspecified WKNavigation *)navigation
{
    NSLog(@"didReceiveServerRedirectForProvisionalNavigation");
    [self replaced_webView:webView didReceiveServerRedirectForProvisionalNavigation:navigation];

}

**Comment by ihnatmoisieiev** [comment]
@211Yang thank you, we will investigate the issue.

**Comment by ihnatmoisieiev** [comment]
@211Yang the issue has been fixed in the latest release.
