### ISSUE TITLE
showInLegend percentage

### ISSUE THREAD

**Issue by cherry143** [highcharts/highcharts-ios#187]
Hello!

#1 
I need to add percentage value with showInLegend label, how? (format)

#2 
can font size of showInLegend changeable?

Thanks...

**Comment by ihnatmoisieiev** [comment]
Hi @cherry143,
could you describe more exactly what you want to achieve?

From the API docs, `showInLegend` is a boolean value:

> Whether to display this particular series or series type in the legend. The default value is `true` for standalone series, `false` for linked series.
> Defaults to **true**.
> **Try it**
> [One series in the legend, one hidden](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-showinlegend/)

**Comment by cherry143** [comment]
I need to have a format like below

tooltip.pointFormat = @"{series.name}:<b>{point.percentage:.1f}%</b>";

FOR>>>         showInLegend.format = @"{point.percentage:.1f}%";

like below...

![fullsizeoutput_11e](https://user-images.githubusercontent.com/42531833/57610272-18007600-758e-11e9-8053-822993e5dea8.jpeg)

**Comment by cherry143** [comment]
I need to have a format like below

tooltip.pointFormat = @"{series.name}:{point.percentage:.1f}%";

FOR>>> showInLegend.format = @"{point.percentage:.1f}%";

like below...

![fullsizeoutput_122](https://user-images.githubusercontent.com/42531833/57610491-8cd3b000-758e-11e9-867b-489cd216d6a5.jpeg)

**Comment by ihnatmoisieiev** [comment]
Hi @cherry143,

try to configure your legend object:

```
let legend = HILegend()
legend.labelFormat = "{name} {percentage:.1f} %"
legend.itemStyle = HICSSObject()
legend.itemStyle.fontSize = "12px"
options.legend = legend
```

**Comment by cherry143** [comment]
Thanks...!
