### ISSUE TITLE
How to put Leading space in X-Axis titles?

### ISSUE THREAD

**Issue by StellarKuldeep** [highcharts/highcharts-ios#192]
I want to put some leading spacing in X-Axis data. because if data is 0 then first X-Axis title goes behind some white transparent view like below image.

![Simulator Screen Shot - iPhone Xs - 2019-05-14 at 12 31 54](https://user-images.githubusercontent.com/38131385/57677453-7c7e0c80-7644-11e9-902a-4a16fc0d6bf9.png)

How can I put leading space so X-Axis data display fully?

**Comment by ihnatmoisieiev** [comment]
Hi @StellarKuldeep,

try to set `autoRotation` to your `xAxis` labels:

```
let xAxis = HIXAxis()
xAxis.labels = HILabels()
xAxis.labels.autoRotation = [-90]
options.xAxis = [xAxis]
```

**Comment by StellarKuldeep** [comment]
@ihnatmoisieiev , Thanks for your help. it works fine
