### ISSUE TITLE
need to get min, max after selection of chart  

### ISSUE THREAD

**Issue by guptavirendra** [highcharts/highcharts-ios#193]

**Comment by ihnatmoisieiev** [comment]
Hi @guptavirendra,

could you please provide more info about what min and max values do you want to get?

Thanks.

**Comment by guptavirendra** [comment]
I have to implement feature as shown in this example https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/events-selection/

I want to get xAxis.min, xAxis.max by pinch zoom on mobile let say I have 1 month data and I have zoom finger from 12 April to 16 April then it should return me in HIFunction context. So that I can use it.
I am trying like this
let highFunction = HIFunction(closure: { (context) in
             let nCenter = NotificationCenter.default
            nCenter.post(name: NSNotification.Name(rawValue: "zoomDone"), object: context, userInfo: nil)
        }, properties: ["this.events"])

        let events = HIEvents()
       
        events.selection = highFunction
        let chart   =  HIChart()
        chart.events =  events

**Comment by ihnatmoisieiev** [comment]
Hello @guptavirendra,

try

```
let chart = HIChart()
chart.zoomType = "x"
chart.events = HIEvents()
chart.events.selection = HIFunction(closure: { context in
    guard let context = context else { return }
    let min = context.getProperty("event.xAxis[0].min")!, max = context.getProperty("event.xAxis[0].max")!
    print("xAxis min: \(min), xAxis max: \(max)")
}, properties: ["event.xAxis[0].min", "event.xAxis[0].max"])
options.chart = chart	
```

**Comment by guptavirendra** [comment]
it was not working

**Comment by ihnatmoisieiev** [comment]
@guptavirendra it works perfectly for me. See example below:

```
let options = HIOptions()

let chart = HIChart()
chart.zoomType = "x"
chart.events = HIEvents()
chart.events.selection = HIFunction(closure: { context in
    guard let context = context else { return }
    let min = context.getProperty("event.xAxis[0].min")!, max = context.getProperty("event.xAxis[0].max")!
    print("xAxis min: \(min), xAxis max: \(max)")
}, properties: ["event.xAxis[0].min", "event.xAxis[0].max"])
options.chart = chart

let column = HIColumn()
column.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

let series = HISeries()
series.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reversed()

options.series = [column, series]
```

**Comment by guptavirendra** [comment]
I have tried it with sample provided on github. But it is still not working. I have put above mentioned code in the optionprovider.swift file. But it is still not working.
[OptionsProvider.swift.zip](https://github.com/highcharts/highcharts-ios/files/3222309/OptionsProvider.swift.zip). Please have a look. It would be great if you find issue in the code

**Comment by ihnatmoisieiev** [comment]
@guptavirendra,

Your `OptionsProvider.swift` looks ok and it works for me. What version of the framework do you use?

See some examples values:

```
xAxis min: 2.732914812460267, xAxis max: 12.97258423394787
xAxis min: 6.381993006993008, xAxis max: 9.018356643356643
xAxis min: 4.308892773892774, xAxis max: 11.14889277389278
xAxis min: 6.385442187628119, xAxis max: 8.891773845919577
xAxis min: 3.433334123999956, xAxis max: 12.02424321490905
```

**Comment by guptavirendra** [comment]
I am using 7.0. But I found 7.1.1 is latest. let me check latest one. Thank you

**Comment by guptavirendra** [comment]
![Screenshot 2019-05-27 at 7 10 13 PM](https://user-images.githubusercontent.com/891554/58423582-15843d00-80b3-11e9-9506-49950693b9d6.png)
latest sample get crashed

**Comment by guptavirendra** [comment]
Can you please send me link of stable version of the framework. i tried master, tag 7.1.1 and 7.0.3. It was crashed. Please do it on the urgent basis.

**Comment by ihnatmoisieiev** [comment]
@guptavirendra The latest version is stable and I can't reproduce any crashes. 

You have something incorrectly configured.

See the [demo project](https://github.com/ihnatmoisieiev/EventsSelection).

**Comment by guptavirendra** [comment]
It is working fine on simulator not on device. The sample is still crashing on device. 
![Screenshot 2019-05-28 at 7 30 27 PM](https://user-images.githubusercontent.com/891554/58484152-28fcda00-817f-11e9-8a53-69267b76fa9d.png)
![Screenshot 2019-05-28 at 7 30 46 PM](https://user-images.githubusercontent.com/891554/58484153-29957080-817f-11e9-9ec1-0c320e545c25.png)

**Comment by guptavirendra** [comment]
I just changed deployment target to 10.3

**Comment by guptavirendra** [comment]
It is crashing on A1458 model of iPad, i.e. 4 th generation

**Comment by guptavirendra** [comment]
It is working fine on iPhone

**Comment by ihnatmoisieiev** [comment]
@guptavirendra,

These devices don't support the latest versions of the framework.

If you want to run your app on the device, you should use the framework from *release* folder.

**Comment by guptavirendra** [comment]
I am using release folder.

**Comment by guptavirendra** [comment]
Can you Please provide me list of supported devices?

**Comment by ihnatmoisieiev** [comment]
Some old devices don't support new versions of the framework starting from 7.0.2.
Newest versions require iOS 11.

**Comment by guptavirendra** [comment]
ok thanks. closing the issue
