### ISSUE TITLE
How to Create Dynamic HIColumn() Object according to server response.

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#195]
{"ResponseData":[{"AryValues":[{"Chartbool":true,"Title":"Apr'19","TitleValue":"24138.96"},{"Chartbool":true,"Title":"Comparison","TitleValue":"26181.67"},{"Chartbool":false,"Title":"Variance","TitleValue":"-2042.71"},{"Chartbool":false,"Title":"Variance %","TitleValue":"-7.8"}],"Title":"Name","TitleValue":"Apr'19 vs. Mar'19"},{"AryValues":[{"Chartbool":true,"Title":"Apr'19","TitleValue":"24138.96"},{"Chartbool":true,"Title":"Comparison","TitleValue":"26043.14"},{"Chartbool":false,"Title":"Variance","TitleValue":"-1904.18"},{"Chartbool":false,"Title":"Variance %","TitleValue":"-7.31"}],"Title":"Name","TitleValue":"Apr'19 vs. Apr'18"}],"ErrorData":null,"ResponseStatus":true}

in my server response only **"Chartbool" : true,** value display in chart.
![Screenshot 2019-05-20 at 5 29 18 PM](https://user-images.githubusercontent.com/48505333/58020112-d7bc6d00-7b24-11e9-8298-bffa650829dd.png)

This is my server response i want to show in chart but dynamic because in future i get more data with title.

Like below screenshot this is static type i was show now i want to show dynamic 

Thank you in Advance

**Comment by ihnatmoisieiev** [comment]
Hello @barotbhavesh,

thank you for your question.

When you get new data from your server, you can `update` your series object:

```
let newColumnOptions = HIColumn()
newColumnOptions.name = "New Column Name"
newColumnOptions.data = newData

let currentColumn = self.chartView.options.series[index]
currentColumn.update(newColumnOptions, redraw: false)
```

**Comment by barotbhavesh** [comment]
Thank you so much for your important time or Your answer.
