### ISSUE TITLE
HIPackedbubble 'useSimulation' and other properties missing

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#196]
According to the [docs](https://api.highcharts.com/ios/highcharts/Classes/HIPackedbubble.html#//api/name/useSimulation), the '`useSimulation`' property should be available for `HiPackedbubble` series, but it is not, just like a few other properties, too:

<img width="154" alt="properties" src="https://user-images.githubusercontent.com/12996815/58072713-d6308a80-7ba0-11e9-956d-ac4f98113ee9.png">

**Comment by skuske** [comment]
My mistake - I was using an outdated version of the wrapper.

**Comment by ihnatmoisieiev** [comment]
No problem. You are welcome!
