### ISSUE TITLE
Hide reset zoom button

### ISSUE THREAD

**Issue by guptavirendra** [highcharts/highcharts-ios#198]
Hi,
I want to zoom our graph, but I do not want to show "reset zoom" button

**Comment by guptavirendra** [comment]
It's been more than 4 days, But I did not see any response.

**Comment by ihnatmoisieiev** [comment]
Hi @guptavirendra,

sorry for the late response. 

Try:

```
let chart = HIChart()
chart.resetZoomButton = HIResetZoomButton()
chart.resetZoomButton.position = HIAlignObject()
chart.resetZoomButton.position.y = -100
options.chart = chart
```

**Comment by guptavirendra** [comment]
@ihnatmoisieiev  thanks. It is working. Hence closing the ticket.
