### ISSUE TITLE
HIAreaspline y-axis always starts at zero

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#199]
How can I prevent the y-axis of an HIAreaspline chart to start from zero? I want the y-axis minimum to be computed automatically and not to start from zero, just like for a HISpline series.

Code example, please. Many thanks.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

try this workaround:

```
let chart = HIChart()
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: "function () { this.series[0].update({ threshold: null }); }")
options.chart = chart
```

**Comment by ihnatmoisieiev** [comment]
@skuske did you try it?

**Comment by skuske** [comment]
@ihnatmoisieiev 

Not yet, will do asap and close issue then.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Your workaround does work, but: is there any way to achieve that through HIPlotOptions? I found this:

```
plotOptions: {
    areaspline: {
        threshold: null
    }
}
```

That would help to get this working for any area spline series... So: is there any way to set the threshold to 'null' through HIPlotOptions?

Thanks! :o)

**Comment by ihnatmoisieiev** [comment]
@skuske unfortunately, it isn't possible to set `nil` value to `plotOptions.areaspline.threshold`, but you can modify `chart.events.load` function to: 

```
chart.events.load = HIFunction(jsFunction: "function () { this.update({ plotOptions: { areaspline: { threshold: null } } } ); }")
```

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks a lot! :o)
