### ISSUE TITLE
HIGChartView not initialized with initWithCoder:

### ISSUE THREAD

**Issue by Ferannor** [highcharts/highcharts-ios#2]
HIGChartView is not initialized properly with initWithCoder: method. 
Without this, we cannot initialize a HIGChartView from a storyboard.

**Comment by ratka6** [comment]
Try now. New 1.0.3 version released. Please give us more feedback.

**Comment by Ferannor** [comment]
Well something is probably missing cause now I've only the title and nothing else. 
If I use the same code and create my HIGChartView with initWithFrame: it's working.

**Comment by ratka6** [comment]
After you add options in code, use [yourChartView loadChart].

**Comment by Ferannor** [comment]
That's perfect! Thanks for your help!
