### ISSUE TITLE
Variablepie not supported?

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#200]
Hello,

I found this comment in headers: 

/**
The default series type for the chart. Can be any of the chart types listed under `plotOptions`.

**Accepted values:** `["line", "spline", "column", "bar", "area", "areaspline",
            "pie", "arearange", "areasplinerange", "boxplot",
            "bubble", "columnrange", "errorbar", "funnel", "gauge",
            "heatmap", "polygon", "pyramid", "scatter", "solidgauge",
            "treemap", "waterfall"]`.

**Defaults to** `line`.

**Try it**

* [Bar](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/type-bar/)
*/

it does not show any "variablepie" option which i need to use.

any comments?

Best

**Comment by ihnatmoisieiev** [comment]
Hello @ergunkocak,

`Variablepie` is supported.

Thank you for reporting. It's a bug in docs.

**Comment by ihnatmoisieiev** [comment]
@ergunkocak the bug has been fixed in the latest release.
