### ISSUE TITLE
Crash of 7.1.2

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#201]
After updating our project with v7.1.2, Xcode (i.e. our app) crashes with this debug information:

`*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <HIChartView 0x1046ba070> for the key path "options.isUpdated" from <HIChartView 0x1046ba070> because it is not registered as an observer.'`

Any help, please. Thanks.

**Comment by ihnatmoisieiev** [comment]
Hi @skuske,

could you please provide steps to reproduce?

Thank you!

**Comment by skuske** [comment]
@ihnatmoisieiev 

That is difficult as that would mean to send you the whole project's source code, and that is something I cannot do.

**Comment by ihnatmoisieiev** [comment]
@skuske 

ok, thank you for reporting. We will investigate the issue and try to fix as soon as possible.

**Comment by skuske** [comment]
https://www.google.com/search?safe=off&client=safari&source=hp&ei=NIgDXa_-FLPAmwWTkLEY&q=reason%3A+%27Cannot+remove+an+observer&oq=reason%3A+%27Cannot+remove+an+observer&gs_l=psy-ab.3..35i39j0i22i30l2.2415.2415..3150...2.0..0.120.232.0j2......0....2j1..gws-wiz.....6.8z2_vVJFY-E

**Comment by ihnatmoisieiev** [comment]
@skuske 7.1.2.1 has been released. Please try and let us know.

**Comment by skuske** [comment]
@ihnatmoisieiev 

v7.1.2.1 fixes the issue. Many thanks! :o)
