### ISSUE TITLE
How to Replace HIDataLabels with HIDataLabelsOptionsObject

### ISSUE THREAD

**Issue by Sreeram888** [highcharts/highcharts-ios#202]
Hi

      I need to disable Datalabel in a pie chart. After upgrading my HighChat Pod it's throwing me the following error. can you please help me fix it.

**Error** 
* Cannot assign value of type 'HIDataLabels' to type '[HIDataLabelsOptionsObject]?'
* Value of type '[HIDataLabelsOptionsObject]?' has no member 'enabled'

**Code Snippet**
            let parentPie = HIPie()
            parentPie.size = "60%"
            parentPie.name = seriesName
            parentPie.dataLabels = HIDataLabels()
            parentPie.dataLabels.enabled = false
            parentPie.data = parentPieData

**Comment by ihnatmoisieiev** [comment]
Hi @Sreeram888,

`dataLabels` is an array from `7.1.2`. Try:

```
let parentPie = HIPie()
parentPie.size = "60%"
parentPie.name = seriesName
let dataLabels = HIDataLabelsOptionsObject()
dataLabels.enabled = false
parentPie.dataLabels = [dataLabels]
parentPie.data = parentPieData
```
