### ISSUE TITLE
Invalid framework bundle version causes error when uploading to Testflight

### ISSUE THREAD

**Issue by martinpilch** [highcharts/highcharts-ios#203]
Hi,
when uploading app to Testflight with your framework I get this error:

> [Transporter Error Output]: ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '7.1.2.1' in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"

Can you please bump the version to `7.1.3` instead?

**Comment by ihnatmoisieiev** [comment]
@martinpilch thank you for reporting. Sure, we will fix it as soon as possible.

**Comment by ihnatmoisieiev** [comment]
@martinpilch the issue has been fixed. Please update your framework to `7.1.3`.

**Comment by ihnatmoisieiev** [comment]
@martinpilch could I close the issue?

**Comment by martinpilch** [comment]
Thanks for resolving! I'm closing it.
