### ISSUE TITLE
How to display multiple line in xAxis Label ?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#204]
![abc](https://user-images.githubusercontent.com/48505333/60265963-a776a400-9904-11e9-9c05-0001fb74e4f6.png)

**Comment by ihnatmoisieiev** [comment]
Hi @barotbhavesh,
to display multiple lines add `<br>` to your label name, eg.

```
xAxis.categories = ["1099", "Franchise Tax <br> Compliance", "Sales Tax Filing"]
```

Also, you can try a workaround

```
chart.events.load = HIFunction(jsFunction: "function () { this.xAxis[0].update({ labels: { autoRotation: false } }); }")
```

to disable rotation and enable word-wrapping.

**Comment by barotbhavesh** [comment]
Thank you so much it's working for me.Thanks a lot.

**Comment by barotbhavesh** [comment]
![Screenshot 2019-07-02 at 4 15 45 PM](https://user-images.githubusercontent.com/48505333/60506966-ac609c80-9ce4-11e9-894f-c332a3be25ba.png)

        chart.events = HIEvents()
        chart.events.load = HIFunction(jsFunction: "function () { this.xAxis[0].update({ labels: { autoRotation: false } }); }")

this solution is only a few lines breaks to the next line, not all lines.
