### ISSUE TITLE
How to Add Comma(,) in ToolTip Value?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#206]
![Screenshot 2019-07-03 at 6 13 45 PM](https://user-images.githubusercontent.com/48505333/60592503-6841ca80-9dbe-11e9-9932-46e6449b9df5.png)
Thank in Advance.

**Comment by ihnatmoisieiev** [comment]
Hi @barotbhavesh,

try to set `decimalPoint` of `HILang` object:

```
let lang = HILang()
lang.decimalPoint = ","
chartView.lang = lang
...
chartView.options = options
```

**Comment by barotbhavesh** [comment]
it is not working on my side. i want add like this **2,39,59.32**.
and thank for your important time sir

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh this format is not supported.

You should format it by yourself and set your series data in the following way:

```
let series = HISeries()

let data = [
    ["y": 23959.32, "formatted": "2,39,59.32"],
    ["y": 11111.11, "formatted": "1,11,11.11"]
]

series.data = data

options.series = [series]
```

and show formatted value in your tooltip:

```
let tooltip = HITooltip()
tooltip.pointFormat = "{point.formatted}"
options.tooltip = tooltip
```

**Comment by barotbhavesh** [comment]
It's not working for me because I have Dynamic data. Can you give me another way?

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh just update your series with new data:

```
let newData = [
    ["y": 13959.32, "formatted": "1,39,59.32"],
    ["y": 41111.11, "formatted": "4,11,11.11"]
]

let series = chartView.options.series[0]
series.setSeriesData(newData) // or series.data = newData
```

**Comment by barotbhavesh** [comment]
I am updating the series or also set series in **HIOptions()** but not get success.

 **let parameters    = NSMutableDictionary()
            parameters.setValue((NSNumber(value: abcd ?? 0.0)), forKey: "y")
            parameters.setValue(COMMON_SHARED.setValueWithoutCurrencySymbol(floatValue: Float(abcd ?? 0.0)), forKey: "formatted")
            aryCurrentMonth.add(parameters)**


 let column1 = HIColumn()
        column1.color = HIColor.init(uiColor: UIColor(hexString: "#08A028"))//CLR_CHART_BLUE)
        **column1.data = aryCurrentMonth as? [Any]**
        column1.stack = "male"
        column1.name = "Revenue"

 let options = HIOptions()
        options.chart = chart
        options.title = title
        options.xAxis = [xaxis]
        options.yAxis = [yaxis]
        options.tooltip = tooltip
        options.series = [column1]
        options.exporting = exporting

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh you don't need to set the chart options again. When you get new data, set it to your series object:

```
let column1 = chartView.options.series[0]
column1.setSeriesData(aryCurrentMonth) // or column1.data = aryCurrentMonth
```

**Comment by barotbhavesh** [comment]
I am adding your suggestion but not working.

let column1 = collection.viewCharts.options.series[0]//HIColumn()
        column1.color = HIColor.init(uiColor: UIColor(hexString: "#08A028"))//CLR_CHART_BLUE)
        column1.data = aryCurrentMonth as? [Any]
        column1.stack = "male"
        column1.name = "Revenue"
        
        let options = HIOptions()
        options.chart = chart
        options.title = title
        options.xAxis = [xaxis]
        options.yAxis = [yaxis]
        options.tooltip = tooltip
        options.series = [column1]
        options.exporting = exporting
        collection.viewCharts.options = options

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh please, see a demo below:

```
import UIKit
import Highcharts

class ViewController: UIViewController {
    
    private var chartView: HIChartView!
    
    private var seriesData = [49.9, 71.5, 106.4, 129.2, 144, 176, 203.4, 177.4, 155.4, 122.2, 95.6, 54.4]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let updateButton = UIButton(type: .system)
        let buttonFrame = CGRect(x: self.view.bounds.size.width / 2 - 75, y: self.view.bounds.size.height / 2 + 30, width: 150, height: 30)
        updateButton.frame = buttonFrame
        updateButton.setTitle("Update data", for: .normal)
        updateButton.addTarget(self, action: #selector(updateData), for: .touchUpInside)
        self.view.addSubview(updateButton)
        
        let chartFrame = CGRect(x: self.view.bounds.origin.x, y: self.view.bounds.origin.y,
                                width: self.view.bounds.size.width, height: self.view.bounds.size.height / 2)
        
        self.chartView = HIChartView(frame: chartFrame)
        
        let options = HIOptions()
        
        let chart = HIChart()
        chart.type = "column"
        options.chart = chart
        
        let title = HITitle()
        title.text = "Demo chart"
        options.title = title
        
        let series = HIColumn()
        series.data = seriesData
        options.series = [series]
        
        self.chartView.options = options
        
        self.view.addSubview(self.chartView)
    }
    
    @objc private func updateData() {
        self.seriesData = self.seriesData.reversed()

        let newData = self.seriesData // change to your dynamic data
        
        let column1 = chartView.options.series[0]
        column1.setSeriesData(newData)
    }
}
```

I hope it's clear.

**Comment by barotbhavesh** [comment]
Hello sir Not show Comma(,) inside the ToolTip Like **12,92,323.2**

I am using your code with this Data
private var seriesData = [49.9, 713232.5, 1063232.4, 1292323.2, 144323, 176, 2033232.4, 177323.4, 155323.4, 1223232.2, 95323.6, 542323.4]

![Screenshot 2019-07-08 at 5 26 39 PM](https://user-images.githubusercontent.com/48505333/60808409-d6fb9b00-a1a5-11e9-8999-38d7ee211c86.png)

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh change `seriesData` array to your own with `formatted` value.
As I mentioned above https://github.com/highcharts/highcharts-ios/issues/206#issuecomment-508659883, e.g.:

```
private var seriesData = [
    ["y": 23959.32, "formatted": "2,39,59.32"],
    ["y": 11111.11, "formatted": "1,11,11.11"]
]
```

and show it in the tooltip:

```
let tooltip = HITooltip()
tooltip.pointFormat = "{point.formatted}"
options.tooltip = tooltip
```

**Comment by barotbhavesh** [comment]
Thank you so much it's working for me Thanks a lot. I am so happy to work with a highchart organization.
