### ISSUE TITLE
Multiple series <> opacity issue

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#207]
With one of the recent updates something changed regarding the opacity of series when the legend is used to hide / show a series.

I found that after hiding one series, all series become extremely translucent and we need to touch the chart area to make the series opaque again.

https://jsfiddle.net/am4jeod1/

Hide the 'Jane' series, and after hiding it, DO NOT move the mouse. You'll notice that the other two series will remain extremely translucent unless you move the mouse, or (on touch devices) you touch the chart area.

How can I stop that? On iOS it is extremely confusing to see that all series change their opacity if one series is hidden, and that the opacity only changes back to the default opacity if you touch the chart area...

Thanks for any help.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @skuske 

It looks like a bug in the core, let me open issue in the main lib repo a ticket: https://github.com/highcharts/highcharts/issues/11301

I don't know how to disable this in iOS, but in js you simply can disable inactive state by setting `inactive.opacity = 1`: https://jsfiddle.net/BlackLabel/t7afpn6s/

**Comment by ihnatmoisieiev** [comment]
Thank you @pawelfus for your quick reply.

@skuske disabling inactive state:

```
let plotOptions = HIPlotOptions()

let states = HIStates()
states.inactive = HIInactive()
states.inactive.opacity = 1
series.states = states

plotOptions.series = series
```

**Comment by skuske** [comment]
@ihnatmoisieiev

Thanks for the workaround, but I‘ll wait for the issue to be fixed with an update...

**Comment by pawelfus** [comment]
@skuske 
Just to be on the same page - what @ihnatmoisieiev posted is not a workaround but a way to disable inactive state. For example when you tap on a line, all others will fade out. If you want to change this behaviour, use code given by @ihnatmoisieiev 

If you are fine with inactive feature and only the legend functionality is broken for you then don't disable inactive state. We don't have ETA for next core release, but it will take longer than usually - it's vacation time, so I wouldn't expect release this month.

**Comment by skuske** [comment]
@pawelfus 

Thanks. We will use the code by @ihnatmoisieiev :o)

**Comment by skuske** [comment]
@pawelfus 

I see that the core has updated recently. When will a new wrapper be available? Thanks.

**Comment by skuske** [comment]
@ihnatmoisieiev 

I see that the core has updated recently. When will a new wrapper be available? Thanks.

**Comment by ihnatmoisieiev** [comment]
@skuske I suppose the wrapper will be updated today or tomorrow.
