### ISSUE TITLE
how to Add Month name in X-Axis title in bubble chart ?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#208]
let chart = HIChart()
chart.type = "bubble"

In the bubble chart,  I want to add a month name in the X-axis title.

![Screenshot 2019-07-05 at 9 05 05 AM](https://user-images.githubusercontent.com/48505333/60696585-00959780-9f04-11e9-9123-4e1810309824.png)

Like This.

**Comment by ihnatmoisieiev** [comment]
Hello @barotbhavesh,

just set `categories` of `xAxis`:

```
let xAxis = HIXAxis()
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"]
options.xAxis = [xAxis]
```

or use data with category name:

```
let xAxis = HIXAxis()
xAxis.type = "category"
options.xAxis = [xAxis]

let bubble = HIBubble()

let data1 = HIData()
data1.name = "Jan"
data1.x = 0
data1.y = 1
data1.z = 2

...

bubble.data = [data1, ... ]

options.series = [bubble]
```

**Comment by barotbhavesh** [comment]
According to your suggestion in first display -1 or in last display 7 Display with the month name.
Look in portrait Mode 
![Screenshot 2019-07-05 at 12 16 33 PM](https://user-images.githubusercontent.com/48505333/60703637-e7024900-9f1f-11e9-9567-49cb718714d2.png)
Look in Landscape Mode 
![Simulator Screen Shot - iPhone 5s - 2019-07-05 at 12 25 54](https://user-images.githubusercontent.com/48505333/60703703-1618ba80-9f20-11e9-8458-74ab51bbc7ed.png)
In Landscape mode Looks good But not in portrait Mode.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh set `min` and `max` values for your `xAxis`. 

For more info see general [docs](https://api.highcharts.com/highcharts/xAxis) and iOS [docs](https://api.highcharts.com/ios/highcharts/).

**Comment by barotbhavesh** [comment]
Its working thank you so much for your help.

**Comment by barotbhavesh** [comment]
It's working but the bubble is not showing properly. Left the Bubble or right bubble is not properly show.
![Simulator Screen Shot - iPhone 5s - 2019-07-05 at 15 10 31](https://user-images.githubusercontent.com/48505333/60713639-0eb0db80-9f37-11e9-98f4-f9d455b0018a.png)

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh try to set `maxSize` on your `HIBubble` series, e.g.:

```
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"]

...

let bubble = HIBubble()
bubble.maxSize = "\(100/xAxis.categories.count)%"
```

or as an alternative solution use labels formatter instead of setting `min` and `max` on `xAxis`:

```
let xAxis = HIXAxis()
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"]
xAxis.labels = HILabels()
xAxis.labels.formatter = HIFunction(jsFunction: "function () { return this.pos >= 0 && this.pos < this.axis.max ? this.value : ''; }")
options.xAxis = [xAxis]
```

**Comment by barotbhavesh** [comment]
Its working thank you so much again and really appreciate it for the quick Answer.
