### ISSUE TITLE
How to break Title in circle donut ?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#209]
![Screenshot 2019-07-12 at 9 46 59 AM](https://user-images.githubusercontent.com/48505333/61102363-2504ed00-a48b-11e9-875c-4e20af3ae86a.png)
I want to break a title in the donut chart. The title is dynamic so we cannot use **BR**

**Comment by ihnatmoisieiev** [comment]
Hello @barotbhavesh,

try to adjust `widthAdjust` value of `HITitle`, e.g.

```
title.widthAdjust = -200
```

See [docs](https://api.highcharts.com/ios/highcharts/) for more info.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh can I close the issue?

**Comment by barotbhavesh** [comment]
title.widthAdjust = -200
Its work but not the text in center in portrait or landscape mode.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh please, see [docs](https://api.highcharts.com/ios/highcharts/).

You need to set `align` and `verticalAlign`, e.g.

```
title.align = "center"
title.verticalAlign = "middle"
```

**Comment by barotbhavesh** [comment]
let title = HITitle()
        title.text = "abc abc abc- dsdsd dsd sd"
        title.align = "center"
        title.verticalAlign = "middle"
        title.y = NSNumber(value: 10)
        title.widthAdjust = -200

I am using the same sir but facing the issue.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh please share your `HIOptions` config.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh it's not config. I need to see all the options configured in your chart.

**Comment by barotbhavesh** [comment]
I am sharing all the code below

 let exporting = HIExporting()
        exporting.enabled = false
        
        let chart = HIChart()
        chart.plotBackgroundColor = HIColor()
        chart.plotShadow = false
        
        let title = HITitle()
        title.text = "Sales"
        title.align = "center"
        title.verticalAlign = "middle"
        title.y = NSNumber(value: 10)
        title.widthAdjust = -200

        let plotoptions = HIPlotOptions()
        plotoptions.pie = HIPie()
        plotoptions.pie.allowPointSelect = NSNumber(value: true)
        plotoptions.pie.cursor = "pointer"
        plotoptions.pie.dataLabels = HIDataLabelsOptionsObject()
        plotoptions.pie.dataLabels.format = "<b>{point.name}</b>: {point.percentage:.2f}%"
        plotoptions.pie.dataLabels.style = HICSSObject()
        plotoptions.pie.dataLabels.style.color = "black"
        plotoptions.pie.dataLabels = HIDataLabelsOptionsObject()
        plotoptions.pie.startAngle = NSNumber(value: 0)
        plotoptions.pie.endAngle = NSNumber(value: 360)
        plotoptions.pie.center = ["50%", "55%"]
        plotoptions.pie.dataLabels.enabled = NSNumber(value: false)
        
        let aryParameters = NSMutableArray()
        _ = dicDashboardModel.ary_Pie.filter { (abc) -> Bool in
            if abc.Name != "Total" {
                let floatSalesTotalValue = Float(dicDashboardModel.Sales) ?? 0.0
                let floatSalesValue = Float(abc.Value ) ?? 0.0
                let FindPerValue = ((floatSalesValue * 100)/floatSalesTotalValue)
                let abcd = Double(FindPerValue)
                let parameters    = NSMutableDictionary()
                parameters.setValue(NSNumber(value: abcd), forKey: "y")
                parameters.setValue(abc.Name, forKey: "name")
                parameters.setValue(NSNumber(value: floatSalesValue), forKey: "z")
                parameters.setValue(COMMON_SHARED.setValueWithCurrencySymbol(floatValue: floatSalesValue), forKey: "formatted")
                aryParameters.add(parameters)
            }
            return true
        }
        
        let tooltip = HITooltip()
        tooltip.headerFormat = ""
        tooltip.pointFormat = "<b><p style=\"font-size:12px\">{point.name}: {point.formatted} ({point.percentage:.2f}%)</p></b>"
        
        let pie = HIPie()
        let data = HIData()
        data.y = NSNumber(value: 0.1)
        pie.innerSize = "70%"
        pie.data = aryParameters as? [Any]
        
        let options = HIOptions()
        options.colors = COMMON_SHARED.aryStaticColorForChart
        options.title = title
        options.tooltip = tooltip
        options.plotOptions = plotoptions
        options.series = [pie]
        options.exporting = exporting
        collection.viewCharts.options = options

**Comment by ihnatmoisieiev** [comment]
Hi @barotbhavesh,

it's centered for me. 

Please see screenshot below

![Zrzut ekranu 2019-07-24 o 09 52 56](https://user-images.githubusercontent.com/11294008/61775310-fe36a700-adf8-11e9-8a9d-013255e95a9a.png)

**Comment by barotbhavesh** [comment]
@ihnatmoisieiev but when your text is large or big then you get the issue in landscape mode.
![Simulator Screen Shot - iPhone 5s - 2019-07-24 at 14 56 43](https://user-images.githubusercontent.com/48505333/61782292-6f8b4f80-ae23-11e9-9f49-4b9cdd275821.png)
Look

It's good in portrait mode.
![Simulator Screen Shot - iPhone 5s - 2019-07-24 at 14 56 48](https://user-images.githubusercontent.com/48505333/61782355-85991000-ae23-11e9-9011-75d9bd961737.png)

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh you also should adjust `widthAdjust` value for landscape mode.

**Comment by barotbhavesh** [comment]
we also set **width adjust** 
title.widthAdjust = -160
in landscape mode looks

![Screenshot 2019-07-26 at 2 57 21 PM](https://user-images.githubusercontent.com/48505333/61941817-d6407280-afb5-11e9-8320-d57e68e3cd6c.png)

or in portrait mode looks like 
![Screenshot 2019-07-26 at 2 57 02 PM](https://user-images.githubusercontent.com/48505333/61941855-ed7f6000-afb5-11e9-9103-27bf3bbb34f1.png)

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh you can set different `widthAdjust` value for portrait and landscape mode.

When the orientation changed, set a new value: 

```
chartView.options.title.widthAdjust = newValue
```

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh can I close the issue?

**Comment by barotbhavesh** [comment]
According the old answer i am fix the text if we have static text but now in my side i have dynamic text(Text come to backend) so your solution is not working in now case.
