### ISSUE TITLE
chart reload

### ISSUE THREAD

**Issue by simerlec** [highcharts/highcharts-ios#21]
Hello,

thanks for the continuous updates to the wrapper - really appreciate it!

I see that the reload method has been deprecated...what's the recommended way to update the chart once the series data has been changed or updated? I can't seem to find it.

kind regards

**Comment by spinneyio** [comment]
The goal is for the chart view to behave as any other view - to allow it to redraw itself when its properties are changed, just like UILabel changes automatically when text property is modified. At this time, chart.options = .... would trigger updates. Changes to the tree assigned to options do not trigger updates yet, this feature would come soon.

**Comment by simerlec** [comment]
Ok so to trigger an update with the new version I need to set the options object to a new value. I will try it out as soon as possible, thanks.

Another issue considering chart loading - im adding the charts (11 of them) dynamically in my project. Sometimes the initialization of the charts is not finished when the view is shown so I get the following error.

```
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo=
{WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't 
find variable: Highcharts, WKJavaScriptExceptionSourceURL=about:blank, 
NSLocalizedDescription=A JavaScript exception occurred, 
WKJavaScriptExceptionColumnNumber=27}
```

Is there some callback yet which I can use to be sure that the chart if fully loaded before using it?

Thanks again

**Comment by simerlec** [comment]
Hmm I can't seem to get it to work - I initialize the chart with a certain set of options which works fine. Then after a http call returns with the chart data I set it again with a completely new options object including the new series and data (as described until the changes on the assigned options tree are recognized) but the chart does not update.

Would you mind providing a snippet, preferably in Swift?

**Comment by mll** [comment]
The chart view has a delegate object that can implement the HIChartViewDelegate protocol:

`self.chartView.delegate = self;`

The delegate has a method:

`- (void) chartViewDidLoad: (HIChartView *) chart;`

which is called when the rendering is complete.

**Comment by simerlec** [comment]
Thanks, that should be exactly what I need.

I tried to use the new update methodology - setting the options new to trigger a reload. This works fine usually but doesn't seem to trigger in a dataTask? Following example:

This works just fine, the chart updates on the setting of the options
```swift
func query(newTimeRange: Int) {
        let series = HISeries()
        series.data = [1, 2, 3, 4, 5, 6, 6, 8, 89]
        
        let newOptions: HIOptions = self.chartView!.options //old options
        newOptions.series = [series]  //old options + new series
       self.chartView!.options = newOptions //triggers chart reload
}
```

whereas the setting does not trigger a reload in the dataTask here...
```swift
func query(newTimeRange: Int) {
    let chartTask = URLSession.shared.dataTask(with: chartUrl!) { data, _, error in
         guard error == nil else {
                print(error!)
                return
         }
         guard let data = data else {
                print("Data is empty")
                return
         }

        let series = HISeries()
        series.data = [1, 2, 3, 4, 5, 6, 6, 8, 89]
        
        let newOptions: HIOptions = self.chartView!.options
        newOptions.series = [series]
        self.chartView!.options = newOptions
    }
    chartTask.resume()
}
```

What am I doing wrong? :)

**Comment by mll** [comment]
The HIChartView is a UIView and therefore is not threadsafe. The dataTask callback is being called on the delegate queue - which might not be the main queue. Try dispatching the update to the main queue by calling:

`DispatchQueue.main.async { self.chartView?.options = newOptions }` 

instead of:

`self.chartView!.options = newOptions `

**Comment by simerlec** [comment]
Thanks for the fast response @mll, that was the issue in this case.

Shows that I'm new to iOS development, doesn't it 😆
