### ISSUE TITLE
How to set Infinity

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#210]
Hello,

How shall we assign Infinity value to threshold as in https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/area-threshold-infinity/ using Swift?

Best

**Comment by ihnatmoisieiev** [comment]
Hello @ergunkocak,

you can try set `chart.events.load` function to:

```
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: "function () { this.update({ plotOptions: { series: { threshold: Infinity } } } ); }")
```

**Comment by ihnatmoisieiev** [comment]
@ergunkocak did you try it? Can I close the issue?

**Comment by ergunkocak** [comment]
Sorry for late reply. I am using an alternative method. So i did not try this.

**Comment by ihnatmoisieiev** [comment]
@ergunkocak ok, can I close the issue?
