### ISSUE TITLE
How to hide or connect to next line value in LineChart?

### ISSUE THREAD

**Issue by StellarKuldeep** [highcharts/highcharts-ios#211]
I use LineChart and I want to hide the line which contains 0 values. for more clarification please consider below image.

Time data with irregular intervals
========================
 
![Simulator Screen Shot - iPhone 6 - 2019-07-22 at 18 38 20](https://user-images.githubusercontent.com/38131385/61634918-0636ff80-acb0-11e9-8e70-a66d3b598e66.png)

I want to show all dates at x-Axis and if any date contains 0 value then I want to connect that to next value.

EX:
===
As you can see that 2019/07/08 date has 0 then I don't want to draw line to 0. If 2019/07/08 date has 0 then line directly draw from 2019/07/07 to 2019/07/09.

is is possible to do this in **Time data with irregular intervals**

For that I have also tried this but I face same issue as I define above.

Here is screen

With data labels
============
![Simulator Screen Shot - iPhone 6 - 2019-07-22 at 18 44 57](https://user-images.githubusercontent.com/38131385/61635349-ff5cbc80-acb0-11e9-8254-2dc6665384df.png)

Please guide me ho can I achieve by using any of this 2.

Thanks

**Comment by ihnatmoisieiev** [comment]
Hello @StellarKuldeep,

thank you for your question.

There are two ways:

1. Removing all `0` values from your series data, eg.

```
[7, 6.9, 0, 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6] -> [7, 6.9, 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
```

But if your `type` of `yAxis` is `"category"`, you can't delete a point, because category will be deleted.

2. Changing all `0` values to `null` and setting `series.connectNulls` to `true`:

```
let line = HILine()
line1.data = [7, 6.9, NSNull(), 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]  // or "null"
line.connectNulls = true

...

options.series = [line]
```

**Comment by StellarKuldeep** [comment]
@ihnatmoisieiev , Thanks for your suggestion and help. it works exactly what I want.
Thanks

**Comment by ihnatmoisieiev** [comment]
@StellarKuldeep can I close the issue?

**Comment by StellarKuldeep** [comment]
@ihnatmoisieiev , yes. Thanks once again and I really appreciated your help.
