### ISSUE TITLE
How to Export the chart or Data in Pdf or Excel ?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#213]
![Screenshot 2019-07-24 at 12 13 43 PM](https://user-images.githubusercontent.com/48505333/61771085-7fe40000-ae0c-11e9-8133-7539ae9fa84f.png)
How to Export Pdf or Excel When I click on the Export button.

**Comment by ihnatmoisieiev** [comment]
Hello @barotbhavesh,

closing as duplicate of https://github.com/highcharts/highcharts-ios/issues/49.

**Comment by barotbhavesh** [comment]
@ihnatmoisieiev PDF not working when I Click to Slide Menu then pop will open and then select PDF share but not any response 

![Screenshot 2019-07-24 at 3 28 20 PM](https://user-images.githubusercontent.com/48505333/61788230-3ce75400-ae2f-11e9-9e9e-bf257875891b.png)

After pop will open click to PDF Share Looks Like this

![Screenshot 2019-07-24 at 3 28 26 PM](https://user-images.githubusercontent.com/48505333/61788281-5b4d4f80-ae2f-11e9-9976-afb548f3da67.png)

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh thank you for the reporting.

It's opening a PDF, but there is no share option.

I will report the issue.

You can use image sharing in the meantime.

**Comment by barotbhavesh** [comment]
@ihnatmoisieiev  one more question can it possible to Image or CSV both are in one share option?
when I selected that share option then both CSV or Image in a single file save on device?

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh it is not possible.

**Comment by barotbhavesh** [comment]
okay, thank you so much and how much time you need to solve the PDF share Bug @ihnatmoisieiev?

**Comment by skuske** [comment]
@ihnatmoisieiev

I am seeing the same PDF issue. When exactly will it be fixed? Can PDF export be disabled programmatically unless this is resolved?

**Comment by skuske** [comment]
@barotbhavesh 

How do you use the export feature although PDF export is not working? Did you find any workaround? Thanks.

**Comment by ihnatmoisieiev** [comment]
@skuske @barotbhavesh the issue will be fixed in the next release.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks - when will the next release be available?

**Comment by ihnatmoisieiev** [comment]
@skuske @barotbhavesh the newest release is available and fixes the issue.

**Comment by skuske** [comment]
@ihnatmoisieiev Everything works fine now. Thanks. :o) I think you can close this.
