### ISSUE TITLE
More than 1000 data points are not loading

### ISSUE THREAD

**Issue by guptavirendra** [highcharts/highcharts-ios#214]
Hi,
When I load json data less than 1000 then it is easily plotted graph.
[json.zip](https://github.com/highcharts/highcharts-ios/files/3441626/json.zip)
in the zip folder there are two json file. 1- response_hour. 2- response_minute.  first one contain less than 1000 data and second one contain more than 2000 data.
![IMG_0315](https://user-images.githubusercontent.com/891554/62042512-e0fc4100-b21b-11e9-84e3-f9e8bff4baae.PNG)
![IMG_0316](https://user-images.githubusercontent.com/891554/62042513-e194d780-b21b-11e9-88e7-7cbea37e6310.PNG) Please do fix it on high priority basis. I have to submit app on appstore.

**Comment by sebastianbochan** [comment]
Hi @guptavirendra,
Thank you for contacting us. You should set the [turboThreshold](https://api.highcharts.com/ios/highcharts/Classes/HISeries.html#//api/name/turboThreshold) parameter.

Let me know if it solved your problem.

**Comment by guptavirendra** [comment]
give me 15 minutes. I will update you.

**Comment by guptavirendra** [comment]
Thanks. it works. BTW how much data points we can plot using turbo?

**Comment by sebastianbochan** [comment]
If you set value as 0 then is unlimited.
