### ISSUE TITLE
toolTip Data View 

### ISSUE THREAD

**Issue by guptavirendra** [highcharts/highcharts-ios#216]
Hi,
When there is large content Tooltp view not display content properly.
![IMG_0318](https://user-images.githubusercontent.com/891554/62629534-ee67a880-b94a-11e9-8f98-1cc1e57ab05a.png)

**Comment by guptavirendra** [comment]
please do response.

**Comment by pawelfus** [comment]
Hi @guptavirendra 

My apologies for the late response! We are short handed this week because of holidays. Could you show your configuration? Thanks!

In general, I suggest to add `<br>` tags between parts of text, so result would like this:
```
Boolean tt: True<br>
Scale tt: -<br>
Body tt: Head Right Should Left ..
```

**Comment by guptavirendra** [comment]
Sure wait 1 minute

**Comment by guptavirendra** [comment]
var toolTip: HITooltip {
        let tooltip = HITooltip()
        let  timeChoice = TimeGroupingChoice(index: 0, tittle: toolTipModelprotocol.groupBy!)
         tooltip.xDateFormat = timeChoice?.toolTipFormat
        /* if collection chart then show only tooltip*/
        if toolTipModelprotocol.collectionChart == true {
            tooltip.pointFormat = "{point.tooltip}"
        }else{
            /* if prefix available then add prefix*/
            if let _ = toolTipModelprotocol.tooltipPrefix, toolTipModelprotocol.tooltipPrefix?.count ?? 0 > 0
            {
                tooltip.valuePrefix = toolTipModelprotocol.tooltipPrefix! + ":"
            }
            /* if suffix avilable then add suffixe*/
            if let _ = toolTipModelprotocol.tooltipSuffix
            {
              let unitConvertor = GraphUnitConverter(isMetric: isMetric, title: toolTipModelprotocol.collectionString[0] ?? "", unit: toolTipModelprotocol.tooltipSuffix ?? "", convertSugarUnit: convertSugarUnit, value:nil)
                tooltip.valueSuffix = " " + unitConvertor.getUnit()
            }
        
            if toolTipModelprotocol is GraphMaster
            {
                let graphData = (toolTipModelprotocol as! GraphMaster)
                /* if collection type health tracker and has tooltip text then add with prefix and tooltip else sho normal*/
                if graphData.collectionType == "healthtracker"{
                    if let  graphArray = graphData.collections?.values {
                        
                        if let graphdataArray = graphArray.first{
                        let filtered  =   graphdataArray?.filter({ (graphData) -> Bool in
                            var valueString = ""
                            switch graphData.tooltip!{
                            case .double( let x):
                                valueString = String(format:"%f", x)
                            case .string( let x):
                                valueString =  x
                            case .int(let x):
                                valueString = String(format:"%d", x)
                            }
                                return valueString.count > 0
                            })
                            if filtered?.count ?? 0 > 0{
                               tooltip.pointFormat = toolTipModelprotocol.tooltipPrefix! + ":" + "{point.tooltip}"
                            }else{
                                tooltip.pointFormat = "{point.y} "
                            }
                        }
                    }
                }else{
                     tooltip.pointFormat = "{point.y} "
                    }
            }
        }
        
        return tooltip
    }

**Comment by pawelfus** [comment]
Thanks, I see you use `point.tooltip` to display tooltip. Could you apply there my suggestion?

**Comment by guptavirendra** [comment]
![Screenshot 2019-08-13 at 4 28 25 PM](https://user-images.githubusercontent.com/891554/62936461-7801f500-bde7-11e9-8cee-96fb5f7a20e9.png)

**Comment by guptavirendra** [comment]
Ok

**Comment by guptavirendra** [comment]
Thanks
