### ISSUE TITLE
Drilldown event triggers but does not provide any property

### ISSUE THREAD

**Issue by hunble** [highcharts/highcharts-ios#218]
First finding decent examples for events is pretty hard. :(

I am having trouble with the following code I am trying to get "category" or any other property possible on the drill-down event but that is not happening. I get the event but the properties are "nil" in all of the cases.

Following is my code

```
let event = HIEvents()
event.drilldown = HIFunction(closure: { [weak self] x in

   print(x?.getProperty("this.category"), x?.getProperty("this.seriesOptions"), x?.getProperty("this.point"), x?.getProperty("this.event.xAxis[0].value"))

},properties: ["this.category", "this.seriesOptions", "this.point", "this.event.xAxis[0].value"])

chart.events = event
```

Its is not just this event other events on "plotoption->series->point" are giving "nil" for properties in most of the cases as well.

What I eventually want to achieve is dynamic minWidth on different levels of drill-down depending on the number of categories on the xAxis

```
chart.scrollablePlotArea = HIScrollablePlotArea()
chart.scrollablePlotArea.minWidth = width
```

**Comment by ihnatmoisieiev** [comment]
Hello @hunble,

thank you for using Highcharts and for your question.

First of all, you can't use the drill-down and point events at the same time, because drill-down is triggered first and point returns `nil` for most properties.

Secondly, the drill-down event has `event` context instead of `this`. So, you can get needed properties in the following way:

```
let event = HIEvents()
event.drilldown = HIFunction(closure: { [weak self] x in

   print(x?.getProperty("event.category"), x?.getProperty("event.seriesOptions"), x?.getProperty("event.point.x"), x?.getProperty("event.point.y"))

},properties: ["event.category", "event.seriesOptions", "event.point.x", "event.point.y"])

chart.events = event
```

Please try and let me know if everything works.

**Comment by hunble** [comment]
Beautiful! worked like a  charm. Thanks a lot. Can we do something in the documentation to make it more obvious? I actually read a lot before opening the issue.
Thanks again

**Comment by ihnatmoisieiev** [comment]
@hunble I will submit your request. Can I close the issue?

**Comment by hunble** [comment]
Closing it, thank for all the support.
