### ISSUE TITLE
How to hide the series in bottom in chart ?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#219]
I want to hide the series at the bottom.
![Screenshot 2019-08-21 at 12 52 14 PM](https://user-images.githubusercontent.com/48505333/63411172-9e8ce500-c412-11e9-910e-108ecd53f6f9.png)

**Comment by ihnatmoisieiev** [comment]
Hello @barotbhavesh,

do you want to hide the series names from a legend?

You can disable the legend by setting `enabled` param to `false` of `HILegend` object:

```
let legend = HILegend()
legend.enabled = false
options.legend = legend
```

Please, see [docs](https://api.highcharts.com/ios/highcharts/Classes/HILegend.html#//api/name/enabled) for more info.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh did you try it? Can I close the issue?
