### ISSUE TITLE
Animation turn off not working (How to turn it off)

### ISSUE THREAD

**Issue by ZuzanaBenicko** [highcharts/highcharts-ios#22]
Hello,

I am using code below to turn off animation during series data reload, but my chart is still animating reload. Not sure if I am missing something or no. (None of the animating options, one by one or both together is working).

options.series = series
options.chart.animation = false
//options.plotOptions.series.animation = false
                    DispatchQueue.main.async {
                        chartViewBar.options = options
                    }

Thank you for your reply,
Zuzana

**Comment by ihnatmoisieiev** [comment]
Hi @ZuzanaBenicko, 

thank you for your question.

You can disable the initial animation when a series is displayed/reloaded by setting series **animation** param to **false** of **plotOptions**, e.g.:

```
let plotOptionsSeries = HIPlotOptionsSeries()
plotOptionsSeries.animation = false

plotOptions.series = plotOptionsSeries
```

**Comment by ZuzanaBenicko** [comment]
Thank you very much! :)

Works perfectly.
