### ISSUE TITLE
Highchart not working on iPad

### ISSUE THREAD

**Issue by vikrantrajput** [highcharts/highcharts-ios#220]
Hello Team, I have integrated iOS Highchart frameworks using CocoaPods successfully. HighChart working well in iPhone device and simulator for both
iPhone & iPad. But When I run Highchart on iPad device which have iOS(10.3) it getting crash every time. I didn't get any warnings or error. Crash control 
always goes to AppDelegate Class  and I am not getting and written  issue of Highchart in console. 
I am giving screenshot url.
Please HELP!
Regards

**Comment by skuske** [comment]
@vikrantrajput 

We have sees similar issues with older iPads, too (see this: https://github.com/highcharts/highcharts-ios/issues/105)

The only solution was to stop support for older iPad devices. There's no way to make the Highcharts wrapper work properly on iPads with iOS 10.

**Comment by vikrantrajput** [comment]
@skuske Thanks for your reply.
But Its working iPad simulator with iOS 10 version.

**Comment by skuske** [comment]
@vikrantrajput 

Yes, it might work on the simulator, as it's not a real physical device, which is a huge difference in regards to the hardware itself (CPU etc.)

**Comment by skuske** [comment]
@vikrantrajput 

In addition: I guess the issue is caused by the fact that older iPads run on 32bit, where newer models run on 64bit CPUs.

**Comment by vikrantrajput** [comment]
For now HighChart is not supporting for 32bit devices ?. If not then is there any way to resolve this issue for iPad(iOS 10)?

**Comment by skuske** [comment]
@vikrantrajput 

Officially you'll not find any statement that Highcharts does not support 32bit CPUs. Actually only iPads are affected as far as we observed this. But I cannot tell for sure.

The iOS Highcharts wrapper uses iOS Webkit and that seems to cause trouble on older devices. See the [thread](https://github.com/highcharts/highcharts-ios/issues/105) I mentioned above.

We stopped supporting iOS < 11 in our app as there's no way to get the wrapper work properly on iOS < 11. We saw quite a few issues with the wrapper on such old devices and as there were just 1% - 3% of our users running older iPads, we just stopped supporting them and we now require iOS 11 or better. That fixed all the issues although some users now can no longer use our app. That's life - you must go with the times, unfortunately. We are not aware of any fix to make Highcharts work on older iPads.

**Comment by skuske** [comment]
@vikrantrajput 

Another addition: we believe that it is actually **not Highcharts**, but iOS Webkit causing the trouble on older devices.

**Comment by ihnatmoisieiev** [comment]
Hello @vikrantrajput,

@skuske described the problem exactly. **Highcharts** requires iOS 11 for iPads. Plese see this [thread](https://github.com/highcharts/highcharts-ios/issues/105) for more info.

@skuske thank you very much!

**Comment by skuske** [comment]
@ihnatmoisieiev 

No problem. :o)

**Comment by vikrantrajput** [comment]
Thanks @skuske & @ihnatmoisieiev
