### ISSUE TITLE
Pie Chart not displaying all dataLabels

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#225]
Hi,

Here is my data:

[["y": 74.8, "name": "Freie Margin"], ["name": "Währungen", "y": 2.3], ["name": "Aktien", "y": 1.3], ["y": 1.3, "name": "Rohstoffe"], ["name": "Indizes", "y": 17.8], ["y": 2.5, "name": "Kryptowährungen "]]

And here is the pie chart : 
![Screenshot 2019-08-30 at 13 34 50](https://user-images.githubusercontent.com/610975/64017957-32edfa80-cb2b-11e9-9a2f-8fc88b88205a.png)

As you can see "Aktien" is missing as data label

**Comment by ergunkocak** [comment]
![Screenshot 2019-08-30 at 13 34 50](https://user-images.githubusercontent.com/610975/64017932-21a4ee00-cb2b-11e9-827a-b9086a9c0548.png)

**Comment by skuske** [comment]
@ergunkocak 

Mostly this is because there's simply no room to display the label. I guess if you deselect (hide) one of the other items, the other one will show up. Maybe using a smaller font size fixes this, too.

**Comment by ihnatmoisieiev** [comment]
Hi @ergunkocak,

@skuske is right. 

Did you try to decrease `dataLabels` font size and set `padding` to `0`?

**Comment by ergunkocak** [comment]
Will try reducing the font size and padding and return to you

**Comment by ergunkocak** [comment]
Font size can not be changed. Its a design decision. 
But "dataLabels.padding = 1" solved my problems.
Thanks

**Comment by ergunkocak** [comment]
Sorry but i had the problem again with another data set :(

![Screenshot 2019-09-03 at 11 57 05](https://user-images.githubusercontent.com/610975/64163709-0e9f6000-ce42-11e9-9500-919f6c2c54b1.png)

[
  ["Freie Margin", 95.39],
  ["Aktien", 0.4],
  ["Indizes", 3.50],
  ["Kryptowährungen", 0.70]
]

I can not reduce the font and padding is 1 at the moment.

What can i do?

**Comment by skuske** [comment]
@ergunkocak 

I doubt that there is anything you can do. If the slices are too thin, then there's not enough room to display the labels. That means that labels are only displayed if the corresponding slice is large enough.

**Comment by ergunkocak** [comment]
But in current case there is a lot of free space?
