### ISSUE TITLE
Limit export buttons to CSV and PNG only

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#227]
Since PDF export is currently not working properly (see https://github.com/highcharts/highcharts-ios/issues/213) I tried to limit the export buttons to CSV and PNG, but that does not work, the PDF option is still displayed:

```
    HIExporting *exporting = [[HIExporting alloc] init];
    exporting.enabled = [[NSNumber alloc] initWithBool:true];
    exporting.buttons=[[HIButtons alloc] init];
    exporting.buttons.contextButton=[[HIContextButton alloc] init];
    exporting.buttons.contextButton.menuItems=@[ @"downloadPNG",@"downloadCSV" ];
```

What can I do to limit export to CSV and PNG?

![PNG-Bild](https://user-images.githubusercontent.com/12996815/64100964-0c1f0680-cd6d-11e9-8bfb-92abab162c6c.png)

Thanks

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

you can't limit the export buttons. They are constant: `image`, `PDF` and `CSV`. 

You can only change the title of the buttons by configuring `HILang` object.

**Comment by skuske** [comment]
@ihnatmoisieiev 

OK, but then we **urgently** need the PDF option to actually work properly, otherwise people will use that option and wonder why it does not do anything...

And: `exporting.buttons.contextButton.menuItems` does not make sense at all then, right? At least on iOS... We thought that `exporting.buttons.contextButton.menuItems` would let us configure the options that should be displayed, just like in JS. See [here](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/exporting/menuitemdefinitions/).

**Comment by ihnatmoisieiev** [comment]
@skuske 

right, `exporting.buttons.contextButton.menuItems` doesn't work on iOS.

**Comment by skuske** [comment]
@ihnatmoisieiev 

OK, when can we expect https://github.com/highcharts/highcharts-ios/issues/213 to be fixed? We really need that **urgently** as the non working PDF export prevents us from using the export feature at all since we cannot remove the PDF button now... Thanks.

**Comment by skuske** [comment]
@ihnatmoisieiev 

An alternative would be to make the export functions for CSV and PNG public, so that we can create our own menu, and trigger the export with 

`[HIChartView TriggerExportToCSV];`

respectively

`[HIChartView TriggerExportToPNG];`

**Comment by ihnatmoisieiev** [comment]
@skuske public export methods have been added to the latest release.

**Comment by skuske** [comment]
@ihnatmoisieiev 

I just tried it, but maybe I am doing something wrong as it does not work: the following code shows the 'Cancel' option only, but nothing else.

```
    exporting.buttons=[[HIButtons alloc] init];
    exporting.buttons.contextButton=[[HIContextButton alloc] init];
    exporting.buttons.contextButton.menuItems=@[ @"downloadPNG",@"downloadCSV" ];
```

![IMG_5132](https://user-images.githubusercontent.com/12996815/64674379-031aed00-d471-11e9-956f-6a660e9f47d3.PNG)

```
    HILang *lang = [[HILang alloc]init];
    lang.downloadCSV=@"CSV";
    lang.downloadPNG=@"PNG";
    lang.downloadPDF=@"PDF";
    lang.cancelButtonTitle=@"Abbrechen";
```

Any idea what's going wrong here?

**Comment by ihnatmoisieiev** [comment]
@skuske the api docs hasn't been updated yet. `menuItems` for iOS are: `sharePNG`, `sharePDF`, `shareCSV`.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks. That works. :o)

**Comment by tharmini75** [comment]
I tried some thing like below not any conclusion,
HIExporting exporting = new HIExporting();
        exporting.setEnabled(true);
        HILang hilang = new HILang();
        //exporting.getButtons();
        //exporting.getButtons().getContextButton();
        exporting.getButtons().getContextButton().getMenuItems()= @'downloadPNG",@"downloadCSV");
        hilang.getViewFullscreen();
        hilang.getPrintChart();
        hilang.getDownloadPNG();
        hilang.getDownloadJPEG();
        hilang.getDownloadPDF();
        hilang.getDownloadSVG();
        hilang.getDownloadCSV();
        hilang.getDownloadXLS();
        hilang.getViewData();
        //exporting.setFallbackToExportServer(false);
        //exporting.setEnabled(Boolean.valueOf(options.get("export")));
        options.setExporting(exporting);
