### ISSUE TITLE
HIExporting 'filename' not working

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#228]
```
    HIExporting *exporting = [[HIExporting alloc] init];
    exporting.filename=@"Test-Filename";
```

This is not working - the filename is ignored: for CSV exports the filename is always 'chart', and for image exports, the filename is always 'PNG-Image".

**Comment by ihnatmoisieiev** [comment]
@skuske it is not possible to change the filename at the moment.

**Comment by skuske** [comment]
@ihnatmoisieiev 

That is really bad as that will overwrite existing files and there's no way to make filenames reflect what type of chart data they actually contain.

I have the impression that the complete export function of the wrapper is largely immature and you can not really use it. Especially the lack of file name support and the malfunctioning PDF export function make the whole thing almost useless.

**Comment by spinneyio** [comment]
Hi @skuske - we are doing our best to improve the functionality you are interested in. We will keep you up to date on our progress here.

**Comment by skuske** [comment]
@spinneyio 

Thanks! :o)

Problem is: we started planning and developing and had to realise, that important parts of the exporting feature do not work, which makes it impossible to continue with our work. The API documentation lists all features as fully supported, but when we implemented them we saw that quite a lot of things are actually **not** supported, or not working properly. And yes, we own a paid license which makes it even more frustrating. I understand that there can be bugs, but I don't understand why incomplete features or not fully supported features are not marked as such within the API docs.

**Comment by ihnatmoisieiev** [comment]
@skuske as you probably noticed, advanced export functionality requires an additional module `export-data`. Additional exporting options were implemented natively on your request https://github.com/highcharts/highcharts-ios/issues/51. It is implemented in iOS and doesn't connect to `exporting.buttons.contextButton`. These https://github.com/highcharts/highcharts-ios/issues/227, https://github.com/highcharts/highcharts-ios/issues/228, https://github.com/highcharts/highcharts-ios/issues/229, https://github.com/highcharts/highcharts-ios/issues/231 issues concern exactly the same.

Thank you for your attention about the API docs. Actually, it's confusing and will be changed.

All the above issues could be fixed on your request. Please, create a list of exporting features which you want to get in the next release. We will try to implement it as soon as possible.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks for your reply.

We need the following features to be implemented asap:

1.) Working PDF export, **or alternatively**: support of `exporting.buttons.contextButton.menuItems=@[ @"downloadPNG",@"downloadCSV" ];` as mentioned [here](https://github.com/highcharts/highcharts-ios/issues/227) so that we can remove the PDF export option.

2.) HIExporting 'filename' support

3.) Working `exporting.buttons.contextButton` customization support - see [here](https://github.com/highcharts/highcharts-ios/issues/231) and [here](https://github.com/highcharts/highcharts-ios/issues/229). Since iOS 13 comes with the new DarkMode, we would also need easy button background color customization. Best would be if the framework would detect DarkMode by itself and adopt button colors automatically.

Most important is (1) and (2) as we are stuck with development due to the fact that both features are not working.

Thanks a lot! :o)

**Comment by skuske** [comment]
@ihnatmoisieiev 

When will the next release be available? We need to get along with a planned release. Thanks.

**Comment by ihnatmoisieiev** [comment]
@skuske the newest release is available.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks very much! I'll give it a try later today.
