### ISSUE TITLE
contextButton.symbolFill not working

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#229]
This is not working:

```
    HIExporting *exporting = [[HIExporting alloc] init];
    exporting.enabled = [[NSNumber alloc] initWithBool:boolUpgraded_Other_StationCache];
    exporting.buttons=[[HIButtons alloc] init];
    exporting.buttons.contextButton=[[HIContextButton alloc] init];
    exporting.buttons.contextButton.symbolFill=[[HIColor alloc] initWithHexValue:@"ff0000"];
```

The fill color of the exporting symbol cannot be changed. `symbolFill` has no effect.

It is important to be able to change the color especially with the upcoming DarkMode of iOS 13.

Also, how to change the background color of the button?

**Comment by sebastianbochan** [comment]
Hi @skuske,
Please let me know about format of symbol do you use (png or svg etc)? It should be SVG symbol which works properly by default.

Demo:
- https://jsfiddle.net/BlackLabel/mr7ea604/

**Comment by skuske** [comment]
@sebastianbochan 

Thanks for getting back. I was using a PNG. Will try a SVG asap, but I might need a few days.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

any update from your side?

**Comment by skuske** [comment]
@ihnatmoisieiev 

I haven't had a chance to test this again. You may close this, though.
