### ISSUE TITLE
Tooltip formatter

### ISSUE THREAD

**Issue by simerlec** [highcharts/highcharts-ios#23]
Hello,

the latest upgrade enabled the use of the tooltip.formatter.

This works just fine so far but I can't figure out whats the correct way to format the date value you get with this.x. In JS this is no issue but here I cannot use (or at least I don't know how exactly) custom formatters. Example case of an arearange date/value chart:

```swift
tooltip.formatter = "function () { return  '<small>' + this.x + '</small><br/>
this.points[0].series.name + ':  ' + this.points[0].point.high + '/' + 
this.points[0].point.low + this.points[0].series.tooltipOptions.valueSuffix }"
```

works just fine but obviously this.x returns me the time in milliseconds. How can I use the default converter or provide my own formatter for this value to print a human readable time value?

thanks and kind regards

**Comment by mll** [comment]
Hi @simerlec. Try:

`(this.x * 1000.0).toFixed(2)`

**Comment by simerlec** [comment]
Sry, I'm not sure that I clearly described what I meant.

I looked around a little more and discovered that I can use a static formatter which is inlcuded in the Highcharts object.

```
...Highcharts.dateFormat('%d %b %y %H:%M:%S', this.x)...
```

which kinda does the job.

I just wanted to know if there is some way to get the tooltip.formatter time to display like the standard tooltip.headerFormat which i use like this

```
tooltip.headerFormat = "<small>{point.key}</small><br/>"
```

and displays it nicely like this - I'm assuming by using moment.js
![screenshot 2017-09-05 09 11 31](https://user-images.githubusercontent.com/5793380/30049262-3a36142c-921a-11e7-996c-6761ef05efe6.png)

I hope I'm not too confusing.

Thanks and kind regards

**Comment by ihnatmoisieiev** [comment]
Hi @simerlec,
did you set up [xAxis type](http://api.highcharts.com/highcharts-ios/xAxis.type) as `"datetime"` and `pointInterval` for your series?

**Comment by simerlec** [comment]
hello @ihnatmoisieiev,

yes my xAxis has the type datetime - point interval is not necessary I believe since my data entries have timestamps.

Using tooltip.formatter I can get these long values fine using `this.x` but I'm not sure what options I have to format this value. Using JS I would do it like this utilizing moment.js:

```
 tooltip: {
                formatter: function () {
                    return `<b>` + moment(this.x).format('LLLL') + ...
                    ... rest ommitted for brevity
                },
                crosshairs: true,
                shared: true
            },
```

So i wanted to know if there is another possibility besides the `Highcharts.dateFormat` function since it seems to me - because of the format that `tooltip.headerFormat = "{point.key}<br/>"` gives me - that moment.js is used internally too :)

**Comment by TorsteinHonsi** [comment]
Moment.js is not used internally, all this is done using the Highcharts.dateFormat function. You can add specific time formats to the tooltip _without_ using the formatters by adding it behind a colon in the inserted variables, for example like this:

`tooltip.pointFormat = "<small>{point.x:%Y-%m-%d}</small>: {point.y}";`

Or you can just call Highcharts.dateFormat, see the documentation [here](http://api.highcharts.com/highcharts/Highcharts.dateFormat).

**Comment by simerlec** [comment]
Thanks @TorsteinHonsi, did not know that PHP's strftime function was that comprehensive.

One more thing which also fits in this ticket I think - I want a custom valueSuffix per series in my chart.

Im trying with
```
let tooltip = HITooltip()
tooltip.shared = true
tooltip.headerFormat = "<small>{point.key}</small><br/>"
tooltip.pointFormat = "{series.name}: {point.y:.1f}{series.tooltip.valueSuffix}"

let options = HIOptions()
options.tooltip = tooltip
````
 where I have overridden the tooltips valueSuffix per series with
```
let splineTooltip = HISplineTooltip()
splineTooltip.valueSuffix = "mySuffix" 
series.tooltip = splineTooltip
```

but all it gives me is a small white rectangle like you see in #6. series.name and series.color work just fine.

I also tried variations like series.valueSuffix but to no avail.

What am I doing wrong?

**Comment by ihnatmoisieiev** [comment]
Hello @simerlec,

you have to set up the **pointFormat** for every series. Try change your code to:

```
let tooltip = HITooltip()
tooltip.shared = true
tooltip.headerFormat = "<small>{point.key}</small><br/>"

let options = HIOptions()
options.tooltip = tooltip
```

then override the tooltips **pointFormat** and **valueSuffix** per series

```
let splineTooltip = HISplineTooltip()
splineTooltip.pointFormat = "{series.name}: <b>{point.y}</b><br/>"
splineTooltip.valueSuffix = " mySuffix"

series.tooltip = splineTooltip
```

I hope this resolve your problem.

**Comment by simerlec** [comment]
Hmm the reason for me trying with some variation of the bracket notation (like {series.valueSuffix}) was that the standard way was not working for me. As I read from the docs the suffix should be present behind the y-values as soon as one sets a custom suffix. But this was not the case for me - and now I know why.

I'm formatting my values even further to include only one decimal point using

```
{point.y:.1f}
```

which apparently hinders the suffix from showing. As soon as i switch to 

```
{point.y}
```

the custom suffix is showing just fine.

**Comment by ihnatmoisieiev** [comment]
@simerlec  can I close this issue?

**Comment by simerlec** [comment]
Sry for the delay - yes, I'll close the issue.

Thx.

**Comment by saurabhjain6853** [comment]
hello, can you give some idea how to use tooltip.formatter in iOS (Swift or Objective C)?

How can I use it?
