### ISSUE TITLE
Could not display HIPlotLines

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#234]
Hi,

Just upgraded to 7.1.4 to be able to work with HIPlotLines. But could not make it work yet.

I have 139 points in my chart with timestamp values as x values. I tried:

```swift
let plotLines = HIPlotLines()
plotLines.color = HIColor(hexValue: "FF0000")
plotLines.width = NSNumber(value: 2)
plotLines.value = NSNumber(value: 50)
plotLines.zIndex = 50
options.xAxis.first!.plotLines = [plotLines]
```

but i did not see any vertical line
![Screenshot 2019-09-03 at 15 17 48](https://user-images.githubusercontent.com/610975/64176584-0523f100-ce5e-11e9-9b88-ab4bb6ca3515.png)

**plotLines.value** is this the index of veritcal line which i want to draw or the value of x axis for the point?

**Comment by ergunkocak** [comment]
plotLines.value

Is this the index of veritcal line which i want to draw or the value of x axis for the point?

**Comment by ihnatmoisieiev** [comment]
Hi @ergunkocak,

yes, `plotLines.value` is the position of the line in axis units.

See a demo below:

```
let options = HIOptions()

let xAxis = HIXAxis()
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

let plotLine = HIPlotLines()
plotLine.color = HIColor(uiColor: UIColor.red)
plotLine.width = 2
plotLine.value = 5.5
xAxis.plotLines = [plotLine]

options.xAxis = [xAxis]

let line = HILine()
line.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [line]
```

**Comment by ergunkocak** [comment]
Hi,

I could not make it work. Here is the code:

```swift
let plotLines = HIPlotLines()
plotLines.id = "lastPointMarkerVerticalLine"
plotLines.color = HIColor(hexValue: "FF0000")
plotLines.width = NSNumber(value: 2)
plotLines.value = NSNumber(value: 50)
plotLines.zIndex = 50
xAxis.plotLines = [plotLines]
```

data:
[[0, 1.13099], [1, 1.1339], [2, 1.13449], [3, 1.13361], [4, 1.1333], [5, 1.13593], [6, 1.13931], [7, 1.13721], [8, 1.13705], [9, 1.13647], [10, 1.13357], [11, 1.13003], [12, 1.13081], [13, 1.11917], [14, 1.12342], [15, 1.1263], [16, 1.12896], [17, 1.13371], [18, 1.13058], [19, 1.13246], [20, 1.13348], [21, 1.13532], [22, 1.1421], [23, 1.13763], [24, 1.13007], [25, 1.13144], [26, 1.12753], [27, 1.12492], [28, 1.12282], [29, 1.12176], [30, 1.1203], [31, 1.12029], [32, 1.12372], [33, 1.12209], [34, 1.12151], [35, 1.12604], [36, 1.12644], [37, 1.12748], [38, 1.12568], [39, 1.12989], [40, 1.13005], [41, 1.12855], [42, 1.12979], [43, 1.12319], [44, 1.12424], [45, 1.1258], [46, 1.12229], [47, 1.11553], [48, 1.11341], [49, 1.11417], [50, 1.1183], [51, 1.1215], [52, 1.11989], [53, 1.11721], [54, 1.12017], [55, 1.11945], [56, 1.11932], [57, 1.11944], [58, 1.12183], [59, 1.12336], [60, 1.12262], [61, 1.12071], [62, 1.1205], [63, 1.1174], [64, 1.11569], [65, 1.11673], [66, 1.11626], [67, 1.11527], [68, 1.11823], [69, 1.12045], [70, 1.11938], [71, 1.11656], [72, 1.11349], [73, 1.11291], [74, 1.1169], [75, 1.12441], [76, 1.12537], [77, 1.12266], [78, 1.12771], [79, 1.13324], [80, 1.13128], [81, 1.13273], [82, 1.12916], [83, 1.1277], [84, 1.12094], [85, 1.12212], [86, 1.11945], [87, 1.12294], [88, 1.12935], [89, 1.13692], [90, 1.13965], [91, 1.13685], [92, 1.13737], [93, 1.13681], [94, 1.13696], [95, 1.12881], [96, 1.12883], [97, 1.12795], [98, 1.12851], [99, 1.12255], [100, 1.12156], [101, 1.1208], [102, 1.12534], [103, 1.12534], [104, 1.12707], [105, 1.12609], [106, 1.12104], [107, 1.12272], [108, 1.1277], [109, 1.12209], [110, 1.1209], [111, 1.11518], [112, 1.11422], [113, 1.11476], [114, 1.11267], [115, 1.11454], [116, 1.11551], [117, 1.10727], [118, 1.10827], [119, 1.11086], [120, 1.12138], [121, 1.12015], [122, 1.12011], [123, 1.11931], [124, 1.11991], [125, 1.12157], [126, 1.11725], [127, 1.11412], [128, 1.11061], [129, 1.10907], [130, 1.10797], [131, 1.10971], [132, 1.10878], [133, 1.10807], [134, 1.11398], [135, 1.11004], [136, 1.10906], [137, 1.10809], [138, 1.10581], [139, 1.09898], [140, 1.09693], [141, 1.09707], [142, 1.10176]]

Screenshot:
![Screenshot 2019-09-04 at 12 34 32](https://user-images.githubusercontent.com/610975/64248010-61dfe400-cf10-11e9-910e-6801e3cbb4f6.png)

**Comment by ergunkocak** [comment]
Also not displaying HIPlotBands.

```swift
if let xAxis = options.xAxis.first {
            let plotBands = HIPlotBands()
            plotBands.from = 20
            plotBands.to = 60
            plotBands.borderWidth = 1
            plotBands.color = HIColor(hexValue: "74CCF4")
            xAxis.plotBands = [plotBands]
}
```

**Comment by ergunkocak** [comment]
Chart type is "areaspline"

**Comment by ergunkocak** [comment]
```swift
xAxis.addPlotLine(plotLines)
```
solved my problem. So assigning plotLines does not trigger redraw ???

But this time, somehow, added plot line is not in plotLines array of chart options:

```swift
options.xAxis.first?.plotLines?.isEmpty
```
but it is always empty 🤦‍♂ 

This does not draw the chart:

```swift
if false == miniHighChartView.options.xAxis.first?.plotLines?.isEmpty {
                if plotLines.value != lastTick.x {
                    plotLines.value = lastTick.x
                    xAxis.removePlotLine("lastPointMarkerVerticalLine")
                    xAxis.addPlotLine(plotLines)
                    lui.l("Chart updated plotLine")
                }
            } else {
                plotLines.value = lastTick.x
                //                miniHighChartView.options.xAxis.first?.plotLines = [plotLines]
                miniHighChartView.options.xAxis.first?.plotLines = [plotLines]
//                miniHighChartView.options.xAxis.first?.removePlotLine("lastPointMarkerVerticalLine")
//                miniHighChartView.options.xAxis.first?.addPlotLine(plotLines)
                lui.l("Chart added plotLine \(self.miniHighChartView.options.xAxis.first?.plotLines?.count ?? 0)")
            }
```

And this adds the plot line always (each time i update the last point y value):

```swift
if false == miniHighChartView.options.xAxis.first?.plotLines?.isEmpty {
                if plotLines.value != lastTick.x {
                    plotLines.value = lastTick.x
                    xAxis.removePlotLine("lastPointMarkerVerticalLine")
                    xAxis.addPlotLine(plotLines)
                    lui.l("Chart updated plotLine")
                }
            } else {
                plotLines.value = lastTick.x
                miniHighChartView.options.xAxis.first?.addPlotLine(plotLines)
                lui.l("Chart added plotLine \(self.miniHighChartView.options.xAxis.first?.plotLines?.count ?? 0)")
            }
```

**Comment by ergunkocak** [comment]
lui.l is my print method

**Comment by ergunkocak** [comment]
@ihnatmoisieiev actually it was not a question :)

**Comment by ihnatmoisieiev** [comment]
@ergunkocak 

if you haven't assign `plotLines` in your initial options and want to add them later, you can do it in the following ways:

1. 
```
let xAxis = chartView.options.xAxis

if let firstAxis = xAxis?.first {
    let plotLine = HIPlotLines()
    plotLine.color = HIColor(uiColor: UIColor.red)
    plotLine.width = 2
    plotLine.value = 5.5
    firstAxis.plotLines = [plotLine]

    chartView.options.xAxis = xAxis
}
```

This will add the plot line to `xAxis.plotLines` array.

2. 
```
let xAxis = self.chartView.options.xAxis

if let firstAxis = xAxis?.first {
    let plotLine = HIPlotLines()
    plotLine.color = HIColor(uiColor: UIColor.red)
    plotLine.width = 2
    plotLine.value = 5.5

    firstAxis.addPlotLine(plotLine)
}
```

3. 
```
let xAxis = self.chartView.options.xAxis

if let firstAxis = xAxis?.first {
    let updatedXAxis = HIXAxis()

    let plotLine = HIPlotLines()
    plotLine.color = HIColor(uiColor: UIColor.red)
    plotLine.width = 2
    plotLine.value = 5.5

    updatedXAxis.plotLines = [plotLine]

    firstAxis.update(updatedXAxis)
}
```

4.
```
let updatedOptions = HIOptions()

let updatedXAxis = HIXAxis()

let plotLine = HIPlotLines()
plotLine.color = HIColor(uiColor: UIColor.red)
plotLine.width = 2
plotLine.value = 5.5

updatedXAxis.plotLines = [plotLine]

updatedOptions.xAxis = [updatedXAxis]

chartView.update(updatedOptions)
```

2, 3, 4 won't update `xAxis.plotLines` array, because it calls native `JS` functions.

**Comment by ergunkocak** [comment]
Hi @ihnatmoisieiev 

Adding and removing plotlines instead of updating is ok for me. But there is a problem; when i add the plot line in initialization it does not display it. I am not sure about the cause. I am in a very strict deadline so as soon as i have some time i will make demo project and showcase the issue. So please do not close the issue :)

**Comment by ihnatmoisieiev** [comment]
@ergunkocak ok, no problem.

**Comment by ergunkocak** [comment]
@ihnatmoisieiev i prepared the mini test project which i can reproduce the issue. Can i email it to you?

**Comment by ergunkocak** [comment]
@ihnatmoisieiev we have a paid license. Am i doing right by posting here? Do i need to do something else to increase the priority?

Best

**Comment by ihnatmoisieiev** [comment]
Hi @ergunkocak,

sure, send me please this test project.

**Comment by ergunkocak** [comment]
ups i dont have ur email :) you can ping me from ekocak@nextmarkets.com

**Comment by ergunkocak** [comment]
Sent 👍

**Comment by ergunkocak** [comment]
@ihnatmoisieiev any updates?

**Comment by ihnatmoisieiev** [comment]
@ergunkocak I answered you yesterday by mail.

**Comment by ergunkocak** [comment]
It worked when i changed :
```swift
let xaxis = HIXAxis()
xaxis.visible = false
```
to :
```swift
        let xaxis = HIXAxis()
        xaxis.visible = true
        xaxis.lineColor = HIColor(uiColor: .clear)
        xaxis.tickColor = HIColor(uiColor: .clear)
        xaxis.labels = HILabels()
        xaxis.labels.enabled = false
```
