### ISSUE TITLE
Question: Is it possible to implement these annotations

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#239]
Hi,

Is it possible to build annotations like this: (image(from web), image(from local), text. All ina rounded transparent bg box)

![Screenshot 2019-09-17 at 14 33 53](https://user-images.githubusercontent.com/610975/65042049-50f39180-d958-11e9-82a1-ab029690a723.png)

I already implement the rest:

![Screenshot 2019-09-17 at 14 35 43](https://user-images.githubusercontent.com/610975/65042103-7385aa80-d958-11e9-9a0e-16aa32315259.png)

**Comment by ihnatmoisieiev** [comment]
Hello @ergunkocak,

it is possible, but we noticed that annotations `borderRadius` doesn't work at the moment.

See [this](https://jsfiddle.net/BlackLabel/u0osd2tm/) example and more advanced: https://www.highcharts.com/ios/demo/annotations

**Comment by ergunkocak** [comment]
So this example is actualy not doing what i need but mimicing it by placing items side by side :(
To be able to use this i need to know the size of text so i can create a background. If the text is variable length which is 99% of the time :) it will be a problem :(

**Comment by pawelfus** [comment]
Hi @ergunkocak 

@ihnatmoisieiev is on vacation till Wednesday.

Meanwhile I can suggest another solution. It has some downsides but please take a look: https://jsfiddle.net/BlackLabel/L2wq7c89/ - solution uses HTML elements to render the label (instead of default SVG elements). The problem is tooltip, that is rendered below the label and without anchor. You can render tooltip using HTML elements too, but this requires extra work. I have created a simple example for you how to start: https://jsfiddle.net/BlackLabel/2a3trxdz/ (

**Comment by ergunkocak** [comment]
@pawelfus @ihnatmoisieiev 
First of all thanks for the last link (https://jsfiddle.net/BlackLabel/2a3trxdz/) but it seems giving 500 for the moment. We need :
- an anchor to a point
- be able to display local and web image side by side
- be able to add a text and box these three

Otherwise i cant see how can i implement it as a swift dev :(

**Comment by ihnatmoisieiev** [comment]
@ergunkocak here is the @pawelfus example in Swift:

```
let options = HIOptions()

let chart = HIChart()
chart.type = "line"
options.chart = chart

let title = HITitle()
title.text = "Basic shape annotations"
options.title = title

let tooltip = HITooltip()
tooltip.useHTML = true
tooltip.borderWidth = 0
tooltip.backgroundColor = HIColor(name: "transparent")

let shadow = HIShadowOptionsObject()
shadow.opacity = 0
shadow.color = "transparent"
tooltip.shadow = shadow

tooltip.distance = 5
tooltip.formatter = HIFunction(jsFunction: "function() { return '<div style=\"padding: 8px; background-color: rgba(247, 247, 247, 0.85); border: 1px solid ' + this.series.color + '; border-radius: 5px;\">' + '<span style=\"color: ' + this.series.color + '\">' + this.series.name + '</span><br>' + 'y: ' + this.y + ', x: ' + this.x + '</div>'; }")
options.tooltip = tooltip

let line = HILine()
line.keys = ["y", "id"]
line.data = [
    [29.9, "0"],
    [71.5, "1"],
    [106.4, "2"],
    [129.2, "3"],
    [144.0, "4"],
    [176.0, "5"]
]
options.series = [line]

let xAxis = HIXAxis()
xAxis.min = 0
xAxis.max = 6
options.xAxis = [xAxis]

let yAxis = HIYAxis()
yAxis.max = 300
options.yAxis = [yAxis]

let annotations = HIAnnotations()

let labels = HILabels()
labels.useHTML = true

let point = HIPoint()
point.y = 129.2
point.x = 3
point.xAxis = 0
point.yAxis = 0
labels.point = point

if let imageIOS = UIImage(named: "apple"), let data = imageIOS.pngData() {
    let base64String = data.base64EncodedString()
    labels.text = "<div><img src=\"https://www.highcharts.com/samples/graphics/sun.png\" width=\"20\" height=\"20\" style=\"vertical-align:middle\"/><img src=\"data:application/png;base64,\(base64String)\" width=\"20\" height=\"20\" style=\"vertical-align:middle\"/> <span>Some long text</span></div>"
}

labels.x = 0
labels.y = -10
labels.align = "left"
labels.shape = "rect"
labels.borderRadius = 10

annotations.labels = [labels]
options.annotations = [annotations]
```

Please try and let us know :)

**Comment by ergunkocak** [comment]
Perfect, thanks a lot 👍
