### ISSUE TITLE
Unable to scroll after zoom

### ISSUE THREAD

**Issue by simerlec** [highcharts/highcharts-ios#24]
Hello,

I have multiple charts inside a scrollview which works perfectly fine - the whole HIChartView area registers the gesture. After I zoom in (chart zoom is set to "x") and reset the zoom the chart area captures the scroll gesture and won't allow to scroll anymore. Here's a capture to help understand what I'm talking about.

![screen_cap](https://user-images.githubusercontent.com/5793380/29875242-a42edb46-8d99-11e7-9918-a5f868707cc7.gif)

Note: The issue is the same using the simulator as well as real devices.

**Comment by ihnatmoisieiev** [comment]
Hello @simerlec,
thanks. I will report it.

**Comment by ihnatmoisieiev** [comment]
@simerlec it is fixed in the newest 6.0.2 release.

**Comment by simerlec** [comment]
Look like it works, thanks.
