### ISSUE TITLE
How can i prevent flicker in annotaion images

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#243]
Hi,

Here is my screenshot. 

![Screenshot 2019-10-01 at 14 42 11](https://user-images.githubusercontent.com/610975/65962760-ab611780-e459-11e9-9113-c8e82a5267aa.png)
![Screenshot 2019-10-01 at 14 40 16](https://user-images.githubusercontent.com/610975/65962761-ab611780-e459-11e9-88f9-a01afdb32a0f.png)

2 blue circles are local images in my app. When i update the last tick. time to time these images flicker. Is there a way to prevent this?

**Comment by ihnatmoisieiev** [comment]
Hello @ergunkocak,

how did you add images and update your chart? I'll try to reproduce the issue.

**Comment by ergunkocak** [comment]
marker.symbol = UIImage(named: "miniChartMarker")!.image()

**Comment by ergunkocak** [comment]
Is there a way to update the last point only without causing a flicker?

**Comment by ergunkocak** [comment]
I also started experiencing annotation place jumps after y value updates:

![Screenshot 2019-10-14 at 16 43 41](https://user-images.githubusercontent.com/610975/66760204-e7f13200-eea1-11e9-8fe4-9e505f488aab.png)
![Screenshot 2019-10-14 at 16 43 37](https://user-images.githubusercontent.com/610975/66760205-e7f13200-eea1-11e9-9929-be8e998fbadc.png)

**Comment by ergunkocak** [comment]
ok last price jumps were my bad, sorry. :) deleting those comments not to confuse

**Comment by ihnatmoisieiev** [comment]
@ergunkocak how do you update your chart? How I can reproduce the issue?

**Comment by ergunkocak** [comment]
@ihnatmoisieiev I found out the problem. I was assigning the marker image from scratch all the time. I made it a static var and the flicker is gone.
