### ISSUE TITLE
In Pie chart inside the text issue

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#244]
In pie chart text looks not good in portrait or landscape mode.Text is not fix side its dynamic 
![Simulator Screen Shot - iPhone 5s - 2019-10-03 at 12 15 10](https://user-images.githubusercontent.com/48505333/66105081-146e9980-e5d8-11e9-92b3-a9da28035a67.png)
![Simulator Screen Shot - iPhone 5s - 2019-10-03 at 12 15 34](https://user-images.githubusercontent.com/48505333/66105084-15073000-e5d8-11e9-8305-2ae12950082c.png)

**Comment by ihnatmoisieiev** [comment]
Hello @barotbhavesh,

please see https://github.com/highcharts/highcharts-ios/issues/209

**Comment by barotbhavesh** [comment]
According the old answer i am fix the text if we have static text but now in my side i have dynamic text(Text come to backend) so your solution is not working in now case.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh did it solve your question? Can I close the issue?

**Comment by barotbhavesh** [comment]
According the old answer i am fix the text if we have static text but now in my side i have dynamic text(Text come to backend) so your solution is not working in now case.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh try to add these two lines to your `HITitle` config:

```
title.useHTML = true
title.text = "<span style=\"width:250px; display:block; white-space:normal; text-align: center;\">Some title</span>"
```

and adjust `width:` param.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh did you try it? Can I close the issue?

**Comment by barotbhavesh** [comment]
Thanks for reply i am trying your code but not get success yet. 
![Simulator Screen Shot - iPhone 5s - 2019-11-28 at 10 47 13](https://user-images.githubusercontent.com/48505333/69779059-b1127980-11cc-11ea-80c6-d95233c4a6be.png)

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh please see:

![Zrzut ekranu 2019-11-28 o 09 31 46](https://user-images.githubusercontent.com/11294008/69790074-0f862a80-11c2-11ea-9f22-10fae18779ef.png)

I'm attaching config of `HITitle` object:

```
let title = HITitle()
title.useHTML = true
title.text = "<span style=\"width:250px; display:block; white-space:normal; text-align: center;\">MTD Diff asaddsds dsdssddsdsdssds dssfdfdfdfd fdfdfdfdfd fdfdfdfdfd</span>"
title.align = "center"
title.verticalAlign = "middle"
title.y = NSNumber(value: 30)
title.widthAdjust = -500
```

**Comment by barotbhavesh** [comment]
please change **orientation** @ihnatmoisieiev

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh 

<img width="887" alt="Screenshot 2019-12-03 at 13 36 54" src="https://user-images.githubusercontent.com/11294008/70043720-06d29180-15d2-11ea-901b-5c6f8d838c9d.png">

Also please see https://github.com/highcharts/highcharts-ios/issues/209#issuecomment-515405734

**Comment by barotbhavesh** [comment]
@ihnatmoisieiev according to your **209** answer every time assign new value like we can say we need to set condition for every Device like **SE different widthAdjust** or for **X different widthAdjust**.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh please try to find the optimal value. Can I close the issue?

**Comment by barotbhavesh** [comment]
@ihnatmoisieiev Do you have to constant solution for this not set widthAdjust according to device ?

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh no, I’ve already share different solutions. You should implement by yourself the rest things.

**Comment by barotbhavesh** [comment]
can you share me different solution i have one solution now **#209** so i will also check another solution then you we can close the issue.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh no. Please read my previous answer.

**Comment by barotbhavesh** [comment]
**okay then close the issue and thank you so much for your answer. I am so happy with you or your Team for quick reply. Thanks a lot.**
