### ISSUE TITLE
When annotations collide :(

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#246]
Hi,

I lost the whole day trying variations then i realized if there is coolision in annotations one of them is not displayed :(

I tested on : https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/annotations/

b changing annotations to : 
```Javascript
{
        labels: [{
            point: {
                xAxis: 0,
                yAxis: 0,
                x: 101.44,
                y: 1026
            },
            x: -30,
            text: 'Col de la Joux'
        }, {
            point: {
                xAxis: 0,
                yAxis: 0,
                x: 110.5,
                y: 1026
            },
            text: 'Côte de Viry'
        }, {
            point: {
                xAxis: 0,
                yAxis: 0,
                x: 176.4,
                y: 1202
            },
            text: 'Montée de la Combe<br>de Laisia Les Molunes'
        }]
    }
```

In my case i am displayin trades on a chart so 2 users may have a trade on same point as in : 

<img width="715" alt="Screenshot 2019-10-12 at 17 37 59" src="https://user-images.githubusercontent.com/610975/66703842-142c7780-ed17-11e9-9ac2-32957eedc2ae.png">

and

<img width="711" alt="Screenshot 2019-10-12 at 17 38 38" src="https://user-images.githubusercontent.com/610975/66703851-29a1a180-ed17-11e9-9668-8b408a13105b.png">

Previously @ihnatmoisieiev  and @pawelfus  were very helpful while implementing the annotations as in https://github.com/highcharts/highcharts-ios/issues/239 

Is it possible to implement such logic with HighCharts?

Best

**Comment by ihnatmoisieiev** [comment]
Hello @ergunkocak,

you can allow the annotation's labels to overlap

```
let label = HILabels()
label.allowOverlap = true
...
annotations.labels = [label]
```

and you also should set to your second annotation `y = -50` to move it up.

Please try it :)

**Comment by ergunkocak** [comment]
I tried it and faced an edge case :(
We have a lo of possibilities like it can be on the next point which can be 30 points below the previous point so they will literally overdraw each other.

So we need something like annotations which push each other without overdrawing and not hiding the other(s)?

I have 3 annotations:
- user
- trainer
- last price

I need to be able to display all these 3 all the time without overdrawing each other.
There are cases like 3 of them can overdraw each other

**Comment by ihnatmoisieiev** [comment]
@ergunkocak unfortunately, there is no such functionality.

You can try to create/find a similar topic on [UserVoices](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) and maybe it will be added in next releases.

**Comment by skuske** [comment]
@ergunkocak 

How did you manage the gradient of the line? Could you provide some sample code? Many thanks!

**Comment by ergunkocak** [comment]
```Swift
        let gradientLineDef: [AnyHashable: Any] = ["x1": 0.0, "x2": 0.0, "y1": 0.0, "y2": 1.0]
        let gradientLineColors: [[Any]] = [ [0.0, "rgb(254,0,81)"], [1.0, "rgba(54,90,206)"] ]
        plotoptions.areaspline.lineColor = HIColor(linearGradient: gradientLineDef, stops: gradientLineColors)
        plotoptions.areaspline.lineWidth = 2
```

**Comment by skuske** [comment]
@ergunkocak Cool, many thanks!
