### ISSUE TITLE
Hide the right menu button.

### ISSUE THREAD

**Issue by chetanzalake** [highcharts/highcharts-ios#25]
How to disable the right button near title above the chart in iOS. I am facing the issue in hiding the right button. It is a button which appears by default at top right corner of chart frame after drawing any chart. It is a three horizontal parallel line button. 
<img width="615" alt="screen shot 2017-09-06 at 1 42 00 pm" src="https://user-images.githubusercontent.com/19661519/30101434-f255f44c-9309-11e7-8823-76cc96461a2b.png">

**Comment by ihnatmoisieiev** [comment]
Hi @chetanzalake,

you can disable the exporting module (right button) by setting export **enabled** param to **false**, e.g. 

```
let exporting = HIExporting()
exporting.enabled = false

options.exporting = exporting
```

**Comment by chetanzalake** [comment]
@ihnatmoisieiev : It worked . Thanks for the quick reply.

**Comment by IntuzJaiminP** [comment]
@ihnatmoisieiev Thanks
