### ISSUE TITLE
3D Pie in a Swift iOS application

### ISSUE THREAD

**Issue by sbuonanno** [highcharts/highcharts-ios#250]
I'm not able to switch a Pie chart from 2D to 3D. The documentation specifies to add highcharts-3d.js to the project. But I could not understand how I could add a Java Script in a native iOS Swift app. The project is an iOS v13 app developed with XCode 11.

**Comment by ihnatmoisieiev** [comment]
Hello @sbuonanno,

thank you for your question. 

You can find how to add an additional js module in [README](https://github.com/highcharts/highcharts-ios/blob/master/README.md), but `highcharts-3d` is added by default.

Please see [3D Pie demo](https://www.highcharts.com/ios/demo/3d-pie).

Did you enable a 3D functionality in your `chart` config?

```
let chart = HIChart()
chart.type = "pie"
chart.options3d = HIOptions3d()
chart.options3d.enabled = true
chart.options3d.alpha = 45
chart.options3d.beta = 0
options.chart = chart
```

**Comment by sbuonanno** [comment]
Thank you very much for your reply. I have done exactly what you wrote, it doesn't work, the Pie appears in 2D and the code I used is exactly the same, taken from the 3D Pie Demo. You can easily try that on a XCode 11, Swift Project for iOS 13 and you'll see that the Pie appears only in 2D no matter whuich HIOptionsXXX class you specify.

**Comment by ihnatmoisieiev** [comment]
@sbuonanno it works perfectly for me. Please see screenshot above and `HIOptions` config:

![Zrzut ekranu 2019-10-22 o 11 23 57](https://user-images.githubusercontent.com/11294008/67273530-eb4a7600-f4be-11e9-9b39-eb9076098c90.png)

```
let options = HIOptions()

let chart = HIChart()
chart.type = "pie"
chart.options3d = HIOptions3d()
chart.options3d.enabled = true
chart.options3d.alpha = 45
chart.options3d.beta = 0
options.chart = chart

let title = HITitle()
title.text = "Browser market shares at a specific website, 2014"
options.title = title

let tooltip = HITooltip()
tooltip.pointFormat = "{series.name}: <b>{point.percentage:.1f}%</b>"
options.tooltip = tooltip

let plotOptions = HIPlotOptions()
plotOptions.pie = HIPie()
plotOptions.pie.allowPointSelect = true
plotOptions.pie.cursor = "pointer"
plotOptions.pie.depth = 35
let dataLabels = HIDataLabelsOptionsObject()
dataLabels.enabled = true
dataLabels.format = "{point.name}"
plotOptions.pie.dataLabels = [dataLabels]
options.plotOptions = plotOptions

let pie = HIPie()
pie.name = "Browser share"
pie.data = [[
              "Firefox",
              45
            ],
            [
              "IE",
              26.8
            ],
            [
              "Chrome",
              12.8,
            ],
            [
              "Safari",
              8.5
            ],
            [
              "Opera",
              6.2
            ],
            [
              "Others",
              0.7
            ]
]
options.series = [pie]
```

**Comment by sbuonanno** [comment]
Hi copied your code and tried with exactly the same data and the results is visible at the following link: [](https://1drv.ms/u/s!AkTDpGHbFtq4nBNgdWuXwE1QFdaM?e=veda7l). Maybe because the chart's view is not full screen ?

**Comment by sbuonanno** [comment]
Is it possible to have your whole Xcode project so that I can check for possible issues in mine ?

**Comment by ihnatmoisieiev** [comment]
@sbuonanno no worries. Can I close the issue?

**Comment by sbuonanno** [comment]
@ihnatmoisieiev, yes, you can. Thank you very much
