### ISSUE TITLE
Documentation issues in Xcode during build

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#255]
Just a few documentation issues, but they always pop up after a clean build:

<img width="309" alt="errors" src="https://user-images.githubusercontent.com/12996815/67977262-0a13df80-fc18-11e9-8833-bb38e24c5e21.png">

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
thank you for the reporting.

**Comment by ihnatmoisieiev** [comment]
@skuske do you have these warnings in the latest release? i can't reproduce it.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Yes, still the same warnings, plus a new one:

<img width="368" alt="warnings" src="https://user-images.githubusercontent.com/12996815/68744801-b630cf80-05f5-11ea-8cac-f5f98b02ea8f.png">

**Comment by skuske** [comment]
@ihnatmoisieiev 

<img width="825" alt="error2" src="https://user-images.githubusercontent.com/12996815/68744890-e11b2380-05f5-11ea-8c43-17179503d5e7.png">

**Comment by ihnatmoisieiev** [comment]
@skuske thank you.

[the last](https://github.com/highcharts/highcharts-ios/issues/255#issuecomment-553288774) is already fixed in [docs](https://api.highcharts.com/ios/highcharts/Classes/HITooltip.html#//api/name/refreshByPoint:), but the latest release doesn't contain this fix.

How I can reproduce and see [HTML](https://github.com/highcharts/highcharts-ios/issues/255#issuecomment-553288396) warnings?

**Comment by skuske** [comment]
@ihnatmoisieiev 

Good - question. Those HTML warnings just pop up when I build the project. I don't have any custom warning settings enabled in Xcode. Strange that they do not pop up on your machine.

Can I ignore https://github.com/highcharts/highcharts-ios/issues/255#issuecomment-553288774 ?

**Comment by ihnatmoisieiev** [comment]
@skuske sure, please ignore  https://github.com/highcharts/highcharts-ios/issues/255#issuecomment-553288774

Yes, it's strange because I don't see them.

**Comment by skuske** [comment]
@ihnatmoisieiev 

What Xcode version do you use?

**Comment by ihnatmoisieiev** [comment]
@skuske 11.0

**Comment by skuske** [comment]
@ihnatmoisieiev 

OK, I cannot remember if the warnings appeared in 11.0, but I am using 11.2.1

**Comment by skuske** [comment]
@ihnatmoisieiev 

I now found the cause for the issues: Xcode sees those html tags within the documentation, but all of them are opening tags, without any closing tags (of course without, as they are for documentation only)... However, Xcode handles them as 'real' tags, and therefore it misses the closing equivalent.

<img width="724" alt="error3" src="https://user-images.githubusercontent.com/12996815/68763604-23099100-0619-11ea-9b2b-fa305836ad99.png">

**Comment by ihnatmoisieiev** [comment]
@skuske thank you. I've reported the issue.

**Comment by ihnatmoisieiev** [comment]
@skuske do yo see the warnings in the latest release?

**Comment by skuske** [comment]
@ihnatmoisieiev 

No, it looks like they are gone. I'll close this and re-open if I see that again. :o)
