### ISSUE TITLE
Data update causing stutter

### ISSUE THREAD

**Issue by ergunkocak** [highcharts/highcharts-ios#258]
Hi,

First of all thanks for great library.

I am updating my chart data :
```Swift
options.plotOptions.series.data[existingDataCount-1] = mappedChartData.last
options.series[0].data[existingDataCount-1] = mappedChartData.last
```

This is causing a stutter for a independent tableView in same viewcontroller. If i disable these 2 lines stutter goes away.

Is there another (less cpu consuming i guess) way to update last point in chart?

Because my last point is a Forex pair price and may update more than 10 times a second :(

Cheers

**Comment by ihnatmoisieiev** [comment]
Hello @ergunkocak,

thank you for your question.

Did you try to update the chart data using Highcharts JS methods?

1. 
```
let updatedOptions = HIOptions()

let series = HISeries()

let updatedData = series[0].data
updatedData[existingDataCount-1] = mappedChartData.last
series.data = updatedData

updatedOptions.series = [series]

chartView.update(updatedOptions)
```

2. In your initial config:

```
self.lastPoint = HIPoint()
self.lastPoint.y = yValue
series.data = [........, self.lastPoint]
```

and update the last point when you need:

```
let updatedPoint = HIPoint()
updatedPoint.y = mappedChartData.last
self.lastPoint.update(updatedPoint)
```
