### ISSUE TITLE
Histogram in iOS

### ISSUE THREAD

**Issue by chetanzalake** [highcharts/highcharts-ios#26]
When can we expect a Histogram combination chart in iOS version?

**Comment by ihnatmoisieiev** [comment]
Hello @chetanzalake,

column charts can be used to make histogram charts by setting the padding between points and groups to 0.

```
column.groupPadding = 0
column.pointPadding = 0
column.borderWidth = 0
```
See example [demo](http://jsfiddle.net/WbHsX/8/).

**Comment by ihnatmoisieiev** [comment]
@chetanzalake did you try it?

**Comment by chetanzalake** [comment]
@ihnatmoisieiev : No, not yet. I will update this once I am done.

**Comment by ihnatmoisieiev** [comment]
@chetanzalake can I close this issue?
