### ISSUE TITLE
Pattern Image Not working

### ISSUE THREAD

**Issue by codal-jayeshk** [highcharts/highcharts-ios#262]
Hi I try to display pattern image of assets instead of color but it's not working.i can't see the pattern image on it.image is also added in asset file.

for (key, value) in dataSource[1] {
            let column = HIColumn()
            column.name = key
            column.color = HIColor(uiColor: UIColor(patternImage: UIImage(named: "patternImage")))
            column.data = [(dataSource[0][key] ?? 0).convertPercentage(total: quarterCount).roundInt(), value.convertPercentage(total: yearCount).roundInt()]
            data.append(column)
            
        }

**Comment by ihnatmoisieiev** [comment]
Hello @codal-jayeshk,

it's not a library functionality. Something wrong with your `UIColor(patternImage: UIImage(named: "patternImage"))`. Please check it.

E.g. `column.color = HIColor(uiColor: .red)` works perfect.

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev yes but if I want to use image then any alternate way for it.

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk no, you should solve it by yourself.

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk can I close the issue?

**Comment by codal-jayeshk** [comment]
No still I have question of this.

I found the way of use the pattern image of provided by your library.

how can I use the my asset image of that instead of library pattern?

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk please see [docs](https://api.highcharts.com/ios/highcharts/Classes/HIColor.html#//api/name/initWithUIColor:) of `HIColor` object and use any option you like.
