### ISSUE TITLE
HighChart view inside tableView cell , taking little bit more time. how to increase its performance ?

### ISSUE THREAD

**Issue by vishal07malvi** [highcharts/highcharts-ios#263]
I am using the HighChart view inside a tableView cell and it's taking time to create / load chart. how can i improve its performance?

**Comment by ihnatmoisieiev** [comment]
Hello @vishal07malvi,
please share your config and see demo app [HighFit](https://github.com/highcharts/highcharts-ios/tree/master/Example/HighFit).

**Comment by vishal07malvi** [comment]
@ihnatmoisieiev i have resolved the issue . thank you
