### ISSUE TITLE
How to add plotShadow in chart ?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#265]
In your demo code we get error
chart.plotShadow = NSNumber(value: false)
**ERROR MESSAGE** :- **Cannot assign value of type 'NSNumber' to type 'HICSSObject?'**
please give a better solution for this.

Thank You

**Comment by ihnatmoisieiev** [comment]
Hello @barotbhavesh,
`chart.plotShadow` type is `HICSSObject`. You can't assign `NSNumber`.
Just set `HICSSObject` object for your `chart.plotShadow`: `chart.plotShadow = HICSSObject()`.

**Comment by barotbhavesh** [comment]
Thanks for reply **@ihnatmoisieiev**
how to set false plotShadow?

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh default value is `false`, so it's not necessary to configure `plotShadow` if you don't use it. Please see [docs](https://api.highcharts.com/ios/highcharts/Classes/HIChart.html#//api/name/plotShadow).

But you can also do something like:

```
chart.plotShadow.width = 0
```

**Comment by barotbhavesh** [comment]
okay got it thank you for quick answer.
