### ISSUE TITLE
How to change background color in SolidGauge?

### ISSUE THREAD

**Issue by KimitoYanagi** [highcharts/highcharts-ios#267]
How to change background color in SolidGauge?
The documentation says use HiColor Class to solve the problem, but in the current version, I have to use HIGradientColorObject. I did many things through trial and error, but I cannot figure it out.

**Comment by ihnatmoisieiev** [comment]
Hello @KimitoYanagi,
thanks for your question.

`chart. backgroundColor` is `HIColor` object.

Please share your `HIOptions` config.

**Comment by KimitoYanagi** [comment]
Thank you for replying @ihnatmoisieiev.
With reference to [the Demo code](https://www.highcharts.com/ios/demo/gauge-activity), I wrote blow.

```      
let paneBackground1 = HIBackground()
paneBackground1.outerRadius = "112%"
paneBackground1.innerRadius = "88%"
paneBackground1.backgroundColor = HIColor.init(hexValue: "#535353")
paneBackground1.borderWidth = 0
```

Then Xcode throws me the error:

> Cannot assign value of type 'HIColor?' to type 'HIGradientColorObject?'

**Comment by ihnatmoisieiev** [comment]
@KimitoYanagi please try:

```
let paneBackground1 = HIBackground()
paneBackground1.outerRadius = "112%"
paneBackground1.innerRadius = "88%"
paneBackground1.backgroundColor = HIGradientColorObject()
paneBackground1.backgroundColor.stops = [[0, "#535353"]]
paneBackground1.borderWidth = 0
```

**Comment by KimitoYanagi** [comment]
@ihnatmoisieiev  Thanks to your help, it went well. I appreciate your continued support.
