### ISSUE TITLE
Callback from legend item select event?

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#269]
Is it possible to get a callback from a HILegend item touch (select/unselect) event? I would like to save a series 'visibility' state so that it is hidden/visible next time the chart is reloaded ...

Thanks! :o)

**Comment by sebastianbochan** [comment]
You can use `legendItemClick` event declared in `HIEvents.h`

```
@property (nonatomic, readwrite) HIFunction *legendItemClick
```

Docs:
- https://api.highcharts.com/ios/highcharts/

**Comment by skuske** [comment]
@sebastianbochan 

Many thanks for the rapid reply. Will try that! :o)

**Comment by skuske** [comment]
I am re-opening this as I am having trouble getting this to work.

I am trying to get the name of the series whose legend item is clicked:

```
    HIClosure closure = ^(HIChartContext *context) {
        
        NSLog(@"%@", [context getProperty:@"series.name"]);

    };
    
    chart.events.legendItemClick = [[HIFunction alloc] initWithClosure:closure properties:@[@"series.name"]];
```

However, this does not do anything. What exactly is wrong here? How can I get the series name for the legend item that is clicked?

Many thanks for a working example. :o)

**Comment by skuske** [comment]
Got it working :o)
