### ISSUE TITLE
Arithmetic function divide (/) in Formatter function not working

### ISSUE THREAD

**Issue by ZuzanaBenicko** [highcharts/highcharts-ios#27]
Hello,

I am trying to show in tooltip percentile difference between 1st and clicked Series as shown below, but unfortunately "/" operation is causing that Highchart is not load at all. All of the other standard operations are working as +,-,*,% but only / is causing this problem.

var tooltip = HITooltip()
        tooltip.shared = true
        tooltip.formatter = "function() {var s =  'Season: <b>'+this.x+'</b>';for (var i = 0 ; i < this.points.length; i++){s += '<br/><b>'+this.points[i].series.name +'</b>: <b>'+Highcharts.numberFormat(this.points[i].y/this.points[0].y)+'</b>% ('+c+')'};return s;}"
        options.tooltip = tooltip

Thank you for your reply,
Zuzana

**Comment by ihnatmoisieiev** [comment]
Hello @ZuzanaBenicko,

you need to set up the desired number of decimals, e.g.:

`Highcharts.numberFormat(this.points[i].y/this.points[0].y, 1)`

For more info see [docs](http://api.highcharts.com/highcharts/Highcharts.numberFormat).

**Comment by mll** [comment]
@ZuzanaBenicko also make sure that you do not have any divisions by 0 - this might be the cause of your problems as well.

**Comment by ZuzanaBenicko** [comment]
Hello, 
thank you for you responses! Unfortunately none of them is causing the problem, because this is working code (with 2 decimals)

tooltip.formatter = "function() {var foo1 = 1+1; var s =  'Season: <b>'+this.x+'</b>'; for (var i = 0 ; i < this.points.length; i++){s += '<br/><b>'+this.points[i].series.name +'</b>: <b>'+Highcharts.numberFormat(foo1)+'</b>% '};return `s;}"

<img width="161" alt="screen shot 2017-09-11 at 12 06 35" src="https://user-images.githubusercontent.com/9416708/30269613-b5b5aa8a-96e9-11e7-95dd-c2e8643b9127.png">


**and this is not** (chart is not displayed - same as when you forget semicolon)

tooltip.formatter = "function() {var foo1 = 1/1; var s =  'Season: <b>'+this.x+'</b>'; for (var i = 0 ; i < this.points.length; i++){s += '<br/><b>'+this.points[i].series.name +'</b>: <b>'+Highcharts.numberFormat(foo1,1)+'</b>% '};return s;}"

I tried to set  foo1 = 1.0/1.0, 2/1, 2.0/1.0 and none of them worked, on the other hand any other arithmetic function is working good.

**Comment by ihnatmoisieiev** [comment]
@ZuzanaBenicko thank you for reporting the bug. We will fix the issue as soon as possible.

**Comment by ihnatmoisieiev** [comment]
@ZuzanaBenicko it is fixed in the newest release.

**Comment by ihnatmoisieiev** [comment]
@ZuzanaBenicko can I close this issue?

**Comment by ZuzanaBenicko** [comment]
Yes, thank you.
