### ISSUE TITLE
Build warning in v8.0.0

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#270]
v8.0.0 produces quite a few build warnings:

<img width="717" alt="Bildschirmfoto 2019-12-18 um 10 04 28" src="https://user-images.githubusercontent.com/12996815/71073963-b33f7680-2181-11ea-879e-a21ed0aef0eb.png">

**Comment by skuske** [comment]
Also note the **double** import of `HIPackedBubble.h`

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

thank you for the reporting.

I don't see these warnings using [HighFit](https://github.com/highcharts/highcharts-ios/tree/master/Example/HighFit) apps. My Xcode version is `11.2.1`.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Xcode 11.3 here, but after building a few times, the warnings all of a sudden disappeared. Don't know why as I have not fixed the case mismatch.

I guess the warnings might appear again soon, as such warnings usually do if they disappeared before.

**Comment by ihnatmoisieiev** [comment]
@skuske the double import of `HIPackedBubble.h` will be fixed in the next release.

**Comment by rubikva** [comment]
Have the same issue. 
When try to #import <Highcharts/Highcharts.h> get an error: "non-portable path to file '"HIPackedbubble.h"'; specified path differs in case from file name on disk".

**Comment by ihnatmoisieiev** [comment]
Hello @rubikva,

thank you for the reporting!

It will be fixed in the next release, but you can omit it for now.

**Comment by ihnatmoisieiev** [comment]
@skuske @rubikva build warnings are fixed in the latest release. Could I close the issue?

**Comment by skuske** [comment]
Yes, fixed.
