### ISSUE TITLE
Does HighCharts support Timeline chart or Road map chart 

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-ios#272]
Dear Team, 

I have a requirement to implement the `Timeline chart` related `RoadMap Chart`, Is it possible to implement the chart with this library? 

For reference I have attached the screenshot please check it. 
<img width="620" alt="Screenshot 2019-12-26 at 6 39 28 PM" src="https://user-images.githubusercontent.com/34921497/71477274-19c23580-280f-11ea-9ac4-a7f0e8b8b2b8.png">

**Comment by ihnatmoisieiev** [comment]
Hello @ArunVicky001,
yes, please read more about `Timeline chart` [here](https://www.highcharts.com/docs/chart-and-series-types/timeline-series) and see a [demo](https://www.highcharts.com/demo/timeline).

You can use `HITimeline` series object. Also, don't forget to add `timeline` module to `chartView.plugins`, ie.

```
chartView.plugins = ["timeline"]
```

**Comment by ArunVicky001** [comment]
Thank you very much for your response, the time line chart is only displaying the single line but in my case I have multiple` Y Axis` lines

**Comment by ihnatmoisieiev** [comment]
@ArunVicky001 please check the answer here: https://github.com/highcharts/highcharts-ios/issues/273. 

Closing this ticket as a duplicate.

**Comment by theadin** [comment]
HI ArunVicky001. Did you ever find a solution for the graph in your picture?

**Comment by theadin** [comment]
Hi @ArunVicky001 Did you ever find a solution for the graph in your picture?
