### ISSUE TITLE
Want to add Line of top and bottom of the range chart

### ISSUE THREAD

**Issue by codal-jayeshk** [highcharts/highcharts-ios#274]
is it possible to add line top and bottom of the range chart?

also see the attached image here.

![Screenshot 2020-01-03 at 2 37 36 PM](https://user-images.githubusercontent.com/52558720/71715198-9d46dc80-2e36-11ea-90ab-8a0a4bce7570.png)

**Comment by ihnatmoisieiev** [comment]
Hello @codal-jayeshk,
you can add plot lines on your chart by setting `yAxis.plotLines`. Please see API [reference](https://api.highcharts.com/ios/highcharts/Classes/HIYAxis.html#//api/name/plotLines).

**Comment by codal-jayeshk** [comment]
will be good if you can provide some demo code of iOS.

I try with almost all the way but I did not get success so.

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk please try it:

```
let options = HIOptions()

let xAxis = HIXAxis()
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
options.xAxis = [xAxis]

let yAxis = HIYAxis()

let plotLineTop = HIPlotLines()
plotLineTop.width = 2
plotLineTop.color = HIColor(uiColor: .red)
plotLineTop.value = 216.4

let plotLineBottom = HIPlotLines()
plotLineBottom.width = 2
plotLineBottom.color = HIColor(uiColor: .red)
plotLineBottom.value = 29.9

yAxis.plotLines = [plotLineTop, plotLineBottom]

options.yAxis = [yAxis]

let series = HISeries()
series.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [series]
```

**Comment by codal-jayeshk** [comment]
Thanks for giving demo code

But it is not what I am looking for.your deme code demostrate like below image.

![Screenshot 2020-01-03 at 3 18 15 PM](https://user-images.githubusercontent.com/52558720/71716948-6c69a600-2e3c-11ea-86bd-410610a8da91.png)

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev waiting for your replay..

**Comment by sebastianbochan** [comment]
Hi @codal-jayeshk,
Have you tried to use the bullet-graph ?

Demo:
- https://www.highcharts.com/ios/demo/bullet-graph

**Comment by ihnatmoisieiev** [comment]
Thank you @sebastianbochan!

@codal-jayeshk try to use the `bullet` series. I've prepared a small demo for you:

```
chartView.plugins = ["bullet"]

...

let options = HIOptions()

let legend = HILegend()
legend.enabled = false
options.legend = legend

let plotOptions = HIPlotOptions()
plotOptions.bullet = HIBullet()
plotOptions.bullet.targetOptions = HITargetOptions()
plotOptions.bullet.targetOptions.width = "95%"
options.plotOptions = plotOptions

let columnRange = HIColumnrange()
columnRange.data = [
    [-9.9, 10.3],
    [-8.6, 8.5],
    [-10.2, 11.8],
    [-1.7, 12.2],
    [-0.6, 23.1]
]

let bullet = HIBullet()
bullet.color = HIColor(uiColor: .red)

let data1 = HIData()
data1.y = 0
data1.target = 10.3

let data2 = HIData()
data2.y = 0
data2.target = 8.5

let data3 = HIData()
data3.y = 0
data3.target = 11.8

let data4 = HIData()
data4.y = 0
data4.target = 12.2

let data5 = HIData()
data5.y = 0
data5.target = 23.1

bullet.data = [data1, data2, data3, data4, data5]

options.series = [columnRange, bullet]
```

**Comment by codal-jayeshk** [comment]
Thank You @ihnatmoisieiev @sebastianbochan 

@ihnatmoisieiev above code helps me a lot.

Now I am very close to achieve what I want.

Now just I want to check two things with you.

1) currently I used two bullets then it just displays 50% width of the bullet.see the image for more information.

2) can I use different liked "dashed" line on the bullets?

Thank you.

**Comment by ihnatmoisieiev** [comment]
Hello @codal-jayeshk,

there is only one way how to achieve this.

We prepared a special function in `JS`:

```
function addLines() {
    var chart = this,
        left = chart.plotLeft,
        top = chart.plotTop,
        r = chart.renderer,
        bottomStyles = {
            'stroke-width': 1,
            stroke: 'green',
            dashstyle: 'dot',
            zIndex: 10
        },
        topStyles = {
            'stroke-width': 1,
            stroke: 'red',
            zIndex: 10
        },
        shapeArgs,
        x,
        y,
        w,
        h;

    chart.series.forEach(function(serie, i) {
        serie.data.forEach(function(p, j) {
console.log(p);
                        shapeArgs = p.shapeArgs;
            x = p.barX + left;
            y = p.plotY + top;
            h = shapeArgs.height;
            w = p.pointWidth;

            if (p.borderExtraLineTop && p.borderExtraLineBottom) {
                // when redraw, edit only path, not render all strokes again.
                p.borderExtraLineTop.attr({
                    d: [
                        'M',
                        x, y - h,
                        'L',
                        x + w, y - h
                    ]
                });

                p.borderExtraLineBottom.attr({
                    d: [
                        'M',
                        x, y,
                        'L',
                        x + w, y
                    ]
                });
            } else {
                p.borderExtraLineTop = r.path(
                        [
                        'M',
                        x, y - h,
                        'L',
                        x + w, y - h
                    ])
                    .attr(topStyles)
                    .add();
                    
                p.borderExtraLineBottom = r.path(
                        [
                        'M',
                        x, y,
                        'L',
                        x + w, y
                    ])
                    .attr(bottomStyles)
                    .add();
            }
        });
    });
}
```

You can modify `bottomStyles` and `topStyles`.

Demo in iOS:

```
let options = HIOptions()

let addLines = "function () { var chart = this, left = chart.plotLeft, top = chart.plotTop, r = chart.renderer, bottomStyles = { 'stroke-width': 1, stroke: 'green', dashstyle: 'dot', zIndex: 10 }, topStyles = { 'stroke-width': 1, stroke: 'red', zIndex: 10 }, shapeArgs, x, y, w, h; chart.series.forEach(function(serie, i) { serie.data.forEach(function(p, j) { console.log(p); shapeArgs = p.shapeArgs; x = p.barX + left; y = p.plotY + top; h = shapeArgs.height; w = p.pointWidth; if (p.borderExtraLineTop && p.borderExtraLineBottom) { p.borderExtraLineTop.attr({ d: [ 'M', x, y - h, 'L', x + w, y - h ] }); p.borderExtraLineBottom.attr({ d: [ 'M', x, y, 'L', x + w, y ] }); } else { p.borderExtraLineTop = r.path( [ 'M', x, y - h, 'L', x + w, y - h ]) .attr(topStyles) .add(); p.borderExtraLineBottom = r.path( [ 'M', x, y, 'L', x + w, y ]) .attr(bottomStyles) .add(); } }); }); }"

let chart = HIChart()
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: addLines)
chart.events.redraw = HIFunction(jsFunction: addLines)
options.chart = chart

let legend = HILegend()
legend.enabled = false
options.legend = legend

let credits = HICredits()
credits.enabled = false
options.credits = credits

let xAxis = HIXAxis()
xAxis.categories = ["Apples", "Oranges", "Pears", "Grapes", "Bananas"]
options.xAxis = [xAxis]

let columnrange = HIColumnrange()
columnrange.data = [
    [2, 3],
    [3, 4],
    [2, 5]
]
options.series = [columnrange]
```

**Comment by codal-jayeshk** [comment]
appreciate your support.i will also recommended my friends to use your libraries..

just last help please.

I am assigning Hexa color of string array but it is not working.

Here is the code.

 let columnrange = HIColumnrange()
 columnrange.data = [20,30,25,40]
 columnrange.colors = ["#4A773C","#BF1D08"]
 columnrange.pointPadding = 0
 columnrange.tooltip = HITooltip()
 columnrange.tooltip.enabled = false

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

Found the solution above problem..

"columnrange.colorByPoint = 1" Helps me to assign color based on column.

Thank you so much for your support.

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev  Still have two questions.

1) how can I add custom tooltip in column chart?
2) how can I give opacity to column?

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk 

1. Set up `options.tooltip` object. Also please see API [reference](https://api.highcharts.com/ios/highcharts/Classes/HITooltip.html).
2. Just set `columnrange.opacity`value.

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 
I am facing one issue when I am passing the data below on your provide code.

let columnrange = HIColumnrange()
            columnrange.data = [
                [2, 3],
                [4, 3],
                [2, 5]
  ]

if you pass higher value first and Lower value last then it displays like below image.

also as our requirement always first value shows ---- line and second value show ______ line.

![Screenshot 2020-01-09 at 10 41 07 AM](https://user-images.githubusercontent.com/52558720/72039922-d36bdc80-32cc-11ea-8e78-c05687eaf5a5.png)

also

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

the line which is draw on the value of it is fine but the line which is draws on 5 value must be on 3 value.

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk please try

```
function () {
    var chart = this,
        left = chart.plotLeft,
        top = chart.plotTop,
        r = chart.renderer,
        bottomStyles = {
            'stroke-width': 1,
            stroke: 'green',
            dashstyle: 'dot',
            zIndex: 10
        },
        topStyles = {
            'stroke-width': 1,
            stroke: 'red',
            zIndex: 10
        },
        shapeArgs,
        plotYTop,
        x,
        y,
        w,
        h;

    chart.series.forEach(function(serie, i) {
        serie.data.forEach(function(p, j) {

			shapeArgs = p.shapeArgs;
            x = p.barX + left;
            h = shapeArgs.height;
            plotYTop = p.plotY + top;
            y = p.low > p.high ? plotYTop + h : plotYTop;
            w = p.pointWidth;

            if (p.borderExtraLineTop && p.borderExtraLineBottom) {
                // when redraw, edit only path, not render all strokes again.
                p.borderExtraLineTop.attr({
                    d: [
                    	'M',
                        x, y - h,
                        'L',
                        x + w, y - h
                    ]
                });

                p.borderExtraLineBottom.attr({
                    d: [
                    	'M',
                        x, y,
                        'L',
                        x + w, y
                    ]
                });
            } else {
                p.borderExtraLineTop = r.path(
                	[
                    	'M',
                        x, y - h,
                        'L',
                        x + w, y - h
                    ])
                    .attr(topStyles)
                    .add();
                    
                p.borderExtraLineBottom = r.path(
                	[
                    	'M',
                        x, y,
                        'L',
                        x + w, y
                    ])
                    .attr(bottomStyles)
                    .add();
            }
        });
    });
}
```

```
let addLines = "function () { var chart = this, left = chart.plotLeft, top = chart.plotTop, r = chart.renderer, bottomStyles = { 'stroke-width': 1, stroke: 'green', dashstyle: 'dot', zIndex: 10 }, topStyles = { 'stroke-width': 1, stroke: 'red', zIndex: 10 }, shapeArgs, plotYTop, x, y, w, h; chart.series.forEach(function(serie, i) { serie.data.forEach(function(p, j) { shapeArgs = p.shapeArgs; x = p.barX + left; h = shapeArgs.height; plotYTop = p.plotY + top; y = p.low > p.high ? plotYTop + h : plotYTop; w = p.pointWidth; if (p.borderExtraLineTop && p.borderExtraLineBottom) { p.borderExtraLineTop.attr({ d: [ 'M', x, y - h, 'L', x + w, y - h ] }); p.borderExtraLineBottom.attr({ d: [ 'M', x, y, 'L', x + w, y ] }); } else { p.borderExtraLineTop = r.path( [ 'M', x, y - h, 'L', x + w, y - h ]) .attr(topStyles) .add(); p.borderExtraLineBottom = r.path( [ 'M', x, y, 'L', x + w, y ]) .attr(bottomStyles) .add(); } }); }); }"
```

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

now line is draw perfectly but still facing issue like every time toppline draws on highest value of range.

like example

Here I am passing data [2,3] and it draws perfect

![Screenshot 2020-01-17 at 1 48 41 PM](https://user-images.githubusercontent.com/52558720/72595556-1878ba00-3930-11ea-8cdb-f7c9a456bd91.png)

But when I am passing data [4,3].it must be reverse like top line become bottom line and bottom line becomes top line.

![Screenshot 2020-01-17 at 1 49 06 PM](https://user-images.githubusercontent.com/52558720/72595581-29293000-3930-11ea-8367-227bb32cea56.png)

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

also we want different line on grouping of range chart.

See the below image for reference.

![Screenshot 2020-01-17 at 2 02 03 PM](https://user-images.githubusercontent.com/52558720/72596735-655d9000-3932-11ea-9831-ca107afc1110.png)

**Comment by sebastianbochan** [comment]
Hi @codal-jayeshk,
Could you attach your json with series / data ? It will allow me to reproduce the problem in native js and improve the solution.

**Comment by codal-jayeshk** [comment]
@sebastianbochan 

Sorry I have code in iOS.i have no json series for that.

Yes but you can create json for the Rangechart from the following code.

  columnrange1.data = [
                [[2, 3]],
                [4, 3],
                [2, 5]
            ]

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk ok, please attach your code in iOS with data.

**Comment by codal-jayeshk** [comment]
> @ihnatmoisieiev
> 
> now line is draw perfectly but still facing issue like every time toppline draws on highest value of range.
> 
> like example
> 
> Here I am passing data [2,3] and it draws perfect
> 
> ![Screenshot 2020-01-17 at 1 48 41 PM](https://user-images.githubusercontent.com/52558720/72595556-1878ba00-3930-11ea-8cdb-f7c9a456bd91.png)
> 
> But when I am passing data [4,3].it must be reverse like top line become bottom line and bottom line becomes top line.
> 
> ![Screenshot 2020-01-17 at 1 49 06 PM](https://user-images.githubusercontent.com/52558720/72595581-29293000-3930-11ea-8367-227bb32cea56.png)

@ihnatmoisieiev 

Here is the demo project.

[HichartPOC.zip](https://github.com/highcharts/highcharts-ios/files/4091124/HichartPOC.zip)


This is the function which is used for showing the chart with data.

  func hichartSupportCode1() {
            
            let chartView: HIChartView = HIChartView.init(frame: self.view.bounds)
            
            let options = HIOptions()

           let addLines = "function () { var chart = this, left = chart.plotLeft, top = chart.plotTop, r = chart.renderer, bottomStyles = { 'stroke-width': 1, stroke: 'green', dashstyle: 'dot', zIndex: 10 }, topStyles = { 'stroke-width': 1, stroke: 'red', zIndex: 10 }, shapeArgs, plotYTop, x, y, w, h; chart.series.forEach(function(serie, i) { serie.data.forEach(function(p, j) { shapeArgs = p.shapeArgs; x = p.barX + left; h = shapeArgs.height; plotYTop = p.plotY + top; y = p.low > p.high ? plotYTop + h : plotYTop; w = p.pointWidth; if (p.borderExtraLineTop && p.borderExtraLineBottom) { p.borderExtraLineTop.attr({ d: [ 'M', x, y - h, 'L', x + w, y - h ] }); p.borderExtraLineBottom.attr({ d: [ 'M', x, y, 'L', x + w, y ] }); } else { p.borderExtraLineTop = r.path( [ 'M', x, y - h, 'L', x + w, y - h ]) .attr(topStyles) .add(); p.borderExtraLineBottom = r.path( [ 'M', x, y, 'L', x + w, y ]) .attr(bottomStyles) .add(); } }); }); }"

            let tooltipFunction = "function () { return 'LOW: '+this.point.low+' HIGH: '+this.point.high; }"

            
            let chart = HIChart()
            chart.events = HIEvents()
            chart.events.load = HIFunction(jsFunction: addLines)
            chart.events.redraw = HIFunction(jsFunction: addLines)
            options.chart = chart

            let legend = HILegend()
            legend.enabled = false
            options.legend = legend

            let credits = HICredits()
            credits.enabled = false
            options.credits = credits

            let xAxis = HIXAxis()
            xAxis.categories = ["Apples", "Oranges", "Pears", "Grapes", "Bananas"]
            options.xAxis = [xAxis]

            
            
            let columnrange = HIColumnrange()
            columnrange.data = [
                [2, 3],
                [4, 3],
                [2, 5]
            ]
            columnrange.tooltip = HITooltip()
            columnrange.tooltip.shared = 1
            columnrange.tooltip.pointFormat = "<tr><td><b>Prescriber: </b><b>{point.low}</b></td></tr></br><tr><td style=\"padding:0\"><b>Delivered: </b><b>{point.high}</b></td></tr>"
            
            options.series = [columnrange]
            
            chartView.options = options
            self.view.addSubview(chartView)
        }

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk 

ok, try the following function:

```
let addLines = "function() { var chart = this, left = chart.plotLeft, top = chart.plotTop, r = chart.renderer, bottomStyles = { 'stroke-width': 1, stroke: 'green', dashstyle: 'dot', zIndex: 10 }, topStyles = { 'stroke-width': 1, stroke: 'red', zIndex: 10 }, shapeArgs, plotYTop, x, y, w, h; chart.series.forEach(function(serie, i) { serie.data.forEach(function(p, j) { shapeArgs = p.shapeArgs; x = p.barX + left; h = p.low > p.high ? -shapeArgs.height : shapeArgs.height; plotYTop = p.plotY + top; y = plotYTop; w = p.pointWidth; if (p.borderExtraLineTop && p.borderExtraLineBottom) { p.borderExtraLineTop.attr({ d: [ 'M', x, y - h, 'L', x + w, y - h ] }); p.borderExtraLineBottom.attr({ d: [ 'M', x, y, 'L', x + w, y ] }); } else { p.borderExtraLineTop = r.path( [ 'M', x, y - h, 'L', x + w, y - h ]) .attr(topStyles) .add(); p.borderExtraLineBottom = r.path( [ 'M', x, y, 'L', x + w, y ]) .attr(bottomStyles) .add(); } }); }); }"
```

**Comment by codal-jayeshk** [comment]
> @ihnatmoisieiev
> 
> also we want different line on grouping of range chart.
> 
> See the below image for reference.
> 
> ![Screenshot 2020-01-17 at 2 02 03 PM](https://user-images.githubusercontent.com/52558720/72596735-655d9000-3932-11ea-9831-ca107afc1110.png)

@ihnatmoisieiev 
can you help me for that?

what we did it is just for one column now we have group of it.and we want to draw chart like display on image.in group both column have different line of top and bottom.

Please help me for that.

**Comment by codal-jayeshk** [comment]
> > @ihnatmoisieiev
> > also we want different line on grouping of range chart.
> > See the below image for reference.
> > ![Screenshot 2020-01-17 at 2 02 03 PM](https://user-images.githubusercontent.com/52558720/72596735-655d9000-3932-11ea-9831-ca107afc1110.png)
> 
> @ihnatmoisieiev
> can you help me for that?
> 
> what we did it is just for one column now we have group of it.and we want to draw chart like display on image.in group both column have different line of top and bottom.
> 
> Please help me for that.

@ihnatmoisieiev 


![Screenshot 2020-01-24 at 6 34 30 PM](https://user-images.githubusercontent.com/52558720/73071356-88f77c00-3ed8-11ea-8050-0c99958ada9d.png)

This is the image which I achieve with your provide JSFunction.But we need different color line for the second group chart like on first image.

Please help me with it.i want similar second column like on first image.

Thanks
Jayesh

**Comment by codal-jayeshk** [comment]
> > > @ihnatmoisieiev
> > > also we want different line on grouping of range chart.
> > > See the below image for reference.
> > > ![Screenshot 2020-01-17 at 2 02 03 PM](https://user-images.githubusercontent.com/52558720/72596735-655d9000-3932-11ea-9831-ca107afc1110.png)
> > 
> > 
> > @ihnatmoisieiev
> > can you help me for that?
> > what we did it is just for one column now we have group of it.and we want to draw chart like display on image.in group both column have different line of top and bottom.
> > Please help me for that.
> 
> @ihnatmoisieiev
> 
> ![Screenshot 2020-01-24 at 6 34 30 PM](https://user-images.githubusercontent.com/52558720/73071356-88f77c00-3ed8-11ea-8050-0c99958ada9d.png)
> 
> This is the image which I achieve with your provide JSFunction.But we need different color line for the second group chart like on first image.
> 
> Please help me with it.i want similar second column like on first image.
> 
> Thanks
> Jayesh

@ihnatmoisieiev 



Here is the JSFunction which through I achieve which showing now just I need to draw left and right line with path.

please help me for adding with this one.

let addLines = """
            function() { var chart = this, left = chart.plotLeft, top = chart.plotTop, r = chart.renderer, bottomStyles = { 'stroke-width': 1, stroke: 'green', dashstyle: 'dot', zIndex: 10 }, topStyles = { 'stroke-width': 1, stroke: 'red', zIndex: 10 },secondBottomStyles = { 'stroke-width': 2, stroke: '#2979FF', dashstyle: 'dot', zIndex: 10 }, secondTopStyles = { 'stroke-width': 2, stroke: '#2979FF', zIndex: 10 },shapeArgs, plotYTop, x, y, w, h;chart.series.forEach(function(serie, i) { if (i == 0){serie.data.forEach(function(p, j) { shapeArgs = p.shapeArgs; x = p.barX + left; h = p.low > p.high ? -shapeArgs.height : shapeArgs.height; plotYTop = p.plotY + top; y = plotYTop; w = p.pointWidth; if (p.borderExtraLineTop && p.borderExtraLineBottom) { p.borderExtraLineTop.attr({ d: [ 'M', x, y - h, 'L', x + w, y - h ] }); p.borderExtraLineBottom.attr({ d: [ 'M', x, y, 'L', x + w, y ] }); } else { p.borderExtraLineTop = r.path( [ 'M', x, y - h, 'L', x + w, y - h ]) .attr(topStyles) .add(); p.borderExtraLineBottom = r.path( [ 'M', x, y, 'L', x + w, y ]) .attr(bottomStyles) .add(); } }); } else {serie.data.forEach(function(p, j) { shapeArgs = p.shapeArgs; x = p.barX + left; h = p.low > p.high ? -shapeArgs.height : shapeArgs.height; plotYTop = p.plotY + top; y = plotYTop; w = p.pointWidth; if (p.borderExtraLineTop && p.borderExtraLineBottom) { p.borderExtraLineTop.attr({ d: [ 'M', x, y - h, 'L', x + w, y - h ] }); p.borderExtraLineBottom.attr({ d: [ 'M', x, y, 'L', x + w, y ] }); } else { p.borderExtraLineTop = r.path( [ 'M', x, y - h, 'L', x + w, y - h ]) .attr(secondTopStyles) .add(); p.borderExtraLineBottom = r.path( [ 'M', x, y, 'L', x + w, y ]) .attr(secondBottomStyles) .add(); } }); } }); }
            """

**Comment by ihnatmoisieiev** [comment]
Hello @codal-jayeshk,

attaching update JS function:

```
function () {
  var chart = this,
    left = chart.plotLeft,
    top = chart.plotTop,
    r = chart.renderer,
    bottomStylesArray = [{
      'stroke-width': 1,
      stroke: 'orange',
      dashstyle: 'dot',
      zIndex: 6
    }, {
      'stroke-width': 1,
      stroke: 'green',
      dashstyle: 'dot',
      zIndex: 6
    }],
    topStylesArray = [{
      'stroke-width': 1,
      stroke: 'black',
      zIndex: 6
    }, {
      'stroke-width': 1,
      stroke: 'violet',
      zIndex: 6
    }],
    shapeArgs,
    plotYTop,
    x,
    y,
    w,
    h;

  chart.series.forEach(function(serie, i) {
    var bottomStyles = bottomStylesArray[i];
    var topStyles = topStylesArray[i];

    serie.data.forEach(function(p, j) {

      shapeArgs = p.shapeArgs;
      x = p.barX + left;
      h = p.low > p.high ? -shapeArgs.height : shapeArgs.height;
      plotYTop = p.plotY + top;
      y = plotYTop;
      w = p.pointWidth;


      if (p.borderExtraLineTop && p.borderExtraLineBottom) {
        p.borderExtraLineTop.attr({
          d: [
            'M',
            x, y - h,
            'L',
            x + w, y - h
          ]
        });

        p.borderExtraLineBottom.attr({
          d: [
            'M',
            x, y,
            'L',
            x + w, y
          ]
        });
      } else {
        p.borderExtraLineTop = r.path(
            [
              'M',
              x, y - h,
              'L',
              x + w, y - h
            ])
          .attr(topStyles)
          .add();

        p.borderExtraLineBottom = r.path(
            [
              'M',
              x, y,
              'L',
              x + w, y
            ])
          .attr(bottomStyles)
          .add();
      }
    });
  });
}
```

You can find in the code:

```
bottomStylesArray = [{
      'stroke-width': 1,
      stroke: 'orange',
      dashstyle: 'dot',
      zIndex: 6
    }, {
      'stroke-width': 1,
      stroke: 'green',
      dashstyle: 'dot',
      zIndex: 6
    }],
    topStylesArray = [{
      'stroke-width': 1,
      stroke: 'black',
      zIndex: 6
    }, {
      'stroke-width': 1,
      stroke: 'violet',
      zIndex: 6
    }],
```

There you can change colors.

Swift:

```
let addLines = "function () { var chart = this, left = chart.plotLeft, top = chart.plotTop, r = chart.renderer, bottomStylesArray = [{ 'stroke-width': 1, stroke: 'orange', dashstyle: 'dot', zIndex: 6 }, { 'stroke-width': 1, stroke: 'green', dashstyle: 'dot', zIndex: 6 }], topStylesArray = [{ 'stroke-width': 1, stroke: 'black', zIndex: 6 }, { 'stroke-width': 1, stroke: 'violet', zIndex: 6 }], shapeArgs, plotYTop, x, y, w, h; chart.series.forEach(function(serie, i) { var bottomStyles = bottomStylesArray[i]; var topStyles = topStylesArray[i]; serie.data.forEach(function(p, j) { shapeArgs = p.shapeArgs; x = p.barX + left; h = p.low > p.high ? -shapeArgs.height : shapeArgs.height; plotYTop = p.plotY + top; y = plotYTop; w = p.pointWidth; if (p.borderExtraLineTop && p.borderExtraLineBottom) { p.borderExtraLineTop.attr({ d: [ 'M', x, y - h, 'L', x + w, y - h ] }); p.borderExtraLineBottom.attr({ d: [ 'M', x, y, 'L', x + w, y ] }); } else { p.borderExtraLineTop = r.path( [ 'M', x, y - h, 'L', x + w, y - h ]) .attr(topStyles) .add(); p.borderExtraLineBottom = r.path( [ 'M', x, y, 'L', x + w, y ]) .attr(bottomStyles) .add(); } }); }); }"
```

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

I think you misunderstood.

I want the line for left and right side as well if you can see on image.currently this code is only draw the top and bottom lines.

Here again I attach screenshot.

![72596735-655d9000-3932-11ea-9831-ca107afc1110](https://user-images.githubusercontent.com/52558720/73174760-96a63f00-412e-11ea-9507-8ab27efd6844.png)

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk we don't understand what do you mean. Please describe everything step by step and attach example of the result.

We hope that you got the answer to your initial question https://github.com/highcharts/highcharts-ios/issues/274#issue-544908316 on this topic.

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk we don't understand what do you mean. Please describe everything step by step and attach an example of the final result.

We hope that you got the answer to your initial question #274 (comment) on this topic.

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev yes I got that answer.

1) Currently we are drawing the line of top and bottom on range chart.
2) Now we require to display chart with group like you see above screen shot.

This is the image like we want to draw the chart

![73174760-96a63f00-412e-11ea-9507-8ab27efd6844](https://user-images.githubusercontent.com/52558720/73268684-6a0f2780-4201-11ea-8d9c-6811e308c8b7.png)
.Please Ignore the text above the image.

3) As we have already solution for first column of draw top line and bottom line.Now we require same solution for second column on group with draw line on each side left, right,bottom and top.


- Here is the image which I achieved with changing on your JSFunction.Now Problem is that I am not able to draw the line on left and right side of second column that you can see on below image.

![Screenshot 2020-01-24 at 7 17 29 PM](https://user-images.githubusercontent.com/52558720/73268732-801ce800-4201-11ea-905e-f7ab728bb09f.png)

Let me know still its not clear.i am available for continue discussion.

Here I attach my demo code as well.

[Uploading HichartPOC 2.zip…]()

Thanks 
Jayesh

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev waiting for your reply.

let me know still you are not clear.

**Comment by ihnatmoisieiev** [comment]
Hello @codal-jayeshk,

your requirement looks like a custom implementation that is not implemented by default. So, it would be better to contact [Support](https://www.highcharts.com/blog/support/) Team. On the right, you can find `Custom implementation services`. 

GitHub is primarily used for reporting bugs.

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev Okay I will try to reach out to the custom implementation service but I think this is something that should be already supported, I am just not sure how to implement this.
I can already draw group column lines, just need to figure out how to draw a bar between these lines.
