### ISSUE TITLE
Use Custom Font in iOS-Highchart

### ISSUE THREAD

**Issue by codal-jayeshk** [highcharts/highcharts-ios#276]
Hello

is there any way to use custom fonts in iOS?

I want to use some custom fonts for axis title

**Comment by ihnatmoisieiev** [comment]
Hello @codal-jayeshk,
it is possible to use custom fonts.
Please, see more info in [readme](https://github.com/highcharts/highcharts-ios/blob/master/README.md) (Custom fonts chapter).
