### ISSUE TITLE
Line not display in HILine Chart 

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#277]
chart display but line, not drow 

![Screenshot 2020-01-10 at 3 38 50 PM](https://user-images.githubusercontent.com/48505333/72145044-a6e4bd00-33bf-11ea-94a5-9b3b5582215d.png)

let line = HILine()
line.name = curDicDashboardChartData.arySeriesModel[i].name
line.color = HIColor(hexValue: strColor)
ine.data = curDicDashboardChartData.arySeriesModel[i].aryData

line.tooltip = HITooltip()
line.lineWidth = NSNumber(value: 3)
line.tooltip.pointFormat = "<b>{series.name}: {point.y:.2f}</b><br/>"

**Comment by ihnatmoisieiev** [comment]
Hello @barotbhavesh,

please share your full chart config including all data.

**Comment by barotbhavesh** [comment]
I am solving this issue in my place thanks for your help.

**Comment by barotbhavesh** [comment]
I am solving this issue in my place thanks for your help.
