### ISSUE TITLE
Error with Cocoapods

### ISSUE THREAD

**Issue by kutran** [highcharts/highcharts-ios#28]
Getting this error using the command specified in README:

`pod 'Highcharts', '~> 1.1'`

[!] Unable to satisfy the following requirements:

- `Highcharts (~> 1.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Highcharts (~> 1.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by kutran** [comment]
However, using Cocoapod with just:

`pod 'Highcharts'`

is working.

**Comment by ihnatmoisieiev** [comment]
Hello @kutran,

it seems that you have a broken Specs repository. Try:

```
sudo rm -fr ~/.cocoapods/repos/master
sudo rm -fr ~/Library/Caches/CocoaPods/
pod setup
```

See this [link](http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/) for more info.

**Comment by ihnatmoisieiev** [comment]
@kutran did it solve your problem?
