### ISSUE TITLE
Intercept tap on export button

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#280]
Is there any way to intercept the tap onto the export button?

Under certain circumstances I would like to display an UIAlert once the user taps onto the export button, instead of showing the export menu. Can that be done?

**Comment by ihnatmoisieiev** [comment]
@skuske 

sure, it is possible.

Don't set up `viewController` param of your `chartView` and config `exporting` options like this e.g.

```
let exporting = HIExporting()
exporting.buttons = HIButtons()
exporting.buttons.contextButton = HIContextButton()
exporting.buttons.contextButton.onclick = HIFunction(closure: { context in
    let alert = UIAlertController(title: "Alert", message: nil, preferredStyle: .alert)
    alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
    self.present(alert, animated: true, completion: nil)
})
options.exporting = exporting
```

**Comment by skuske** [comment]
@ihnatmoisieiev 

Cool! Many thanks!
