### ISSUE TITLE
Export methods - how to use them?

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#281]
Since v7.2.0 we have three new methods:

> Added `exportToPNG`, `exportToPDF` and `exportToCSV` methods to `HIChartView`

However, I have no idea how to use them. Calling

`[chartView exportToPNG];`

 doesn't do anything.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
did you set `viewController` property of your `chartView` object? (e.g. `chartView.viewController = self`)

I have now checked and each method works for me.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Yes, just got it working. Thanks and sorry for the trouble.
