### ISSUE TITLE
How to change Postion of tooltip in iOS

### ISSUE THREAD

**Issue by codal-jayeshk** [highcharts/highcharts-ios#282]
Hello I want to change the position of tooltip.

I try with JSFunction but it is not working.

Please provide me solution for that.

![Screenshot 2020-01-22 at 12 02 39 PM](https://user-images.githubusercontent.com/52558720/72870776-1c7d5100-3d0f-11ea-886d-fb2fa448afcc.png)

Want to display start tooltip from top of the bar.

also it don't overlap on column.

Thanks

**Comment by ihnatmoisieiev** [comment]
Hello @codal-jayeshk,

you should use `tooltip.positioner`. 

Please check API [docs](https://api.highcharts.com/ios/highcharts/Classes/HITooltip.html#//api/name/positioner).

**Comment by codal-jayeshk** [comment]
Yes 

I already try with it but it is not working.


 let legendPositions = "function () { return { x: 80, y: 50 }; }"

columnrange.tooltip.positioner = HIFunction(jsFunction: legendPositions)


can you provide me jsFunction for that? because I don't know how to write js function for that.
also I assigned jsFunction is not working.

Thanks 
Jayesh

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk,

try the following function:

```
let tooltip = HITooltip()
let x = 0, y = -100
let tooltipPositioner = "function(labelWidth, labelHeight, point) { var tooltipX = point.plotX + \(x); var tooltipY = point.plotY + \(y); return { x: tooltipX, y: tooltipY }; }"
tooltip.positioner = HIFunction(jsFunction: tooltipPositioner)
options.tooltip = tooltip
```

Change `x`, `y` values on your needs.

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

Thanks For Reply

But I want to display dynamically like it always show top of the column if there is no space of top then it will display on center of column or below of the column.

![Screen Shot 2020-01-24 at 10 05 15 AM](https://user-images.githubusercontent.com/52558720/73044882-a2c1a080-3e91-11ea-9647-8138f836ff32.png)

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk please try another positioner function:

```
let tooltip = HITooltip()
let offset = 5 // offset is the distance from the edge of the tooltip to the top of the column
let tooltipPositioner = "function(width, height, point) { var offset = \(offset), tooltipX = point.plotX + this.chart.plotLeft - width / 2, tooltipY = point.plotY - point.h / 2 - offset; if (tooltipY < this.chart.plotTop) { tooltipY = point.plotY; } return { x: tooltipX, y: tooltipY } }"
tooltip.positioner = HIFunction(jsFunction: tooltipPositioner)
options.tooltip = tooltip
```

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

Above solution will not work for dynamic so leave it.

![Screen Shot 2020-01-27 at 6 42 19 PM](https://user-images.githubusercontent.com/52558720/73177559-54343080-4135-11ea-82ec-7099e8ec69bd.png)
please help me to hide this line which is showing on tooltip.

I tried with alpha and everything but it is not working.

Thanks
Jayesh

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk we don't understand what do you mean. Please describe everything step by step.

**Comment by codal-jayeshk** [comment]
sure @ihnatmoisieiev 

1) we added top and bottom line on chart with js function.

2) when we click on column chart it shows tooltip but on tooltip it showing the draw line on chart we want to hide it that is the issue.

if you see on above screenshot there is showing one blue line on tooltip box.i want to hide it.

Please let me know still it is not clear.

Thanks
Jayesh

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk did you try to use JS function from this https://github.com/highcharts/highcharts-ios/issues/274#issuecomment-578720561?

The problem is that your `zIndex` has value `10`. It should be `6` as in the latest version of JS function here:  https://github.com/highcharts/highcharts-ios/issues/274#issuecomment-578720561

**Comment by codal-jayeshk** [comment]
Okay Got it.

Thanks.

**Comment by baagii-tmcn** [comment]
Dear, 

I know it is a closed issue but the tooltip is always moving as click on different points. 

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/positioner/

I wanted to have a fixed tooltip as above.
