### ISSUE TITLE
Not able to get index of showing tooltip column on the formatter function.

### ISSUE THREAD

**Issue by codal-jayeshk** [highcharts/highcharts-ios#285]
Hello

I want to get index of showing tooltip column.

Here is the my code but it is showing me "undefinem" on tooltip.

    var toolTipfunction = " function () { return this.points.reduce(function (s, point) { return s + '<br/>' + point.series.name + ': ' + point.index + 'm'; }, '<b>' + this.x + '</b>'); }"

help me how I can get index of selected column?

**Comment by ihnatmoisieiev** [comment]
Hello @codal-jayeshk,

do you want to get the index of the selected column in Swift or display in the tooltip?

What does the `toolTipfunction` do?

**Comment by codal-jayeshk** [comment]
I want to check the condition of value with the value in array so for that I require the index of the showing tooltip column index.

For ex.

I have an array which I use for display the data in chart.now I want to compare value of range column chart when tooltip shows and display value accordingly.

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk please try

```
var toolTipfunction = " function () { return this.points.reduce(function (s, point, index) { return s + '<br/>' + point.series.name + ': ' + index + 'm'; }, '<b>' + this.x + '</b>'); }"
```

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

it is not working.

it always give me 0,1  0,1.

See the below attach images

![Screenshot 2020-02-04 at 4 25 57 PM](https://user-images.githubusercontent.com/52558720/73738881-40a74c00-476b-11ea-95b8-8d8983415f35.png)

![Screenshot 2020-02-04 at 4 26 42 PM](https://user-images.githubusercontent.com/52558720/73738893-46049680-476b-11ea-8b52-bb709ceec6f6.png)

.

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk sorry, my mistake. 

```
var toolTipfunction = "function () { return this.points.reduce(function (s, point) { return s + '<br/>' + point.series.name + ': ' + point.series.points.indexOf(point) + 'm'; }, '<b>' + this.x + '</b>'); }"
```

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

Still it is not working, Now it gives me "1,1","1,1"..

![Screenshot 2020-02-04 at 4 40 37 PM](https://user-images.githubusercontent.com/52558720/73739891-1c4c6f00-476d-11ea-9281-1328b8239fec.png)

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk 

```
var toolTipfunction = "function () { return this.points.reduce(function (s, point) { return s + '<br/>' + point.series.name + ': ' + point.series.points.indexOf(point.point) + 'm'; }, '<b>' + this.x + '</b>'); }"
```

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev 

I get the index but now facing the issue I am not able to use declared array of swift into jsfunction.

I want to get element from the array based on the index and want to compare with point.low and point.hight.

see the code below.

 

` let toolTipfunction = "function () { return this.points.reduce(function (s, point) { return s + '<br/>' + point.series.name + ': ' + \(arr["point.series.points.indexOf(point.value)"]) + 'm'; }, '<b>' + this.x + '</b>'); }"
`

it gives me error "Cannot subscript a value of type '[Int]' with an argument of type 'String'". 
I understood the error like it not able to convert index to Int on swift.

Waiting for your reply!

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk it's technically impossible. You can only get the index from `JS` to `iOS`.
