### ISSUE TITLE
How to implement range selector in HighCharts 

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-ios#287]
I have a requirement to show range selection in the chart, I could see there is an option to implement range selection in `stockChart`.  is it possible to implement the same in iOS `HighChart` library ?

[Stock Demo Range Selection](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/floating/)

my requirement.. 
 
<img width="281" alt="Screenshot 2020-02-19 at 12 31 29 PM" src="https://user-images.githubusercontent.com/34921497/74809818-15e4f800-5314-11ea-9b29-b8d3c27d7014.png">

**Comment by ArunVicky001** [comment]
Team is it possible to integrate the Rage selection in `iOS` `HighCharts` ?

**Comment by ihnatmoisieiev** [comment]
Hello @ArunVicky001,

your requirement looks like a custom implementation that is not implemented by default. So, please contact [Support](https://www.highcharts.com/blog/support/) Team. On the bottom, you can find `Custom implementation services`.

**Comment by ArunVicky001** [comment]
Thank you very much for your response.
