### ISSUE TITLE
Change the precision of x or y axis label if value is in decimal format in every chart

### ISSUE THREAD

**Issue by chetanzalake** [highcharts/highcharts-ios#29]
![img_1185](https://user-images.githubusercontent.com/19661519/30363096-87a4a36e-987c-11e7-97f8-5281dd41f4f0.PNG)

I want to change the values of labels to a maximum of 3 decimals. I am not able to find how I can get this done. 
Can some please let me know how to do it?

**Comment by ihnatmoisieiev** [comment]
Hello @chetanzalake,

you can do it using **formatter** for labels, e.g.:

```
let xAxisLabels = HIXAxisLabels()
xAxisLabels.formatter = "function() { return Highcharts.numberFormat(this.value, 3); }"
xAxix.labels = xAxisLabels
```

**Comment by TorsteinHonsi** [comment]
@chetanzalake 
It seems like you are using categories for what is actually a linear axis... If the points are distributed along a linear axis, I strongly recommend not you use categories, but rather give each point an X value and let the axis itself lay out the ticks. Then you don't have to think about the `xAxisLabels.formatter`.

@ihnatmoisieiev 
To avoid using callback strings and mixing JavaScript into the setup, `xAxisLabels.format` is a cleaner choice:
```js
let xAxisLabels = HIXAxisLabels()
xAxisLabels.format = "{value:.3f}"
xAxix.labels = xAxisLabels
```

**Comment by ihnatmoisieiev** [comment]
@TorsteinHonsi yes, you are right. Thank you for your reply!

**Comment by chetanzalake** [comment]
@ihnatmoisieiev @TorsteinHonsi: It worked. Thank you, guys.

**Comment by chetanzalake** [comment]
@ihnatmoisieiev : Just one more thing to add from the same screenshot. How can I disable the HILegend i.e. Series 1 label which is at bottom o screenshot? 
Though I didn't set the legend to chart options it is still showing it.

**Comment by ihnatmoisieiev** [comment]
@chetanzalake you can disable it by setting **showInLegend** param to **false** of your series, e.g.:

```
let column = HIColumn()
column.showInLegend = false
```

**Comment by ihnatmoisieiev** [comment]
@chetanzalake does it work?

**Comment by chetanzalake** [comment]
@ihnatmoisieiev : Yes it worked.

**Comment by Evyasafmordechai** [comment]
Is there a way to write the formatter function in Swift instead of javaScript?
