### ISSUE TITLE
Tableview cell not loading multiple HighCharts in cell

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-ios#291]
In my application I have table view and the cell count is 5 each cell should display two different HighCharts, 

In this case first cell displays the correct charts and second cell is not displaying the charts, It's showing the white colour background. Also third cell displaying the same value of the first chart 

```
class ChartTableViewCell: UITableViewCell {

    @IBOutlet weak var lineChartView: HIChartView!
    @IBOutlet weak var line2ChartView: HIChartView!

}
```

````
let cell = tableView.dequeueReusableCell(withIdentifier: "ChartTableViewCell", for: indexPath) as! ChartTableViewCell

cell.lineChartView.options = CreateChartCharts.loadCharts(.....)

cell.line2ChartView.options = CreateChartCharts.loadSampleChart(....)

return cell
````

Could you please help me solve this issue

**Comment by ihnatmoisieiev** [comment]
Hello @ArunVicky001,

please check a demo app [`HighFit `](https://github.com/highcharts/highcharts-ios/tree/master/Example/HighFit/HighFit%20Swift). 

If this doesn't help, please attach a demo with your problem.

**Comment by ArunVicky001** [comment]
I have attached the demo project please check it. 
 
[ChartDemo.zip](https://github.com/highcharts/highcharts-ios/files/4312513/ChartDemo.zip)

**Comment by ArunVicky001** [comment]
Also I tried setting Boolean value to restrict the table view reloading process, In this case chart is not showing the correct value it's showing the older chart value to the newer chart which their in the cell

**Comment by ihnatmoisieiev** [comment]
@ArunVicky001 this is not HC issue.

It's too much data and very hard to check something, but I see a major mistake on your side - every time you setting options object (`chartView.options = options`), the chart is rendering. You should prevent it.

**Comment by ArunVicky001** [comment]
The problem is I am using `UITableViewCell.Xib` and I have register the nib with table view cell 

`tableView.register(UINib(nibName: "ChartTableViewCell", bundle: nil), forCellReuseIdentifier: "ChartCell")`

in this case I can't able to check the case  if cell == nil { } because it will always return false.  

In the demo you were dynamically creating the HIChartView and checking cases like below 

       ```
var options = self.sources[indexPath.row]
        
        let cellReuseIdentifier: String = options["chartType"] as! String
        
        var cell: UITableViewCell? = tableView.dequeueReusableCell(withIdentifier: cellReuseIdentifier)
        
        if cell == nil {
            cell = UITableViewCell(style: .default, reuseIdentifier: cellReuseIdentifier)
            
            cell!.selectionStyle = UITableViewCell.SelectionStyle.none
            
            let chartView = HIChartView(frame: CGRect(x: 5.0, y: 5.0, width: self.view.bounds.size.width - 20, height: 240.0))
            chartView.backgroundColor = UIColor.clear
            chartView.delegate = self
}
return cell!
```


In my situation how can I prevent calling chartView.options = options. if I did with any boolean value it will not show the correct value in the chart some time it's not displaying the chart. Please help to achieve this. 

Thanks!

**Comment by ihnatmoisieiev** [comment]
@ArunVicky001 I suppose you have many ways to achieve the goal. The simplest is to create a variable e.g. `var loadedCharts: [Int: (HIChartView, HIChartView)]` and checking if the chart is loaded for special index.

**Comment by ArunVicky001** [comment]
Could you please elaborate your answer? 

Let’s say I have 5 `tableViewCell` Count when `ViewController` initialised the `table view cell for at index path` method will call, in that we have (`chartView.options = options`) function 

How can I check whether the chart is loaded or not ? With this variable `var loadedCharts: [Int: (HIChartView, HIChartView)]` 

How can I predict which chart has loaded? 
Because each cell I am displaying two different charts like `line chart `and `xRange` chart

**Comment by ihnatmoisieiev** [comment]
@ArunVicky001 you can use `HIChartViewDelegate` and implement `func chartViewDidLoad(_ chart: HIChartView!)` method.

Also in your `table view cell for at index path method` you can check if your chart (or pair) is loaded or not and setting options (`chartView.options = options`) only for the proper index.

**Comment by ArunVicky001** [comment]
Thanks for your suggestion Will do the same.
