### ISSUE TITLE
Customization of data labels for the funnel chart does not work on iOS using SWIFT

### ISSUE THREAD

**Issue by gasta-java** [highcharts/highcharts-ios#293]
Expected behavior:
I want to customize data labels in iOS using SWIFT (as it's customizable in web java script);
And It would be appreciated to get some iOS SWIFT code snippet examples of how to customize them; (we need to change the font style of data labels and align them to the left in widget comparing to the chart)
<img width="336" alt="Screenshot at Mar 26 12-33-27" src="https://user-images.githubusercontent.com/8984253/77637270-1188ac00-6f5e-11ea-9bff-d768908219fa.png">

Actual behavior:
Customization of data labels for the funnel chart does not work on iOS using SWIFT;
<img width="331" alt="Screenshot at Mar 26 12-23-07" src="https://user-images.githubusercontent.com/8984253/77637301-1ea59b00-6f5e-11ea-8648-a331c2bcb413.png">

Product version
iOS SDK is integrated using Carthage:
github "https://github.com/highcharts/highcharts-ios" == 8.0.0

**Comment by ihnatmoisieiev** [comment]
Hello @gasta-java,

please share your data labels config (JS) which you want to implement in iOS.

**Comment by gasta-java** [comment]
Hi @ihnatmoisieiev,
Thank you for your answer.
So here is the JS example which we can't achieve in iOS SWIFT app:

https://jsfiddle.net/1qeLdz3w/8/

and particularly this part related to data labels style:

plotOptions: {
    series: {
      dataLabels: {
        enabled: true,
        softConnector: true,
        position: 'left',
        style: {
                    fontWeight: 'regular',
                    color: 'red',
                    fontSize: 15,
                    fontFamily: 'serif'
                }
      },
      center: ['40%', '50%'],
      neckWidth: '30%',
      neckHeight: '25%',
      width: '80%'
    }
  },

**Comment by ihnatmoisieiev** [comment]
Hello @gasta-java,

I've checked this demo and it's a bug that will be fixed in the next release. 

Thank you for reporting!

**Comment by gasta-java** [comment]
Hi @ihnatmoisieiev !  I am glad to hear that you're going to fix this. So we will be waiting for the new release with the fix :-) Thank you!

**Comment by ihnatmoisieiev** [comment]
@gasta-java the issue has been fixed in the latest release. Can I close it?

**Comment by gasta-java** [comment]
@ihnatmoisieiev thank you! Yes, it could be closed
