### ISSUE TITLE
"Reset to Zoom" button event is not working in the chart after getting the min, max values of the selection

### ISSUE THREAD

**Issue by ArunVicky001** [highcharts/highcharts-ios#294]
Hi Team, 

I have written the closure function to get the `min` and `max` values of the selection area of the chart. After adding this function into `HIEvent` section `Reset Button` event is not working. 

if I Comment the `HIEvent` Selection function `Reset To Zoom` event is working fine.
 
My requirement is to get the min and max values also the Reset Button event.
please help me on this. 

Example : 
        
```
let options = HIOptions()
let chart = HIChart()
chart.zoomType = "x"
chart.events = HIEvents()
chart.events.selection = HIFunction(closure: { context in
guard let context = context else { return }
let min = context.getProperty("event.xAxis[0].min") as! Double , max = context.getProperty("event.xAxis[0].max") as! Double
print("xAxis min: \(Int(min)), xAxis max: \(Int(max))")
 }, properties: ["event.xAxis[0].min", "event.xAxis[0].max"])
.....,
options.series = [....]
```

[I have followed this](https://github.com/highcharts/highcharts-ios/issues/193)

Many Thanks.

**Comment by ihnatmoisieiev** [comment]
Hello @ArunVicky001,

thank you for your question. We will investigate it as soon as possible.

**Comment by ihnatmoisieiev** [comment]
Hello @ArunVicky001,

please change your `charts.events.selection` function to the following: 

```
let selection = HIFunction(closure: { context in
    guard let context = context,
        let min = context.getProperty("event?.xAxis?.[0]?.min") as? Double,
        let max = context.getProperty("event?.xAxis?.[0]?.max") as? Double else { return }

    print("min: \(min), max: \(max)")
}, properties: ["event?.xAxis?.[0]?.min", "event?.xAxis?.[0]?.max"])
chart.events.selection = selection
```

Please try and let us know.

**Comment by ArunVicky001** [comment]
@ihnatmoisieiev Thanks for your response, 

the above is not loading the chart

**Comment by ihnatmoisieiev** [comment]
@ArunVicky001 it works perfectly for me. Please check the demo below:

```
let options = HIOptions()

let chart = HIChart()
chart.zoomType = "x"
chart.events = HIEvents()

let selection = HIFunction(closure: { context in
    guard let context = context,
        let min = context.getProperty("event?.xAxis?.[0]?.min") as? Double,
        let max = context.getProperty("event?.xAxis?.[0]?.max") as? Double else { return }

    print("min: \(min), max: \(max)")
}, properties: ["event?.xAxis?.[0]?.min", "event?.xAxis?.[0]?.max"])
chart.events.selection = selection

options.chart = chart

let xAxis = HIXAxis()
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
options.xAxis = [xAxis]

let line = HILine()
line.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [line]
```

![Screen-Recording-2020-04-03-at-13 08 37](https://user-images.githubusercontent.com/11294008/78354617-7b333680-75ac-11ea-8256-3ded10969e1d.gif)

**Comment by ArunVicky001** [comment]
Thank you for response I will follow the same.

**Comment by ihnatmoisieiev** [comment]
@ArunVicky001 can I close the issue?

**Comment by ArunVicky001** [comment]
@ihnatmoisieiev Thanks for the support you can close the issue.
