### ISSUE TITLE
How can we modify tooltip font-weight using CSS?

### ISSUE THREAD

**Issue by gasta-java** [highcharts/highcharts-ios#295]
Hello! 
How can we modify tooltip font-weight using CSS?

We are trying to do this in iOS SWIFT and can't make font-weight work:
`hiTooltip.headerFormat = "<table><tr><td style=\"font-size: 40px; color: blue; font-weight: 100\">{point.y}</td><tr/>"`

Also, we can't make it work even in JS:
http://jsfiddle.net/qzhfxb3d/18/

**Comment by ihnatmoisieiev** [comment]
Hello @gasta-java,

it works in JS and in iOS for me.

Please check the demo and screenshots below for ` font-weight: 100` and ` font-weight: 700`:

```
let options = HIOptions()

let tooltip = HITooltip()
tooltip.formatter = HIFunction(jsFunction: "function () { return '<p style = \"font-size: 20px\">' + this.x + '</p>' + '<br> <p style = \"font-size: 50px; color: blue; font-weight: 700\">' + this.y + '</p>'; }")
tooltip.useHTML = true
options.tooltip = tooltip

let xAxis = HIXAxis()
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
options.xAxis = [xAxis]

let series1 = HISeries()
series1.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

let series2 = HISeries()
series2.data = [194.1, 95.6, 54.4, 29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4]

options.series = [series1, series2]
```

![Simulator Screen Shot - iPhone 11 Pro - 2020-04-02 at 14 16 39](https://user-images.githubusercontent.com/11294008/78248540-195fc780-74ed-11ea-9e1f-f6acf46e0f68.png)

![Simulator Screen Shot - iPhone 11 Pro - 2020-04-02 at 14 16 51](https://user-images.githubusercontent.com/11294008/78248544-1a90f480-74ed-11ea-8a48-d043c3a9ad76.png)

**Comment by gasta-java** [comment]
@ihnatmoisieiev  thank you for the answer! We are trying to use in code like this:        
tooltip.headerFormat = "<table><tr><td style=\"font-size: 40px; color: blue; font-weight: 700\">{point.y}</td><tr/>"
And this does not work? Can you confirm this should work, please?

**Comment by ihnatmoisieiev** [comment]
@gasta-java it also works for me. 

Please try:

```
let tooltip = HITooltip()
tooltip.headerFormat = "<table><tr><td style=\"font-size: 40px; color: blue; font-weight: 100\">{point.y}</tr><tr></td><td style=\"font-size: 40px; color: blue; font-weight: 700\">{point.y}</td><tr/>"
tooltip.useHTML = true
options.tooltip = tooltip
```

![Simulator Screen Shot - iPhone 11 Pro - 2020-04-03 at 11 15 03](https://user-images.githubusercontent.com/11294008/78344363-90a06480-759c-11ea-90ee-70141e3b1ea8.png)

**Comment by gasta-java** [comment]
@ihnatmoisieiev thank you! I tried it and it works for me as well; Probably the problem was in smth else; Thanks for your help;
