### ISSUE TITLE
HIDataLabels().enabled = true prevents drawing of column chart

### ISSUE THREAD

**Issue by DavidKasprzyk** [highcharts/highcharts-ios#296]
In trying to match our web Highcharts styling for column charts:

    "plotOptions": {
        "column": {
            "dataLabels": {
                "enabled": true,
                "style": {
                    "color": "#ffffff",
                    "fontSize": "14px"
                }
            }
        }
    },

I tried testing the following swift code:

        options.plotOptions = HIPlotOptions()
        options.plotOptions.column = HIColumn()

        let dataLabels = HIDataLabels()
        dataLabels.enabled = true
        dataLabels.style = HIStyle()
        dataLabels.style.color = "#ffffff"
        dataLabels.style.fontSize = "14px"

        options.plotOptions.column.dataLabels = [dataLabels]

However, the columns would not draw at all. I swapped to testing using the HighFit example app, and found that for the column type of chart, used for calories burned, if I editing the plotOptions and added:

let dataLabels = HIDataLabels()
            dataLabels.enabled = true
//            dataLabels.enabled = false
            dataLabels.style = HIStyle()
            dataLabels.style.color = "#ffffff"
            dataLabels.style.fontSize = "14px"
            plotOptions.column.dataLabels = [dataLabels]

The chart values would not render. However if I changed the true to false for enabled:

let dataLabels = HIDataLabels()
//            dataLabels.enabled = true
            dataLabels.enabled = false
            dataLabels.style = HIStyle()
            dataLabels.style.color = "#ffffff"
            dataLabels.style.fontSize = "14px"
            plotOptions.column.dataLabels = [dataLabels]

then the chart values render correctly, albeit without labels.

Is there some property of DataLabels that I'm missing or is this a bug?

**Comment by ihnatmoisieiev** [comment]
Hello @DavidKasprzyk,

thank you for the reporting. It's connected with https://github.com/highcharts/highcharts-ios/issues/293 and will be fixed in the next release.

**Comment by DavidKasprzyk** [comment]
@ihnatmoisieiev thank you for the follow up and update.

**Comment by ihnatmoisieiev** [comment]
@DavidKasprzyk as a workaround, you can change `plotOptions.column` to `plotOptions.series` if it is possible for your chart, e.g.

```
let plotOptions = HIPlotOptions()
plotOptions.series = HISeries()

let dataLabels = HIDataLabels()
dataLabels.enabled = true
dataLabels.style = HIStyle()
dataLabels.style.color = "#ffffff"
dataLabels.style.fontSize = "14px"

plotOptions.series.dataLabels = [dataLabels]
```

**Comment by ihnatmoisieiev** [comment]
@DavidKasprzyk the issue has been reported: https://github.com/highcharts/highcharts/issues/13260

**Comment by DavidKasprzyk** [comment]
I'm not seeing any labels still with changing to using series:

        options.chart = HIChart()
        options.chart.backgroundColor = HIColor(uiColor: .gray700)
//        options.chart.type = "column"

        options.credits = HICredits()
        options.credits.enabled = false

        options.exporting = HIExporting()
        options.exporting.enabled = false

        options.title = HITitle()
        options.title.text = ""

        options.legend = HILegend()
        options.legend.enabled = false

        options.tooltip = HITooltip()
        options.tooltip.enabled = false

        options.plotOptions = HIPlotOptions()
        options.plotOptions.series = HISeries()
        options.plotOptions.series.color = HIColor(uiColor: .blue300)
//        options.plotOptions.series.borderRadius = 2
//        options.plotOptions.series.borderWidth = 0

        let dataLabels = HIDataLabels()
        dataLabels.enabled = false
        dataLabels.style = HIStyle()
        dataLabels.style.color = "#ffffff"
        dataLabels.style.fontSize = "14px"

        options.plotOptions.series.dataLabels = [dataLabels]

        let xAxis = HIXAxis()
        xAxis.categories = categories
        xAxis.labels = HILabels()
        xAxis.labels.rotation = -45
        xAxis.labels.style = HICSSObject()
        xAxis.labels.style.color = "#ffffff"
        xAxis.labels.style.fontSize = "12px"

        options.xAxis = [xAxis]
        
        let yAxis = HIYAxis()
        yAxis.min = 0
        yAxis.title = HITitle()
        yAxis.title.text = ""
        yAxis.gridLineColor = HIColor(uiColor: .gray600)
        yAxis.gridLineWidth = 1
        yAxis.labels = HILabels()
        yAxis.labels.enabled = false

        options.yAxis = [yAxis]
        
        let column = HISeries()
        column.data = series
        options.series = [column]

**Comment by ihnatmoisieiev** [comment]
@DavidKasprzyk please check the demo below:

```
let options = HIOptions()

let xAxis = HIXAxis()
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
options.xAxis = [xAxis]

let plotOptions = HIPlotOptions()
plotOptions.series = HISeries()

let dataLabels = HIDataLabels()
dataLabels.enabled = true
dataLabels.style = HIStyle()
dataLabels.style.color = "#ffffff"
dataLabels.style.fontSize = "14px"

plotOptions.series.dataLabels = [dataLabels]

options.plotOptions = plotOptions

let column = HIColumn()
column.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [column]

return options
```

**Comment by DavidKasprzyk** [comment]
Thanks, found my issue and it's working fine until the patched version is released.
