### ISSUE TITLE
Click function callback does not work on iOS-12 but works on iOS-13

### ISSUE THREAD

**Issue by gasta-java** [highcharts/highcharts-ios#299]
Hey! Click function callback does not work on iOS-12 but works on iOS-13: 

 ```
        let plotOptions = HIPlotOptions()                       
        let selectionFunction = HIFunction(closure: { (context) in
            print(context?.getProperty("this.index"))
        }, properties: ["this.index"])                
        
        plotOptions.series = HISeries()
        plotOptions.series.point = HIPoint()
        plotOptions.series.point.events = HIEvents()
        plotOptions.series.point.events.click = selectionFunction
```

======================================================
Envirement:
- Carthage: github "https://github.com/highcharts/highcharts-ios" == 8.0.0
- SWIFT,   xCode 11.2.1      
- iPhone simulator iOS 12.2

**Comment by ihnatmoisieiev** [comment]
Hello @gasta-java,
I've checked and it works for me with iOS 12.4.

**Comment by gasta-java** [comment]
@ihnatmoisieiev  thanks for the checking. But on  12.2 if it does not for me. Can you try a lower version?

**Comment by ihnatmoisieiev** [comment]
@gasta-java iPhone 8 with iOS 12.12 also works.

**Comment by gasta-java** [comment]
@ihnatmoisieiev  hm, strange. Are you using 8.0.0 version of SDK?

**Comment by ihnatmoisieiev** [comment]
@gasta-java yes.

**Comment by gasta-java** [comment]
@ihnatmoisieiev  Thank you for the help. I will think what could be wrong on our side;
