### ISSUE TITLE
WKWebView is always opaque.

### ISSUE THREAD

**Issue by Ferannor** [highcharts/highcharts-ios#3]
You can't have a transparent background behind you chart. Properties are not set on the WKWebView.

For now, I fix this with : 

>for (UIView* subview in chartView.subviews) {
>        if ([subview isKindOfClass:[WKWebView class]]) {
>            subview.opaque = NO;
>           subview.backgroundColor = [UIColor clearColor];
>           ((WKWebView*)subview).scrollView.backgroundColor = [UIColor clearColor];
>      }
>    }

**Comment by mll** [comment]
Hi, we are close to publishing a new version that fixes the issue.

**Comment by mll** [comment]
This should be fixed in 1.1.0
