### ISSUE TITLE
How to get the real height of a chart / HiCHartView?

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#30]
Hello,

The height of a chart is not always the height given for the frame.
How can I get the real height of any chart?

TIA

Regards,
Alexandre

**Comment by ihnatmoisieiev** [comment]
Hello @AlexandreMinard,

thank you for your question. 
The height of a chart is the height of the frame. 
Can you explain when it is not equal?

**Comment by AlexandreMinard** [comment]
Forget that, my mistake :)
