### ISSUE TITLE
Advanced customization of tooltip for line chart

### ISSUE THREAD

**Issue by gasta-java** [highcharts/highcharts-ios#300]
Hi! Can I find somewhere or can you provide please an ios SWIFT example for the line  chart tooltip to achieve smth like this:

https://prnt.sc/rz0iip

1) Header: x value;
2) A stack of rows with all line values; (And rounded circle with color of the line on each row);

Huge thank you for the help;

====================
And the second part is it possible to make this effect:
https://prnt.sc/rz0p6i

1) When a category on the x-axis is selected, all data points corresponding to that value along the y-axis enter the focused state.
2) The line element in the background is 2px dots with 6px gaps

**Comment by ihnatmoisieiev** [comment]
Hello @gasta-java,

please try to set `xAxis.crosshair = true`, `tooltip.shared = true` and modify your [`tooltip. pointFormat`](https://api.highcharts.com/ios/highcharts/Classes/HITooltip.html#//api/name/pointFormat).

Also, please check the [API](https://api.highcharts.com/ios/highcharts/) reference.

**Comment by gasta-java** [comment]
@ihnatmoisieiev  thanks, I will try to play with crosshair.

But what about the first issue, do you have ios SWIFT example of similar formatting?

**Comment by ihnatmoisieiev** [comment]
@gasta-java unfortunately, we don't have such example at the moment.

**Comment by gasta-java** [comment]
@ihnatmoisieiev  thanks for the answer. Could you at least provide an example of how can we aggregate data from all lines into the tooltip in SWIFT?

**Comment by ihnatmoisieiev** [comment]
@gasta-java can I close the issue?

**Comment by gasta-java** [comment]
@ihnatmoisieiev yep, it could be closed; Thanks
