### ISSUE TITLE
How to add multiple columns on each x-asix title in column chart?

### ISSUE THREAD

**Issue by lhvan89** [highcharts/highcharts-ios#302]
How to add multiple columns on each x-asix title in **column chart** like this photo?

<img width="819" alt="Screen Shot 2020-04-21 at 3 31 56 PM" src="https://user-images.githubusercontent.com/15281280/79845518-6269b400-83e7-11ea-8065-1829a5a434c2.png">

I didn't find any solution in **Swift** with this case.

Could you show me how to solve this?

Thanks and best regards!

**Comment by ihnatmoisieiev** [comment]
Hello @lhvan89,

Thanks for choosing Highcharts!

Just add multiple series to `options.series` object. Please try:

```
let options = HIOptions()

let chart = HIChart()
chart.type = "column"
options.chart = chart

let title = HITitle()
title.text = "Demo"
options.title = title

let xAxis = HIXAxis()
xAxis.categories = ["Apples", "Pears", "Plums", "Bananas", "Oranges"]
options.xAxis = [xAxis]

let jane = HIColumn()
jane.name = "Jane"
jane.data = [3, 2, 5, 1, 2]

let john = HIColumn()
john.name = "John"
john.data = [4, NSNull(), 11, 1, 4]

options.series = [jane, john]
```

**Comment by lhvan89** [comment]
@ihnatmoisieiev 

Thanks for your support.
Your are great!

**Comment by ihnatmoisieiev** [comment]
@lhvan89 could I close the issue?

**Comment by lhvan89** [comment]
Yes sir.
