### ISSUE TITLE
Unable to add custom font

### ISSUE THREAD

**Issue by mansoor92** [highcharts/highcharts-ios#309]
I am unable to add custom font. I followed the steps mentioned in [Custom font section](https://github.com/highcharts/highcharts-ios/blob/master/README.md).
But HiChartView.addfont method gives the following error:

`Error adding font: OpenSans-Regular. Code: 2`

Here is the code that i am using:

```
if let path = Bundle.main.path(forResource: "OpenSans-Regular", ofType: "ttf"){
	HIChartView.addFont(path)
}
let options = HIOptions()
let chart = HIChart()
let title = HITitle()
title.text = "This is a title"
let style = HICSSObject()
style.color = "#000000"
style.fontFamily = "OpenSans-Regular"
title.style = style
```
I am unable to find any documentation that refers to this error code 2.
Please guide me if i am doing something wrong.

**Comment by ihnatmoisieiev** [comment]
Hello @mansoor92,

Thanks for choosing Highcharts!

This bug has been already reported: https://github.com/highcharts/highcharts-ios/issues/306

It will be fixed in the next release.

**Comment by mansoor92** [comment]
Hi ,
Can you please give an estimate for next release.
Also is there any fix, workaround or prerelease i can try. It is really crucial for my client to have custom font in charts.

Thanks

**Comment by ihnatmoisieiev** [comment]
@mansoor92 unfortunately, there is no any workaround for that bug.

The next release of the main framework is planned by the end of the next week. iOS wrapper usually is updated a few days after it.

**Comment by mansoor92** [comment]
Thanks for your support

**Comment by ihnatmoisieiev** [comment]
@mansoor92 the issue has been fixed in the latest release. Can I close it?

**Comment by mansoor92** [comment]
Hi @ihnatmoisieiev ,

Yes it is fixed and working great. i'm closing the issue
Thanks for your support and fast response.  

Regards
