### ISSUE TITLE
onClick() events from HighCharts to Swift

### ISSUE THREAD

**Issue by kutran** [highcharts/highcharts-ios#31]
Is there an example of receiving events from HighCharts to Swift?

I have seen an example of where one creates a WebView manually along with WebKitOptions to specify the onClick.  But doing that solution won't be able to take an advantage of highcharts-ios library.

Thank you.

**Comment by ihnatmoisieiev** [comment]
Hello @kutran,
what events do you need to receive?

For example you can set up event for clicking on the plot background. See [docs](http://api.highcharts.com/highcharts-ios/chart.events.click).

**Comment by kutran** [comment]
Hello @ihnatmoisieiev,

I was trying to get an tap event callback.

I was looking at the docs and tried using that event : NSStrting, but it was crashing at that line for me while passing in the name of the Swift function or selector.  Is there an example for that piece of code?

Thank you,

**Comment by ihnatmoisieiev** [comment]
@kutran you need to pass a string with the **js** function, example from [demo](http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/chart/events-click/):

```
let events = HIChartEvents()
events.click = "function (event) { var label = this.renderer.label('x: ' + Highcharts.numberFormat(event.xAxis[0].value, 2) + ', y: ' + Highcharts.numberFormat(event.yAxis[0].value, 2), event.xAxis[0].axis.toPixels(event.xAxis[0].value), event.yAxis[0].axis.toPixels(event.yAxis[0].value)).attr({fill: Highcharts.getOptions().colors[0], padding: 10, r: 5, zIndex: 8}).css({color: '#FFFFFF'}).add();setTimeout(function () {label.fadeOut();}, 1000);}"
chart.events = events
```

**Comment by kutran** [comment]
Awesome thanks!

Is there any way to receive tap events from HighCharts to Swift?

**Comment by ihnatmoisieiev** [comment]
If you want handle tap events on `HIChartView`, you can add gesture recognizer and your UIViewController subclass should implement `UIGestureRecognizerDelegate`.

**Comment by kutran** [comment]
Okay that makes sense.  But what if I want to know what elements being tapped on HighCharts?

**Comment by kutran** [comment]
Along with their data.

**Comment by ihnatmoisieiev** [comment]
Actually, it is not possible.

**Comment by KacperMadej** [comment]
@kutran Yes, it can be. There's no userVoice for highcharts-iOS, so let's keep this enhancement suggestion in here.

**Comment by ihnatmoisieiev** [comment]
@kutran this feature is added to the latest release. Can I close this issue?

**Comment by kutran** [comment]
Yes, thank you.

**Comment by eviathan** [comment]
How does this work? I cant find any information on how to handle events in iOS. 

How do you handle selection events?

**Comment by ihnatmoisieiev** [comment]
Hi @eviathan,
see [readme](https://github.com/highcharts/highcharts-ios/blob/master/README.md) and search closed issues.
