### ISSUE TITLE
How to remove the default legend Image and how to set custom multiple legends??

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#311]
How to remove the default legend Image and how to set custom multiple legends?

_Originally posted by @barotbhavesh in https://github.com/highcharts/highcharts-ios/issues/297#issuecomment-625113519_

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh please check [`legend.symbolWidth`](https://api.highcharts.com/ios/highcharts/Classes/HILegend.html#//api/name/symbolWidth) property and set it to `0`.

>  how to set custom multiple legends

Please describe what do you mean.

**Comment by barotbhavesh** [comment]
The below image has two custom images in legends on how to set two custom legends images in one chart. 

![Screenshot 2020-05-08 at 10 18 13 AM](https://user-images.githubusercontent.com/48505333/81371347-3bb0ba80-9115-11ea-8449-2877d8c38811.png)

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh there are two series with custom legend symbols. I've shown you how to add a custom image here: https://github.com/highcharts/highcharts-ios/issues/297#issuecomment-611063678

**Comment by barotbhavesh** [comment]
yes right @ihnatmoisieiev it's working in I have one legend but if I have two legends then how to add 2 images that my query.

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh if you have only two series, you can firstly add an `id` to your first series:
`firstSeries.id = "myFirstSeriesID"` and then modify `legend.labelFormatter` function, e.g.

```
legend.labelFormatter = HIFunction(jsFunction: "function() { var name = this.name; var img; if (this.options.id === "myFirstSeriesID") { img = '<img src = \"\(base64ImageForFirstSeries)\" width = \"15px\" height = \"15px\">'; } else { img = '<img src = \"\(base64ImageForSecondSeries)\" width = \"15px\" height = \"15px\">'; } return img + ' ' + name; }")
```

**Comment by barotbhavesh** [comment]
**It's not working** 

I have one series  with **options.series = [column1, line2]**
I have set column1.id = "columnLegendId1"
and line2.id = "lineLegendId2"

        let legend = HILegend()
             legend.useHTML = true
             legend.symbolWidth = 0
    
             let imageDataLegend1 = #imageLiteral(resourceName: "Compare").pngData()!
             let base64ImgLegend1 = "data:image/png;base64," + imageDataLegend1.base64EncodedString(options: Data.Base64EncodingOptions.lineLength64Characters)
               
 let imageDataLegend2 = #imageLiteral(resourceName: "CompareSecond").pngData()!
             let base64ImgLegend2 = "data:image/png;base64," + imageDataLegend2.base64EncodedString(options: Data.Base64EncodingOptions.lineLength64Characters)

 legend.labelFormatter = HIFunction(jsFunction: "function() { var name = this.name; var img; if (this.options.id === columnLegendId1) { img = '<img src = \"\(base64ImgLegend1)\" width = \"15px\" height = \"15px\">'; } else { img = '<img src = \"\(base64ImgLegend2)\" width = \"15px\" height = \"15px\">'; } return img + ' ' + name; }")

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh please check the following example with column and line series

```
let options = HIOptions()

let legend = HILegend()
legend.useHTML = true
legend.squareSymbol = false
legend.symbolWidth = 0
let image = UIImage(named: "sun")!
let imageData = image.pngData()!
let base64Image1 = "data:image/png;base64," + imageData.base64EncodedString(options: Data.Base64EncodingOptions.lineLength64Characters)
legend.labelFormatter = HIFunction(jsFunction: "function() { var name = this.name; var img; if (this.options.id === 'columnLegendId1') { img = '<img src = \"\(base64Image1)\" width = \"15px\" height = \"15px\">'; } else { img = '<img src = \"\(base64Image2)\" width = \"15px\" height = \"15px\">'; } return img + ' ' + name; }")
options.legend = legend

let column = HIColumn()
column.id = "columnLegendId1"
column.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

let line = HILine()
line.id = "lineLegendId2"
line.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reversed()

options.series = [column, line]
```

**Comment by barotbhavesh** [comment]
Thanks for the Update
it's working but the image not in the center for reference please check below image

![Screenshot 2020-05-13 at 10 23 54 AM](https://user-images.githubusercontent.com/48505333/81772823-74c9a000-9504-11ea-8504-1da518af49d4.png)

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh there is another option which fixes this problem. You need to create an additional `HIScatter` series and set `marker.symbol`, then link your main series with `scatter`. Example:

```
let options = HIOptions()

let image = UIImage(named: "sun")!
let imageData = image.pngData()!
let base64Image = "data:image/png;base64," + imageData.base64EncodedString()

let columnScatter = HIScatter()
columnScatter.id = "columnScatter"
columnScatter.marker = HIMarker()
columnScatter.marker.symbol = "url(\(base64Image))"

let column = HIColumn()
column.linkedTo = "columnScatter"
column.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

let lineScatter = HIScatter()
lineScatter.id = "lineScatter"
lineScatter.marker = HIMarker()
lineScatter.marker.symbol = "url(\(base64Image2))"

let line = HILine()
line.linkedTo = "lineScatter"
line.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reversed()

options.series = [columnScatter, lineScatter, column, line]
```

**Comment by barotbhavesh** [comment]
it's working, an image showing in the center but name not display 
please check below image
![Screenshot 2020-05-14 at 10 53 15 AM](https://user-images.githubusercontent.com/48505333/81895992-35b55080-95d1-11ea-9979-e9917bf71782.png)

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh please set name to the scatters series. For this case: 

```
let columnScatter = HIScatter()
columnScatter.name = "Custom name 1"
...

let lineScatter = HIScatter()
lineScatter.name = "Custom name 2"
```

**Comment by barotbhavesh** [comment]
its working thank you so much
