### ISSUE TITLE
How to add License ID in IOS Project ?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#312]
I have Highchart "License ID" so please show me where I need to add an ID.
Can you show me the code on how to add a License ID?

**Comment by ihnatmoisieiev** [comment]
@barotbhavesh you don't need to include the license key in the code.

**Comment by barotbhavesh** [comment]
Okay thanks for the update.

**Comment by samulla** [comment]
then how does the license for highcharts work?

**Comment by samulla** [comment]
@ihnatmoisieiev
