### ISSUE TITLE
How to center align legends in multiple lines? 

### ISSUE THREAD

**Issue by intelligentsiatech** [highcharts/highcharts-ios#313]
I am having issue in center aligning legends for multiple lines. If I make legend.align = "center" it will center aligned first line and the second line starts from left or right side. Attached is the image of legends not aligning center. 
![Screenshot 2020-05-30 at 4 14 36 PM](https://user-images.githubusercontent.com/57785461/83326873-c6a65000-a290-11ea-87a5-fd17dcf80c33.png)

**Comment by ihnatmoisieiev** [comment]
Hello @intelligentsiatech,

Thanks for choosing Highcharts!

Thanks for the reporting. We are currently working on it. You can monitor a status here: https://github.com/highcharts/highcharts/pull/12478

**Comment by intelligentsiatech** [comment]
Thank you for your feedback. Can you give estimate of how much time will it take for next release where legends will all center aligned?

**Comment by ihnatmoisieiev** [comment]
@intelligentsiatech, unfortunately, I don't know the exact date. Maybe it will be released in a week or later.

**Comment by intelligentsiatech** [comment]
Hello @ihnatmoisieiev , I am waiting for this issue to be fixed, as I saw new release two hours ago does not include legend center aligned issue. Can you please tell me when this issue will be resolved?

**Comment by pawelfus** [comment]
Hi @intelligentsiatech 

We area actively working on that feature. There are some unexpected issues we are trying to sort out. Instead of postponing the release, we decided to introduce this in the next one. No ETA for the next release (as we just released new version). My apologies for the inconvenience! 

PS: Could you attach an image of the expected result? Thanks!

**Comment by intelligentsiatech** [comment]
![Screenshot 2020-06-23 at 4 26 01 PM](https://user-images.githubusercontent.com/57785461/85398202-4d87d900-b56e-11ea-82ea-444701d4aedb.png)
This should be the expected result for legends to be center aligned.

**Comment by pawelfus** [comment]
Thanks for the confirmation @intelligentsiatech - my apologies for the confusion, but the design you want to achieve is not part the scope of https://github.com/highcharts/highcharts/pull/12478 and it's not planned at this moment.

I prepared a plugin to achieve what you need, please take a look: https://jsfiddle.net/BlackLabel/84d3c0Lx/ - @ihnatmoisieiev could you provide implementation example in iOS wrapper? Thanks!

**Comment by ihnatmoisieiev** [comment]
@pawelfus sure. Example in iOS wrapper:

```
let options = HIOptions()

let chart = HIChart()
chart.events = HIEvents()
chart.events.render = HIFunction(jsFunction: "function() { var chart = this, legend = chart.legend; var lines = [], itemY = null, index = 0, legendWidth = legend.legendWidth; legend.allItems.forEach(function(item) { if (item._legendItemPos[1] === itemY) { lines[index].items.push(item); lines[index].width += item.itemWidth; } else { itemY = item._legendItemPos[1]; index = lines.push({ items: [item], y: itemY, width: item.itemWidth }) - 1; } }); lines.forEach(function(line) { var offset = (legendWidth - line.width) / 2; line.items.forEach(function(item) { item.legendGroup.attr({ translateX: offset + item._legendItemPos[0] }); }); }); }")
options.chart = chart

let legend = HILegend()
legend.borderWidth = 1
legend.alignColumns = false
options.legend = legend

let xAxis = HIXAxis()
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
options.xAxis = [xAxis]

let series1 = HISeries()
series1.data = [1, 2]
series1.name = "Series 1"

let series2 = HISeries()
series2.data = [11, 22]
series2.name = "Series long name"

let series3 = HISeries()
series3.data = [1, 2]
series3.name = "Series even longer name"

let series4 = HISeries()
series4.data = [11, 22]
series4.name = "Series 2"

let series5 = HISeries()
series5.data = [1, 2]
series5.name = "Series 3"

let series6 = HISeries()
series6.data = [1, 2]
series6.name = "Series 4"

let series7 = HISeries()
series7.data = [1, 2]
series7.name = "Series 4"

let series8 = HISeries()
series8.data = [1, 2]
series8.name = "Series 4"

options.series = [series1, series2, series3, series4, series5, series6, series7, series8]
```

**Comment by intelligentsiatech** [comment]
Thank you for your prompt response. It worked! Really appreciated.  
Closing this issue now.

**Comment by Javedmansuri1** [comment]
This is not suitable for non IOS wrapper 
I am facing this same issue with same above mentioned requirement for to align legend item to be centre when they are in multiple row
Could please help me How I can achieve this same in pie chart with legends ?

**Comment by Javedmansuri1** [comment]
@pawelfus Could you please help me ?

**Comment by Javedmansuri1** [comment]
Do we have any way for to show tooltip on legend hover  ?

I would like to display a tooltip when hovering over a legend, similar to how we see tooltips when hovering over a series in a pie chart.

**Comment by Javedmansuri1** [comment]
@pawelfus could you please help me on this ?
