### ISSUE TITLE
Webkit warning messages 

### ISSUE THREAD

**Issue by KarthikShiva97** [highcharts/highcharts-ios#314]
1) **Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service**
2) **[Process] kill() returned unexpected error 1**

These message are being logged too many times on the console and I think its slowing up the UI a little bit

**Comment by ihnatmoisieiev** [comment]
Hello @KarthikShiva97,

thanks for the reporting. 

Unfortunately, I can't reproduce these messages. Which version of the framework do you use?

**Comment by KarthikShiva97** [comment]
Highcharts version. -> 7.1.1
iOS version -> 13.3.1

**Comment by ihnatmoisieiev** [comment]
@KarthikShiva97 please update to the latest version `8.1.0`

**Comment by KarthikShiva97** [comment]
Ok thanks! I'll let you know if this issue persists after migrating
