### ISSUE TITLE
How can I add border between heat map cells? HIHeatMap does not have a border property and HIChart's plotBordercolour does not help 

### ISSUE THREAD

**Issue by KarthikShiva97** [highcharts/highcharts-ios#315]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/40565839/84132294-556e5600-aa63-11ea-8cbe-0a95f2baa8c8.png">

**Comment by ihnatmoisieiev** [comment]
Hello @KarthikShiva97,

please use `marker.lineWidth` and `marker.lineColor` for this.
