### ISSUE TITLE
HIDataLabels Y - NSNumber or NSString?

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#316]
After upgrading to 8.1.1 XCode complains that

`HIDataLabels.y` must be NSString, but the documentation says that it should be an NSNumber.

Changing the Y value to an NSString makes HIDataLabels not to work, changing the Y value back to an NSNumber makes it work again.

<img width="838" alt="Bildschirmfoto 2020-06-16 um 14 27 54" src="https://user-images.githubusercontent.com/12996815/84774098-a212dd80-afdd-11ea-9da7-6116d1757f5c.png">

y is declared as an NString, but that is obviously not correct as only an NSNumber value works fine:

<img width="731" alt="Bildschirmfoto 2020-06-16 um 14 41 29" src="https://user-images.githubusercontent.com/12996815/84775547-a63ffa80-afdf-11ea-9a94-743940386a5a.png">

<img width="455" alt="Bildschirmfoto 2020-06-16 um 14 48 09" src="https://user-images.githubusercontent.com/12996815/84776360-7f35f880-afe0-11ea-8039-12f9b1e4b3ed.png">

Any help please. Many thanks.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

thanks for the reporting! It will be fixed in the next release.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks. How safe is it to use v8.1.1 with an NSNumber for the Y value? We use the Y value property a lot in our code and wonder if we should better not upgrade to 8.1.1 for production.

**Comment by ihnatmoisieiev** [comment]
@skuske please don't update to 8.1.1 for production in this case. I hope 8.1.2 will be available soon.

**Comment by skuske** [comment]
Fixed in 8.1.2
