### ISSUE TITLE
Blue Square Box appear when app goes to background state and comes back on active state

### ISSUE THREAD

**Issue by intelligentsiatech** [highcharts/highcharts-ios#318]
Hi, I am facing issue that whenever we select some area from chart, it shows tooltip then I click on home button app goes to background state and then by clicking on app again the app comes to active state again, by doing these steps a Square box appear and does not go away until I refresh the chart. 
![Screenshot 2020-06-24 at 6 00 18 PM](https://user-images.githubusercontent.com/57785461/85561806-5b5c5d80-b645-11ea-9fd1-bb11dda7da1a.png)

Kindly provide any solution to it that blue square box should not appear in any state of app in chart. 

Regards.

**Comment by ihnatmoisieiev** [comment]
Hello @intelligentsiatech,

you can disable focus border. Please try to set `accessibility.keyboardNavigation.focusBorder.enabled` property to `false`.

**Comment by intelligentsiatech** [comment]
Yes, it worked. Thanks you for your prompt reply.
