### ISSUE TITLE
Heat map data goes out of bounds when zoomed

### ISSUE THREAD

**Issue by chetanzalake** [highcharts/highcharts-ios#32]
In Heat Map, is there anyway if I could manage to clip the data which is displayed out of bounds?
![img_1241](https://user-images.githubusercontent.com/19661519/30630830-cf54d4b2-9dff-11e7-93f8-4356a2e6965a.PNG)

**Comment by pawelfus** [comment]
Hi @chetanzalake 

Thank you for reporting the issue - this shouldn't happen. Could you follow our steps for reporting an issue and recreate this in jsFiddle? Thank you.

**Comment by chetanzalake** [comment]
@pawelfus : How can I do that? Please let me know the steps.

**Comment by pawelfus** [comment]
Hi @chetanzalake 

My apologies, I just noticed it is reported in highcharts-ios repository, not in the JS lib repo. Could you show your chart config?

**Comment by ihnatmoisieiev** [comment]
@chetanzalake can I close it?

**Comment by chetanzalake** [comment]
{
    
    HIGChartView *chartView = [[HIGChartView alloc] initWithFrame:CGRectMake(0, 30, view.frame.size.width, 400)];
    [chartView setClipsToBounds:YES];
    
    HIOptions *options = [[HIOptions alloc]init];
    
    HIChart *chart = [[HIChart alloc]init];
    chart.zoomType = @"xy";
    chart.type = @"heatmap";
    chart.marginTop = @20;
    chart.marginBottom = @120;
    chart.plotBorderWidth = @1;
    options.chart = chart;
    
    HITitle *title = [[HITitle alloc]init];
    title.text = @"";
    options.title = title;
    
    HIXAxis *xaxis = [[HIXAxis alloc]init];
    xaxis.categories = heatMapChartData.xAxisCategories;
    xaxis.title = [[HIXAxisTitle alloc]init];
    xaxis.title.text = heatMapChartData.attribute;
    
    
    if ([heatMapChartData.xAxisCategories count] > 0){
        if ([heatMapChartData.xAxisCategories.lastObject isKindOfClass:[NSNumber class]]){
            if(strcmp([heatMapChartData.xAxisCategories.lastObject objCType], @encode(double)) == 0){
                
                HIXAxisLabels *xAxisLabels = [[HIXAxisLabels alloc]init];
                xAxisLabels.format = @"{value:.5f}";
                xaxis.labels = xAxisLabels;
            }
        }else{
            if ([heatMapChartData.xAxisCategories.lastObject isKindOfClass:[NSString class]]){
                
                NSScanner *scanner = [NSScanner scannerWithString:heatMapChartData.xAxisCategories.lastObject];
                BOOL isDoubleVal = [scanner scanDouble:NULL] && [scanner isAtEnd];
                
                if (isDoubleVal){
                    HIXAxisLabels *xAxisLabels = [[HIXAxisLabels alloc]init];
                    xAxisLabels.format = @"{value:.5f}";
                    xaxis.labels = xAxisLabels;
                }
            }
        }   
    }
    HIYAxis *yaxis = [[HIYAxis alloc]init];
    yaxis.allowDecimals = @true;
    yaxis.categories = heatMapChartData.yAxisCategories;
    yaxis.title = [[HIYAxisTitle alloc]init];
    yaxis.title.text = heatMapChartData.yaxis_attribute;
    
    if ([heatMapChartData.yAxisCategories count] > 0){
        if ([heatMapChartData.yAxisCategories.lastObject isKindOfClass:[NSNumber class]]){
            if(strcmp([heatMapChartData.yAxisCategories.lastObject objCType], @encode(double)) == 0){
                
                HIYAxisLabels *yAxisLabels = [[HIYAxisLabels alloc]init];
                yAxisLabels.format = @"{value:.5f}";
                yaxis.labels = yAxisLabels;
            }
        }else{
            if ([heatMapChartData.yAxisCategories.lastObject isKindOfClass:[NSString class]]){
                
                NSScanner *scanner = [NSScanner scannerWithString:heatMapChartData.yAxisCategories.lastObject];
                BOOL isDoubleVal = [scanner scanDouble:NULL] && [scanner isAtEnd];
                
                if (isDoubleVal){
                    HIYAxisLabels *yAxisLabels = [[HIYAxisLabels alloc]init];
                    yAxisLabels.format = @"{value:.5f}";
                    yaxis.labels = yAxisLabels;
                }
            }
        }   
    }
    options.xAxis = @[xaxis];
    options.yAxis = @[yaxis];
    
    HILegend *legend = [[HILegend alloc]init];
    legend.align = @"right";
    legend.layout = @"vertical";
    legend.margin = @0;
    legend.verticalAlign = @"top";
    legend.y = @20;
    legend.symbolHeight = @200;
    options.legend = legend;
    
    HITooltip *tooltip = [[HITooltip alloc]init];
    tooltip.enabled = @false;
    options.tooltip = tooltip;
    
    HIExporting *exporting = [[HIExporting alloc]init];
    exporting.enabled = [NSNumber numberWithBool:false];
    
    HICredits *credits = [[HICredits alloc]init];
    credits.enabled = @false;
    
    HIHeatmap *heatmap = [[HIHeatmap alloc]init];
    heatmap.name = @"";
    heatmap.borderWidth = @1;
    heatmap.dataLabels = [[HIHeatmapDataLabels alloc]init];
    heatmap.dataLabels.enabled = @true;
    
    if ([heatMapChartData.seriesData count] > 0){
        if ([heatMapChartData.seriesData.lastObject isKindOfClass:[NSNumber class]]){
            if(strcmp([heatMapChartData.seriesData.lastObject objCType], @encode(double)) == 0){
                heatmap.dataLabels.format = @"{value:.2f}";
            }
        }
    }
    heatmap.dataLabels.color = [[HIColor alloc]initWithHexValue:@"000000"];
    heatmap.data = heatMapChartData.seriesData;
    
    options.credits = credits;
    options.series = @[heatmap];
    
    options.exporting = exporting;
    options.additionalOptions = @{@"colorAxis": @{
                                          @"min": @0,
                                          @"minColor": @"#FFFFFF",
                                          @"maxColor": @"#7cb5ec"
                                          }};
    
    chartView.options = options;
    
    [view.contentView addSubview:chartView];
    
    if (heatMapChartData.seriesData.count == 0){
        UILabel *label = (UILabel *)[view.contentView viewWithTag:1000];
        label.hidden = false;
        [view.contentView bringSubviewToFront:label];
    }
}


This is the attached code. Just let me know if I need to do any hanges in this.

**Comment by ihnatmoisieiev** [comment]
Did you try the latest 6.0.2 release?
