### ISSUE TITLE
Memory leak and High Memory usage 

### ISSUE THREAD

**Issue by KarthikShiva97** [highcharts/highcharts-ios#320]
**[LeaksHighChart.zip](https://github.com/highcharts/highcharts-ios/files/4869991/LeaksHighChart.zip)**

**Highcharts version -> 8.1.2 (Latest)**

Hello, we are a heavy user of HighCharts and we have been encountering app termination due to high memory usage. The reason for this is twofold,
1) There's a memory leak which has been demonstrated in the zip file attached.
2) The memory usage is very high. We show about 30 components in a single page. It takes about 2GB. This occupied memory does not show up in the app's memory but rather is denoted as "Other processes" by Xcode. You can try this out yourself by putting 30 views in a list and observing the memory usage.

**Memory usage screenshot**

<img width="1163" alt="79MB copy" src="https://user-images.githubusercontent.com/40565839/86476173-a4a65e80-bd63-11ea-816a-e811248b2a07.png">

**Memory leak screenshots (Please refer to them as you try out the demo project)**

<img width="272" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/40565839/86475625-aa4f7480-bd62-11ea-9d2b-d841b60fa158.png">
<img width="1291" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/40565839/86475636-af142880-bd62-11ea-96c9-da776871c135.png">
<img width="1143" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/40565839/86475640-b1768280-bd62-11ea-88cc-23ba5db51fd4.png">
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/40565839/86767350-78435880-c069-11ea-9941-9d78d7b88333.png">
<img width="269" alt="0x105228360" src="https://user-images.githubusercontent.com/40565839/86475650-b50a0980-bd62-11ea-8a54-5d95e3790a75.png">

**Comment by ihnatmoisieiev** [comment]
Hello @KarthikShiva97,
thanks for reporting. We will investigate the issue as soon as possible.

**Comment by ihnatmoisieiev** [comment]
@KarthikShiva97 the issue will be fixed in the next release.

**Comment by skuske** [comment]
@ihnatmoisieiev 

We are seeing the same issue. When can we expect the next release fixing this? Thanks.

**Comment by ihnatmoisieiev** [comment]
@skuske I don't know the final date, but it seems to be released the next week.

**Comment by KarthikShiva97** [comment]
@ihnatmoisieiev Is there a revised release date?

**Comment by ihnatmoisieiev** [comment]
@KarthikShiva97 the issue has been fixed in the latest release. Can I close it?
