### ISSUE TITLE
Xaxis labels event do not work

### ISSUE THREAD

**Issue by intelligentsiatech** [highcharts/highcharts-ios#321]
I am having a problem with events on xaxis labels. For example, if we have column chart, I want event click on "column bars" and click on "xaxis". Kindly provide information regarding this issue ASAP. 

Regards.

**Comment by ihnatmoisieiev** [comment]
Hello @intelligentsiatech,

please describe what do you mean about 

> click on "xaxis"

You can use `column.point.events.click` to get a click event. Please check an example at **HIFunction example** chapter from the [README](https://github.com/highcharts/highcharts-ios/blob/master/README.md).

**Comment by intelligentsiatech** [comment]
By click on xAxis, it means "xAxis.events.click". When we use column.point.events.click, it works fine by clicking on points. But xAxis.events.click does not work at all. When we click on xAxis on chart, the click does not trigger. Kindly provide any solution if any.

**Comment by pawelfus** [comment]
There's no such event in the Highcharts core. See related request in Highcharts repo: https://github.com/highcharts/highcharts/issues/13745 - you can vote for that feature bu adding thumbs-up reaction (👍 ) in https://github.com/highcharts/highcharts/issues/13745
