### ISSUE TITLE
Datalabels have no option of fontFamily in style

### ISSUE THREAD

**Issue by intelligentsiatech** [highcharts/highcharts-ios#322]
Hi, 

I am applying fontFamily in all of highCharts but I am having problem with font family in dataLabels. Other things like tooltip, legends, etc have style (i.e. HICSSOBJECT) but on dataLabels we have only "HIStyle", so HIStyle have no option of applying fontFamily. Please provide solution to this ASAP.

Regards.

**Comment by ihnatmoisieiev** [comment]
Hello @intelligentsiatech,

thank you for reporting the issue. I hope it will be fixed in the next release.

**Comment by intelligentsiatech** [comment]
Thank you for your prompt response. Please do make sure that it will be fixed in next release. Thanks.

**Comment by fahadbaigios** [comment]
Dear @ihnatmoisieiev ,

When will the next release coming? Can you guide about how many days are left for next release to come and please make sure that fontFamily added on dataLabels style. 

Thanks and Regards.

**Comment by ihnatmoisieiev** [comment]
Hello @fahadbaigios,

unfortunately, we don't have ETA for the next release at the moment. I can only assume that no sooner than 3-4 weeks.

**Comment by fahadbaigios** [comment]
Hi,

When is the release coming? Can you give estimate? I need data labels font solution immediately. Kindly let me know.

Regards.

**Comment by fahadbaigios** [comment]
Got workaround on this bug. If anyone faces this issue, use this:
chart.style = HICSSObject()
chart.style.fontFamily = "GE_Flow_Regular_0"

Giving chart -> font family implements globally on whole chart.

**Comment by ihnatmoisieiev** [comment]
@intelligentsiatech @fahadbaigios the issue has been fixed in the latest release. Can I close it?

**Comment by fahadbaigios** [comment]
Yes, Thank you for your help.
