### ISSUE TITLE
Dependency Wheel Diagram Data labels InLine and rotation issue

### ISSUE THREAD

**Issue by fahadbaigios** [highcharts/highcharts-ios#325]
Hi,

I am having problem with inlining data labels in dependency wheel and rotating of labels as well. I found code in jsFiddle of dependencywheel as follows:
dataLabels: {
            color: '#333',
            textPath: {
                enabled: true,
                attributes: {
                    dy: 5
                }
            },
            distance: 10
        }

JsFiddle URL = https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/dependency-wheel

I could not find any property "dy" in HISVGAttributes in iOS. Please let me know the solution ASAP. Reference image is as follows:

![Screenshot 2020-08-11 at 5 45 11 PM](https://user-images.githubusercontent.com/34839837/89899859-5014bf80-dbfc-11ea-96f8-ac1fab1d28fd.png)

I also want to rotate the labels because there is limited space to show labels. I want labels to show vertically (i.e. rotate).

Thanks and regards.

**Comment by fahadbaigios** [comment]
Please also suggest how can I enable connector to these data labels so that they show correctly.

**Comment by ihnatmoisieiev** [comment]
@fahadbaigios I've reported missing `dy` property of `HISVGAttributes` object. As a workaround, you can do it in the following way ([JS](https://jsfiddle.net/hmtd8ef9/)):

```
let chart = HIChart()
chart.events = HIEvents()
chart.events.render = HIFunction(jsFunction: "function () { this.series[0].nodes.forEach(point => { if (point.dataLabel && point.dataLabel.text) { point.dataLabel.text.attr({ dy: 5 }); } }); }")
options.chart = chart
```

**Comment by fahadbaigios** [comment]
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-08-12 at 14 15 12](https://user-images.githubusercontent.com/34839837/89997988-62e3ce80-dca6-11ea-802d-a2ccae0d96ca.png)

Thanks, this is what I want. But still problem persist, can you send another workaround to **rotate labels**? As you can see in image, some labels are cropped due to space limit.

**Comment by ihnatmoisieiev** [comment]
@fahadbaigios can you try to change `dy` value inside `render` function? For rotation you can use `rotation` property. Please chech API [docs](https://api.highcharts.com/ios/highcharts/Classes/HISVGAttributes.html#//api/name/rotation).

**Comment by fahadbaigios** [comment]
Please can you provide any workaround of rotating label also?

**Comment by ihnatmoisieiev** [comment]
@fahadbaigios unfortunately, I can't provide any other workaround at the moment. The issue has been already reported. Please check and subscribe https://github.com/highcharts/highcharts/issues/11115
