### ISSUE TITLE
Integration with Carthage not functional

### ISSUE THREAD

**Issue by fchauvin** [highcharts/highcharts-ios#327]
When using Highcharts via Carthage, it seems the platform `iOS` is not supported.

The following is printed by the console.

command:
`carthage update highcharts-ios --platform ios --no-use-binaries`

output: 
`Dependency "highcharts-ios" has no shared framework schemes for any of the platforms: iOS`

**Comment by ihnatmoisieiev** [comment]
Hello @fchauvin,

thanks for the reporting. We will investigate the issue as soon as possible.

**Comment by ihnatmoisieiev** [comment]
@fchauvin, unfortunately, we don't have any update at the moment. You can use other methods: Cocoapods, XCFramework, drag/drop the .framework file from [development](https://github.com/highcharts/highcharts-ios/tree/master/development/Highcharts.framework)/[release](https://github.com/highcharts/highcharts-ios/tree/master/release/Highcharts.framework) folder into your project.

**Comment by ihnatmoisieiev** [comment]
@fchauvin the issue has been fixed in the latest build.
