### ISSUE TITLE
Not able to set column background color

### ISSUE THREAD

**Issue by codal-jayeshk** [highcharts/highcharts-ios#328]
<img width="84" alt="Screenshot 2020-08-14 at 4 50 23 PM" src="https://user-images.githubusercontent.com/52558720/90245141-b9404100-de4f-11ea-8092-cde169fe8846.png">

Hello I am using the column chart and I am not able to set background color on it.

let column = HIColumn()
column.name = strUnIntentional
column.colors = ["#000000"]
column.data = [10,20,30]

**Comment by ihnatmoisieiev** [comment]
Hello @codal-jayeshk,
you should use `column.color` property instead of `column.colors` in this case. Please check API [docs](https://api.highcharts.com/ios/highcharts/Classes/HISeries.html#//api/name/color) before creating the issue.

**Comment by codal-jayeshk** [comment]
@ihnatmoisieiev also try with color but it is not working. can you guide me there is still have to add another color?

**Comment by ihnatmoisieiev** [comment]
@codal-jayeshk it works perfectly for me:

```
let options = HIOptions()

let chart = HIChart()
chart.type = "column"
options.chart = chart

let title = HITitle()
title.text = "Demo chart"
options.title = title

let series = HIColumn()
series.color = HIColor(uiColor: .yellow)
series.data = [49.9, 71.5, 106.4, 129.2, 144, 176, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [series]
```
