### ISSUE TITLE
ios 14 crash 

### ISSUE THREAD

**Issue by KarthikShiva97** [highcharts/highcharts-ios#329]
<img width="1009" alt="Pasted Graphic 17" src="https://user-images.githubusercontent.com/40565839/90369532-9305e580-e089-11ea-9af1-2b376973282b.png">

We have been facing crashes on iOS 14 Beta 1. I don't have any steps to reproduce since this occurs randomly. Will update If I find a pattern

**Comment by ihnatmoisieiev** [comment]
Hello @KarthikShiva97,
thanks for the reporting, but we're not supporting iOS 14 at the moment and we can't reproduce. If you will have steps, please update this topic.

**Comment by KarthikShiva97** [comment]
Isn't beta period the time to start testing and supporting iOS 14? A lot of people will upgrade to iOS 14 in a month's time. We don't want our customers to face any crashes when they upgrade to iOS 14. I still don't have the steps but I can assure you, that it happens from time to time

**Comment by ihnatmoisieiev** [comment]
@KarthikShiva97 we just checked and haven't got any crashes on officially released iOS 14.
Do you still able to reproduce the problem?

**Comment by KarthikShiva97** [comment]
@ihnatmoisieiev Yes, I can confirm that the crashes have disappeared in the GM version
