### ISSUE TITLE
Can't use lang.drillUpText property

### ISSUE THREAD

**Issue by thanhan123** [highcharts/highcharts-ios#33]
I want to localize the text of drill up button. I searched the api document and it show that i need to set text for lang.drillUpText property. I also created a lang object and set value for lang.drillUpText. But i can't find Highcharts.setOptions to set this "lang" object for it

**Comment by ihnatmoisieiev** [comment]
Hello @thanhan123,
thank you for your attention. Yes, it is correct. Unfortunately, it is not possible at the moment.

**Comment by ihnatmoisieiev** [comment]
Hi @thanhan123,
in the newest release you can modify language object. Firstly, create and set up `HILang` instance. Next, add it to your chartView:
```
let lang = HILang()
...
chartView.lang = lang
```

**Comment by ihnatmoisieiev** [comment]
@thanhan123 can I close this issue?

**Comment by thanhan123** [comment]
yes please close it, thank @ihnatmoisieiev
