### ISSUE TITLE
Custom series marker symbol - disable series does not grayscale symbol

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#330]
I am using a custom series marker symbol, and that works just fine as it should. 

However, if I hide the series from the chart, the marker symbol does not get grayscaled in the Legend, just as it does for the default marker symbols.

How can I get the custom marker symbol to grayscale in the Legend if the related series is hidden from the chart?

Many thanks for any help.

![grayscale](https://user-images.githubusercontent.com/12996815/90391279-25f44f00-e08d-11ea-987b-98775f0bd4b2.jpeg)

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

we prepared a workaround for you. Please try:

```
let chart = HIChart()
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: "function() { var r = this.renderer; var filter = r.definition({ tagName: 'filter', id: 'grayscale', children: [{ tagName: 'feColorMatrix', type: 'matrix', values: '0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0' }] }); const style = document.createElement('style'); style.textContent = ` .highcharts-legend-item-hidden image { filter: url(#grayscale); }`; document.head.append(style); }")
options.chart = chart
```

**Comment by skuske** [comment]
@ihnatmoisieiev 

What should I say? BRILLIANT! Works perfect. Many, many thanks!

**Comment by ihnatmoisieiev** [comment]
@skuske we also have reported it in main repo: https://github.com/highcharts/highcharts/issues/14066

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks. However, I see this as a (minor) bug and not necessarily as an additional feature ... ;o)

But thanks again for a working solution. Much appreciated. Great service, as always!
