### ISSUE TITLE
v8.2.0 - What happened to HIHour etc. and Xaxis.dateTimeLabelFormats ??? 

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#337]
The latest release causes trouble with `HIHour` and `Xaxis.dateTimeLabelFormats`:

<img width="1070" alt="Bildschirmfoto 2020-09-10 um 10 20 33" src="https://user-images.githubusercontent.com/12996815/92700624-5313e480-f34f-11ea-9b54-f5189305cebb.png">

<img width="1066" alt="Bildschirmfoto 2020-09-10 um 10 20 42" src="https://user-images.githubusercontent.com/12996815/92700638-57400200-f34f-11ea-974a-76bc17f5f9bc.png">

How do I set Xaxis `dateTimeLabelFormats` in v8.2.0?

It's a pain that fundamental things are changed without any information and without any documentation.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Could you please at least confirm that this is a bug or if we are missing something as we are now trying to get that working again for 5 hours. Thanks.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

thank you for the reporting. 

Please do not update to the latest release if these changes are destructive for you at the moment. I have reported it and will let you know what happened.

According to the newest JS [API](https://api.highcharts.com/highcharts/tooltip.dateTimeLabelFormats), `HIHour`, `HIDay`, etc. objects have been changed to `string` type. So, e.g. it's not needed to create a new `HIDay` object and set `main` property. Just set `day` property with `string` value.

About `axis.dateTimeLabelFormats`, I will let you know as soon as possible.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks for the update. I found out about `HIHour` etc. and that it now expects `NSString`. However, the missing `axis.dateTimeLabelFormats` is really critical. Hopefully you get that fixed asap as we wanted to use v8.2.0 due to the fixed memory issues.

**Comment by sebastianbochan** [comment]
Hi @skuske,
Thank you for reporting.

Due to unsuspected changes in the Highcharts core, some options disappeared. We are still debugging the problem and will fix it as soon as possible.

Thank you for your patience.

**Comment by skuske** [comment]
Any update on this? I see that the original issue has been fixed - when can I expect a fixed wrapper for iOS? Thanks! :o)

**Comment by pawelfus** [comment]
You can check the status in the linked PR, right above your post :) Right now, fix is awaiting review & merge.

**Comment by ihnatmoisieiev** [comment]
@skuske `axis.dateTimeLabelFormats` property has been reverted in the latest release.

**Comment by skuske** [comment]
Fixed. Thanks! :o)
