### ISSUE TITLE
Tooltip is not removed automatically when show drill down

### ISSUE THREAD

**Issue by thanhan123** [highcharts/highcharts-ios#34]
My app show a drill down, but the tooltip of the first chart still remain in the second chart ( as in image https://monosnap.com/file/OBc87b0oLcsbSRjW7Ur9UhgXO4VtBh). Do we have any way to remove this tooltip automatically?

**Comment by ihnatmoisieiev** [comment]
Hello @thanhan123,

currently you can hide tooltip using **events**

```
let events = HIChartEvents()
events.drilldown = "function (e) { this.tooltip.hide(); }"

chart.events = events
```
