### ISSUE TITLE
Warning "Failed to parse executable" during build

### ISSUE THREAD

**Issue by 7-plus-t** [highcharts/highcharts-ios#340]
When building a project using Highcharts iOS version 8.1.2 or 8.2.0 in Xcode 11.7, I get the following warning:
```
warning: ./Carthage/Build-Release/iOS/Highcharts.framework/com.highcharts.charts.bundle/highcharts.css: Failed to parse executable: Invalid read request. startingAt: 0, offsetBy: 0, typeSize: 4, dataSize: 1
```

Apparently the Xcode build gets irritated by the fact, that `highcharts.css` has the execute flag set:
`-rwxr-xr-x@  1 user  group     1 Sep 10 09:38 highcharts.css*`

When I manually remove the execute flag, the warning is gone. I suggest removing the flag unless there is a good reason for it?

**Comment by ihnatmoisieiev** [comment]
Hello @7-plus-t,

thanks for the reporting. We will investigate it as soon as possible and let you know.

**Comment by ihnatmoisieiev** [comment]
@7-plus-t this warning will be fixed in the next release.

**Comment by ihnatmoisieiev** [comment]
@7-plus-t the issue has been fixed in the latest release. Can I close it?

**Comment by 7-plus-t** [comment]
Updated and tested: works. Thanks for the fast support!
