### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by fchauvin** [highcharts/highcharts-ios#343]
With the recent support of binary targets, it would be great to have SPM support. This would offer an alternative to the currently broken Carthage integration, as well as utilizing 1st party dependency management tools.

Here is an example of another repo which vends an XCFramework and how it could potentially be done in highcharts:

https://github.com/plaid/plaid-link-ios/pull/8

**Comment by ihnatmoisieiev** [comment]
Hello @fchauvin,
I think thanks to Swift 5.3, we can add SPM support soon.

**Comment by ihnatmoisieiev** [comment]
@fchauvin SPM support has been added with the latest release v9.0.0. 
Can I close the issue?
