### ISSUE TITLE
v8.2.2: HIHour etc.

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#345]
What does

> Reverted HIMillisecond, HIWeek, HIHour, HIMonth, HISecond, HIYear, HIDay and HIMinute types.

in the Changelog of 8.2.2 mean in relation to

https://github.com/highcharts/highcharts-ios/issues/337 ?

Do we now have to revert all changes back prior to v8.2.0 ?

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

unfortunately, there was a bug in the `8.2.0` API of the main framework.

We apologies, please revert back your changes to use these types.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Oh, well - if I don't have to change it again for 8.2.3 ... ;o/
