### ISSUE TITLE
Crash when HIChartView is created from a storyboard.

### ISSUE THREAD

**Issue by Ferannor** [highcharts/highcharts-ios#35]
Since 1.01, all chart created in a storyboard crash the app with this stack : 

> ***
> 
>  Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter is nil'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x000000010cb181cb __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x000000010bd9cf41 objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000010cb8cb95 +[NSException raise:format:] + 197
> 	3   Foundation                          0x0000000105544506 +[NSJSONSerialization dataWithJSONObject:options:error:] + 99
> 	4   Highcharts                          0x0000000105b7e0ce -[HIGJavaScript JSObject:] + 52
> 	5   Highcharts                          0x0000000105b95e13 -[HIGHTML prepareOptions:] + 92
> 	6   Highcharts                          0x0000000105c98fe0 -[HIChartView loadChartWorker] + 1763
> 	7   Foundation                          0x00000001055a51ee __NSFireTimer + 83
> 	8   CoreFoundation                      0x000000010caa8374 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
> 	9   CoreFoundation                      0x000000010caa8032 __CFRunLoopDoTimer + 1026
> 	10  CoreFoundation                      0x000000010caa7bea __CFRunLoopDoTimers + 266
> 	11  CoreFoundation                      0x000000010ca9f604 __CFRunLoopRun + 2308
> 	12  CoreFoundation                      0x000000010ca9ea89 CFRunLoopRunSpecific + 409
> 	13  GraphicsServices                    0x0000000110cbf9c6 GSEventRunModal + 62
> 	14  UIKit                               0x000000010832ed30 UIApplicationMain + 159
> 	15  you                                 0x0000000101db9f94 main + 196
> 	16  libdyld.dylib                       0x000000010e34bd81 start + 1
> )

>

**Comment by ihnatmoisieiev** [comment]
Hello @Ferannor,
thank you. I will report it.

**Comment by ihnatmoisieiev** [comment]
Hello @Ferannor,
I have checked and it works perfect for me. It seems that you didn't set up **options** for your chart.

**Comment by Ferannor** [comment]
I'm in a case where a chart appear when an async request finished. So indeed, the chart has no option before that. But having a crash is a little rough. Better print a console warning no?

**Comment by ihnatmoisieiev** [comment]
@Ferannor, ok. Thank you. It will be fixed.

**Comment by ihnatmoisieiev** [comment]
@Ferannor It is fixed in the newest 6.0.2 release.

**Comment by ihnatmoisieiev** [comment]
@Ferannor can I close this issue?
