### ISSUE TITLE
How can I increase tooltip label font and remove legend name from tooltip 

### ISSUE THREAD

**Issue by bcsezer** [highcharts/highcharts-ios#350]
<img width="264" alt="Ekran Resmi 2020-12-04 16 07 16" src="https://user-images.githubusercontent.com/24293237/101167417-e5740d80-364a-11eb-9adf-7fae49929319.png">

I wanto increase date font and remove Scrap - Shredded.. part

**Comment by ihnatmoisieiev** [comment]
Hello @bcsezer,

you can adjust [`headerFormat`](https://api.highcharts.com/ios/highcharts/Classes/HITooltip.html#//api/name/headerFormat) and [`pointFormat`](https://api.highcharts.com/ios/highcharts/Classes/HITooltip.html#//api/name/pointFormat) properties from [`HITooltip`](https://api.highcharts.com/ios/highcharts/Classes/HITooltip.html) object.
