### ISSUE TITLE
Nothing happens when I press the export button.

### ISSUE THREAD

**Issue by bcsezer** [highcharts/highcharts-ios#351]
Nothing happens when I press the export button. But the button disappears and the chart is not responding any finger movements. 

Before I click Export button : 
![Simulator Screen Shot - iPhone 8 - 2020-12-07 at 16 25 11](https://user-images.githubusercontent.com/24293237/101356195-c83c7a80-38a8-11eb-9534-4e788f971981.png)

and after click : 
![Simulator Screen Shot - iPhone 8 - 2020-12-07 at 16 25 47](https://user-images.githubusercontent.com/24293237/101356280-dee2d180-38a8-11eb-9260-400075e6313d.png)

when I long pressed the chart this view appear : 
![Simulator Screen Shot - iPhone 8 - 2020-12-07 at 16 26 47](https://user-images.githubusercontent.com/24293237/101356357-020d8100-38a9-11eb-9365-708a1b92c7af.png)

here is my code : 

        let exporting = HIExporting()
        exporting.accessibility = HIAccessibility()  
        options.exporting = exporting

also my page can be scrolled. Maybe the problem is caused by this I don't know

**Comment by ihnatmoisieiev** [comment]
Hello @bcsezer,

did you set [`chartView.viewController`](https://api.highcharts.com/ios/highcharts/Classes/HIChartView.html#//api/name/viewController) property?

**Comment by bcsezer** [comment]
yes I set in viewDidLoad   chartView.viewController = self

**Comment by ihnatmoisieiev** [comment]
@bcsezer in this case please share your chart configuration options, because export button works for me.

![Screen-Recording-2020-12-08-at-1](https://user-images.githubusercontent.com/11294008/101472194-8a8f2e80-3948-11eb-880a-47fd6ae0592c.gif)

**Comment by bcsezer** [comment]
//MARK: - HIChartViewDelegate
        
        func chartViewDidLoad(_ chart: HIChartView!) {
            print("Did load chart ")
        }
@IBOutlet weak var chartView: HIChartView!
    let options = HIOptions()
 override func viewDidLoad() {
        super.viewDidLoad()

        self.chartView.delegate = self
        self.chartView.viewController = self
        loadPricesFromService(ID: choosenPriceModel.sharedInstance.priceID, language: languageCheking())
    
       
        // Do any additional setup after loading the view.
    }

    func configureChartView(name:String,date:[String],data:[Double]){
//        chartView.plugins = ["line"]
        
    
        let title = HITitle()
        title.text = ""
        options.title = title
        
        let chart = HIChart()
        chart.plotBackgroundImage = "https://www.steelorbis.com/so/img/cmn/highchart-orbital-watermark.png"
        
        options.chart = chart
        let credits = HICredits()
        credits.text = "SteelOrbis"
        
        options.credits = credits
      
     
//        let exporting = HIExporting()
//        exporting.enabled = options.exporting as? NSNumber
//        options.exporting = exporting
        let exporting = HIExporting()
        exporting.enabled = false
        exporting.accessibilityRespondsToUserInteraction = true
        
        options.exporting = exporting
       
        
        let yAxis = HIYAxis()
        yAxis.title = HITitle()
        yAxis.title.text = NSLocalizedString("yAxis", comment: "")
        options.yAxis = [yAxis]

        let xAxis = HIXAxis()
        xAxis.showFirstLabel = true
        xAxis.showLastLabel = true
        
        xAxis.title = HITitle()
        xAxis.title.text = NSLocalizedString("xAxis", comment: "")

        xAxis.categories = date
        options.xAxis = [xAxis]
        
        let pricesSeries = HISeries()
      
        pricesSeries.name = detailUrunBasligi.text
        pricesSeries.data = dailyAvgPriceDoubleArray.reversed()


        options.series = [pricesSeries]
        
        let plotOptions = HIPlotOptions()
        
        plotOptions.series = HISeries()
        plotOptions.series.marker = HIMarker()
        plotOptions.series.label = HILabel()
        
        plotOptions.series.label.connectorAllowed = true
        
        plotOptions.series.marker.enabled = false
        plotOptions.series.color = HIColor(hexValue: "EE5525")
    
        options.plotOptions = plotOptions
        let tooltip = HITooltip()
        tooltip.useHTML = true
        tooltip.headerFormat = "<big>{point.key}</big>"
        options.tooltip = tooltip
      

        let responsive = HIResponsive()
        let rules = HIRules()
        rules.condition = HICondition()
        rules.condition.maxWidth = 413
        rules.chartOptions = [
            
          "legend": [
             "layout": "horizontal",
             "align": "left",
             "verticalAlign": "bottom"
          ]
        ]
    
        responsive.rules = [rules]
        options.responsive = responsive
        
        self.chartView.options = options
       

    }

**Comment by ihnatmoisieiev** [comment]
@bcsezer I see that you set `exporting.enabled ` to `false`. Please remove all exporting configuration.

Working demo:

```
let options = HIOptions()

let chart = HIChart()
chart.type = "column"
options.chart = chart

let title = HITitle()
title.text = "Demo chart"
options.title = title

let series = HIColumn()
series.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [series]

chartView.options = options

chartView.viewController = self
```

**Comment by bcsezer** [comment]
Okay I removed.

**Comment by ihnatmoisieiev** [comment]
@bcsezer please try example above.

**Comment by bcsezer** [comment]
when i tried the example it worked. What is the problem with my code

**Comment by ihnatmoisieiev** [comment]
@bcsezer unfortunately, I can't build your code.

The export button also works for the demo that you shared above:
```
let chartView = HIChartView(frame: view.bounds)
chartView.plugins = ["series-label"]

let options = HIOptions()

let title = HITitle()
title.text = "Solar Employment Growth by Sector, 2010-2016"
options.title = title

let subtitle = HISubtitle()
subtitle.text = "Source: thesolarfoundation.com"
options.subtitle = subtitle

let yAxis = HIYAxis()
yAxis.title = HITitle()
yAxis.title.text = "Number of Employees"
options.yAxis = [yAxis]

let xAxis = HIXAxis()
xAxis.accessibility = HIAccessibility()
xAxis.accessibility.rangeDescription = "Range: 2010 to 2017"
options.xAxis = [xAxis]

let legend = HILegend()
legend.layout = "vertical"
legend.align = "right"
legend.verticalAlign = "middle"
options.legend = legend

let plotOptions = HIPlotOptions()
plotOptions.series = HISeries()
plotOptions.series.label = HILabel()
plotOptions.series.label.connectorAllowed = false
plotOptions.series.pointStart = 2010
options.plotOptions = plotOptions

let installation = HISeries()
installation.name = "Installation"
installation.data = [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]

let manufacturing = HISeries()
manufacturing.name = "Manufacturing"
manufacturing.data = [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]

let salesDistribution = HISeries()
salesDistribution.name = "Sales & Distribution"
salesDistribution.data = [11744, 17722, 16005, 19771, 20185, 24377, 32147, 39387]

let projectDevelopment = HISeries()
projectDevelopment.name = "Project Development"
projectDevelopment.data = [NSNull(), NSNull(), 7988, 12169, 15112, 22452, 34400, 34227]

let other = HISeries()
other.name = "Other"
other.data = [12908, 5948, 8105, 11248, 8989, 11816, 18274, 18111]

options.series = [installation, manufacturing, salesDistribution, projectDevelopment, other]

let responsive = HIResponsive()
let rules = HIRules()
rules.condition = HICondition()
rules.condition.maxWidth = 500
rules.chartOptions = [
  "legend": [
     "layout": "horizontal",
     "align": "center",
     "verticalAlign": "bottom"
  ]
]
responsive.rules = [rules]
options.responsive = responsive

chartView.options = options
chartView.viewController = self

self.view.addSubview(chartView)
```

<img width="484" alt="Screenshot 2020-12-09 at 14 09 16" src="https://user-images.githubusercontent.com/11294008/101634351-d913fa00-3a28-11eb-8661-1dd06a3e863b.png">

Please share your code in the same format, so I can build & run it.

**Comment by bcsezer** [comment]
Hello. the problem is the image I put in the chart background

 chart.plotBackgroundImage = "https://www.steelorbis.com/so/img/cmn/highchart-orbital-watermark.png"

when delete this line it works.

**Comment by ihnatmoisieiev** [comment]
@bcsezer it's also happening for me while setting `chart.plotBackgroundImage`.

Please try to set your local `UIImage` using base64:

```
let image = UIImage(named: "imageName")!
let imageData = image.pngData()!
let base64Image = "data:image/png;base64," + imageData.base64EncodedString(options: Data.Base64EncodingOptions.lineLength64Characters)
chart.plotBackgroundImage = base64Image
```

**Comment by bcsezer** [comment]
Thank you for your time. It worked.

**Comment by ihnatmoisieiev** [comment]
@bcsezer can I close the issue?

**Comment by bcsezer** [comment]
Yes. Thank you
