### ISSUE TITLE
Legends are wrongly rendered when using custom font

### ISSUE THREAD

**Issue by unreg-rea** [highcharts/highcharts-ios#355]
Hello, 
Thanks for great library!

I am using Highcharts v8.2.2 in my iOS project. But when applying custom fonts, the legends are wrongly rendered at very first time, the space between legend items is calculated incorrectly. At the second time, rendering is working correctly.

First time rendering:
![Screen Shot 2021-01-04 at 11 18 06](https://user-images.githubusercontent.com/3985013/103500799-c2718f00-4e7e-11eb-9cb0-2fa824f85727.png)

Second time rendering:
![Screen Shot 2021-01-04 at 11 22 23](https://user-images.githubusercontent.com/3985013/103500905-2b590700-4e7f-11eb-9870-c28031137acc.png)

**Comment by ihnatmoisieiev** [comment]
Hello @unreg-rea,

Thanks for choosing Highcharts!

Could you please share a simple demo so I can reproduce the issue?

**Comment by unreg-rea** [comment]
Hello @ihnatmoisieiev,

I have create an example which reproduces the problem. Source code is attached below. You can see the screenshots: First image is the 1st rendering and second one is on other render times.

![Simulator Screen Shot - iPhone 11 - 2021-01-08 at 17 42 16](https://user-images.githubusercontent.com/3985013/104006585-460de180-51d9-11eb-9bd2-014014727ccb.png)

![Simulator Screen Shot - iPhone 11 - 2021-01-08 at 17 42 21](https://user-images.githubusercontent.com/3985013/104006615-4d34ef80-51d9-11eb-8cf0-438069e493bc.png)

Source code: 
[HighchartsDemo.zip](https://github.com/highcharts/highcharts-ios/files/5786716/HighchartsDemo.zip)

Thanks!

**Comment by ihnatmoisieiev** [comment]
@unreg-rea I'm able to reproduce the issue with your demo. Thank you for the reporting! We will investigate the problem as soon as possible.
