### ISSUE TITLE
how can i set to zoom in level when chart load initially.

### ISSUE THREAD

**Issue by pruharikantamipara** [highcharts/highcharts-ios#356]
Hello i need to set zoom in default when my chart is initially loading. i have attached screenshot for better understanding. one screenshot is default chart loading & second is zoom in using pinch zoom. so i required same zoom in level without pinch zoom.

![Default Chart](https://user-images.githubusercontent.com/51121784/106444041-3f564f80-64a3-11eb-9f48-cd94e5d3ac14.png)

![required zoom in chart](https://user-images.githubusercontent.com/51121784/106444073-467d5d80-64a3-11eb-9576-1b42f7fe3b10.png)

**Comment by ihnatmoisieiev** [comment]
Hello @pruharikantamipara,
you can achieve that by setting extremes after your chart is finished loading, eg.

```
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: "function () { this.xAxis[0].setExtremes(min, max); }")
```

Just replace `min` and `max` with proper values.

**Comment by pruharikantamipara** [comment]
thank you for the help me. i have set above code and working fine. but is there any way to set zoom level without getting min max value from console?

**Comment by ihnatmoisieiev** [comment]
@pruharikantamipara you can use any values you need. Please check [API](https://api.highcharts.com/ios/highcharts/Classes/HIXAxis.html#) of `setExtremes` method.

**Comment by pruharikantamipara** [comment]
can you please provide me the demo code for  `setExtremes`.

**Comment by ihnatmoisieiev** [comment]
@pruharikantamipara sure.

```
chart.events.load = HIFunction(jsFunction: "function () { this.xAxis[0].setExtremes(0, 5); }")
```

and on `HIXaxis` or `HIYAxis` object:

```
let xAxis = chart.options.xAxis.first!
 
xAxis.setExtremes()
xAxis.setExtremes(0)
xAxis.setExtremes(0, newMax: 5)
xAxis.setExtremes(0, newMax: 5, redraw: false)

let animation = HIAnimationOptionsObject()
animation.duration = 0
xAxis.setExtremes(0, newMax: 5, redraw: false, animation: animation)
```

**Comment by pruharikantamipara** [comment]
Hello @ihnatmoisieiev can you please check this out.

let chartView = HIChartView(frame: CGRect(x: 0.0, y: 0.0, width: cell.chartView.bounds.width - 20, height: cell.chartView.bounds.height - 20))
        chartView.plugins = ["boost"]
        //chartView.zoomOut()
        chartView.sizeToFit()
        
        let options = HIOptions()

        let chart = HIChart()
        //chart.zoomType = "y"
        chart.type = "area"
                
        chart.resetZoomButton = HIResetZoomButton()
        chart.resetZoomButton.position = HIAlignObject()
        chart.resetZoomButton.position.y = -100
        
        chart.events = HIEvents()
        chart.events.selection = HIFunction(closure: { context in
            guard let context = context else { return }
            let min = context.getProperty("event.yAxis[0].min")!, max = context.getProperty("event.yAxis[0].max")!
            print("yAxis min: \(min), yAxis max: \(max)")
        }, properties: ["event.yAxis[0].min", "event.yAxis[0].max"])
        options.chart = chart
        
        
        let boost = HIBoost()
        boost.enabled = true
        boost.useGPUTranslations = true
        options.boost = boost
        
        let plotOptions = HIPlotOptions()
        plotOptions.area = HIArea()
        plotOptions.series = HISeries()

        boost.allowForce = true
        boost.seriesThreshold = 2
        plotOptions.area.boostThreshold = 1000

        let exporting = HIExporting()
        exporting.enabled = false
        options.exporting = exporting // hide contact menu
        
        let navigation = HINavigation()
        navigation.buttonOptions = HIButtonOptions()
        navigation.buttonOptions.symbolStroke = HIColor(rgba: 236, green: 112, blue: 38, alpha: 0.4)
        navigation.buttonOptions.theme = HITheme()
        navigation.buttonOptions.theme.fill = HIColor(rgba: 0, green: 0, blue: 0, alpha: 0.0)
        options.navigation = navigation
        options.navigation.enabled = false
                
        let credits = HICredits()
        credits.enabled = false
        options.credits = credits // hide highchart weburl
                
        let title = HITitle()
        title.text = ""//"US and USSR nuclear stockpiles"
        options.title = title

        let subtitle = HISubtitle()
        subtitle.text = ""
        options.subtitle = subtitle
        
        let xaxis = HIXAxis()
        xaxis.tickColor = HIColor(rgba: 236, green: 112, blue: 38, alpha: 0.0)
        xaxis.lineColor = HIColor(rgba: 236, green: 112, blue: 38, alpha: 0.3)
        xaxis.type = "datetime"
        xaxis.dateTimeLabelFormats = HIDateTimeLabelFormats()
        
        xaxis.title = HITitle()
        xaxis.title.text = ""
        xaxis.labels = HILabels()
        xaxis.labels.style = HICSSObject()
        xaxis.labels.style.color = "rgb(236, 112, 38)"
        xaxis.labels.style.textOutline = "10px Arial"
                
        let yAxis = HIYAxis()
        yAxis.lineColor = HIColor(rgba: 236, green: 112, blue: 38, alpha: 0.3)
        yAxis.lineWidth = 1
        yAxis.gridLineWidth = 0
        yAxis.title = HITitle()
        yAxis.title.text = ""
        yAxis.labels = HILabels()
        yAxis.labels.enabled = true

        plotOptions.series.cursor = "pointer"
        plotOptions.series.point = HIPoint()
        plotOptions.series.point.events = HIEvents()

        plotOptions.area.fillColor = HIColor(linearGradient: ["x1": 0, "y1": 0, "x2": 0, "y2": 1], stops: [[0, "rgba(236,112,38, 0.90)"], [1, "rgba(236,112,38, 0.20)"]])

        plotOptions.area.marker = HIMarker()
        plotOptions.area.marker.enabled = false
        plotOptions.area.marker.symbol = "circle"
        plotOptions.area.marker.radius = 1
        plotOptions.area.marker.states = HIStates()
        plotOptions.area.marker.states.hover = HIHover()
        plotOptions.area.marker.states.hover.enabled = true

        plotOptions.series.point.events.click = HIFunction(jsFunction: "function (e) { hs.htmlExpand(null, { pageOrigin: { x: e.pageX || e.clientX, y: e.pageY || e.clientY }, headingText: this.series.name, maincontentText: Highcharts.dateFormat('%e %b %Y', this.x) + ':<br/> ' + this.y + ' visits', width: 300 }); }")
        plotOptions.series.marker = HIMarker()
        plotOptions.series.marker.lineWidth = 2

        let usa = HIArea()
        usa.showInLegend = false // hide chart buttton
        usa.name = ""
        usa.color = HIColor(rgb: 236, green: 112, blue: 38)

let maxValue =  self.mutArr[0].array!.map({ $0["price"].doubleValue}).max()
        let newMaxValue = NSNumber(value: maxValue!)
        print(("Maximum Value:",newMaxValue))

        let minValue =  self.mutArr[0].array!.map({ $0["price"].doubleValue}).min()
        let newMinValue = NSNumber(value: minValue!)
        print(("Minimum Value:",newMinValue))

var data: [Any] = []

data = [["08/02 09:04", 15094.8], ["08/02 09:09", 15064.3], ["08/02 09:14", 15064.3], ["08/02 09:19", 15085.75], ["08/02 09:24", 15090.15], ["08/02 09:29", 15098.7], ["08/02 09:34", 15087.5], ["08/02 09:39", 15086.85], ["08/02 09:44", 15096.5], ["08/02 09:49", 15105.2], ["08/02 09:54", 15096.05], ["08/02 09:59", 15092.8], ["08/02 10:04", 15103.7], ["08/02 10:09", 15110.15], ["08/02 10:14", 15103.25], ["08/02 10:19", 15103.3], ["08/02 10:24", 15103.25], ["08/02 10:29", 15119.65], ["08/02 10:34", 15126.5], ["08/02 10:39", 15121.35], ["08/02 10:44", 15125.95], ["08/02 10:49", 15117.3], ["08/02 10:54", 15115.85], ["08/02 10:59", 15113.85], ["08/02 11:04", 15114.55], ["08/02 11:09", 15124.45], ["08/02 11:14", 15114.8], ["08/02 11:19", 15116.25], ["08/02 11:24", 15105.75], ["08/02 11:29", 15105.25], ["08/02 11:34", 15118.6], ["08/02 11:39", 15126.0], ["08/02 11:44", 15114.1], ["08/02 11:49", 15109.25], ["08/02 11:54", 15118.3], ["08/02 11:59", 15112.9], ["08/02 12:04", 15108.55], ["08/02 12:09", 15098.8], ["08/02 12:14", 15091.2], ["08/02 12:19", 15075.3], ["08/02 12:24", 15068.7], ["08/02 12:29", 15072.65], ["08/02 12:34", 15097.9], ["08/02 12:39", 15108.1], ["08/02 12:44", 15112.65], ["08/02 12:49", 15111.9], ["08/02 12:54", 15106.85], ["08/02 12:59", 15104.15], ["08/02 01:04", 15110.45], ["08/02 01:09", 15110.45], ["08/02 01:14", 15124.55], ["08/02 01:19", 15114.05], ["08/02 01:24", 15117.2], ["08/02 01:29", 15117.2], ["08/02 01:34", 15118.25], ["08/02 01:39", 15115.4], ["08/02 01:44", 15110.75], ["08/02 01:49", 15119.55], ["08/02 01:54", 15122.4], ["08/02 01:59", 15144.0], ["08/02 02:04", 15143.85], ["08/02 02:09", 15148.0], ["08/02 02:14", 15138.15], ["08/02 02:19", 15157.3], ["08/02 02:24", 15137.05], ["08/02 02:29", 15140.9], ["08/02 02:34", 15143.7], ["08/02 02:39", 15138.85], ["08/02 02:44", 15131.15], ["08/02 02:49", 15127.6], ["08/02 02:54", 15116.9], ["08/02 02:59", 15111.6], ["08/02 03:04", 15107.35], ["08/02 03:09", 15110.65], ["08/02 03:14", 15116.2], ["08/02 03:19", 15111.7], ["08/02 03:24", 15123.8], ["08/02 03:29", 15129.45], ["08/02 03:34", 15115.8], ["08/02 03:39", 15115.8], ["08/02 03:44", 15115.8], ["08/02 03:49", 15115.8], ["08/02 03:54", 15115.8], ["08/02 03:59", 15115.8], ["08/02 04:04", 15115.8], ["08/02 04:09", 15115.8], ["08/02 04:14", 15115.8]]

usa.data = data
options.chart = chart
options.xAxis = [xaxis]
options.yAxis = [yAxis]
options.plotOptions = plotOptions
options.series = [usa]
chartView.options = options

after i call below code

Example 1 - Not working, when i set dynamic value then it will not working

-> chart.events.load = HIFunction(jsFunction: "function () { this.yAxis[0].setExtremes(\(newMinValue), \(newMaxValue); }")

Example 2 - working when i pass direct value

-> chart.events.load = HIFunction(jsFunction: "function () { this.yAxis[0].setExtremes(13960.83175803403, 14730.39697542533); }")


Example 3 - not working

let yAxis = chartView.options.yAxis.first!
let animation = HIAnimationOptionsObject()
animation.duration = 0
yAxis.setExtremes(3873.145780051153, newMax: 19637.85166240409, redraw: true, animation: animation)

Example 4 - not working

let yAxis = chartView.options.yAxis.first!
let animation = HIAnimationOptionsObject()
animation.duration = 0
 yAxis.setExtremes(newMinValue, newMax: newMaxValue, redraw: true, animation: animation)

**Comment by pruharikantamipara** [comment]
Hello @ihnatmoisieiev
 i have tired last solution  `xAxis.setExtremes(min, max: 5, redraw: false)` but isn't work well. 

so i try with this code `chart.events.load = HIFunction(jsFunction: "function () { this.xAxis[0].setExtremes(min, max); }")` and its working fine.

**Comment by ihnatmoisieiev** [comment]
@pruharikantamipara when you need to get it on init, use `chart.events.load = HIFunction(jsFunction: "function () { this.xAxis[0].setExtremes(min, max); }")`.

**Comment by pruharikantamipara** [comment]
Hello @ihnatmoisieiev my query resolved.  i do not have any query now. thank you.
