### ISSUE TITLE
 architecture arm64

### ISSUE THREAD

**Issue by bcsezer** [highcharts/highcharts-ios#359]
Hi, I change my computer to Mac mini m1. I was able to use pod on my previous  macOS without any problems. After I clone my project I start to get "ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/x/Desktop/xyz/Pods/Highcharts/development/Highcharts.framework/Highcharts' for architecture arm64" error. I try pod deintagrate, uninstall and install. But it keeps showing this error.

**Comment by ihnatmoisieiev** [comment]
Hello @bcsezer,
do you use Cocoapods?
I have just tried and can't reproduce the issue.

Could you please try again with the latest v9.0.0 release?

**Comment by skuske** [comment]
That is an M1 architecture specific issue and affects not just Highcharts. Google is full of M1 and Xcode simulator specific issues. Here's just one for example: https://developer.apple.com/forums/thread/667156

**Comment by skuske** [comment]
We also have an M1 Mac mini here and due to all those issues we decided to keep our old Mac mini for debugging.

**Comment by YuriFuze** [comment]
I was able to build it by setting Excluded Architectures in the project target Build Settings.
use "Any iOS Simulator SDK" and set arm64 as excluded (to both debug and release).
Do the same in the pod project!

**Comment by cjohn001** [comment]
Hello together, I have the same problem, like described here.  I just tried to port the higcharts nativescript plugin

https://github.com/NativeScript/nativescript-ui-charts

to apple silicon. The problem arising can to all what I read only be solved if the highcharts plugin is build as a universal binary. Could you please provide an updated cocopad? Thanks a lot guys! @YuriFuze, does the approach you sketched than still allow you to run in arm64 mode? Or can you just link the binary? I would expect that it than can only run wit Rosetta2 ?

**Comment by ihnatmoisieiev** [comment]
https://github.com/highcharts/highcharts-ios/issues/379#issuecomment-969090818
