### ISSUE TITLE
How to change the Highcharts timezone from UTC to local in iOS?

### ISSUE THREAD

**Issue by chetanzalake** [highcharts/highcharts-ios#36]
I have a timezone on one of the axis, but the time is converted into UTC timeZone, but I want it to convert it in local timeZone in iOS.
Please let me know how can I do that. I have seen there is a class name HIGlobal, but I am not able to set options using HIGlobal instance.

**Comment by ihnatmoisieiev** [comment]
Hello @chetanzalake,
thank you for your question. Unfortunately, it is not possible at the moment.

**Comment by ihnatmoisieiev** [comment]
Hi @chetanzalake,
in the newest release you can modify global options. Firstly, create and set up `HIGlobal` instance. Next, add it to your `chartView`:

```
let global = HIGlobal()
...
chartView.global = global
```

**Comment by ihnatmoisieiev** [comment]
@chetanzalake can I close this issue?

**Comment by chetanzalake** [comment]
Sorry, I didn’t try this yet. I will update once done. 
--
Regards,
Chetan Zalake
Senior Software Engineer
Great Software Laboratory
+91 20 4670 2438
+91 992 111 1280
