### ISSUE TITLE
PDF Export special character issue

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#365]
I am using special characters in a chart to mark highs and lows in a HIPlotBand. The characters are

⤒ (UPWARDS ARROW TO BAR Unicode: U+2912, UTF-8: E2 A4 92)

and 

⤓ (DOWNWARDS ARROW TO BAR Unicode: U+2913, UTF-8: E2 A4 93)

When I export the chart as a PNG, the characters show up as they should:

<img width="892" alt="png-export" src="https://user-images.githubusercontent.com/12996815/113662354-3868da80-96a8-11eb-9121-1f693cc07ec8.png">

However, when I export to PDF the arrows are not showing up in the PDF:

<img width="891" alt="no-arrows" src="https://user-images.githubusercontent.com/12996815/113662471-7665fe80-96a8-11eb-9efa-0188503f7ca5.png">

It seems to be a font type bug. I tested this on different devices, but the problem is always the same.

Any help?

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

thank you. The issue is reported here: https://github.com/highcharts/highcharts/issues/15454

**Comment by ihnatmoisieiev** [comment]
https://github.com/highcharts/highcharts/issues/15454#issuecomment-1092707742
