### ISSUE TITLE
Map related Graphs 

### ISSUE THREAD

**Issue by Ranga321** [highcharts/highcharts-ios#369]
How to implement map related graphs like Point Map, Choropleth Map and Bubble Map ?  
If this library supports these graphs please provide any demo.

Thanks in Advance...!

**Comment by ihnatmoisieiev** [comment]
Hello @Ranga321,
you can find all iOS demos [here](https://www.highcharts.com/demo/ios).

**Comment by chennaranganath965** [comment]
![Screenshot 2021-07-09 at 2 48 12 PM](https://user-images.githubusercontent.com/44457067/125055336-b2a06500-e0c4-11eb-812c-3124918bdb5e.png)
but there is no this kind of map related graph

**Comment by ihnatmoisieiev** [comment]
@chennaranganath965 you have attached the example from `Highcharts Maps Library`. Unfortunately, this library is not available on iOS.

**Comment by chennaranganath965** [comment]
Thanks for respose 🙂
