### ISSUE TITLE
iOS developer: change the color?

### ISSUE THREAD

**Issue by tanvohuynh** [highcharts/highcharts-ios#37]
https://monosnap.com/file/ePAN3xiciSso6ZJBiWi7zAp4gnzKSI
above image, How to change this color of the line?thanks for sharing

**Comment by ihnatmoisieiev** [comment]
Hello @tanvohuynh,
you can change this color by setting **gridLineColor** param of your Y-axes, e.g.

`yAxis.gridLineColor = HIColor(name: "red")`

**Comment by tanvohuynh** [comment]
perfect, thanks
