### ISSUE TITLE
How to change the language used by Highcharts?

### ISSUE THREAD

**Issue by andrija-ostojic** [highcharts/highcharts-ios#370]
I have gone through the documentation but nothing works for me. I need to change the labels for weekdays form English to my native language. Documentation for HILang says: 

> HILang Class Reference => Language object. The language object is global and it can’t be set on each chart initialization. Instead, use Highcharts.setOptions to set it before any chart is initialized. js Highcharts.setOptions({ lang: { months: [ 'Janvier', 'FÃ©vrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'AoÃ»t', 'Septembre', 'Octobre', 'Novembre', 'DÃ©cembre' ], weekdays: [ 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi' ] } });

But I cannot access this setOptions() function. There is no Highcharts singleton with global settings that I can access, there is only Highcharts module. I can't find this HILang object anywhere, not in HIChartView, not in HIChart, not in HIOptions, is there even a way to do it?

**Comment by ihnatmoisieiev** [comment]
Hello @andrija-ostojic,

thanks for choosing Highcharts!

Just create a `HILang` object, set up and set it to your `HIChartView` before setting `HIOptions` object.

```
let lang = HILang()
...
chartView.lang = lang


let options = HIOptions()
...
chartView.options = options
```

Please let us know if it works for you.

https://github.com/highcharts/highcharts-ios/issues/33
https://github.com/highcharts/highcharts-ios/issues/65

**Comment by andrija-ostojic** [comment]
Thank you, this worked out fine!
