### ISSUE TITLE
Tap Function issue

### ISSUE THREAD

**Issue by dev766** [highcharts/highcharts-ios#371]
I am using your framework in my iOS Swift app.
Is there any “Tap” function for column chart, when user tap’s on bar in column charts.
Need to get the data on which column user has tapped.
I have implemented some tap function but it is not working for me.
Looks like it works on tapping on the 'hoverer box' rather than the column.

Here is the code below which I used for tap function:

let closure: HIClosure = { context in
print("Chart clicked!")
print(chart.getParams())
}
chart.events = HIEvents()
chart.events.click = HIFunction(closure: closure)
options.chart = chart

Any example or any pointers please.

**Comment by ihnatmoisieiev** [comment]
Hello @dev766,

did you try a **HIFunction example** from the [README](https://github.com/highcharts/highcharts-ios#readme)?

Also please check 
https://github.com/highcharts/highcharts-ios/issues/154
 https://github.com/highcharts/highcharts-ios/issues/106
 https://github.com/highcharts/highcharts-ios/issues/100
 https://github.com/highcharts/highcharts-ios/issues/44

**Comment by dev766** [comment]
thank you issue is solved now
