### ISSUE TITLE
HIAnimationOptionsObject : Undefined symbol: _OBJC_CLASS_$_HIAnimationOptionsObject

### ISSUE THREAD

**Issue by reena129** [highcharts/highcharts-ios#373]
When i use let animation = HIAnimationOptionsObject()
i get error :  
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_HIAnimationOptionsObject", referenced from:
      objc-class-ref in GenerateHorizontalBarChart.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

pod 'Highcharts', '~> 9.0.1' 

Below is my code : 

`        let animation = HIAnimationOptionsObject()
            animation.duration = 0
            chart.animation = animation
    `

**Comment by ihnatmoisieiev** [comment]
Hello @reena129,

unfortunately, I can't reproduce your issue using `9.1.2` version. 

Here you can find a simple demo:

```
let options = HIOptions()

let chart = HIChart()
chart.type = "column"
options.chart = chart

let title = HITitle()
title.text = "Demo chart"
options.title = title

let plotOptions = HIPlotOptions()
plotOptions.series = HISeries()
let animation = HIAnimationOptionsObject()
animation.duration = 0
plotOptions.series.animation = animation
options.plotOptions = plotOptions

let series = HIColumn()
series.data = [49.9, 71.5, 106.4, 129.2, 144, 176, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [series]
```

Please try to update to the latest version and let us know.

**Comment by reena129** [comment]
Have update latest version and now it's working.
Thanks u
