### ISSUE TITLE
How to set fix x-Axis & y-Axis in highCharts Barchart for swift

### ISSUE THREAD

**Issue by reena129** [highcharts/highcharts-ios#374]
I use Highcharts in my ios app. I make horizontal column chart with 2 y-Axis (top & bottom) I want to set static xAxis & yAxis value. How can i set? I want to below static values :

xAxis :[text1,text2,text3,text4,text5]

yAxis (at top) : [0,200,400,600,800,1000]

yAxis (at bottom) : [text1,text2,text3,text4]

Have try with setting min & max value but not get the result. I am not able to set String value for yAxis at bottom

Pls suggest.

**Comment by ihnatmoisieiev** [comment]
@reena129 please check Highcharts iOS Demos here: https://www.highcharts.com/demo/ios

**Comment by vijayradke** [comment]
@ihnatmoisieiev Could you please check and guide me on - https://github.com/highcharts/highcharts-ios/issues/375
