### ISSUE TITLE
MultiDepth 3D Pie Chart in iOS

### ISSUE THREAD

**Issue by zayantharani** [highcharts/highcharts-ios#376]
3D Pie charts are working fine. However, I am looking for multi-depth
 pie chart where depth should be dependent on the data value. 
Tried a lot of options but nothing seems to work. 
I'm attaching a picture of the expected output

![Screenshot 2021-09-15 at 6 35 19 PM](https://user-images.githubusercontent.com/20544146/133443639-4eb14d51-8d13-4791-b9fa-e0ae75f4657c.png)

**Comment by MuhammadAhmed1994** [comment]
I also need the same behavior is there any solution for implementing it? please guide
