### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#380]
Memory leak in WKContentView, can be reproduced by any sample project.

<img width="1195" alt="memoryleak" src="https://user-images.githubusercontent.com/12996815/142590711-151abb90-eb02-4c92-9e78-ca986f52b759.png">

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
thank you for the reporting.
Could you please add more info how to reproduce a memory leak?
We will investigate it as soon as possible.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Well, create a simple test project with a Highcharts view, start it, switch to 'Debug navigator' in Xcode, then click on 'Profile in Instruments'. You'll notice the leak in the leak list.

**Comment by ihnatmoisieiev** [comment]
@skuske 

Hello! Could you please check if the issue is actual, because I can't reproduce it at the moment. Thank you!

**Comment by skuske** [comment]
@ihnatmoisieiev

I'll do that asap.

**Comment by skuske** [comment]
Issue seems to have disappeared. I'll close now.
