### ISSUE TITLE
Export methods no longer working

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#383]
I was working with v8.2.2 in one of my projects, and the export methods (`exportToCSV`, `exportToPNG`, and `exportToPDF`) work fine there.

After upgrading to v9.3.1 all of the export methods stopped working. Actually the `exportToCSV` only works when you call it once, next time it does not work. Even restarting the app will not fix that. I have no idea in which version of the framework this issue appeared first.

`exportToPNG`, and `exportToPDF` do not work at all in v9.3.1, `exportToPNG` only works sometimes.

**Comment by ihnatmoisieiev** [comment]
@skuske thank you for the reporting. We will check export methods.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

the issue has been fixed in the latest release. 
Please try and let us know. 
Thank you!

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks, everything seems to be working again.

**Comment by skuske** [comment]
I am re-opening this issue because the 'Export to PDF' method does not work. Actually it does not do anything at all.

**Comment by ihnatmoisieiev** [comment]
@skuske the issue has been fixed in the latest release.
Please try and let us know.
Thank you!

**Comment by skuske** [comment]
@ihnatmoisieiev 

Everything seems to be working fine now. :o)

**Comment by skuske** [comment]
Re-opeing this due to https://github.com/highcharts/highcharts-ios/issues/396

**Comment by ihnatmoisieiev** [comment]
@skuske can I close the issue?
