### ISSUE TITLE
Unable to Integrate Highcharts in android studio arctic fox gradle version 4.2.2

### ISSUE THREAD

**Issue by Navnath1989** [highcharts/highcharts-ios#385]
No cached version of com.highsoft.highcharts:highcharts:7.0.3 available for offline mode.
Disable Gradle 'offline mode' and sync project

Please give me steps to start integration hightchartin my android project.

Thanks & Regards,
Navnath.

**Comment by ihnatmoisieiev** [comment]
Hello @Navnath1989,
please create an issue in the [proper repository](https://github.com/highcharts/highcharts-android).
Thank you!
