### ISSUE TITLE
Cannot have a control over scroll

### ISSUE THREAD

**Issue by baagii-tmcn** [highcharts/highcharts-ios#388]
Hello, I am trying to make a graph view with setExtremes and load part by part as client scroll over it. 

`
let scrollablePlotArea = HIScrollablePlotArea()
scrollablePlotArea.minWidth = 500
scrollablePlotArea.scrollPositionX = 1

xAxis.events.afterSetExtremes = HIFunction(closure: { context in
          guard let context = context
                let currentMin = context.getProperty("event.min") as? Double else {return}
                let currentMax = context.getProperty("event.max") as? Double
                let dataMin = context.getProperty("event.dataMin") as? Double
                let dataMax = context.getProperty("event.dataMax") as? Double
          
          if ( Double(xAxis.min!) > Double(dataMin!)) { print("Fetch new data MIN")
              xAxisRangeStep = xAxisRangeStep + 3600000
              xAxis.max = NSNumber(value: (tempDateMax.max()! * 1000) - xAxisRangeStep + 10800000)
              xAxis.min = NSNumber(value: (tempDateMax.max()! * 1000) - xAxisRangeStep)

              xAxis.setExtremes(((tempDateMax.max()! * 1000) - xAxisRangeStep) as NSNumber, newMax: (tempDateMax.max()! * 1000 - xAxisRangeStep + 10800000) as NSNumber)
              chartView.redraw()
          }
      
      }, properties: ["event.min", "event.max", "event.dataMin", "event.dataMax"])
`

The issue is there is no control over when to trigger a new set of xAxis.min, xAxis.max and, xAxis.setExtremes. 
Are there any other events to handle this? 

Thank you for your support.

**Comment by baagii-tmcn** [comment]
Hello, 

This code works but automatically moves without any user action. What I want to achieve is user scroll and load new data. 
Or at least in a simple way, limit visibility on loaded data.

**Comment by ihnatmoisieiev** [comment]
Ok, I think there is no any issues to call `xAxis.setExtremes` after your new data will be fully loaded or I misunderstand something?

**Comment by baagii-tmcn** [comment]
The issue is with xAxis.events.afterSetExtremes is not the right choice to make this task. 

And even without scroll and load, loaded data is ~43000, visibility range when the first load is ~4300. 
But it is not achievable by setting xAxis.min, xAxis.max and setExtremes

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn could you please prepare some test configuration options and data? So, we can check and suggest something.
Thank you!

**Comment by baagii-tmcn** [comment]
Dear 

I cut code into minimal and only related to the issue and put sample data CSV too into the shared link folder. 

[https://drive.google.com/drive/folders/1KKOGaV8GjoVCJKkxpmMvCMvkke5Yji4M?usp=sharing](url) 

Thank you very much. I am sorry for the inconvenience

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn unfortunately I can't run your code, because there is no `Sensor` and `TemperatureHumidData` classes.

According to your comment [here](https://github.com/highcharts/highcharts-ios/issues/388#issuecomment-1035952960):

> Or at least in a simple way, limit visibility on loaded data.

Did you try to set `xAxis.min` and `xAxis.max`? What do you mean "limit visibility on loaded data"?

**Comment by baagii-tmcn** [comment]
I just copied the screenshot video on the shared folder. This video represents what the code creates. 
During a video there is no touch on the screen, it is automatically moving backward.

**Comment by baagii-tmcn** [comment]
I am looking for ways to solve the issue: 

`let mouseOverFunction = HIFunction(closure: {context in
        guard let context = context else { return }
          let dataMin = context.getProperty("event.dataMin") as? Double
          print("clickFunction")
          print(dataMin)
      }, properties: ["event.dataMin"])
      
      plotOptions.series.point.events.mouseOver = mouseOverFunction`
      
      for example, this should work. But dataMin is nil all the time when this triggers.

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn unfortunately mouse events are not working on mobile devices.

**Comment by baagii-tmcn** [comment]
> Did you try to set xAxis.min and xAxis.max? What do you mean "limit visibility on loaded data"?

Let's say if the loaded data is 100, I want to show the last 10 of them at once loaded and scroll the other 90. 

Originally I wanted to load 30 of 100, show the last 10 while scrolling through load others.

**Comment by baagii-tmcn** [comment]
> @baagii-tmcn unfortunately mouse events are not working on mobile devices.

The above code's dataMin is still nil even with click instead of mouseOver event

**Comment by baagii-tmcn** [comment]
It does not help. You can see panning is enabled in the code I sent to you if you open it.

**Comment by pawelfus** [comment]
Hi @baagii-tmcn 

Just to be on the same page, you said:
> This code works but automatically moves without any user action. What I want to achieve is user scroll and load new data.
> Or at least in a simple way, limit visibility on loaded data.

To limit the visibility on loaded data, you need to set `min` + `max` and enable `panning`. 

> It does not help. 

Could you please describe the issues with the solution from Ihnat? Thank you!

**Comment by baagii-tmcn** [comment]
Dear 

Let's say 100 data loaded 
`let chart = HIChart()
      chart.panning = HIPanning()
      chart.panning.enabled = true
      chart.panning.type = "x"
      chart.pinchType = "x"
      chart.type = "spline"
      options.chart = chart
      chart.zoomType = "x"

xAxis.min = 90
xAxis.max = 100

xAxis.setExtremes(90, newMax: 100)`

This limits only showing the last 10 and no scrollable option. Every time changing xAxis.min and xAxis.max only limiting visibility. What I want is able to scroll through loaded data with 10 data window.

**Comment by baagii-tmcn** [comment]
There are two ways I am trying to achieve this: 
(* example)
1. Load 30 data, show last 10 when graph loads. Load older data when the user scrolls to the first 10 loaded data and so on. 

2. Simple way: Load 100 data, show last 10 when graph loads. Scroll through loaded data

**Comment by baagii-tmcn** [comment]
I know it is HighStock and not available in IOS. But what I want to achieve is similar to this. 

https://www.highcharts.com/demo/stock/stock-tools-gui

https://www.highcharts.com/demo/stock/basic-line

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn we have just checked and it should work for you when you are scrolling with double touch (2 fingers). It will be better noticeable if you disable `zoomType`. If you want to have a single touch, you should set `tooltip.followTouchMove` to `false`.

Example demo options:


```
let options = HIOptions()

let chart = HIChart()
chart.type = "spline"
chart.pinchType = "x"
// chart.zoomType = "x"
chart.panning = HIPanning()
chart.panning.enabled = true
chart.panning.type = "x"
options.chart = chart

let xAxis = HIXAxis()
xAxis.min = 90
xAxis.max = 100
options.xAxis = [xAxis]

let tooltip = HITooltip()
tooltip.followTouchMove = false
options.tooltip = tooltip

let spline = HISpline()
spline.data = [99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
options.series = [spline]
```

https://user-images.githubusercontent.com/11294008/154250097-6b4db6b0-8915-40f0-8b9a-785dae6313fb.mov

**Comment by baagii-tmcn** [comment]
All it needed was adding "tooltip.followTouchMove = false"

**Comment by baagii-tmcn** [comment]
Thank you for your support. Coming back to the first issue is there is no way to trigger a custom function when scroll reaches the limit, is that right?

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn could you try something like that:

```
xAxis.events.afterSetExtremes = HIFunction(closure: { [weak self] context in
      guard let context = context,
            let currentMin = context.getProperty("event.min") as? Double,
            let currentMax = context.getProperty("event.max") as? Double,
            let dataMin = context.getProperty("event.dataMin") as? Double,
            let dataMax = context.getProperty("event.dataMax") as? Double else { return }
      
      let currentRange = currentMax - currentMin
      
      if currentMin - dataMin <= currentRange {
        self?.loadData(from: dataMin - 100, to: dataMax)
      }
    }, properties: ["event.min", "event.max", "event.dataMin", "event.dataMax"])
    
private func loadData(from: Double, to: Double) {
   let newData = getNewDataFromTheServer(from: from, to: to)
   chartView.options.series[0].setSeriesData(newData)
}
```

**Comment by baagii-tmcn** [comment]
Dear 

Thank you for your advice. 

`chartView.options.series = [graph1]
  chartView.options.series[0].setSeriesData(graph1.data)`

which is the right method? graph1 is let graph1 = HISpline()

Should I call self.view.addSubview(chartView) again or any other chatView.redraw() or chartView.reload()?
After changing data a graph disappeared.

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn you can use both:

1. `chartView.options.series[0].data = newData`
2. `chartView.options.series[0].setSeriesData(graph1.data)`

You shouldn't call any additional methods like self.view.addSubview(chartView) or chatView.redraw() or chartView.reload().

**Comment by baagii-tmcn** [comment]
I am not sure what is the reason behind it. But after setting new data a graph disappears but the plotline (my graph has plotline) shows.

**Comment by baagii-tmcn** [comment]
Dear 

No luck with the graph disappearing issue. 

`let graphNew = HISpline()
  graphNew.data = [[Any]]()
hartView.options.series[0].data = graphNew.data
//OR chartView.options.series[0].setSeriesData(graphNew.data)`

I tried with:

chartView.update(options)
chartView.redraw()
chartView.reload()
self.view.addSubview(chartView)

each and every combination of them. 

I don't really see where and what I am missing.

**Comment by baagii-tmcn** [comment]
The issue was related to the data. Not with the library. 

Thank you very much for your support. Keep it up.
