### ISSUE TITLE
hello,how to change the chart backgroundColor?

### ISSUE THREAD

**Issue by zhoupIT** [highcharts/highcharts-ios#39]
I use backgroundColor in DataSources.json,but it don't work.
```
        "title": "Calories (Eaten)",
        "subtitle": "",
         "source": "DataCaloriesIn",
         "unit": "kcal",
         "chartType": "spline",
         "icon": "ic_local_dining",
         "exporting": false,
         "backgroundColor":"#7cb5ec"
```

**Comment by ihnatmoisieiev** [comment]
@zhoupIT, you need to modify **chart** object

```
let chart = HIChart()
chart.backgroundColor = HIColor(hexValue: "7cb5ec")
```

**Comment by zhoupIT** [comment]
@ihnatmoisieiev thank you!And more,if i want to use gradient,use which param?

**Comment by ihnatmoisieiev** [comment]
`HIColor(linearGradient: ["x1": 0, "y1": 0, "x2": 0, "y2": 0.5], stops: [[0, "rgba(255,255,255, 0.75)"], [1, "rgba(255,255,255, 0.02)"]])`

**Comment by zhoupIT** [comment]
@ihnatmoisieiev thank you so much!
