### ISSUE TITLE
useUTC: false causes fatal error

### ISSUE THREAD

**Issue by baagii-tmcn** [highcharts/highcharts-ios#390]
The graph datetime is not matching the actual data. 
Therefore I needed to add this option:

`chart.events.load = HIFunction(jsFunction: "function () { Highcharts.setOptions({ global: { useUTC: false } }); }")`

But it causes following error:

"Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value"

Do I need to call it a different way?

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn did you initizialize a `chart.events` object: 
```
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: "function () { Highcharts.setOptions({ global: { useUTC: false } }); }")
```
?

I've just checked and it works for me.

**Comment by baagii-tmcn** [comment]
You are right. Sorry for bothering you with a simple mistake. Thank you very much!

**Comment by baagii-tmcn** [comment]
Thank you very much. BTW both of the solutions work. Do you care to explain the difference?

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn the last one is faster and correct.

**Comment by baagii-tmcn** [comment]
Got it. Thank you.
