### ISSUE TITLE
HIPoint missing x / y coordinates

### ISSUE THREAD

**Issue by shanselm-ergon** [highcharts/highcharts-ios#392]
Since version 9.3.x the x and y coordinates are missing in the HIPoint class, this time in iOS. 

Same issue got resolved for Android, see https://github.com/highcharts/highcharts-android/issues/212

in v9.2.2 https://github.com/highcharts/highcharts-ios/blob/v9.2.2/development/Highcharts.framework/Headers/HIPoint.h
line 23 and 27 are x and y coordinates.

in v9.3.0 https://github.com/highcharts/highcharts-ios/blob/v9.3.0/development/Highcharts.framework/Headers/HIPoint.h
x and y are missing.

**Comment by ihnatmoisieiev** [comment]
Hello @shanselm-ergon,
could you please send an example when you need to use `x, y` of `HIPoint`?

**Comment by 7-plus-t** [comment]
@ihnatmoisieiev 
I don't see how an example is relevant here. Please refer to: 
https://api.highcharts.com/class-reference/Highcharts.Point and https://github.com/highcharts/highcharts-android/issues/212 . The iOS implementation does currently not adhere to the API specification.

**Comment by ihnatmoisieiev** [comment]
@7-plus-t please check iOS API [docs](https://api.highcharts.com/ios/highcharts/Classes/HIPoint.html), there is no `x, y` fields.

**Comment by 7-plus-t** [comment]
@ihnatmoisieiev I assume the API docs are generated based on the faulty source code, which is missing the `x, y` fields?
Why should the iOS API be different from all the other platforms? Wouldn't you consider `x, y` coordinates relevant for a point? ;)

**Comment by shanselm-ergon** [comment]
The workaround with the `HIData` instead of `HIPoint` works for us, therefore the ticket can be closed. 

I also don't understand the inconsistency across the different APIs, `x` and `y` coordinates on a point would sound logical to me. In our case the Android and iOS chart implementation now differ, because one can use `HIPoint`, whereas the other must use `HIData`. I haven't seen anything related in the docs, therefore I thought it is a bug. 

@ihnatmoisieiev thanks for the suggestion of `HIData`, we go on with it.

**Comment by ihnatmoisieiev** [comment]
Hello @shanselm-ergon,
missing fields have been added in the [latest](https://github.com/highcharts/highcharts-ios/releases/tag/v10.0.0) release.
