### ISSUE TITLE
Gauge chart format in swift 

### ISSUE THREAD

**Issue by reena129** [highcharts/highcharts-ios#393]
Below is my code for gauge chart 

`
       
        func gaugeCHART()
        {
        let options = HIOptions()
     
        let chart = HIChart()
        chart.type = "gauge"
        chart.plotBorderWidth = 0
        chart.plotShadow = HICSSObject()
        chart.plotShadow.width = 0
        
        options.chart = chart
        
        options.credits.enabled = false
        
        let title = HITitle()
        title.text = ""
        options.title = title

        let pane = HIPane()
        pane.startAngle = -120
        pane.endAngle = 120
                                
        
        let background1 = HIBackground()
        background1.shape = "arc"
        background1.backgroundColor = HIColor(uiColor: UIColor.clear)
        background1.borderWidth = 0

        pane.background = [background1]
        
        options.pane = pane
        
        
        let yAxis = HIYAxis()
        yAxis.min = 0
        yAxis.max = 1000
        
        yAxis.minorTickInterval = "nil"

         yAxis.tickPixelInterval = 30
         yAxis.tickWidth = 0
         yAxis.tickPosition = "inside"
         yAxis.tickLength = 10
         yAxis.tickColor = HIColor(hexValue: "666")

        
        yAxis.labels = HILabels()
        yAxis.labels.step = 4
        
        yAxis.labels.style = HICSSObject()
        yAxis.labels.style.color = "darkgray"
        yAxis.labels.style.fontSize = "15"
        yAxis.labels.align = "center"
        
        yAxis.offset = -30
        
        let greenPlotBands = HIPlotBands()
        greenPlotBands.from = 0
        greenPlotBands.to = 500
        
        greenPlotBands.color = HIColor(linearGradient: ["x1": 0, "y1": 1, "x2": 0.5, "y2": 0], stops: [[0, "#ff0000"],[1,"#ffff00"]])
        greenPlotBands.thickness = 30
        
        
        let yellowPlotBands = HIPlotBands()
        yellowPlotBands.from = 500
        yellowPlotBands.to = 1000
        yellowPlotBands.color = HIColor(linearGradient: ["x1": 0.5, "y1": 0, "x2": 1, "y2": 1], stops: [[0,"#ffff00"], [1,"#00ff00"]])
        yellowPlotBands.thickness = 30
        
        yAxis.plotBands = [greenPlotBands,yellowPlotBands]
        
        options.yAxis = [yAxis]
        
        let speed = HIGauge()
        speed.name = "Good"
        
        let score : Int = Int(340.8)
        speed.data = [score]
        
        speed.tooltip = HITooltip()
        speed.showInLegend = true
        
        speed.dial = HIDial()
        speed.dial.radius = "60%"
        speed.dial.baseWidth = 20
        speed.dial.topWidth = 1
        speed.dial.baseLength = "3%"
        
        speed.dial.rearLength = "0%"
        
        speed.dial.backgroundColor = HIColor(uiColor: UIColor.gray)
        
        speed.pivot = HIPivot()
        speed.pivot.backgroundColor = HIColor(uiColor: UIColor.white)
        speed.pivot.borderWidth = 5
        speed.pivot.borderColor = HIColor(uiColor: UIColor.gray)
        speed.pivot.radius = 8
        let legend = HILegend()
        
        legend.layout = "vertical"
        legend.align = "center"
        legend.verticalAlign = "middle"
        legend.y = 70
        legend.floating = true
        options.legend = legend
        
        options.series = [speed]
        
        //Stop Animation
        let plotOptions = HIPlotOptions()
        plotOptions.series = HISeries()
        
        let animation = HIAnimationOptionsObject()
        animation.duration = 0
        plotOptions.series.animation = animation
        
        options.plotOptions = plotOptions
                
        chartView.options = options
        
        view.addSubview(chartView)
    }
`

I get the below output :

![Screenshot 2022-03-01 at 7 19 14 PM](https://user-images.githubusercontent.com/88645966/156183158-a80032a6-e248-4c9d-833a-0b14be60eb8c.png)

But i need same like below screen : 

![Screenshot 2022-03-01 at 7 24 06 PM](https://user-images.githubusercontent.com/88645966/156183226-49bdbbbe-9999-4410-b69b-43b090e646ff.png)

1. Rounded corner of arc
2. Same pivot & dial format
3. display rounded ticker 
ect .

**Comment by ihnatmoisieiev** [comment]
@reena129 please check [API](https://api.highcharts.com/ios/highcharts/) docs and example [demos](https://www.highcharts.com/demo/ios).

**Comment by reena129** [comment]
I follow this same API doc & demo but i can't find solution for rounded arc corner & dial

**Comment by ihnatmoisieiev** [comment]
@reena129 did you try [solidgauge](https://www.highcharts.com/demo/ios/gauge-activity)?

**Comment by reena129** [comment]
Yes i have try it but with HISolidgauge i am not able to set dial & pivot
