### ISSUE TITLE
HIStackLabels Alignment not working as expected.

### ISSUE THREAD

**Issue by vijayradke** [highcharts/highcharts-ios#394]
Hi Team, I need HIStackLabels to be aligned to right so I did below code,
 
```
let labels = HIStackLabels()
labels.enabled = true
labels.align = "right"
labels.formatter = HIFunction(jsFunction: "function() { return Highcharts.numberFormat(this.total, 1) + '%' ; }")
let stackLabelStyle = HICSSObject()
stackLabelStyle.color = "rgb(37, 55, 70)"
stackLabelStyle.fontFamily = "IBMPlexSans-Regular"
stackLabelStyle.fontSize = "14px" 
labels.style = stackLabelStyle
```

I am getting below result 

<img width="315" alt="Implemented" src="https://user-images.githubusercontent.com/6542056/157826446-c04a06a7-3bcb-41b1-b16e-c4e121dec4a9.png">

I need result as below (highlighted in red), how can I implemented?

<img width="247" alt="Expected" src="https://user-images.githubusercontent.com/6542056/157826565-4075f10c-0d8f-451e-921b-33ed45b6aaaf.png">

**EDIT:** After some research I found that when we added padding to HIStackLabels then labels will move towards right **but padding only works in .js not in iOS code.** Do you know how to set padding in iOS?

**Comment by vijayradke** [comment]
@ihnatmoisieiev  Could you please help me here? 
I also wanted to add click events on X-Axis Labels  (helpful, staff, checkout etc). How to achieve that?

**Comment by ihnatmoisieiev** [comment]
Hello @vijayradke,

> but padding only works in .js not in iOS code
could you please share this solution?

> add click events on X-Axis Labels (helpful, staff, checkout etc)
It seems like it requires an additional module that is not supported, but I will come back to you later about this.

**Comment by vijayradke** [comment]
@ihnatmoisieiev I found the solution to move stack labels on right side, I added below code for HIStackLabels and all labels moved to right side.
 `   labels.x = 1000`

Here is the result,

![Graph](https://user-images.githubusercontent.com/6542056/159643403-cd690ff4-707b-4ba9-8be5-65a8269ccf0e.JPG)

   
I have some questions here, 

- Is it correct way to move labels on right side?
- How to fix the overlapping of labels on graph?

**Comment by vijayradke** [comment]
@ihnatmoisieiev 

Here is padding solution

```
 stackLabels: {
          enabled: true,
          align: 'right',
          padding: 970,
          style: {
            fontSize: '0.75rem',
            fontWeight: 'normal',
            fontFamily: 'IBM Plex Sans',
            lineHeight: 18.2,
            textOutline: 'none',
            textDecoration: 'none',
            textTransform: 'none',
            fill: 'transparent',
            opacity: 100
          },
          format: '{total}%'
        }
```
