### ISSUE TITLE
followTouchMove update

### ISSUE THREAD

**Issue by baagii-tmcn** [highcharts/highcharts-ios#397]
Hello, 

I am trying to make followTouchMove option dynamic. 

By clicking on the graph, followTouchMove value changes true/false.

`plotOptions.series.point.events.click = HIFunction(closure: { (context) in
                print(tooltip.followTouchMove)
                if(tooltip.followTouchMove == false) {
                    tooltip.followTouchMove = true
                    options.tooltip = tooltip
                    self.chartView.update(options)
                }
                else {
                    let newOptions = options.copy() as! HIOptions
                    let newTooltip = options.tooltip
                    newTooltip?.followTouchMove = false
                    self.chartView.update(newOptions as! HIOptions)                    
                }
          })`

As you see, I tried 2 different methods. Both of them failed. 

The following line code replace with self.chartView.update(options) works. But it reloads the graph, which is not what I need. 

DispatchQueue.main.async { self.chartView.options = newOptions }

Am I missing some other settings?

**Comment by ihnatmoisieiev** [comment]
Hello @baagii-tmcn,
please check `update` method [docs](https://api.highcharts.com/ios/highcharts/Classes/HIChartView.html#//api/name/update:redraw:).
Just call `update` method with `redraw: false` arg: `update(options, redraw: false)`.

**Comment by baagii-tmcn** [comment]
The main issue is not related to redraw: false

tooltip.followTouchMove = true
options.tooltip = tooltip

then calling the below both changes value of tooltip.followTouchMove 

`self.chartView.update(options)` - this won't change anything except tooltip.followTouchMove value

`DispatchQueue.main.async { self.chartView.options = options }` - this changes tooltip.followTouchMove value and scroll/track options but it reloads the graph. 

`self.chartView.update(options, redraw: false)` - this freezes and clears all options, xAxis, yAxis, and, tooltip

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn ok, pls describe clearly what do you want to achieve, because I don't understand at the moment.
Thank you!

**Comment by baagii-tmcn** [comment]
I want to make a graph able to use one finger scroll and one finger tracking by changing tooltip.followTouchMove = false/true.

**Comment by baagii-tmcn** [comment]
Let me describe it more. 

`tooltip.followTouchMove = false` set false when a graph loads which makes able to touch-track by one finger sliding on the graph. 

But it will disable one-finger scrolling and only be able to scroll with two fingers. 

`plotOptions.series.point.events.click = HIFunction()` by triggering this function: 
 changing `tooltip.followTouchMove` value to true/false will enable/disable one-finger scrolling. 

That's what I want to achieve. Thank you.

**Comment by ihnatmoisieiev** [comment]
Is it not that you are looking for
https://github.com/highcharts/highcharts-ios/issues/388#issuecomment-1041364728
?

**Comment by baagii-tmcn** [comment]
#388  is static. I want to make it dynamic. 
`tooltip.followTouchMove = false` - able to one finger scroll, but no touch-track
`tooltip.followTouchMove = true` - able to touch-track

I want to make the following: 

`plotOptions.series.point.events.click = HIFunction(closure: { (context) in
                if(tooltip.followTouchMove == false) {
                    tooltip.followTouchMove = true
                    options.tooltip = tooltip
                    self.chartView.update(options, redraw: false)
                }
                else {
                    tooltip.followTouchMove = false
                    options.tooltip = tooltip
                    self.chartView.update(options, redraw: false)
                    
                }
          })` 

which changes the tooltip.followTouchMove value when the user taps on the graph. Value changes every time but it does not do what it is supposed to do. 

As I mentioned earlier `DispatchQueue.main.async { self.chartView.options = options }` instead of `                    self.chartView.update(options, redraw: false)` works but it reloads a graph.

**Comment by baagii-tmcn** [comment]
That's great. Thank you very much for your response. 

The above solution works well, but it disables the zoom. 

`chart.panning = HIPanning()
  chart.panning.enabled = true
  chart.panning.type = "x"
  chart.pinchType = "x"`

with   `chart.pinchType = "x"` whole graph has only one finger zoom. (no scroll, no tracking)
without `chart.pinchType = "x"` zooming not available. 

I suppose I am missing some other configuration.

**Comment by ihnatmoisieiev** [comment]
@baagii-tmcn 
if you want not to use `zoomBySingleTouch`:

```
let options = HIOptions()

let chart = HIChart()
chart.type = "line"
chart.panning = HIPanning()
chart.panning.enabled = true
chart.panning.type = "x"
chart.zoomBySingleTouch = false
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: "function() { Highcharts.addEvent(this, 'afterUpdate', function() { if (this.pointer) { this.pointer.followTouchMove = Highcharts.pick(this.options.tooltip.followTouchMove, true); } }) }")
options.chart = chart

let xAxis = HIXAxis()
xAxis.max = 5
xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
options.xAxis = [xAxis]

let tooltip = HITooltip()
tooltip.followTouchMove = true
options.tooltip = tooltip

let series = HILine()
series.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
series.point = HIPoint()
series.point.events = HIEvents()
series.point.events.click = HIFunction(jsFunction: "function() { const chart = this.series.chart; chart.update({ tooltip: { followTouchMove: !chart.options.tooltip.followTouchMove } }) }")
options.series = [series]
```

Example in [JS](https://jsfiddle.net/BlackLabel/qe8ymhc2/21).

**Comment by baagii-tmcn** [comment]
Thank you very much! It works like a charm.
