### ISSUE TITLE
Support for Mac Catalyst

### ISSUE THREAD

**Issue by MaJa1980** [highcharts/highcharts-ios#398]
Hello,

how is the status about adding Mac Catalyst support? 
(Yes i found the closed issue https://github.com/highcharts/highcharts-ios/issues/361)

Since you managed to create a xcframework the effort should not too huge?

Best, Martin

**Comment by MaJa1980** [comment]
No feedback here?

**Comment by ihnatmoisieiev** [comment]
Hello @MaJa1980,

thanks for asking. I will come back with an answer to you asap.

**Comment by MaJa1980** [comment]
Hi!

Do you have any news for me? We are using commercial license for our Mac product which we will replace soon by a Catalyst version. Without support for Catalyst we will need to exchange the library.

**Comment by ihnatmoisieiev** [comment]
Hello @MaJa1980,
Mac Catalyst support will be added in the next release soon.

**Comment by ihnatmoisieiev** [comment]
Hello @MaJa1980,
the latest [release](https://github.com/highcharts/highcharts-ios/releases/tag/v10.1.0) contains the build for Mac Catalyst. You can find it [here](https://github.com/highcharts/highcharts-ios/tree/master/MacCatalyst).

**Comment by ihnatmoisieiev** [comment]
@MaJa1980 the size of the framework. Most don't need it. 
Can I close the issue?

**Comment by ihnatmoisieiev** [comment]
Closing due to Mac Catalyst support is already added
