### ISSUE TITLE
HIGChartView doesn't react to autolayout updates.

### ISSUE THREAD

**Issue by Ferannor** [highcharts/highcharts-ios#4]
(Me again, sorry ^^°)
I've just discovered that HIGChartView doesn't react to autolayout updates. For example, I've put a HIGChartView in UITableViewCell. When a rotate my device, graph keep the previous width in the webview.

**Comment by ratka6** [comment]
I'll try to fix this today, but I need more info: did you set chartView in code or in XiB/Storyboard? I'm glad that you post this errors - we need feedback to improve our framework!

**Comment by Ferannor** [comment]
Yes I've created the view inside my storyboard. In fact, the problem is inside the webview. All content are fixed in px so when I rotate my device, the HIGChartView is resized but not the content inside the webview. 

For the moment, I've used a tricky method who reset the webview this an empty webpage then reload my creation chart method.

**Comment by mll** [comment]
Hi, we are close to publishing a new version that fixes the issue.

**Comment by dzmitry-sazanovich-epam** [comment]
Hi folks. I faced with the same issue. When are you going to publish a new version with the fix?

**Comment by mll** [comment]
This is fixed in 1.1.0
