### ISSUE TITLE
Add a new font in iOS

### ISSUE THREAD

**Issue by tanvohuynh** [highcharts/highcharts-ios#40]
Hi guy,
in my project, I added a new font file (example get from here: https://www.dropbox.com/s/stvismqcox9nsem/proxima.zip?dl=0). but when I try to change the font by title.style = ["font-family": "Proxima Nova Regular"], it's not work for me.
please show me how to do right way? 
thanks

**Comment by ihnatmoisieiev** [comment]
Hello @tanvohuynh,
unfortunately you can't use your own font.

**Comment by tanvohuynh** [comment]
thanks for your response
