### ISSUE TITLE
Incorrect architecture for release

### ISSUE THREAD

**Issue by Kelend** [highcharts/highcharts-ios#403]
The xcframework contains arm64 for simulator in the release portion of the binary.

`building for iOS, but linking in object file built for iOS Simulator, for architecture arm64`

Was able to downgrade to 10.0.0.1 and the architectures are correct in that build

Framework was downloaded / installed via cocoapods.

**Comment by ihnatmoisieiev** [comment]
Hello @Kelend,
thank you for the reporting. It will be fixed in the next release.

**Comment by ihnatmoisieiev** [comment]
Hello @Kelend,
could you pls try 10.2.1 version?

**Comment by Kelend** [comment]
Confirmed fixed in 10.2.1

**Comment by ihnatmoisieiev** [comment]
Closing due opening new issue: https://github.com/highcharts/highcharts-ios/issues/405
