### ISSUE TITLE
Compiling issue using .mm extension

### ISSUE THREAD

**Issue by alessioemireni** [highcharts/highcharts-ios#408]
When I change the extension file of AppDelegate from` .m `to `.mm` I have the compiling error below:

<img width="576" alt="Screenshot 2023-01-03 at 12 51 20" src="https://user-images.githubusercontent.com/9269526/210352313-d6070120-1125-45f5-8842-71ebd8133ff1.png">

The error seems to be similar to this one https://github.com/facebook/facebook-ios-sdk/issues/2140

Could you please check if we can apply a workaround or it is necessary a fix in this framework?

Thx

**Comment by ihnatmoisieiev** [comment]
Hello @alessioemireni,

thanks for your question.
Could you please describe when needed to have AppDelegate`.m` to `.mm` and why?
Looking forward to your response.

**Comment by alessioemireni** [comment]
Hi @ihnatmoisieiev ,
this is a prerequisites for react native applications if you want to enable the new turbo module architecture: https://reactnative.dev/docs/next/new-architecture-app-intro#ios---use-objective-c-mm-extension

If you read the issue linked above in my previous comment there is a good explanation.

Thank you

**Comment by ihnatmoisieiev** [comment]
@alessioemireni we are not supporting React Native officially at the moment, so we can't do such changes, sorry.
