### ISSUE TITLE
Using Carthage generates an error

### ISSUE THREAD

**Issue by danmunk** [highcharts/highcharts-ios#41]
Attempting to use with Carthage.  Added:
github "https://github.com/highcharts/highcharts-ios" >= 1.1.0

Running carthage update yields:
*** Skipped building highcharts-ios due to the error:
Dependency "highcharts-ios" has no shared framework schemes

**Comment by ihnatmoisieiev** [comment]
Hello @danmunk,
thank you. I will report it.

**Comment by siomon0330** [comment]
same problem here! please fix it...

**Comment by mll** [comment]
Hi @siomon0330 and  @danmunk . Try the newest 6.0.2 release.

**Comment by danmunk** [comment]
@mll Sorry, I'm still getting the same error with 6.0.2.

**Comment by mll** [comment]
@danmunk We are working to resolve the issue.

**Comment by iSachdeva** [comment]
@mll Is it possible to implement Sunburst chart in native swift iOS as of now?
What I can see is that chart.type doesn't support option of "sunburst". Please help to clarify this. Thanks.

**Comment by ihnatmoisieiev** [comment]
Hi @iSachdeva,
you can implement Sunburst chart. You only need to add `sunburst` plugin to your `HIChartView`, e.g.
```
chartView.plugins = ["sunburst"]
```
and your configured `HISunburst` series to options:
```
let sunburst = HISunburst()
...

hioptions.series = [sunburst]
```

**Comment by iSachdeva** [comment]
@ihnatmoisieiev  Thanks a lot. Its working now.

**Comment by ihnatmoisieiev** [comment]
@danmunk @siomon0330, carthage problem is fixed. First of all, clean the working carthage folders:
```
rm -rf ~/Library/Caches/org.carthage.CarthageKit
rm -rf Carthage
``` 
then run carthage update
```
carthage update --platform iOS
```

**Comment by ihnatmoisieiev** [comment]
@danmunk @siomon0330 can I close this issue?

**Comment by danmunk** [comment]
👍

**Comment by fchauvin** [comment]
I seem to be getting this issue while trying to install v8.1.2 via Carthage.

**Comment by ihnatmoisieiev** [comment]
@fchauvin could you please write what error do you receive?

**Comment by fchauvin** [comment]
@ihnatmoisieiev Of course, currently just trying to test the library however for Carthage I'm receiving the following when installing v8.1.2

```
Dependency "highcharts-ios" has no shared framework schemes for any of the platforms: iOS
```

**Comment by fchauvin** [comment]
@ihnatmoisieiev Would you like me to create a new issue for this?
