### ISSUE TITLE
Memory leaks, once again

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#416]
Create a simple test project with any kind of a HighChartView and you'll see these memory leaks in Xcode Instruments. It looks like 

`-[HIChartView setupWithFrame:]	`

leaks. Can you please investigate and offer a fix? Thanks!

![leaks](https://user-images.githubusercontent.com/12996815/228437568-83763cf6-ed5e-40ca-bc87-855fd63fdde4.png)

![leaks_1](https://user-images.githubusercontent.com/12996815/228437585-b9449cfb-7034-453e-978f-2bfbd1b5ee9e.png)

![leaks_2](https://user-images.githubusercontent.com/12996815/228437600-8d48fe80-debf-46e5-9162-43dc8ec4da55.png)

![leaks_3](https://user-images.githubusercontent.com/12996815/228437617-9d87a3a3-6c6c-46ef-b960-e578b71bef2a.png)

![leaks_4](https://user-images.githubusercontent.com/12996815/228437630-29b05b81-fa5a-446e-beed-a7bffbda9dd4.png)

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
we will investigate it asap. Thank you!

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
in the attachment, you can find a simple test project with a demo example from the readme.
Any Xcode tool(Memory Graph, Instruments, Analyze)  doesn't show any leaks.

Could you please provide more info about how to reproduce the leak step by step?

Thank you in advance.

[MemoryCheck.zip](https://github.com/highcharts/highcharts-ios/files/11304783/MemoryCheck.zip)

<img width="297" alt="Screenshot 2023-04-23 at 13 25 02" src="https://user-images.githubusercontent.com/11294008/233862640-73e9edb5-de26-4399-9d40-606e2b164aae.png">

<img width="396" alt="Screenshot 2023-04-23 at 13 25 35" src="https://user-images.githubusercontent.com/11294008/233862650-71d1f45c-6e0d-420a-9023-389fbeb8ad06.png">

<img width="293" alt="Screenshot 2023-04-23 at 13 26 06" src="https://user-images.githubusercontent.com/11294008/233862665-edfbc9ad-a27a-49e3-a45a-a0835733887c.png">

**Comment by skuske** [comment]
@ihnatmoisieiev 

I have attached a test project that shows the leaks:

[HighCharts-LeakTest.zip](https://github.com/highcharts/highcharts-ios/files/11306889/HighCharts-LeakTest.zip)

The zip file also contains a 'leaks.trace' file from instruments. Here are the screenshots showing the leaks:

<img width="1871" alt="leak_4" src="https://user-images.githubusercontent.com/12996815/233908231-c5b8ca41-256e-4a3e-9e01-36d0c3f20ee2.png">
<img width="1871" alt="leak_3" src="https://user-images.githubusercontent.com/12996815/233908241-3d7d4688-f463-4218-a77d-9b9f763a3404.png">
<img width="1869" alt="leak_2" src="https://user-images.githubusercontent.com/12996815/233908245-e0150ae8-7393-44f5-a45f-0b0a47e03397.png">
<img width="1867" alt="leak_1" src="https://user-images.githubusercontent.com/12996815/233908249-0d884809-b85b-4a6d-ab3e-7bc9eefd0dbc.png">

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,

I've reproduced the same behavior with the following simple code:

```
#import "ViewController.h"
#import <WebKit/WebKit.h>

@interface ViewController ()
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
  
    WKWebView *webView = [[WKWebView alloc] initWithFrame:CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height/2)];
}

@end
```

So, it means that it's not a Higcharts iOS or core Highcharts JS framework specific issue.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks, I'll close the issue.
