### ISSUE TITLE
How to hidden the exporting? iOS OC

### ISSUE THREAD

**Issue by PankeGao** [highcharts/highcharts-ios#42]
I set "exporting.enabled = @false;" but it does not work;
and I set other parameters , they can work;

in simulator 6s(11.0.1)

**Comment by ihnatmoisieiev** [comment]
Hello @PankeGao,
have you added **exporting** to yours **options** `options.exporting = exporting` ?

**Comment by PankeGao** [comment]
yes,i did .but it did not work;
the following is the code:

{
       HIExporting * exporting = [[HIExporting alloc] init];

        exporting.enabled = @false;//does not work
        exporting.buttons = [[HIExportingButtons alloc] init];
        exporting.buttons.contextButton = [[HIExportingButtonsContextButton alloc] init];
        exporting.buttons.contextButton.symbol = @"triangle";//works
        exporting.buttons.contextButton.align = @"left";//works
        exporting.buttons.contextButton.enabled = @false;//does not work

       options.exporting = exporting
}

attribute such as "symbol"、“align” can work;but  "exporting.enabled" and "exporting.buttons.contextButton.enabled" can not work; 
I just want to hide the exporting button;
Could you test this attribute and show me the code? Thanks.

**Comment by ihnatmoisieiev** [comment]
If you want just hide the exporting button, you only need to set export **enabled** param to **false**:

```
HIExporting *exporting = [[HIExporting alloc] init];
exporting.enabled = false;

options.exporting = exporting;
```

See [https://github.com/highcharts/highcharts-ios/issues/25]().

**Comment by PankeGao** [comment]
I write like that, but it did not work in iOS; I used highcharts.framework

**Comment by ihnatmoisieiev** [comment]
Please check your code one more time. It works perfect for me.

**Comment by PankeGao** [comment]
I just copy the code from '' https://www.highcharts.com/ios/demo/line-basic'' and add  ''HIExporting * exporting = [[HIExporting alloc] init];   exporting.enabled = @false;'' but it did not work;  the following is my code and the result(in simulator 6s 11.0.1):
- (void)viewDidLoad {
    [super viewDidLoad];
    
    HIChartView *chartView = [[HIChartView alloc] initWithFrame:self.view.bounds];
    
    HITitle *title = [[HITitle alloc]init];
    title.text = @"Monthly Average Temperature";
    title.x = @-20;
    
    HISubtitle *subtitle = [[HISubtitle alloc]init];
    subtitle.text = @"Source: WorldClimate.com";
    subtitle.x = @-20;
    
    HIXAxis *xaxis = [[HIXAxis alloc]init];
    xaxis.categories = [NSMutableArray arrayWithObjects:@"Jan",
                        @"Feb",
                        @"Mar",
                        @"Apr",
                        @"May",
                        @"Jun",
                        @"Jul",
                        @"Aug",
                        @"Sep",
                        @"Oct",
                        @"Nov",
                        @"Dec", nil];
    HIYAxis *yaxis = [[HIYAxis alloc]init];
    yaxis.title = [[HIYAxisTitle alloc]init];
    yaxis.title.text = @"Temperature (°C)";
    yaxis.plotLines = [NSMutableArray arrayWithObjects:@{
                                                         @"value": @0,
                                                         @"width": @1,
                                                         @"color": @"#808080"
                                                         }, nil];
    
    HITooltip *tooltip = [[HITooltip alloc]init];
    tooltip.valueSuffix = @"°C";
    
    HILegend *legend = [[HILegend alloc]init];
    legend.layout = @"vertical";
    legend.align = @"right";
    legend.verticalAlign = @"middle";
    legend.borderWidth = @0;
    
    
    HIExporting * exporting = [[HIExporting alloc] init];
    exporting.enabled = @false;
    
    HILine *line1 = [[HILine alloc]init];
    line1.name = @"Tokyo";
    line1.data = [NSMutableArray arrayWithObjects:@7,
                  @6.9,
                  @9.5,
                  @14.5,
                  @18.2,
                  @21.5,
                  @25.2,
                  @26.5,
                  @23.3,
                  @18.3,
                  @13.9,
                  @9.6, nil];
    
    HILine *line2 = [[HILine alloc]init];
    line2.name = @"New York";
    line2.data = [NSMutableArray arrayWithObjects:@7,
                  @-0.2,
                  @0.8,
                  @5.7,
                  @11.3,
                  @17,
                  @22,
                  @24.8,
                  @24.1,
                  @20.1,
                  @14.1,
                  @8.6,
                  @2.5, nil];
    
    HILine *line3 = [[HILine alloc]init];
    line3.name = @"Berlin";
    line3.data = [NSMutableArray arrayWithObjects:@7,
                  @-0.9,
                  @0.6,
                  @3.5,
                  @8.4,
                  @13.5,
                  @17,
                  @18.6,
                  @17.9,
                  @14.3,
                  @9,
                  @3.9,
                  @1, nil];
    
    HILine *line4 = [[HILine alloc]init];
    line4.name = @"London";
    line4.data = [NSMutableArray arrayWithObjects:@7,
                  @3.9,
                  @4.2,
                  @5.7,
                  @8.5,
                  @11.9,
                  @15.2,
                  @17,
                  @16.6,
                  @14.2,
                  @10.3,
                  @6.6,
                  @4.8, nil];
    
    
    HIOptions *options = [[HIOptions alloc]init];
    options.title = title;
    options.subtitle = subtitle;
    options.xAxis = [NSMutableArray arrayWithObject:xaxis];
    options.yAxis = [NSMutableArray arrayWithObject:yaxis];
    options.tooltip = tooltip;
    options.legend = legend;
    options.exporting = exporting;
    options.series = [NSMutableArray arrayWithObjects:line1, line2, line3, line4, nil];
    
    chartView.options = options;
    
    [self.view addSubview:chartView];
        
}
![simulator screen shot - iphone 6s - 2017-10-27 at 10 22 25](https://user-images.githubusercontent.com/15138910/32085327-e8657952-bb00-11e7-96bf-efb7ca55f52b.png)

**Comment by ihnatmoisieiev** [comment]
@PankeGao, ok, thank you for your question. Try:
`exporting.enabled = [[NSNumber alloc] initWithBool:false];`

**Comment by PankeGao** [comment]
yes, this works.thank you so much!
