### ISSUE TITLE
Cannot hide Chart title

### ISSUE THREAD

**Issue by AzeemMuzammil** [highcharts/highcharts-ios#421]
```swift
let options = HIOptions()

let title = HITitle()
title.text = nil
options.title = title
```

This does not remove the title in the chart, but in JS it removes it.

**Comment by ihnatmoisieiev** [comment]
Hello @AzeemMuzammil,
did you try to set empty string?

```
let title = HITitle()
title.text = ""
options.title = title
```

**Comment by AzeemMuzammil** [comment]
HI @ihnatmoisieiev, yes I tried setting an empty string to `title.text` and it was working, Thaks for the prompt response. :)
