### ISSUE TITLE
loadJSONOptions doesn't hide export button

### ISSUE THREAD

**Issue by nectar1** [highcharts/highcharts-ios#422]
Hello 

I use `loadJSONOptions` method to setup a chart and hiding of the export button doesn't work.

```
let options = ["exporting": ["enabled": false]]
let chart = HIChartView()
chart.loadJSONOptions(options)
```

**Comment by ihnatmoisieiev** [comment]
Hello @nectar1,

I've just checked and it's working as expected for me.

Please try example below:
```
let options = [
  "exporting": false,
  "series": [
    [
      "type": "column",
      "data": [49.9, 71.5, 106.4, 129.2, 144, 176, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    ] as [String: Any]
  ],
  "title": [
    "text": "Demo chart"
  ],
  "chart": [
    "type":"column",
    "renderTo":"container"
  ]
] as [String: Any]

chartView.loadJSONOptions(options)
```
<img width="565" alt="Screenshot 2023-10-04 at 19 40 25" src="https://github.com/highcharts/highcharts-ios/assets/11294008/52858d03-29ff-4a27-b3bd-275fd3467215">

**Comment by nectar1** [comment]
Hello @ihnatmoisieiev 
Thank you for your answer! 
It helped me to hide the button.

I relied on this https://api.highcharts.com/highcharts/exporting.enabled
and expected the format `let options = ["exporting": ["enabled": false]]`

Anyway there is strange behavior if I use your example and change **false** on **true**
like that`"exporting": true`
I expect that the button will be presented but it is hidden.

**Comment by ihnatmoisieiev** [comment]
@nectar1 to enable/disable the button please use: `"exporting": ["enabled": false]` or `"exporting": ["enabled": true]`.

2 demos are below.

Enabled:
```
let options = [
  "exporting": [
    "enabled": true
  ],
  "series": [
    [
      "type": "column",
      "data": [49.9, 71.5, 106.4, 129.2, 144, 176, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    ] as [String: Any]
  ],
  "title": [
    "text": "Demo chart"
  ],
  "chart": [
    "type":"column",
    "renderTo":"container"
  ]
] as [String: Any]

chartView.loadJSONOptions(options)
```

<img width="565" alt="Screenshot 2023-10-12 at 08 02 56" src="https://github.com/highcharts/highcharts-ios/assets/11294008/5807cf87-e38c-4b06-b50a-d286417c42c7">

Disabled:
```
let options = [
  "exporting": [
    "enabled": false
  ],
  "series": [
    [
      "type": "column",
      "data": [49.9, 71.5, 106.4, 129.2, 144, 176, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    ] as [String: Any]
  ],
  "title": [
    "text": "Demo chart"
  ],
  "chart": [
    "type":"column",
    "renderTo":"container"
  ]
] as [String: Any]

chartView.loadJSONOptions(options)
```

<img width="565" alt="Screenshot 2023-10-12 at 08 04 05" src="https://github.com/highcharts/highcharts-ios/assets/11294008/a2292725-4100-4faf-9562-79d22881ece2">

It works as expected for me. Can I close the issue?

**Comment by nectar1** [comment]
@ihnatmoisieiev yes, it can be closed, thank you!
