### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by ZainabAl-khabori** [highcharts/highcharts-ios#427]
I would like to ask for RTL support for rendering of text. Arabic is an RTL language, so having a text with mixed Arabic and English would be displayed wrong if the text was left-aligned.

**Comment by ihnatmoisieiev** [comment]
Hello @ZainabAl-khabori,
seems like it's not connected to the iOS wrapper. Please create an issue on the [main](https://github.com/highcharts/highcharts) JS core library.
