### ISSUE TITLE
Mac OS version

### ISSUE THREAD

**Issue by Vincz** [highcharts/highcharts-ios#428]
Hi. Is there a reason or an specific API being used that prevent the support of Mac OSX?

**Comment by ihnatmoisieiev** [comment]
Hello @Vincz,
I guess MacOS is supported. 
Do you have any issues? 
Please give more details.
Thank you!

**Comment by Vincz** [comment]
Hi @ihnatmoisieiev , i can't install the package on Mac Os. I think the problem may be related to the package file as it only indícate support for IOS. I'll try to clone and Add support to Mac OS to see.

**Comment by ihnatmoisieiev** [comment]
@Vincz which version of the framework are you using? MacOS should be included on the latest versions also.

**Comment by Vincz** [comment]
@ihnatmoisieiev My bad. It's working. It's just that by default, when we add the package, it set the version to `6 -> 7`, so the installation failed. With the right version it works.
I think the default would be fixed by adding `macOs(v11)` in the 
`https://github.com/highcharts/highcharts-ios/blob/master/Package.swift`

**Comment by Vincz** [comment]
@ihnatmoisieiev  I've been able to add the package and the framework to a Mac Os project.
But when I try to compile it, I get the following error message:

`/Users/xxx/Library/Developer/Xcode/DerivedData/UI-dtbldhmcdmcdzkfnzcaoknvsksrf/SourcePackages/checkouts/highcharts-ios/Highcharts.xcframework:1:1 While building for macOS, no library for this platform was found in '/Users/xxx/Library/Developer/Xcode/DerivedData/UI-dtbldhmcdmcdzkfnzcaoknvsksrf/SourcePackages/checkouts/highcharts-ios/Highcharts.xcframework'.`

I'm not an expert in Xcode frameworks, but shouln't the compatibility with macOs be declared somewhere? I only see stuff related to IOS.

![Screenshot 2023-11-22 at 4 32 57 PM](https://github.com/highcharts/highcharts-ios/assets/400525/00a5d3ed-fbfa-4784-8175-391d646c0731)

**Comment by Vincz** [comment]
Hey @ihnatmoisieiev! Any idea how we could make this work with Mac OS?

**Comment by ihnatmoisieiev** [comment]
Hello @Vincz,
as you can see from the framework's content we are only supporting Mac Catalyst at the moment.

**Comment by Vincz** [comment]
@ihnatmoisieiev I see. Any plan to release it for Mac OS?

**Comment by ihnatmoisieiev** [comment]
@Vincz  there are no any plans for Mac OS as far as I know at the moment.

**Comment by ihnatmoisieiev** [comment]
Closing for now. Feel free to ask any additional questions you have.
