### ISSUE TITLE
Update JSON data without reloading chart

### ISSUE THREAD

**Issue by sagar-kudale30** [highcharts/highcharts-ios#429]
Is it possible to update chart JSON without re-rendering entire chart. I'm trying to update series visibility without resetting chart. 

To load chart we are using `loadJSONOptions` method but not able to find any method to update json.

**Comment by ihnatmoisieiev** [comment]
Hello,
thanks for your question. At the moment it's possible only with `update` method from `HIChartView` and `HIOptions` object or with reloading using `loadJSONOptions`.
How critical is it for you?

**Comment by sagar-kudale30** [comment]
Hey @ihnatmoisieiev Thanks for the reply. We have one feature depend on this ability to update JSON without reloading entire chart.

**Comment by ihnatmoisieiev** [comment]
Hello @sagar-kudale30,
we added a possibility to update chart options with `JSON` data in our latest [11.3.0](https://github.com/highcharts/highcharts-ios/releases/tag/v11.3.0) release version. 
Seems like I can close the issue at the moment.
