### ISSUE TITLE
Several colors on the same HISpline

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#43]
Hi all,

I'd like to draw a spline with several different colors on the same spline.
For instance, between the 2 first points in white, then in black.

Is that possible?

Thanks in advance.

Best regards,
Alexandre

**Comment by ihnatmoisieiev** [comment]
Hi @AlexandreMinard,
yes, it is possible. Try to set up `zones` and `zoneAxis` params for your `spline`. 
See [docs](https://api.highcharts.com/ios/series.spline.zones) and [example](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series/color-zones-simple/).

**Comment by AlexandreMinard** [comment]
Thanks a lot, works fine!
