### ISSUE TITLE
Sunburst chart getting cutoff on iPad.

### ISSUE THREAD

**Issue by jobinsjohn** [highcharts/highcharts-ios#430]
I am adding mutiple charts in a collection view and each cell holds different kinds of charts. But when sunburst charts are added, the chart goes out of bounds in iPad. There is no issue with the UI in iPhone. Please see the screenshots below.

**iPhone ScreenShot**

![image](https://github.com/highcharts/highcharts-ios/assets/3398498/468b99e2-3a3f-404d-9103-812cc19b4a10)

**iPad Screenshot**

![image](https://github.com/highcharts/highcharts-ios/assets/3398498/171d1547-b718-41f0-9b8f-a98d8ab07ae4)

Can someone help me with the issue?

**Comment by ihnatmoisieiev** [comment]
Hello @jobinsjohn,
is this question actual or already has been resolved?
Thank you for the reply.

**Comment by jobins-musashi** [comment]
The question was relevant and I guess it's a bug. I was able to resolve it by removing the following code which added to the code

`chartView.height = 96%`

While this code was there, the UI was breaking in iPad.
