### ISSUE TITLE
11.3.0 is causing app store release issue

### ISSUE THREAD

**Issue by ravitejabb** [highcharts/highcharts-ios#432]
Hi Team,
Appstore is rejecting the app when using the latest highcharts version 11.3.0
due to below reason.
<img width="1149" alt="Screenshot 2024-02-28 at 8 41 23 AM" src="https://github.com/highcharts/highcharts-ios/assets/120622460/cd886f98-7bc6-43f6-bd08-7ee75569f972">

**Comment by ihnatmoisieiev** [comment]
Hello @ravitejabb,
thank you for the reporting. We will fix it in our next release.

**Comment by ihnatmoisieiev** [comment]
Hello, the issue was fixed in the latest version `11.4.0`.
