### ISSUE TITLE
Privacy Manifest for iOS 

### ISSUE THREAD

**Issue by jobinsjohn** [highcharts/highcharts-ios#433]
Is there any plan to add privacy manifest into the framework?

**Comment by jobinsjohn** [comment]
@ihnatmoisieiev Thanks for confirming. Can we expect this before April 1 as apple will need this for all the releases from April 1.

**Comment by ihnatmoisieiev** [comment]
@jobinsjohn I think so.

**Comment by jobinsjohn** [comment]
Closing as privacy manifest has been added in version 11.4.0
