### ISSUE TITLE
Invalid Version Number 11.4.1.1 Blocks Releasing

### ISSUE THREAD

**Issue by 7-plus-t** [highcharts/highcharts-ios#436]
The current version number `11.4.1.1` is an invalid CFBundleShortVersionString and fails the upload of the host app with:
```
[ContentDelivery.Uploader] Asset validation failed (90060) This bundle is invalid. The value for key CFBundleShortVersionString '11.4.1.1' in the Info.plist file at 'Frameworks/Highcharts.framework' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring 
```
See:
https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring
https://forums.developer.apple.com/forums/thread/747288

**Comment by MikolajMichalczak** [comment]
Hi all!
We apologize for the delay. A new release is in preparation and will be available shortly. Thank you for your patience.

**Comment by MikolajMichalczak** [comment]
@7-plus-t @zcjhnsn Version 11.4.3 has been released and is now available.

**Comment by 7-plus-t** [comment]
With 11.4.3 the build fails on Highcharts.framework/Headers/HITooltip.h201:997 with error:
'/*' within block comment

I will open a new issue.

**Comment by 7-plus-t** [comment]
See #439 for follow up issue.
