### ISSUE TITLE
Using highcharts-regression plugin in iOS highchart

### ISSUE THREAD

**Issue by sagar-kudale30** [highcharts/highcharts-ios#437]
Is there a way to use Highchart-regression (https://www.npmjs.com/package/highcharts-regression) in iOS through plugin. 

We want to show linear regression series with scatter chart.

**Comment by MikolajMichalczak** [comment]
Hi @sagar-kudale30! 
Here is a demo of a scatter plot with a regression line on iOS: https://www.highcharts.com/demo/ios/combo-regression. There is no way to use custom plugins at the moment.

**Comment by sagar-kudale30** [comment]
Hey @MikolajMichalczak  Thanks for the reply and demo link. 

We are using JSON to load charts via loadJSONOptions method so it will not help us in our case.

**Comment by MikolajMichalczak** [comment]
I recreated this chart with the use of `loadJSONOptions` method:
```swift
let options = [
  "series": [
    [
      "type": "line",
      "data": [[0, 1.11], [5, 4.51]]
    ] as [String: Any],
    [
      "type": "scatter",
      "data": [1, 1.5, 2.8, 3.5, 3.9, 4.2]
    ] as [String: Any]
  ],
  "title": [
    "text": "Demo chart"
  ],
  "chart": [
    "type":"column",
    "renderTo":"container"
  ]
] as [String: Any]

chart.loadJSONOptions(options)
```
Unfortunately, you have to calculate line series data by yourself according to your scatter data.

**Comment by MikolajMichalczak** [comment]
@sagar-kudale30 Can i close this issue?

**Comment by sagar-kudale30** [comment]
Hey @MikolajMichalczak  This will not help us as we don't want to do line series calculation ourself. We are displaying same chart on web as well with the help on Highchats-regression.  
Do we have any plan to add native support for linear regression or Plugin for same in near future?

**Comment by MikolajMichalczak** [comment]
@sagar-kudale30 Unfortunately, there are currently no options or plans to support the use of custom plugins, including regression, either on Android or iOS.
