### ISSUE TITLE
Increased app size

### ISSUE THREAD

**Issue by simeonhhristov** [highcharts/highcharts-ios#438]
We are experiencing an issue with an increased app size, due to some random images,  which keeps getting worse with every version. We noticed that you agreed to resolve it in the following way for android https://github.com/highcharts/highcharts-android/issues/281.  Is there a possibility that something similar is done for iOS as well?

**Comment by MikolajMichalczak** [comment]
Hi @simeonhhristov!
We understand the issue you're experiencing. Similar to our approach for Android, we plan to release the next version for iOS without the mentioned folder. We hope this will help alleviate the problem.

**Comment by MikolajMichalczak** [comment]
@simeonhhristov Version 11.4.3 has been released and is now available.

**Comment by simeonhhristov** [comment]
The issue is indeed resolved. But something small occurred. in Highcharts/Highcharts.framework/Headers/HITooltip.h Line: 201, There is a '/*' within block comment. Could it also be resolved? Thank you!

**Comment by MikolajMichalczak** [comment]
@Simeonhhristov The issue you highlighted is mentioned here: #439 and will be fixed in the next release. Thank you for your keen observation.
