### ISSUE TITLE
Build Warning with Version 11.4.3

### ISSUE THREAD

**Issue by 7-plus-t** [highcharts/highcharts-ios#439]
With version 11.4.3 the build fails on Highcharts.framework/Headers/HITooltip.h:201:997 with error:
`'/*' within block comment`

Built with Xcode 15.3

**Comment by 7-plus-t** [comment]
Hi @MikolajMichalczak 
Good catch! Indeed we have the `GCC_TREAT_WARNINGS_AS_ERRORS` enabled for release builds. I've changed the title of the issue accordingly. 
As a workaround, I will exclude the library from the check temporarily. I think the warning should still be fixed though.
Thanks!

**Comment by MikolajMichalczak** [comment]
@7-plus-t Nice to hear that you managed to find a workaround. Indeed, we will fix this warning in the next release. Thank you for your support and engagement.

**Comment by MikolajMichalczak** [comment]
Hi @7-plus-t!

I wanted to let you know that the new version (11.4.5) is now available and it should resolve the issue you reported. If you encounter any further problems or have any questions, please feel free to reach out.

**Comment by 7-plus-t** [comment]
Hi @MikolajMichalczak 
I've integrated it and it works. Thanks for your help :)
