### ISSUE TITLE
Want to get tap event on bar chart in iOS native code

### ISSUE THREAD

**Issue by anurag1991** [highcharts/highcharts-ios#44]
Hi,

I am using HighCharts to represent my data, but I want click event when user tap on any bar char, but I want to do some custom things by myself. and don't have any idea how do I get this event in my controller, is there any delegate or any call back that we can use?

Please help me with this, i am waiting for any help.

**Comment by ihnatmoisieiev** [comment]
Hello @anurag1991,
at this moment you can handle tap events on `HIChartView` by adding a gesture recognizer and your `UIViewController` subclass should implement `UIGestureRecognizerDelegate`.

**Comment by speedoholic** [comment]
I believe this issue corresponds to existing issue #31  

https://github.com/highcharts/highcharts-ios/issues/31

I am also looking for this solution, but the framework here only includes header files.

**Comment by ihnatmoisieiev** [comment]
@speedoholic it would be added soon.

**Comment by ihnatmoisieiev** [comment]
@anurag1991 @speedoholic this feature is added to the newest release. Can I close this issue?

**Comment by speedoholic** [comment]
@ihnatmoisieiev can you please confirm if you are referring to the following function for getting tapped index:
```
HIFunction * function = [[HIFunction alloc] initWithClosure:^(HIChartContext *context) {
        NSInteger groupTapped = [context valueForKey:@"index"];
        NSInteger barTapped = [context valueForKey:@"colorIndex"];
    } properties:@[@"index", @"colorIndex"]];
```
Please help us learn how to get rest of the parameters like data value of the tapped item?

**Comment by ihnatmoisieiev** [comment]
@speedoholic you should use `getProperty` on `HIChartContext ` object to get the current property value. For example, if you want to get a Y value of the tapped point, you can use this function
```
HIFunction * function = [[HIFunction alloc] initWithClosure:^(HIChartContext *context) {
        NSLog(@"Y value: %@", [context getProperty:@"y"]);
        NSLog(@"Index: %@", [context getProperty:@"index"]);
        NSLog(@"Category: %@", [context getProperty:@"category"]);
} properties:@[@"y", @"index", @"category"]];
point.events.click = function;
```

The rest of parameters you can find in Highcharts [class reference](https://api.highcharts.com/class-reference/Highcharts.Point) and [docs](https://api.highcharts.com/ios/highcharts/).
See other event [examples](https://api.highcharts.com/ios/highcharts/series.area.point.events) in JS.

**Comment by speedoholic** [comment]
@ihnatmoisieiev Thanks for your prompt response. Is it possible to get all the available properties without specifically providing the names in second argument of HIFunction? If any of the mentioned properties are not present in a chart, the corresponding closure is not getting called.

Also , the following function is only returning the UUID:
`- (instancetype)initWithClosure:(HIClosure)closure;`

being able to get all the available properties would really help with quick implementation of tap event for different kinds of charts.

**Comment by ihnatmoisieiev** [comment]
@speedoholic thanks for your observations. 
Unfortunately, there is no way to get all available properties at the moment, but you could add it to UserVoice for Highcharts iOS.

**Comment by speedoholic** [comment]
@ihnatmoisieiev thanks for confirming, have posted in Javascript API since I could not find a user voice for Highcharts iOS: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/33833515-get-all-properties-with-hichartcontext-on-tap-for

**Comment by tripathishivam35** [comment]
HIFunction * function = [[HIFunction alloc] initWithClosure:^(HIChartContext *context) {
        NSLog(@"Y value: %@", [context getProperty:@"y"]);
        NSLog(@"Index: %@", [context getProperty:@"index"]);
        NSLog(@"Category: %@", [context getProperty:@"category"]);
} properties:@[@"y", @"index", @"category"]];
point.events.click = function;

I tried to use this but It is throwing error as there is no function available with "intWithClosure" . Is things are changed or there is some other function?
