### ISSUE TITLE
Dependency wheel no longer working

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#442]
https://www.highcharts.com/demo/ios/dependency-wheel

That is no longer working with the most recent version. Blank screen.

**Comment by skuske** [comment]
The issue does not only apply to the demo, actually all dependency charts no longer work.

**Comment by MikolajMichalczak** [comment]
Hi @skuske!
Thank you for reporting this issue. We are currently investigating the problem.
Could you please clarify what you mean by "all dependency charts"?

**Comment by skuske** [comment]
@MikolajMichalczak 

Yes, I meant whatever dependency chart I try to set up, they're all not working, not just the demo.

**Comment by skuske** [comment]
@MikolajMichalczak 

Any update on this? TIA.

**Comment by MikolajMichalczak** [comment]
Hi @skuske,
Thank you for your patience. This was a challenging bug to pinpoint, and the issue occurred on both iOS and Android. It will be fixed in the release of the next version.

**Comment by skuske** [comment]
@MikolajMichalczak 

Many thanks for the update! Is that an issue within the JS library?

**Comment by MikolajMichalczak** [comment]
@skuske This is an issue related to the iOS and Android wrapper, not the JS library.

**Comment by MikolajMichalczak** [comment]
Hi @skuske!

I wanted to let you know that the new version (11.4.5) is now available and it should resolve the issue you reported. If you encounter any further problems or have any questions, please feel free to reach out.
