### ISSUE TITLE
Property 'legendItemClick' not found on object of type 'HIEvents *'

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#445]
@MikolajMichalczak 

I read about the deprecated `legendItemClick` event in the latest version, but: I need that event in my project, it is substantially, but now I get this error:

`Property 'legendItemClick' not found on object of type 'HIEvents *'`

How can I continue using it or a replacement that has the same functionality? Obj-C, please. Many thanks.

**Comment by MikolajMichalczak** [comment]
Hi @skuske,

Please use events on the legend object now: [legend.events.itemClick](https://api.highcharts.com/highcharts/legend.events.itemClick).

**Comment by skuske** [comment]
@MikolajMichalczak 

Well, now my HIClosure no longer works as before:

```
    HILegend *legend = [[HILegend alloc] init];
    legend.enabled=@1;
    legend.events=[[HIEvents alloc] init];
    legend.events.itemClick = [[HIFunction alloc] initWithClosure: objClosure properties:@[@"this.visible",@"this.name"]];
```

The properties don't seem to work or deliver what they should.

How do I access the corresponding `series.visible` and a `series.name` properties from a legend item?

**Comment by skuske** [comment]
Resolved.
