### ISSUE TITLE
Heatmap not working with all versions above v11.2.0

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#447]
@MikolajMichalczak 

I have ported

https://www.highcharts.com/demo/highcharts/calendar-heatmap-month

to Obj-C and it's working fine with v11.2.0 of the wrapper, but it is no longer working with v11.3.0 and above. I am not getting any error, the chart area is just blank, the color legend appears.

Attached is the sample Xcode project. Note: PODs removed from zip to make the file smaller.

[HighCharts Test Heatmap.zip](https://github.com/user-attachments/files/16402529/HighCharts.Test.Heatmap.zip)

What's the problem and how can I fix it so that it works fine with the latest version of the wrapper?

**Comment by skuske** [comment]
@MikolajMichalczak 

Some additional information after my own debugging.

Removing

```
    yAxis.min = @0;
    yAxis.max = @5;
```

makes the heat map work, however, I need to set min and max.

**Comment by MikolajMichalczak** [comment]
Hi @skuske!

If the `max` or `min` value is not provided, it is automatically calculated, so it should work just fine.

**Comment by skuske** [comment]
@MikolajMichalczak 

Many thanks. Issue closed.
