### ISSUE TITLE
Windbarb zoom issue

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#46]
I am seeing an issue with a windbarb chart and zooming enabled - when zoomed in, the wind barbs appear at the top of the chart, too:

![img_3505](https://user-images.githubusercontent.com/12996815/34668952-cf6ade94-f46f-11e7-8985-4c65f4b9b72e.PNG)

Code looks like this:

```
    HIChartView *chartView = [[HIChartView alloc] initWithFrame:self.view.bounds];
    chartView.plugins = @[ @"windbarb" ];
    
    HIOptions *options = [[HIOptions alloc] init];
    
    HIChart *chart = [[HIChart alloc] init];
    chart.type = @"windbarb";
    chart.zoomType = @"xy";
    
    HITitle *title = [[HITitle alloc] init];
    title.text = @"Highcharts Wind Barbs";
    
    HIXAxis *xaxis = [[HIXAxis alloc] init];
    xaxis.type = @"datetime";
    xaxis.offset = @40;
    
    HIPlotOptions *plotoptions = [[HIPlotOptions alloc] init];
    plotoptions.series = [[HISeries alloc] init];
    plotoptions.series.pointStart = @1485648000000;
    plotoptions.series.pointInterval = @36e5;

    
    HIWindbarb *windbarb = [[HIWindbarb alloc] init];
    windbarb.name = @"Wind";
    windbarb.color = [[HIColor alloc] initWithHexValue:@"0d233a"];
    windbarb.showInLegend = [[NSNumber alloc] initWithBool:false];
    windbarb.tooltip = [[HITooltip alloc] init];
    windbarb.tooltip.valueSuffix = @" m/s";

    windbarb.tooltip.pointFormat = @"<b>{point.value:.1f} aus {point.direction:.1f}°</b><br/>";
    windbarb.data = [NSMutableArray arrayWithObjects:
                     @[@9.8, @177.9],
                     @[@10.1, @177.2],
                     @[@11.3, @179.7],
                     @[@10.9, @175.5],
                     @[@9.3, @159.9],
                     @[@8.8, @159.6],
                     @[@7.8, @162.6],
                     @[@5.6, @186.2],
                     @[@6.8, @146.0],
                     @[@6.4, @139.9],
                     @[@3.1, @180.2],
                     @[@4.3, @177.6],
                     @[@5.3, @191.8],
                     @[@6.3, @173.1],
                     @[@7.7, @140.2],
                     @[@8.5, @136.1],
                     @[@9.4, @142.9],
                     @[@10.0, @140.4],
                     @[@5.3, @142.1],
                     @[@3.8, @141.0],
                     @[@3.3, @116.5],
                     @[@1.5, @327.5],
                     @[@0.1, @1.1],
                     @[@1.2, @11.1],
                     nil];
    
    HIArea *area = [[HIArea alloc] init];
    area.keys = @[@"y", @"rotation"];
    area.data = [NSMutableArray arrayWithObjects:
                 @[@9.8, @177.9],
                 @[@10.1, @177.2],
                 @[@11.3, @179.7],
                 @[@10.9, @175.5],
                 @[@9.3, @159.9],
                 @[@8.8, @159.6],
                 @[@7.8, @162.6],
                 @[@5.6, @186.2],
                 @[@6.8, @146.0],
                 @[@6.4, @139.9],
                 @[@3.1, @180.2],
                 @[@4.3, @177.6],
                 @[@5.3, @191.8],
                 @[@6.3, @173.1],
                 @[@7.7, @140.2],
                 @[@8.5, @136.1],
                 @[@9.4, @142.9],
                 @[@10.0, @140.4],
                 @[@5.3, @142.1],
                 @[@3.8, @141.0],
                 @[@3.3, @116.5],
                 @[@1.5, @327.5],
                 @[@0.1, @1.1],
                 @[@1.2, @11.1],
                 nil];
    area.color = [[HIColor alloc] initWithHexValue:@"2f7ed8"];
    area.fillColor = [[HIColor alloc] initWithLinearGradient:@{ @"x1": @0, @"x2": @0, @"y1": @0, @"y2": @1 } stops:@[
                                                                                                                     @[@0, @"#2f7ed8"],
                                                                                                                     @[@1, @"rgba(47, 126, 216, 0.25)"]
                                                                                                                     ]];
    area.name = @"Wind speed";
    area.tooltip = [[HITooltip alloc] init];
    area.tooltip.valueSuffix = @" m/s";
    area.tooltip.pointFormat = @"<b>{point.y:.1f} aus {point.rotation:.1f}°</b><br/>";
    
    options.chart=chart;
    options.title = title;
    options.xAxis = [NSMutableArray arrayWithObjects:xaxis, nil];
    options.plotOptions = plotoptions;
    options.series = [NSMutableArray arrayWithObjects:windbarb, area, nil];
    
    chartView.options = options;
    
    [self.view addSubview:chartView];
    
    [self.view addSubview:self.chartView];
```

**Comment by ihnatmoisieiev** [comment]
It is not an iOS bug. See [https://github.com/highcharts/highcharts/issues/7507](https://github.com/highcharts/highcharts/issues/7507) for more info.

**Comment by skuske** [comment]
Thanks. Unfortunately the fix suggested by rychoo2

> We found out that setting pointRange: 0 in plotOptions.series fixes the problem

does actually **not** fix this for us.

**Comment by skuske** [comment]
I saw that 6.0.4 will obviously fix that. Will there be a 6.0.4 iOS framework soon?

**Comment by ihnatmoisieiev** [comment]
Yes, I hope will be 6.0.4 release soon.

**Comment by TorsteinHonsi** [comment]
There were two issues. First, the wind barbs showed outside the plot area. Next, after fixing that, we discovered that sometimes one wind barb on either side was displaced to the top. This will be fixed in Highcharts v6.0.5, to be released within a few weeks.

**Comment by skuske** [comment]
Thanks.

Another question: is there any way to limit the number of wind barbs so that they are now drawn on top of each other if there are a lot of data points? I mean: there should be an option to force the windbarb chart to check if there are too many barbs to be displayed at the current zoom level. In such a case barbs should only be drawn for every 10th data point or so, or maybe the number of drawn barbs should be calculated so that they do not draw on top of each other... Maybe there already is a way to do that... ???

**Comment by TorsteinHonsi** [comment]
Currently there is no such feature though it certainly makes sense. It could be implemented in two ways:
* Either like Highstock's data grouping feature that aggregates the data and creates a new value. In wind barbs it would be the combined vector of the grouped points.
* Or as you say, like a simple skipping of overlapping barbs.

**Comment by skuske** [comment]
Thanks for your reply, Torstein. :o)

Actually without such a feature the windbarb chart is pretty useless for us as in most of the charts we had planned to display as a windbarb chart there is a huge amount of datapoints and without having an option to automatically reduce the amount of windbarbs, the whole chart looks extremely ugly and the windbarb area becomes kind of useless.

Maybe you put this onto your list of feature requests.

**Comment by ihnatmoisieiev** [comment]
@skuske is it fixed in the latest release and can I close this issue?

**Comment by skuske** [comment]
Hmmm - as far as I know this has not been fixed in the most recent version of Highcharts... 

See https://github.com/highcharts/highcharts/issues/7630

**Comment by ihnatmoisieiev** [comment]
@skuske ok, thank you for the info.

**Comment by ihnatmoisieiev** [comment]
Highcharts issue : [https://github.com/highcharts/highcharts/issues/7630](https://github.com/highcharts/highcharts/issues/7630)
