### ISSUE TITLE
Export button cannot be removed

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#47]
While removing the credits via

```
            HIOptions *options = [[HIOptions alloc]init];
            options.credits.enabled=@0;
```

does work, removing the export button in the top right of any chart does not work:

```
            HIOptions *options = [[HIOptions alloc]init];
            options.exporting.enabled=@0;
```

It works fine in JS, though, but not in the iOS wrapper. Am I doing something wrong, or is this a bug?

Thanks.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
it is not a bug. See [https://github.com/highcharts/highcharts-ios/issues/42](https://github.com/highcharts/highcharts-ios/issues/42).

**Comment by skuske** [comment]
Cool. Thanks. That works now. :o)
