### ISSUE TITLE
Export button shows, but no context menu

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#49]
I imported the correct plugins:

` chartView.plugins = @[ @"exporting",@"export-data"];`

but the Export menu button does not work at all in iOS. There's no context menu popping up, although it should, according to the [documentation](https://www.highcharts.com/docs/export-module/export-module-overview):

> To enable exporting, the module needs to be included

Furthermore, the docs say:

> When enabled, a context button _**with a menu**_ appears in the top right corner of the chart

That is true for JS, but in iOS only the button appears, but **_no_** context menu when you click the button. Actually the debug area of XCode (9.2, iOS 11.2) shows this warning two times (one after the other) in the debug console when the export button is clicked:

`[App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction`

So, it looks like the button receives the click event, but the context menu does not show. My code is below.

I honestly must say that the iOS documentation is extremely poor as all samples are either outdated (because deprecated), or the samples are in JS, which does not help at all. We need pure and **up-to-date** Objective-C samples to get that going properly! Thank you.

Here 's my code - run it and you'll notice that the export button is there, but you cannot click it.

```
    HIChartView *chartView = [[HIChartView alloc] initWithFrame:self.view.bounds];
    HIChart *chart = [[HIChart alloc]init];
    chart.polar = @true;
    chart.type = @"area";

    chartView.plugins = @[ @"exporting",@"export-data"];

    HITitle *title = [[HITitle alloc]init];
    title.text = @"Highcharts Polar Chart";    
    
    HIPane *pane = [[HIPane alloc]init];
    pane.size = @"80%";
    
    HIXAxis *xaxis = [[HIXAxis alloc]init];
    xaxis.categories=[NSMutableArray arrayWithObjects:@"N",@"NNO",@"NO",@"ONO",@"O",@"OSO",@"SO",@"SSO",@"S",@"SSW",@"SW",@"WSW",@"W",@"WNW",@"NW",@"WNW", nil];
    xaxis.tickmarkPlacement=@"on";
    xaxis.lineWidth=@0;
    
    HILabels *labels = [[HILabels alloc] init];
    labels.style = [[HIStyle alloc] init];
    labels.style.fontSize = @"8px";
    xaxis.labels = labels;
    
    HIYAxis *yaxis = [[HIYAxis alloc]init];
    yaxis.gridLineInterpolation=@"polygon";
    yaxis.lineWidth=@0;
    yaxis.min=0;
    
    HITitle *titleYaxis = [[HITitle alloc]init];
    titleYaxis.text=@"Speed";
    
    yaxis.title=titleYaxis;
    yaxis.tickAmount=@15;

    HISeries *series = [[HISeries alloc]init];
    series.name=@"Wind";
    series.data=[NSMutableArray arrayWithObjects:@11,@12,@13,@14,@11,@12,@13,@14,@11,@12,@13,@14,@11,@12,@13,@14, nil];
    series.pointPlacement=@"on";
    
    HIOptions *options = [[HIOptions alloc]init];
    
    HINavigation *navigation = [[HINavigation alloc]init];
    navigation.buttonOptions = [[HIButtonOptions alloc]init];
    navigation.buttonOptions.enabled=[[NSNumber alloc] initWithBool:true];

    HIExporting *exporting = [[HIExporting alloc] init];
    exporting.enabled = [[NSNumber alloc] initWithBool:true];
    
    options.exporting = exporting;
    options.navigation=navigation;
    options.chart = chart;
    options.title = title;
    options.pane = pane;

    options.xAxis = [NSMutableArray arrayWithObjects:xaxis, nil];
    options.yAxis = [NSMutableArray arrayWithObjects:yaxis, nil];
    options.series = [NSMutableArray arrayWithObjects: series, nil];
    chartView.options = options;
    
    [self.view addSubview:chartView];
```

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
thank you for your remarks.
First of all, you don't need to include exporting modules. 
According to your code, it seems that you missed to set up view controller for your `chartView `. That is why a context menu don't popping up. Try add: `chartView.viewController = self;` after adding the options. 
Lastly, if you want to use an area series, you should to set up `HIArea` object instead of `HISeries`.

**Comment by ihnatmoisieiev** [comment]
@skuske did it solve your problem? Can I close it?

**Comment by skuske** [comment]
Sorry. Yes, solved.
