### ISSUE TITLE
Highcharts was built without full bitcode.

### ISSUE THREAD

**Issue by Ferannor** [highcharts/highcharts-ios#5]
I've got an error if I want to build a version for the App Store. 

> bitcode bundle could not be generated because 'MyProject/Pods/Highcharts/Highcharts.framework/Highcharts' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64

So basically I'm stuck :/

**Comment by ratka6** [comment]
Did you try this:
http://stackoverflow.com/questions/33580528/xcode-7-1-swift-framework-app-builds-but-not-archiving/33581287

**Comment by ratka6** [comment]
I will archive it again. Did you use Cocoapods, Carthage or manual download?

**Comment by Ferannor** [comment]
I use CocoaPods ;) Thanks!

**Comment by ratka6** [comment]
Before I upload new version, would you mind checking "Update" section in this article:
http://arsenkin.com/ios-universal-framework.html

**Comment by Ferannor** [comment]
Thanks for the link but sadly my app need the Bitcode and the script in the Update section is works only without Bitcode support.

**Comment by ratka6** [comment]
Ok, I'll post another version. Please send me info as soon as you test it.

**Comment by Ferannor** [comment]
Yup no problem ;)

**Comment by ratka6** [comment]
You can update your pods now

**Comment by Ferannor** [comment]
Ok I'll test it right now.

**Comment by Ferannor** [comment]
Sorry, I've always the same issue :(

**Comment by ratka6** [comment]
We fixed bitcode error. Now version 1.0.5 supports it. You can update your pods. Thanks for feedback!

**Comment by Ferannor** [comment]
I confirm it works ;)
