### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#51]
Someone from the Highcharts support team told me this:

> At this moment the iOS wrapper allows you to convert chart into an image, but unfortunately not to CSV.

There are the [exporting.CSV](https://api.highcharts.com/ios/highcharts/exporting.csv) methods, though, and I am wondering how to use them if exporting to CSV is not supported according to the quote above.

I would like to be able to export chart data to an array of strings and then offer an option to email the data.

Can someone shed some light on this? Thanks very much! :o)

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
it is true, exporting to CSV is not supported at this moment. You can only export the chart to an image, but, of course, you can implement this functionality by yourself.

**Comment by skuske** [comment]
Thanks, can you add the 'Enhancement' tag? :o)

**Comment by ihnatmoisieiev** [comment]
Yes, of course.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Does the updated wrapper include CSV exporting? Also: is there a version history file or something that shows what changed? I noticed that there are a few API changes and I was wondering if there's a list of all changes. which would be extremely helpful. Thanks. :o)

**Comment by ihnatmoisieiev** [comment]
@skuske CSV exporting  is not included in this update. The changelog will be added soon.

**Comment by ihnatmoisieiev** [comment]
@skuske this feature has been added to the newest release. Can I close this issue?

**Comment by skuske** [comment]
Sure.
