### ISSUE TITLE
The display Numbers are inconsistent.(How should I modify it?)

### ISSUE THREAD

**Issue by lxd123** [highcharts/highcharts-ios#52]
This is my incoming data 1.06688, but the figure in the chart is 1.0668799877166748
![snip20180117_2](https://user-images.githubusercontent.com/16974787/35035550-b10a0a08-fbac-11e7-966c-eea69fd1f560.png)
![snip20180117_5](https://user-images.githubusercontent.com/16974787/35035572-c6b29348-fbac-11e7-8aef-161cca8d5381.png)
![snip20180117_7](https://user-images.githubusercontent.com/16974787/35035595-e0d43006-fbac-11e7-8bc4-51c63124012b.png)
![snip20180117_10](https://user-images.githubusercontent.com/16974787/35035613-ef0c71ec-fbac-11e7-832b-3f2b3f49bf39.png)

**Comment by ihnatmoisieiev** [comment]
Hi @lxd123,
try to set up the number of decimals places in `plotOptions` for your series, e.g. :
```
HIPlotOptions *plotOptions = [[HIPlotOptions alloc]init];
plotOptions.line = [[HILine alloc]init];
plotOptions.line.dataLabels = [[HIDataLabels alloc]init];
plotOptions.line.dataLabels.enabled = [[NSNumber alloc]initWithBool:true];
plotOptions.line.dataLabels.format = @"{y:.1f}";
options.plotOptions = plotOptions;
```

**Comment by lxd123** [comment]
this works,thanks

**Comment by ihnatmoisieiev** [comment]
@lxd123 can I close this issue?
