### ISSUE TITLE
3d options causing chart view to shrink

### ISSUE THREAD

**Issue by ejosephwilson** [highcharts/highcharts-ios#54]
When 3d options are enabled and you re-set the HIChartView options, portions of the chart view shrink. I have a pull to refresh method that contacts an API to get updated data for the charts and then re-sets the chart options. Each time that happens the chart reloads and portions of the chart slightly shrink. The shrinking increases after each subsequent refresh. 

Any help would be appreciated. Thanks!

**Comment by ihnatmoisieiev** [comment]
Hello @ejosephwilson, 
thank you for your question. In what way do you reset the chart options? Try dispatching the update to the main queue by calling:
```
DispatchQueue.main.async { self.chartView.options = newOptions }
```

**Comment by ejosephwilson** [comment]
Thanks for the tip. However, that did not work. I reset the chart options the same way as you described above:
`self.chartView.options = newOptions`

**Comment by ejosephwilson** [comment]
Here is a visual comparison of the issue:
![chartafterrefresh](https://user-images.githubusercontent.com/18560418/35632405-316c004c-066c-11e8-88b2-773dafc87482.jpeg)
![chartbeforerefresh](https://user-images.githubusercontent.com/18560418/35632406-318865ac-066c-11e8-81e6-abf5efb82d07.jpeg)

**Comment by ihnatmoisieiev** [comment]
@ejosephwilson thank you for screens. It seems as a bug. I will report it.

**Comment by ejosephwilson** [comment]
Thank you!

**Comment by ihnatmoisieiev** [comment]
@ejosephwilson try to set up `fitToPlot` param to `false`, i.e.
```
options3d.fitToPlot = false
```
Can you send your code for this chart? What objects of the chart's options are changed after the update?

**Comment by ejosephwilson** [comment]
Just tried that and unfortunately the issue remains. Here is my code for the chart:

`func createTopFiveTagsChart() -> HIOptions {
        
        let options = HIOptions()
        let exporting = HIExporting()
        exporting.enabled = false
        options.exporting = exporting
        let chart = HIChart()
        let options3d = HIOptions3d()
        let events = HIEvents()
        chart.type = "column"
        chart.events = events
        options3d.enabled = true // uncomment this line to enable 3d options
        options3d.alpha = 10
        options3d.beta = 0
        options3d.depth = 150
        options3d.fitToPlot = false
        chart.options3d = options3d
        options.chart = chart
        let credits = HICredits()
        let position = HIPosition()
        // set credits.enabled to true to display text at the bottom right of the graph
        credits.enabled = false
        // set credits.enabled to true to display text at the bottom right of the graph
        credits.text = ""
        credits.href = ""
        position.y = -15
        credits.position = position
        options.credits = credits
        let legend = HILegend()
        legend.enabled = false
        options.legend = legend
        let title = HITitle()
        title.text = "Top Five Tags"
        title.x = 30
        title.align = "low"
        options.title = title
        let series = HIColumn()
        let marker = HIMarker()
        marker.enabled = false
        series.marker = marker
        series.data = restHelper.tagsEarnedArray
        series.color = HIColor(hexValue: "3CAC9E")
        series.name = " "
        options.series = [series]
        let yAxis = HIYAxis()
        let yTitle = HITitle()
        yTitle.text = ""
        yAxis.title = yTitle
        options.yAxis = [yAxis]
        let xAxis = HIXAxis()
        xAxis.categories = restHelper.nameArray
        options.xAxis = [xAxis]
        let toolTip = HITooltip()
        let formatter = HIFunction()
        formatter.function = "function() { var formatter = new Intl.NumberFormat('en-US', {style: 'currency', currency: 'USD', minimumFractionDigits: 2, }); return this.x + '<br><b>' + formatter.format(this.y) + '</b>'}"
        toolTip.formatter = formatter
        options.tooltip = toolTip
        
        return options
    }` 

The only things that get updated on refresh are:

`series.data = restHelper.tagsEarnedArray`
and
`xAxis.categories = restHelper.nameArray`

**Comment by ihnatmoisieiev** [comment]
Ok, thank you. I hope it will be fixed in the next release.

**Comment by ihnatmoisieiev** [comment]
@ejosephwilson did you try the newest release? Changing any object from the chart’s options causes the chart to be updated automatically.
