### ISSUE TITLE
How to get total data in stackedAndGroupedColumn's chart?

### ISSUE THREAD

**Issue by PankeGao** [highcharts/highcharts-ios#55]
![2018-02-07 10 29 55](https://user-images.githubusercontent.com/15138910/35896634-14411eb2-0bf8-11e8-98df-eb26bf49ce72.png)

how can get 1+2+3= ?

**Comment by PankeGao** [comment]
when click column 1 show total data(1+2+3),so does when click 2 an 3.

**Comment by ihnatmoisieiev** [comment]
Hi @PankeGao,
see this [example](https://jsfiddle.net/Lfvnraqd/2/).

**Comment by ihnatmoisieiev** [comment]
@PankeGao can I close it?
