### ISSUE TITLE
How to get click's call back(include chart's data and information)?

### ISSUE THREAD

**Issue by PankeGao** [highcharts/highcharts-ios#56]
I just want to get point or column's data and xAxis's data whith clicked on chart.
1、How can get click point or column's call back(include point's data and chart's data)?
2、How to write in OC with following property?
In HIChartEvents  @property(nonatomic, readwrite) NSString /* Function */ *click;
Is there any demo?

**Comment by ihnatmoisieiev** [comment]
Hi @PankeGao,
see [https://github.com/highcharts/highcharts-ios/issues/31](https://github.com/highcharts/highcharts-ios/issues/31).

**Comment by ihnatmoisieiev** [comment]
@PankeGao this feature is added to the newest release.
