### ISSUE TITLE
Chart transparent background?

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#57]
How can I set a transparent background for a HIChart? Thanks.

**Comment by LoOsSs** [comment]
HiChart * chart = [[HiChart alloc]init];
chart.backgroundColor = [[HIColor alloc]initWithRGBA:0 green:0 blue:0 alpha:0.0];

*important part is alpha:0.0

**Comment by ihnatmoisieiev** [comment]
Thank you @LoOsSs

**Comment by ihnatmoisieiev** [comment]
@skuske can I close this issue?

**Comment by skuske** [comment]
Sorry, yes. Sure. :o)
