### ISSUE TITLE
When will this update?

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#58]
When can we expect an update of the iOS wrapper to reflect the fixes and changes since 6.0.2?

**Comment by ihnatmoisieiev** [comment]
Hi @skuske,
I suppose next week.

**Comment by skuske** [comment]
:o) Thanks.

**Comment by skuske** [comment]
Almost 3 weeks passed now...  When can we expect an update of the iOS wrapper now?

**Comment by ihnatmoisieiev** [comment]
@skuske, sorry for the delay, because one more feature would be added to the new release.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Can be closed. :o)
