### ISSUE TITLE
formatter function doesn't display data

### ISSUE THREAD

**Issue by oleg-poliukhovych** [highcharts/highcharts-ios#6]
Hi, I am trying to implement HITooltip formatter function but it doesn't work.

sample in swift 3 (simplified for demonstration):

```
let hioptions = HIOptions()
...
let tooltip = HITooltip()
tooltip.formatter = "function() { return 'test'; }"
hioptions.tooltip = tooltip
```

<img width="487" alt="screen_shot_2017-05-25_at_12_22_45_am" src="https://cloud.githubusercontent.com/assets/26556262/26469184/ad5a9bea-41a1-11e7-9e63-313a1fb0e412.png">

**Comment by ratka6** [comment]
Hi!
We are still working on implementing javascript functions in iOS. For now they are not available. 
Krzysztof

**Comment by oleg-poliukhovych** [comment]
Thanks for very fast response!
Is there any option to provide similar functionality via available API?
I have to display custom point description according to state of this point value, can I do it somehow without formatter function?

**Comment by ratka6** [comment]
You can try with header, point and footer format. See:
http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/tooltip/footerformat/

**Comment by jagatfx** [comment]
It would be good to note this in the iOS API docs until formatter property is available.

**Comment by mll** [comment]
The 1.1.0 version introduces functions to the iOS wrapper.

**Comment by saurabhjain6853** [comment]
hello, can you give some idea how to use tooltip.formatter in iOS?
