### ISSUE TITLE
How to disable Legend Click Event?

### ISSUE THREAD

**Issue by kuldeep13990** [highcharts/highcharts-ios#60]
I want to disable legend click event and for that I tries below code but not working.

    ```
plotoptions.column.point.events.legendItemClick = false;
    plotoptions.series.point.events.legendItemClick = false;
```

how to disable legend click event?
thanks in advance.

**Comment by ihnatmoisieiev** [comment]
Hello @kuldeep13990,
try
```
plotoptions.column.point.events.legendItemClick = HIFunction(function: "function() { return false; }")
```

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev not working getting an error.
![screen shot 2018-03-08 at 3 42 12 pm](https://user-images.githubusercontent.com/5965337/37145627-563b2974-22e7-11e8-8a5b-35522e197e7f.png)

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 do you write in Swift or Objective-C?
Do you use the last 6.0.2 release?

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev  Objective-C.

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 ok, in this case try
```
plotoptions.column.point.events.legendItemClick = [[HIFunction alloc] initWithFunction:@"function() { return false; }"];
```

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev still not working.
I upload gif file.
![legend](https://user-images.githubusercontent.com/5965337/37148183-81e807ec-22ef-11e8-8abe-85ff952b616b.gif)

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 this should work:
```
plotoptions.column.events = [[HIEvents alloc] init];
plotoptions.column.events.legendItemClick = [[HIFunction alloc] initWithFunction:@"function() { return false; }"];
```

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev  Thanks a lot, now its working.
