### ISSUE TITLE
How to build pie charts with Swift ?

### ISSUE THREAD

**Issue by Karthikeyan1108** [highcharts/highcharts-ios#61]
I am trying to create a pie chart with the below code, it crashes with the message 

> GraphsDemo[22619:504021] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter is nil'

Code:
  let options = HIOptions()
        let chart = HIChart()
        chart.type = "pie"
        
        let legend = HILegend()
        legend.enabled = false
        
        let exporting = HIExporting()
        exporting.enabled = false
        
        
        let title = HITitle()
        title.text = ""
        let subtitle = HISubtitle()
        subtitle.text = ""
    
        
        let plotoptions = HIPlotOptions()
        plotoptions.pie = HIPlotOptionsPie()
        plotoptions.pie.allowPointSelect = true
        plotoptions.pie.cursor = "pointer"
        plotoptions.pie.dataLabels = HIPlotOptionsPieDataLabels()
        plotoptions.pie.dataLabels.enabled = true
        plotoptions.pie.dataLabels.format = "{point.name}: <b>{point.percentage:.1f}%</b>"
        plotoptions.pie.showInLegend = true
        
        let credits = HICredits()
        credits.enabled = false
        
        let pie = HIPie()
        pie.name = ""
        pie.data = NSMutableArray(object: [["name": "Microsoft Internet Explorer", "y": 56.33], ["name": "Chrome", "y": 24.03, "sliced": (true ? 1 : 0), "selected": (true ? 1 : 0)], ["name": "Firefox", "y": 10.38], ["name": "Safari", "y": 4.77], ["name": "Opera", "y": 0.91], ["name": "Proprietary or Undetectable", "y": 0.2]]) as! [Any]
        print(pie.data)
        options.chart = chart
        options.plotOptions = plotoptions
        options.credits = credits
        options.title = title
        options.subtitle = subtitle
        options.exporting = exporting
        options.legend = legend
        options.series = NSMutableArray(object: pie) as! [HISeries]
        pieChartView.options = options

Kindly help me to fix this issue.

**Comment by ihnatmoisieiev** [comment]
Hello @Karthikeyan1108,
do you use the last version?

See [pie chart](https://www.highcharts.com/ios/demo/pie-basic) demo.

**Comment by ihnatmoisieiev** [comment]
@Karthikeyan1108 did it resolve your problem?

**Comment by Karthikeyan1108** [comment]
@ihnatmoisieiev Thanks for the prompt reply. I will check your comments and get back to you.
