### ISSUE TITLE
How can I hide or change data labels colour if value is 0?

### ISSUE THREAD

**Issue by kuldeep13990** [highcharts/highcharts-ios#62]
I want to hide or change plotoptions.column.dataLabels if the column value is 0?
currently it loo like below image.
![simulator screen shot - iphone 8 plus - 2018-03-10 at 12 45 20](https://user-images.githubusercontent.com/5965337/37239410-47fda8ca-2461-11e8-98ff-c8839d5c2129.png)

1. Now I want to hide that 0 display in columns. how can do this?
2. Can I add any Prefix value to this dataLabels like **$** **Rs.** ?
thanks in advance.

**Comment by TorsteinHonsi** [comment]
0 is also a value. Did you consider using `null` instead?

**Comment by ihnatmoisieiev** [comment]
Hello @kuldeep13990, 
try:
```
plotoptions.column.dataLabels.formatter = HIFunction(function: "function() { if(this.y > 0) return this.y; }")
```
and
```
plotoptions.column.dataLabels.format = "$ Rs. {y}"
```

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev can you please provide this in objective C?

**Comment by kuldeep13990** [comment]
Thanks @TorsteinHonsi  and @ihnatmoisieiev 
by using @ihnatmoisieiev code, now 0 value is not displayed in chart. thanks a lot.

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 can I close the issue?

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev  sorry for late response, you can close this question. Thanks
