### ISSUE TITLE
Dynamic Charts

### ISSUE THREAD

**Issue by williamcaruso** [highcharts/highcharts-ios#63]
When can we expect to see the dynamic chart ability (that one can currently achieve using HIEvent --> HIFunction --> and provide a JavaScript snippet).

Example: https://www.highcharts.com/ios/demo/dynamic-update/sand-signika

It would be great if the HIFunction could connect with Obj-C  code!!

**Comment by ihnatmoisieiev** [comment]
Hi @williamcaruso,
I suppose it would be added this week.

**Comment by ihnatmoisieiev** [comment]
@williamcaruso this feature is added to the newest release. Can I close this issue?
