### ISSUE TITLE
How to unhighlight the HILine names initially in HighChart for ios

### ISSUE THREAD

**Issue by tripathishivam35** [highcharts/highcharts-ios#64]
I referred this demo  : https://www.highcharts.com/ios/demo/line-basic

What i want to achieve is initially draw one line with all the line names remain unhighlighted. As user press on unhighlighted cells it will make it highlight and draw corresponding graph. How to achieve this.

**Comment by ihnatmoisieiev** [comment]
Hello @tripathishivam35, 
you need to set up `visible` param to `false` for series that you want to unhighlight.
See [docs](https://api.highcharts.com/ios/highcharts/series.line.visible).

**Comment by tripathishivam35** [comment]
I am doing like this but it is of no effect ,
HILine *line10 = [[HILine alloc]init];
    line10.name = @"July";
    [line10 setVisible:false];
    line10.data = [NSMutableArray arrayWithObjects:@1408, @548, @105, @1128, @899, @1816, @1824, @1811, nil];
    HIResponsive *responsive = [[HIResponsive alloc] init];
    
    HIRules *rules1 = [[HIRules alloc] init];
    rules1.condition = [[HICondition alloc] init];
    rules1.condition.maxWidth = @500;
    rules1.chartOptions = @{
                            @"legend" : @{
                                    @"layout": @"horizontal",
                                    @"align": @"center",
                                    @"verticalAlign": @"bottom"
                                    }
                            };
    responsive.rules = [NSMutableArray arrayWithObjects:rules1, nil];
    options.title = title;
    options.yAxis = [NSMutableArray arrayWithObject:yaxis];
    options.legend = legend;
    options.plotOptions = plotoptions;
    options.series = [NSMutableArray arrayWithObjects:line1, line2, line3, line4, line5,line6,line7,line8,line9,line10, nil];
    
    options.responsive = responsive;
    self.chartView.options = options;
where line1,2... are all initialised with some values like like line 10.
How to set visible to false for series?

**Comment by ihnatmoisieiev** [comment]
@tripathishivam35, 
`line10.visible = [[NSNumber alloc] initWithBool:false];` or `[line10 setVisible:[[NSNumber alloc] initWithBool:false]];`
