### ISSUE TITLE
Change months and days language

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#65]
Hello,

I'm trying to have my month and days displayed in my language (French) and I'm unable to do that.

Here is a screenshot of what I've (months in English)
<img width="287" alt="screen shot 2018-03-13 at 14 14 46" src="https://user-images.githubusercontent.com/726972/37343789-e7760190-26c8-11e8-83ba-8e54c8d02e8f.png">
I'd like to have them in French.

I tried that:

```
let lang = HILang()
lang.months = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août","Septembre", "Octobre", "Novembre", "Décembre"]
lang.weekdays = ["Dimanche","Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi"]
        
lineChartView.lang = lang // lineChartView is a HIChartView object
```

It doesn't work.

I read the doc, it's said to use the HiCharts.setOptions
https://api.highcharts.com/highcharts/lang
but I don't understand how to do that.

Please help me.

Regards,
Alexandre

**Comment by ihnatmoisieiev** [comment]
Hello @AlexandreMinard,
the `lang` object should be set upped before the `options` object.

**Comment by AlexandreMinard** [comment]
any code for me?

**Comment by ihnatmoisieiev** [comment]
@AlexandreMinard please:
```
let lang = HILang()
lang.resetZoom = "My reset zoom button"
chartView.lang = lang

let options = HIOptions()
....
chartView.options = options
```

**Comment by AlexandreMinard** [comment]
you're welcome

I'm already doing that, and the legend remains "feb" and not "fev"

**Comment by AlexandreMinard** [comment]
I found my mistake :)
I was not setting the shortMonths but the months
it's working now :)

**Comment by ihnatmoisieiev** [comment]
Can I close it?
