### ISSUE TITLE
Links in documentation are wrong

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#66]
for instance, good link is 

`https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/area-fillopacity/`

but link in HiAreaspline.h is

`https://jsfiddle.net/gh/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/area-fillopacity/`

**Comment by ihnatmoisieiev** [comment]
@AlexandreMinard thank you for reporting an issue!

**Comment by ihnatmoisieiev** [comment]
@AlexandreMinard it is fixed in the newest release. Can I close it?

**Comment by AlexandreMinard** [comment]
yes thanks!
