### ISSUE TITLE
Add additional data to tooltip in iOS which does not belongs to x&y-axis of graph.

### ISSUE THREAD

**Issue by tripathishivam35** [highcharts/highcharts-ios#67]
I followed this demo to draw Column charts.
(https://www.highcharts.com/ios/demo/column-rotated-labels).

What Issue I am facing is : I can easily show x-axis and y-axis information in tooltip. But I am not able to put additional information in tooltip from a different array (suppose array for depicting required qty for item).

I tried to do like this ;
 1. tooltip.pointFormat = [NSString stringWithFormat:@"Velocity : <b>{point.y:.2f}</b> <br> Remaining Quantity : <b>%@</b>",RemainingQtyArray];
It will print whole array in tooltip.
2.  tooltip.pointFormat = [NSString stringWithFormat:@"Velocity : <b>{point.y:.2f}</b> <br> Remaining Quantity : <b>%@</b>",RemainingQtyArray[i++]];
It will print last item from array.

So, how can i put additional info so that when anyone taps on graph, it will show this info too.

**Comment by tripathishivam35** [comment]
![screen shot 2018-03-20 at 1 17 14 pm](https://user-images.githubusercontent.com/13601158/37641818-21814b06-2c41-11e8-910a-5580521ea9aa.png)

I want tooltip like this.

**Comment by ihnatmoisieiev** [comment]
Hello @tripathishivam35,
thank you for your question. 
You need to adjust your different array with data from your series. So, for example, your series data could be an array of dictionaries:
```
series.data = [NSMutableArray arrayWithObjects:@{
                                                     @"quantity": @431,
                                                     @"time": @"8 Day and 19 Hour",
                                                     @"y": @2.04,
                                                     @"sold": @49
                                                }, ...
```
Then showing those values in the tooltip is the same as for x-axis and y-axis:
```
tooltip.pointFormat = @"Remaining Quantity: <b>{point.quantity}</b> <br /> Time Left for Soldout: <b>{point.time}</b> <br /> Velocity: <b>{point.y}</b> <br /> Sold Qty(last 24 Hours): <b>{point.sold}</b>";
```

**Comment by tripathishivam35** [comment]
I was able to solve my problem with above approach.

**Comment by ihnatmoisieiev** [comment]
@tripathishivam35 ok, also your series data could be an array of `HIData` objects : 
```
HIData *data1 = [[HIData alloc] init];
data1.name = @"Shanghai";
data1.y = @23.7;
    
HIData *data2 = [[HIData alloc] init];
data2.name = @"Lagos";
data2.y = @16.1;
...

series.data = [NSMutableArray arrayWithObjects:data1, data2, ... ,  nil];
```

**Comment by saurabhjain6853** [comment]
It not show any data on tooltip
      ```
   var tooltipData = [Any]()
           for j in 0 ..< arrLists.count {
               let dictX = arrLists[j] as! NSDictionary
               
                let dataDic = [
                    "speed":"\(dictX.object(forKey: "speed") ?? "0")",
                    "distance":"\(dictX.object(forKey: "dist") ?? "0")",
                    "user":mdlMylaps.LapUsrFullNames ?? "",
                    "accel_x":"\(dictX.object(forKey: "accel_x") ?? "0")",
                    "accel_y":"\(dictX.object(forKey: "accel_y") ?? "0")",
                    "accel_z":"\(dictX.object(forKey: "accel_z") ?? "0")",
                    "brake_calc":"\(dictX.object(forKey: "brake_calc") ?? "0")",
                    "acc_calc":"\(dictX.object(forKey: "acc_calc") ?? "0")",
                    "brake_on":"\(dictX.object(forKey: "brake_on") ?? "0")",
                    "acc_on":"\(dictX.object(forKey: "acc_on") ?? "0")"] as! [String : String]
                tooltipData.append(dataDic)
            }
         let plotOptions = HIPlotOptions()
         plotOptions.series = HISeries()
         plotOptions.series.data = tooltipData

        tooltip.pointFormat = "Speed:<b>{point.speed}</b>"

        options.series = dataSets
        options.plotOptions = plotOptions
        graphViews.options = options
```
