### ISSUE TITLE
How to stop initial bar animation from bottom to top?

### ISSUE THREAD

**Issue by kuldeep13990** [highcharts/highcharts-ios#68]
I want to instantly load chart so I don't need bar animation display in below image.
![animation](https://user-images.githubusercontent.com/5965337/37711351-6e8912b2-2d36-11e8-9978-317131522153.gif)

how can I do this?
thanks in advance.

**Comment by pawelfus** [comment]
Hi @kuldeep13990 

Thank you for contacting us. If you have questions, please contact our support: https://www.highcharts.com/support We use github issue as bug reports, not support tickets.

PS: To answer your question: https://api.highcharts.com/highcharts/series.column.animation

**Comment by ihnatmoisieiev** [comment]
Hello @kuldeep13990,
```
plotOptions.column.animation = HIAnimation()
plotOptions.column.animation.duration = 0
```
Thanks @pawelfus.

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev , thanks for your help, thank you so much,
