### ISSUE TITLE
HIColumn - tooltip 'followTouchMove' not working

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#70]
On a HIColumn series, HITooltip "followTouchMove" does not work.

```
    HITooltip *tooltip = [[HITooltip alloc]init];
    tooltip.followTouchMove=[[NSNumber alloc] initWithBool:true];
```

That does not make the tooltip follow any touches. I must release the finger and touch another column to make the tooltip appear for that column.

It works fine for area, areaspline, spline etc. (did not test all types, though), but not for columns.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
thank you for the reporting. It is a bug in the Highcharts. 
For more info see: [https://github.com/highcharts/highcharts/issues/7484](https://github.com/highcharts/highcharts/issues/7484)

**Comment by skuske** [comment]
Hello @ihnatmoisieiev,

will this be fixed with the upcoming update of the wrapper?

**Comment by ihnatmoisieiev** [comment]
@skuske I guess it won't be fixed with the upcoming update, because it isn't a wrapper's bug.

**Comment by skuske** [comment]
@ihnatmoisieiev 

understood, but: the wrapper is build upon Highcharts, so: it is a bug. I just wanted to know if the upcoming update of the wrapper will include an updated version of Highcharts which fixes this.

**Comment by ihnatmoisieiev** [comment]
@skuske no, because it is not fixed in Highcharts yet.

**Comment by skuske** [comment]
@ihnatmoisieiev

This issue is open since Dec 2017 - no update since then. When can we expect that this gets fixed?

https://github.com/highcharts/highcharts/issues/7484

**Comment by sebastianbochan** [comment]
Hi @skuske,
I sent the main bug (Highcharts) to our developers and someone will answer [here](https://github.com/highcharts/highcharts/issues/7484) as soon as possible.

**Comment by skuske** [comment]
@sebastianbochan 

I see that the original bug has been fixed. However, the current iOS wrapper does not seem to have the fix included. When will this be done? Thanks.

**Comment by skuske** [comment]
@pawelfus 

13 days passed now - when will the updated wrapper be released?

Thanks.

**Comment by skuske** [comment]
@pawelfus 

The iOS wrapper v6.1.2 does not really fix the issue as the tooltip does not update according to the column below the finger. It displays the data for the column that is initially touched, but if you move the finger, the tooltip does not update - it displays the data for the initially touched column, and you need to release the finger and touch a new column in order to update the tooltip.

**Comment by pawelfus** [comment]
Thank you for info @skuske !

Let me reopen issue on the main repo.
