### ISSUE TITLE
How can I set pass Column data as String instead of number?

### ISSUE THREAD

**Issue by kuldeep13990** [highcharts/highcharts-ios#71]
I want to show some text content like **good, bad, Poor** on Stacked Bar. like below image, I rotate labels using this. How can I display this string?

```
column1.dataLabels = [[HIDataLabels alloc]init];
column1.dataLabels.rotation = @-90;
```
I know that text can be append using below line. but how can I do it dynamically as display in below image?

`plotoptions.column.dataLabels.formatter = [[HIFunction alloc] initWithFunction:@"function() { if(this.y > 0) return 'Poor'}"];`

How can I hide only 1st column text like below?

![screen shot 2018-03-23 at 5 53 49 pm](https://user-images.githubusercontent.com/5965337/37829249-566ade92-2ec4-11e8-813b-a2d8df3ac7f3.png)

**or how can I replace red Colour text with my custom text like good, bad, poor?**

![screen shot 2018-03-23 at 5 56 30 pm](https://user-images.githubusercontent.com/5965337/37829283-73a6027a-2ec4-11e8-874e-f08333396027.png)

I also review this link but I didn't found any solution. : https://www.highcharts.com/ios/demo

I found something like this, http://jsfiddle.net/yybLxgkd/2/

```
stackLabels: {
    qTotals: ['This','is','a','qTotal','!'],
    enabled: true,
    style: {
        fontWeight: 'bold'
    },
    formatter: function() {            
        return this.options.qTotals[this.x];
    }
}
```

`yAxis.stackLabels` doesn't have any property like `qTotals`
how can I implement in Objective C?
Thanks in advance.

**Comment by ihnatmoisieiev** [comment]
Hello @kuldeep13990,
follow this [demo](https://www.highcharts.com/ios/demo/column-stacked) and change only `stackLabels` for `yAxis`, e.g.
```
yaxis.stackLabels = [[HIStackLabels alloc]init];
yaxis.stackLabels.enabled = [[NSNumber alloc] initWithBool:true];
yaxis.stackLabels.formatter = [[HIFunction alloc] initWithFunction:@"function() { if(this.total > 9) return 'Good'; }"];
```

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev Thanks for your help.

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev  Thanks for your help. 
![simulator screen shot - iphone 8 plus - 2018-03-26 at 14 11 54](https://user-images.githubusercontent.com/5965337/37895728-cd263422-30ff-11e8-8fec-d2b64d06629a.png)
I want to show this result string based on Only Red Bar value and can I use if statement like this? 

`yaxis.stackLabels.formatter = [[HIFunction alloc] initWithFunction:@"function() { if(this.total > 80) return 'Poor'; if(this.total > 70) return 'Average'; if(this.total > 25) return 'Below Average'; if(this.total > 9) return 'Good';}"];` 

When I replace `this.total` with `this.y` it doesn't display anything. 
How can I do this?

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 ok, if you want to show this on specific columns, you need to set up `dataLabels` for your series in `plotOptions`, e.g.
```
plotoptions.column.dataLabels = [[HIDataLabels alloc]init];
plotoptions.column.dataLabels.enabled = [[NSNumber alloc] initWithBool:true];
plotoptions.column.dataLabels.formatter = [[HIFunction alloc] initWithFunction:@"function() { if(this.y > 2) return 'Good';}"];
```
For more info see [docs](https://api.highcharts.com/ios/highcharts/plotOptions.column.dataLabels).

**Comment by kuldeep13990** [comment]
I want to show column2 and for that I disable column data using this.
`column2.dataLabels.enabled = [NSNumber numberWithInteger:0];`

If I didn't hide column2 dataLabels than below code works for column2 but after hiding column2 dataLabels below code does not display for column1. am I missing something?

`plotoptions.column.dataLabels.formatter = [[HIFunction alloc] initWithFunction:@"function() { if(this.y == 60) return 'Poor'; if(this.y == 30) return 'Average'; if(this.y == 20) return 'Below Average'; if(this.y == 11) return 'Good';}"];`

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 in this case set up `dataLabels` for specific column separately and remove it from `plotOptions`:

column2.dataLabels = [[HIDataLabels alloc] init];
column2.dataLabels.enabled = [[NSNumber alloc] initWithBool:true];
column2.dataLabels.formatter =  [[HIFunction alloc] initWithFunction:@"function() { if(this.y == 60) return 'Poor'; if(this.y == 30) return 'Average'; if(this.y == 20) return 'Below Average'; if(this.y == 11) return 'Good';}"];

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev  Thanks you very much. Now you can close this question.
