### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#72]
File HIData.h

@interface HIData: HIChartsJSONSerializable

/**
* description: The wind speed in meters per second. => not good...
*/
@property(nonatomic, readwrite) NSNumber *value;

**Comment by ihnatmoisieiev** [comment]
@AlexandreMinard thank you for the reporting.

**Comment by AlexandreMinard** [comment]
looks better :)
