### ISSUE TITLE
set font to HIXAxis  categories

### ISSUE THREAD

**Issue by vnanaware** [highcharts/highcharts-ios#73]
How to set font to HIXAxis  categories?

**Comment by ihnatmoisieiev** [comment]
Hi @vnanaware,
set up `style` object for `xAxis.labels`. 
See [docs](https://api.highcharts.com/ios/highcharts/xAxis.labels.style).

**Comment by ihnatmoisieiev** [comment]
@vnanaware did you try it and can I close this issue?
