### ISSUE TITLE
6.0.7 not available via Cocoapods yet

### ISSUE THREAD

**Issue by speedoholic** [highcharts/highcharts-ios#74]
As per the current details available at Cocoapods website: https://cocoapods.org/pods/Highcharts

And this project's [pod spec](https://github.com/CocoaPods/Specs/blob/master/Specs/3/d/5/Highcharts/6.0.2/Highcharts.podspec.json)

The latest version (6.0.7) is not yet available via Cocoapods.

Can you please update the **Readme** file or the **pod spec** accordingly?
This will ensure that users don't get any trouble while trying to install  **pod 'Highcharts', '~> 6.0.7'**

PFB the command line log for your reference:

```
[!] CocoaPods could not find compatible versions for pod "Highcharts":
  In Podfile:
    Highcharts (~> 6.0.7)

None of your spec sources contain a spec satisfying the dependency: `Highcharts (~> 6.0.7)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

```

**Comment by ihnatmoisieiev** [comment]
Hello @speedoholic,
thank you for the reporting. We are currently working to solve it.

**Comment by ihnatmoisieiev** [comment]
@speedoholic it's fixed. Please try again.

**Comment by ihnatmoisieiev** [comment]
@speedoholic can I close this issue?

**Comment by speedoholic** [comment]
@ihnatmoisieiev yes please. Thanks for your prompt action.
