### ISSUE TITLE
How to Limit decimal point to 2 digits in ToolTip view?

### ISSUE THREAD

**Issue by kuldeep13990** [highcharts/highcharts-ios#75]
My array contains data something like this..
`<__NSArrayM 0x60400025ec30>(0, 127, 0, 0, 0, 76.2, 0, 482.6)`

I passed that array data to HIColumn when I click on particular bar, ToolTip display with too many decimal point after amount.

![screen shot 2018-03-29 at 12 32 50 pm](https://user-images.githubusercontent.com/5965337/38074836-dba13024-334d-11e8-9475-819298027d0f.png)

How can I limit decimal point to 2 digits?
Thanks in advance.

**Comment by ihnatmoisieiev** [comment]
Hi @kuldeep13990,
to limit decimal point to 2 digits use `{point.y:.2f}` in your `tooltip.pointFormat`.
For more info see [docs](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting).

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev  Thanks, You can close this question.
