### ISSUE TITLE
Set Specific Range on X-Axis.

### ISSUE THREAD

**Issue by tripathishivam35** [highcharts/highcharts-ios#76]
I am following This Charts Demo 
[https://www.highcharts.com/ios/demo/line-basic].
I want to set specific Range on X-axis like this
 "range": ["04","05","06",
    "07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","00","01","02","03","04" ].
What I am noticing it is taking values automatically based on starting point. How can i set specific range?

**Comment by ihnatmoisieiev** [comment]
Hi @tripathishivam35,
see `pointStart ` and `pointInterval ` in [docs](https://api.highcharts.com/ios/highcharts/series.line.pointStart).

**Comment by tripathishivam35** [comment]
@ihnatmoisieiev  I can define pointStart with @4 and pointInterval with @1 but I want to know how could i put 00 after 23 as mentioned in above thread. As I am defining an interval of 24 it is taking as 4 to 28. How could i put in this order "range": ["04","05","06",
"07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","00","01","02","03","04" ].

**Comment by ihnatmoisieiev** [comment]
@tripathishivam35 try to add it to categories:
```
xAxis.categories = ["04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","00","01","02","03","04" ]
```

**Comment by tripathishivam35** [comment]
I put it but there is no effect on graph:
    xaxis.categories = [NSArray arrayWithObjects:@"04",@"05",@"06",@"07",@"08",@"09",@"10",@"11",@"12",@"13",@"14",@"15",@"16",@"17",@"18",@"19",@"20",@"21",@"22",@"23",@"00",@"01",@"02",@"03",@"04", nil];

**Comment by ihnatmoisieiev** [comment]
@tripathishivam35 did you add xAxis to your `options`? Can you send a piece of your code?

**Comment by tripathishivam35** [comment]
Yes, Its working. I missed to add xAxis to code.
