### ISSUE TITLE
How to get group name by the click event?

### ISSUE THREAD

**Issue by maple101leaf** [highcharts/highcharts-ios#77]
In v6.0.7, we can use the event to capture the click event in swift. But we can not precise positioning which bar be clicked by a user. Example code: 

            let column = HIColumn()
            column.tooltip = HITooltip()
            column.tooltip.headerFormat = ""
            column.tooltip.valueSuffix = " kcal"
            column.showInLegend = false
            column.data = series
            column.name = options["title"] as! String            
            column.events = HIEvents()
            column.events.click = HIFunction(closure: { (context) in
                print("Series tapped")
                guard let context = context else {return}
                print(context.getProperty("name"))
            }, properties: ["name", "index"])
we only can get the name and index by the property, but we can not get the group name. we are data is the group bar chart. So how to get this bar's information? Like the group name, value, and other detail information.....

**Comment by ihnatmoisieiev** [comment]
Hi @maple101leaf,
I don't understand what you want to get exactly, but I suppose you need to add this event to `point` instead of `series`, i.e.
```
column.point = HIPoint()
column.point.events = HIEvents()
column.point.events.click = HIFunction(closure: { (context) in
     print("Point tapped")
     guard let context = context else {return}
     print(context.getProperty("y"))
}, properties: ["y"])
```

**Comment by maple101leaf** [comment]
@ihnatmoisieiev Thank you reply, I had found this event.
