### ISSUE TITLE
How to customise ToolTip?

### ISSUE THREAD

**Issue by kuldeep13990** [highcharts/highcharts-ios#78]
I want to add Text content in ToolTip. and for that I have tried below code.

```
HIColumn *column1 = [[HIColumn alloc]init];
    column1.name = @"Actual";
    column1.data = [NSMutableArray arrayWithArray:arrColumn1Data];
    column1.dataLabels = [[HIDataLabels alloc]init];
    column1.dataLabels.rotation = @-90;
    column1.dataLabels.enabled = [NSNumber numberWithInteger:1];
    column1.dataLabels.formatter = [[HIFunction alloc] initWithFunction:@"function() { if(this.y == 60) return 'Excellent'; else if(this.y == 30) return 'Good'; else if(this.y == 20) return 'BB'; else if(this.y == 11) return 'AA';}"];
```

![simulator screen shot - iphone 8 plus - 2018-03-30 at 12 20 44](https://user-images.githubusercontent.com/5965337/38127728-0d2327f2-3415-11e8-8805-242fcbcff391.png)

Now I  want is, when I click on any of the **Excellent, Good, AA, BB** bar I want to display that string  in ToolTip.

![simulator screen shot - iphone 8 plus - 2018-03-30 at 12 20 49](https://user-images.githubusercontent.com/5965337/38127780-44adc89e-3415-11e8-932a-3f19d71736bb.png)

**Rating: Excellent or Rating: Good or Rating: AA or Rating: BB**

for that I have tried below code but nothing display in rating.

```
tooltip.pointFormat = @"{series.name}: {point.y}<br/>Rating: { if(this.y == 60) return 'Excellent'; else if(this.y == 30) return 'Good'; else if(this.y == 20) return 'BB'; else if(this.y == 11) return 'AA';}";
    tooltip.headerFormat = @"<b>{point.x}</b><br/>";
```

**and**

```
tooltip.pointFormat = @"{series.name}: {point.y}<br/>Rating: { if(point.y == 60) return 'Excellent'; else if(point.y == 30) return 'Good'; else if(point.y == 20) return 'BB'; else if(point.y == 11) return 'AA';}";
    tooltip.headerFormat = @"<b>{point.x}</b><br/>";
```

If I pass Static text like this than it works. but I want like above dynamically based on value.
`tooltip.pointFormat = @"{series.name}: {point.y}<br/>Rating: Good}";`

I also refer this but it have static text : http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/tooltip/format/

If I use below code than it displays only Text.
`tooltip.formatter = [[HIFunction alloc] initWithFunction:@"function() { if(this.y == 60) return 'Excellent'; else if(this.y == 30) return 'Good'; else if(this.y == 20) return 'BB'; else if(this.y == 11) return 'AA';}"];`
How can I do this?
Thanks in advance.

**Comment by ihnatmoisieiev** [comment]
Hi @kuldeep13990,
you should to use `formatter` for it. Try change your formatter function to:
```
tooltip.formatter = [[HIFunction alloc] initWithFunction:@"function() { if(this.point.y == 60) return 'Excellent'; else if(this.point.y == 30) return 'Good'; else if(this.point.y == 20) return 'BB'; else if(this.point.y == 11) return 'AA'; else return ''; }"];
```

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev , Thanks for your help. It display only Text like this.

![simulator screen shot - iphone 8 plus - 2018-03-30 at 14 46 16](https://user-images.githubusercontent.com/5965337/38132566-2ff08ee6-3429-11e8-9f55-8e78a4b95c45.png)

but I want something like this.

![simulator screen shot - iphone 8 plus - 2018-03-30 at 14 47 34](https://user-images.githubusercontent.com/5965337/38132631-6fa5396a-3429-11e8-8c34-663bcd13d282.png)

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 modify formatter function and get what you want, e.g.
```
tooltip.formatter = [[HIFunction alloc] initWithFunction:@"function() { var tooltip = '<b>' + this.x + '</b><br/>'; tooltip += this.series.name + ': ' + this.point.y + '<br/>'; if(this.point.y == 2) return tooltip + 'Rating: Excellent'; else if(this.point.y == 30) return tooltip + 'Rating: Good'; else if(this.point.y == 20) return tooltip + 'Rating: BB'; else if(this.point.y == 11) return tooltip + 'Rating: AA'; else return tooltip; }"];
```

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 can I close it?

**Comment by kuldeep13990** [comment]
Yes, you can close this question. Thanks for your helps.

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev  I want to limit 2 decimal points in below function. 

`tooltip.formatter = [[HIFunction alloc] initWithFunction:@"function() { var tooltip = '<b>' + this.x + '</b><br/>'; tooltip += this.series.name + ': ' + this.point.y + '%<br/>'; if(this.y >= 2 && this.y <= 5) return tooltip + 'Rating: Essential fat'; else if(this.y >= 6 && this.y <= 13) return tooltip + 'Rating: Athlete'; else if(this.y >= 14 && this.y <= 17) return tooltip + 'Rating: Fitness'; else if(this.y >= 18 && this.y <= 24) return tooltip + 'Rating: Average'; else if(this.y >= 25) return tooltip + 'Rating: Obese'; else return tooltip; }"];`

how can I do this?

**Comment by ihnatmoisieiev** [comment]
See [https://github.com/highcharts/highcharts-ios/issues/80](https://github.com/highcharts/highcharts-ios/issues/80).
