### ISSUE TITLE
After updating to 6.0.7, getting HIFunction Error.

### ISSUE THREAD

**Issue by kuldeep13990** [highcharts/highcharts-ios#79]
After updating 6.0.2 to 6.0.7, I am getting too many errors of `HIFunction` `No visible @interface for 'HIFunction' declares the selector 'initWithFunction:'`

`6.0.2 --> plotoptions.column.events.legendItemClick = [[HIFunction alloc] initWithFunction:@"function() { return false; }"];`

I tried below but chart is not generating?

`6.0.7 --> plotoptions.column.events.legendItemClick = [[HIFunction alloc] initWithJSFunction:@"function() { return false; }"];`

Please help me.
Thanks

**Comment by ihnatmoisieiev** [comment]
Hi @kuldeep13990,
do you create `events` object by `plotoptions.column.events = [[HIEvents alloc] init];`?
```
plotoptions.column.events.legendItemClick = [[HIFunction alloc] initWithJSFunction:@"function() { return false; }"];
```
works perfectly for me.
Can you send a piece of your code?

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev , 2 days ago, it doesn't generate chart so I downgrade version to 6.0.2 and now I updated to 6.0.7, now chart is generate.

In previous version, chart works fine.
after updated to new version I replace only 1 thing `initWithFunction` to `initWithJSFunction`.

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 it is impossible. 2 days ago and current it is the same version. Is it working now?

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev , yes now it is working.
