### ISSUE TITLE
HIGChartView size and position

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#8]
Hi all,

I spend one day on this, so I'm willing to share my experience to save you some time...

When creating a HIGChartView, you MUST set the origin (x,y) to (0,0), then set the options and finally you can change the (x,y) of the view to what you need.

If you create the HIGChartView with its origin different of (0,0) the chart inside the view will be offset and then everythings sucks :(

Hope this will help someone.

Regards,
Alexandre

**Comment by ratka6** [comment]
Thanks! I didn't know about this bug. This is still BETA so we have a lot of work ahead.

**Comment by AlexandreMinard** [comment]
good luck for that!

**Comment by sebastianbochan** [comment]
Hi @AlexandreMinard
I apologize for late reply. The issue will be resolved until 20th July.

**Comment by mll** [comment]
Hi @AlexandreMinard we are close to publishing a new version that fixes the issue.

**Comment by mll** [comment]
The 1.1.0 version resolves this issue.
