### ISSUE TITLE
how to limit 2 decimal point after value in toolTip?

### ISSUE THREAD

**Issue by kuldeep13990** [highcharts/highcharts-ios#80]
I want to limit 2 decimal point after value in toolTip.

If I use `pointFormat` like this than it works.
`tooltip.pointFormat = @"{series.name}: {point.y:.2f}<br/>";`

but I use `formatter` like below.
`tooltip.formatter   = [[HIFunction alloc] initWithFunction:@"function() { var tooltip = '<b>' + this.x + '</b><br/>'; tooltip += this.series.name + ': ' + this.point.y + ' %<br/>'; if(this.y >= 2 && this.y <= 5) return tooltip + 'Rating: Essential fat'; else if(this.y >= 6 && this.y <= 13) return tooltip + 'Rating: Athlete'; else if(this.y >= 14 && this.y <= 17) return tooltip + 'Rating: Fitness'; else if(this.y >= 18 && this.y <= 24) return tooltip + 'Rating: Average'; else if(this.y >= 25) return tooltip + 'Rating: Obese'; else return tooltip; }"];`

I replace in above `formatter` something like this but chart not generate.

`this.point.y` --> `this.point.y:.2f`
`this.point.y` -->` {this.point.y:.2f}`

How to do this?
thanks in advance.

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990,
you can round to 2 decimals by using the `Highcharts.numberFormat()` in your formatter function:

`
tooltip.formatter = [[HIFunction alloc] initWithFunction:@"function() { var tooltip = '<b>' + this.x + '</b><br/>'; tooltip += this.series.name + ': ' + Highcharts.numberFormat(this.point.y, 2) + ' %<br/>'; if(this.y >= 2 && this.y <= 5) return tooltip + 'Rating: Essential fat'; else if(this.y >= 6 && this.y <= 13) return tooltip + 'Rating: Athlete'; else if(this.y >= 14 && this.y <= 17) return tooltip + 'Rating: Fitness'; else if(this.y >= 18 && this.y <= 24) return tooltip + 'Rating: Average'; else if(this.y >= 25) return tooltip + 'Rating: Obese'; else return tooltip; }"];
`

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev , thanks for your reply and help, it works.
can I ask you 1 more question?

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 yes, of course.

**Comment by kuldeep13990** [comment]
Here is my `HILegend` code.

```
HILegend *legend = [[HILegend alloc]init];
    legend.align = @"center";
    //legend.x = @-20;
    legend.verticalAlign = @"bottom";
    legend.reversed = [NSNumber numberWithInteger:1];
    //legend.y = @0;
    legend.width = [NSNumber numberWithFloat:[UIScreen mainScreen].bounds.size.width - 40]; // PACKAGE WIDTH
    legend.itemDistance = [NSNumber numberWithInt:10];               // PADDING BETWEEN PACKAGES
    legend.floating = [[NSNumber alloc] initWithBool:true];
    legend.backgroundColor = [[HIColor alloc]initWithName:@"white"]; // PACKAGES BACKGROUND COLOR
    legend.borderColor = [[HIColor alloc]initWithHexValue:@"ccc"];   // PACKAGES TEXT COLOR
    legend.borderWidth = @1;
    legend.shadow = [[NSNumber alloc] initWithBool:false];
    //legend.enabled = [[NSNumber alloc] initWithBool:false];           // HIDE OR SHOW BELOW PACKAGE NAMES
    legend.symbolRadius = [NSNumber numberWithInteger:0];   // SHOW SQUARE OR ROUND LEGEND SYMBOL
```

so the output is like this.
![current](https://user-images.githubusercontent.com/5965337/38187453-51884ad2-3675-11e8-98de-92babe23fed9.png)


but I require it like this.
![require](https://user-images.githubusercontent.com/5965337/38187468-5bcbe9ae-3675-11e8-86d0-2239ba54dd13.png)


if u use `legend.itemDistance = [NSNumber numberWithInt:10];   ` this is static space, if I run this code in iPad it not looks. how to do this dynamic? like leading for goal and trailing for actual space are same?

**Comment by ihnatmoisieiev** [comment]
@kuldeep13990 thank you for your question. Unfortunately, the only way is setting up `legend.itemDistance`. For example, you can check the device and based on this properly add `itemDistance` to your `legend`.

**Comment by kuldeep13990** [comment]
@ihnatmoisieiev Okay, thanks
