### ISSUE TITLE
HIColumn for HIDrilldown 

### ISSUE THREAD

**Issue by vnanaware** [highcharts/highcharts-ios#83]
How to create  HIColumn unique object in for loop?

**Comment by ihnatmoisieiev** [comment]
@vnanaware can you write more details?

**Comment by vnanaware** [comment]
let drillDown=HIDrilldown()
        let dColumn1=HIColumn()
        let dColumn2=HIColumn()
        let dColumn3=HIColumn()
        let dColumn4=HIColumn()
        let dColumn5=HIColumn()
        
        dColumn1.name="Person 1"
        dColumn2.name="Person 2"
        dColumn3.name="Person 3"
        dColumn4.name="Person 4"
        dColumn5.name="Person 5"
        
        dColumn1.id="Person 1"
        dColumn2.id="Person 2"
        dColumn3.id="Person 3"
        dColumn4.id="Person 4"
        dColumn5.id="Person 5"
        
        dColumn1.data=[["Task 1", 56.33], ["Task 2",17.2], ["Task 3", 8.11]]
        dColumn2.data=[["Task 1", 5], ["Task 2",4.32], ["Task 3", 3.68], ["Task 4" , 2.96], ["Task 5",2.53], ["Task 6",1.45]]
        dColumn3.data=[["Task 1", 2.76], ["Task 2",2.32], ["Task 3", 2.31], ["Task 4" , 1.27], ["Task 5",1.02], ["Task 6",0.33]]
        dColumn4.data=[["Task 1", 2.76], ["Task 2",0.32], ["Task 3", 2.31], ["Task 4" , 1.27], ["Task 5",1.02], ["Task 6",0.33]]
        dColumn5.data=[["Task 1", 2.76], ["Task 2",0.32], ["Task 3", 2.31], ["Task 4" , 1.27], ["Task 5",1.02], ["Task 6",0.33]]
        
        drillDown.series=[dColumn1, dColumn2, dColumn3, dColumn4, dColumn5]

**Comment by vnanaware** [comment]
Above is the my static code, Now I want to display live data, I don't  no how many records will come from server, So I want to  create object of HIColumn()  in for loop. Hows it ?

**Comment by vnanaware** [comment]
for i in 0  ..< self.arrMainData.count
        {
             let drillDown=HIDrilldown()
            let clm1 = HIColumn()
            var strEmpName=""
            
            strEmpName=self.arrEmpName_List.object(at: i) as! String
            
            clm1.name="\(strEmpName)"
            clm1.id="\(strEmpName)"
            
            clm1.data=[["Task 1", 56.33], ["Task 2",17.2], ["Task 3", 8.11]]
            drillDown.series=[clm1]
            options.drilldown=drillDown
        }

**Comment by ihnatmoisieiev** [comment]
@vnanaware e..g you can have an array of `HIColumn ` and after getting new records from the server, modify this array and update `options.drilldown.series` object
```
options.drilldown.series = newSeries
``` 
, it causes the chart to be updated automatically.

**Comment by vnanaware** [comment]
Actually there is no fixed HIColumn array count ,  Its depend on server records count.

**Comment by ihnatmoisieiev** [comment]
@vnanaware I don't understand exactly what you want to get, but I propose you try

```
        var newSeries = [HIColumn]()
        for i in 0 ..< self.arrMainData.count {
            let clm = HIColumn()
            var strEmpName = ""
            
            strEmpName=self.arrEmpName_List.object(at: i) as! String
            
            clm.name="\(strEmpName)"
            clm.id="\(strEmpName)"
            
            clm.data=[["Task 1", 56.33], ["Task 2",17.2], ["Task 3", 8.11]]
            
            newSeries.append(clm)
        }
        options.drilldown.series = newSeries
```

**Comment by vnanaware** [comment]
Okay thank you. Working
