### ISSUE TITLE
missing required architecture x86_64 after carthage update to 6.0.7

### ISSUE THREAD

**Issue by merdok** [highcharts/highcharts-ios#84]
Hi,

i am using carthage to keep my external frameworks up to date, after the latest release 6.0.7 i get this error when i run carthage update and try to run my project. It was working fine on 6.0.2 release. I know that i have to use the development framework when i develop in simulator, but like noted before, it was working fine with the older release, i could do carthage update and use the framework from Carthage Build directory for both simulator and device development the without any issues...
How can i fix that?

`missing required architecture x86_64`

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_HIFunction", referenced from:
      objc-class-ref in Provider.o
  "_OBJC_CLASS_$_HIDataLabels", referenced from:`

**Comment by ihnatmoisieiev** [comment]
Hi @merdok,
thank you for the reporting. Yes, you're right. But you will have some errors with uploading your app to the App/iTunes Store later.

**Comment by merdok** [comment]
Hi @ihnatmoisieiev 
yes, i am aware of that. For my release scheme i use the the framework from the release directory and for development i use the one from the Carthage build directory. Apparently the release one is now also used in the Carthage build directory, which is a little bit inconvenient when i develop since i get this error. 

Was this an intended change from you or is it a bug? Can this be adjusted to the way it was before?

**Comment by mll** [comment]
Hi @merdok. This was a deliberate change as we believe it is more harmful to get an unexpected AppStore submission rejection than to be manually using the development framework. We are investigating what other options Carthage would allow. The Pods automatically strip when needed, but I understand you are not using Pods. You can expect a fix this week. In the meantime, just overwrite the framework with the development version in your Carthage directory.

**Comment by mll** [comment]
Hi. The issue should now be solved for 6.1.0 - you install v6.1.0d if you need to run on the simulator (and are aware that this version will not be uploadable to AppStore) or v6.1.0r if you want to release.

**Comment by merdok** [comment]
Thanks, but i am getting the following error when i try to run carthage update:
`Parse error: unexpected trailing characters in line: github "https://github.com/highcharts/highcharts-ios" >= 6.1.0d`

the same goes for the 6.1.0r version:

`Parse error: unexpected trailing characters in line: github "https://github.com/highcharts/highcharts-ios" >= 6.1.0r`

**Comment by ihnatmoisieiev** [comment]
@merdok thank you, it will be fixed soon. Release version is available via `github "https://github.com/highcharts/highcharts-ios" >= 6.1.0`

**Comment by ihnatmoisieiev** [comment]
@merdok please try last release `6.1.0`. The issue has been fixed.

**Comment by merdok** [comment]
@ihnatmoisieiev yes, the issue seems to be resolved. Just did a carthage update and it works both on the device and simulator, without any modifications. Thanks!
