### ISSUE TITLE
Can't disable animation

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#85]
In JS you can do that:

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-animation-disabled/

but in Swift you've to do that:

```
let animation = HIAnimation()
animation.duration = 0.0
plotOptions.series.animation = animation
```

and it does not work, I can see the animation :(

**Comment by AlexandreMinard** [comment]
I'm trying to disable animations because on iPad (and only on iPad) when drawing a chart outside the screen and then scroll this view to the visible part of the view makes a bug: a part of the chart is not displayed.

So I'm reloading the chart with:

```
let high = v as! HIChartView
let options = high.options
high.options = options
```

but I see the animation and it's really a bad visual effect :(

**Comment by AlexandreMinard** [comment]
I forgot to tell you that:

`chart.animation = false` does not work

```
let anim = HIAnimation()
anim.duration = 0.0
chart.animation = anim
``` 
crashed my application!!!


and
```
let anim = HIAnimation()
anim.duration = 100
chart.animation = anim
```
also crashed my application!!!

**Comment by ihnatmoisieiev** [comment]
Hello @AlexandreMinard,
your example from `jsfiddle` in `JS` works perfect and I don't have any crashes:

```
        let options = HIOptions()
        
        let xAxis = HIXAxis()
        xAxis.categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        options.xAxis = [xAxis]
        
        let plotOptions = HIPlotOptions()
        plotOptions.series = HISeries()
        let animation = HIAnimation()
        animation.duration = 0
        plotOptions.series.animation = animation
        options.plotOptions = plotOptions
        
        let series = HISeries()
        series.data = [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
        options.series = [series]
```

**Comment by ihnatmoisieiev** [comment]
@AlexandreMinard can I close it?

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev I tried this and got error in the line
            plotOptions.series.animation = animation

I want animation during the initial load and disable animation after first time load. Please let me know how to achieve this.

**Comment by ihnatmoisieiev** [comment]
Hi @arunavasumathi,
what error did you get?

You can enable the initial animation by setting an animation object in plot options:

```
let plotOptions = HIPlotOptions()
plotOptions.series = HISeries()
let animation = HIAnimationOptionsObject()
animation.duration = 1000
plotOptions.series.animation = animation
options.plotOptions = plotOptions
```

and disable other animations in your chart object:

```
let chart = HIChart()
let animation = HIAnimationOptionsObject()
animation.duration = 0
chart.animation = animation
options.chart = chart
```

**Comment by arunavasumathi** [comment]
@ihnatmoisieiev thank you.
