### ISSUE TITLE
pass a "bridged json"

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-ios#87]
Passing a question from e-mail:

> Q: We'd like to be able to pass a "bridged json" (NSDictionary of NSArrays
> of NSDictionaries....) configuration to native highcharts in the same
> format as we do currently for JS Highcharts.

If the feature is currently not available please mark this issues as a enhancement.

**Comment by ihnatmoisieiev** [comment]
This feature has been added to the newest release.
