### ISSUE TITLE
Asign options straight from Dictionary?

### ISSUE THREAD

**Issue by merdok** [highcharts/highcharts-ios#89]
Hi,

is there a possibility to just assign a dictionary with options to the chart options? I mean like in the js version where you just pass the options json to the highchart object? 

The problem is that we use highcharts on both web(JS) and iOS with the same json file. The problem on iOS is that we have to map every single property of the json(dictionary) to the native objects, which is very time consuming and not really future safe...

If such possibility is not yet available, can this be added?

**Comment by ihnatmoisieiev** [comment]
Hi @merdok, 
it is connected with [https://github.com/highcharts/highcharts-ios/issues/87](https://github.com/highcharts/highcharts-ios/issues/87). I guess this feature will be added.

**Comment by merdok** [comment]
Yes, this seems to be the same feature request. Would be great if this could be added. Thanks!

**Comment by ihnatmoisieiev** [comment]
@merdok this feature has been added to the newest release. Can I close this issue?

**Comment by merdok** [comment]
Thanks!
I suppose the method name is `loadJSONOptions`? Can you explain how it works? 
Right now when i pass my NSDictionary with the options as a parameter the options will stay `nil` without any errors. Maybe a simple error Information would be good, like what went wrong?

**Comment by merdok** [comment]
@ihnatmoisieiev 
Okay now i understand it. The `chartView.options` will stay nil but the chart will load anyway. Is that the correct behaviour? 
I was expecting that after i run `loadJSONOptions` the options of the chart view will be filled so i can modify them.

**Comment by ihnatmoisieiev** [comment]
@merdok, yes, it is correct behavior. 
Unfortunately, you can't modify the chart's options after loading from the dictionary. You can modify the input dictionary.

**Comment by merdok** [comment]
Ok, but that is fine!
Thanks!

**Comment by Mehul18292** [comment]
@ihnatmoisieiev I have added options as you provided, but how to define chart type in this case?

**Comment by ihnatmoisieiev** [comment]
@Mehul18292 just add `chart` object with `type` to your init dictionary if you want to set a default chart type: 

```
"chart": [
   "type": "line"
],
```

You can find more info [here](https://www.highcharts.com/docs/chart-and-series-types/chart-types).
