### ISSUE TITLE
Events...

### ISSUE THREAD

**Issue by AlexandreMinard** [highcharts/highcharts-ios#9]
Hi,

I don't understand how to use events to catch when the user clicks on my charts.
Could someone help me please?

Thanks in advance.

Regards,
Alexandre

**Comment by ratka6** [comment]
Thanks for the feedback. For now the only events we support are: 
- hamburger tap - this opens exporting options
- credits tap - you can set any url there to open in external browser
- internal taps - basically these are handled by our wrapper to show some more info - you can set them by using HIToolbar object

**Comment by AlexandreMinard** [comment]
Thanks for your answer.
You certainly mean HITooltip and not HIToolbar.

So, I can't be notified when a user clicks on a slice on my pie chart?

**Comment by ratka6** [comment]
Unfortunately no. It is a wrapper for JS charts, so everything is done "behind the scenes".

**Comment by AlexandreMinard** [comment]
OK thanks for the answer again.
Any plan to provide such feature?

**Comment by ratka6** [comment]
I am not aware of any plans for that, but I can't say for sure.

**Comment by KacperMadej** [comment]
@ratka6 If point click event function is not available, then API seems to be a bit misleading in case of point click and other events - http://api.highcharts.com/highcharts-ios/plotOptions.pie.point.events.click Is this click event function available?

**Comment by ratka6** [comment]
All Function types are currently not available. We are working on them

**Comment by mll** [comment]
The functions are now enabled in v 1.1.0

**Comment by kutran** [comment]
Is there an example for this?  I would like to see if I can get onClick() events in HiCharts across Swift.  Thank you.
