### ISSUE TITLE
Problem with chart auto update on options change

### ISSUE THREAD

**Issue by merdok** [highcharts/highcharts-ios#90]
Hi,

i noticed the following problem with the latest update. In our app we have a collection of small chart views which a user can expand to full screen on demand. When the user does that i use the chart options from the small chart and pass it over to the full screen chart view to render it, i also need to change the height property of the chart options so that it grows to full screen. Now comes the problem, since the options is just a reference also the small chart view gets updated with the chart height which was only to be meant for the full screen chart, and after i close the full screen chart my small chart also has the bigger height which is wrong. 

Would it somehow be possible to copy the HiOptions object? Or maybe as an alternative disable the auto update on options change and only update the chart on demand?

**Comment by ihnatmoisieiev** [comment]
Hi @merdok,
thank you for the reporting. Copy feature will be added to the next release. 
 
You can create new `HIOptions` object with the same params as for the previous object to solve this problem at the moment.

**Comment by ihnatmoisieiev** [comment]
@merdok this feature has been added to the newest release. Can I close this issue?

**Comment by merdok** [comment]
Copy works perfect! Thanks!
