### ISSUE TITLE
HITooltip hideDelay not working, or: how to hide a tooltip after x seconds?

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#97]
```
    HITooltip *tooltip = [[HITooltip alloc]init];
    tooltip.hideDelay=@2000;
```

does not seem to have any effect. Tooltips do not auto-hide. Can you post a working example? Thanks.

**Comment by ihnatmoisieiev** [comment]
Hello @skuske,
thank you for your question. 
According to the documentation `hideDelay is the number of milliseconds to wait until the tooltip is hidden when mouse out from a point or chart`. So, that is why it's not working. 

But you can simulate this behavior by e.g. 
```
plotOptions.series.point.events.click = [[HIFunction alloc] initWithJSFunction:@"function() { this.series.chart.tooltip.hide(2000); }"];
```

**Comment by skuske** [comment]
So, `hideDelay` not applies to touches by a finger, right? It applies to a mouse event only?

**Comment by ihnatmoisieiev** [comment]
@skuske yes, it applies only to a mouse event.

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thank you. How can I make the tooltip to auto-hide after 2000ms on touch devices?

Your suggestion:

```
    HIPlotOptions *plotOptions = [[HIPlotOptions alloc] init];
    plotOptions.series.point.events.click = [[HIFunction alloc] initWithJSFunction:@"function() { this.series.chart.tooltip.hide(2000); }"];
    options.plotOptions=plotOptions;
```

does not work on iOS. The tooltip does not auto-hide.

**Comment by ihnatmoisieiev** [comment]
Try:
```
HIPlotOptions *plotOptions = [[HIPlotOptions alloc] init];
plotOptions.series = [[HISeries alloc] init];
plotOptions.series.point = [[HIPoint alloc] init];
plotOptions.series.point.events = [[HIEvents alloc] init];
plotOptions.series.point.events.click = [[HIFunction alloc] initWithJSFunction:@"function() { this.series.chart.tooltip.hide(0); }"];
options.plotOptions = plotOptions;
```
It's working only by tapping in the point.

**Comment by skuske** [comment]
@ihnatmoisieiev 

No luck. That doesn't work either... :o(

**Comment by ihnatmoisieiev** [comment]
![hidetooltip](https://user-images.githubusercontent.com/11294008/40293514-9400fd5a-5cd1-11e8-9839-aa614e3039ac.gif)

**Comment by skuske** [comment]
@ihnatmoisieiev 

OK, I now understand. But: my intention was to let the tooltip auto hide once touch events have ended, i.e. once the finger has been moved out of the chart. I do not understand the purpose of a 'mouse click only event' on touch devices... Makes no sense at all as there is no mouse available on touch devices.

How can I make the tooltip auto hide once the finger ended a touch, or once a finger moved out of a chart?

**Comment by ihnatmoisieiev** [comment]
@skuske, yes, you are right. There is no mouse on touch devices.
You can simulate it by adding the same click event for all touch objects to hide the tooltip, e.g.

```
chart.events = [[HIEvents alloc] init];
chart.events.click = [[HIFunction alloc] initWithJSFunction:@"function() { this.series[0].chart.tooltip.hide(0); }"];
```

**Comment by skuske** [comment]
@ihnatmoisieiev 

Thanks. I'll try that asap.

**Comment by skuske** [comment]
@ihnatmoisieiev 

I tried that, but the tooltip still does not auto hide.

**Comment by skuske** [comment]
@ihnatmoisieiev 

I am 're-opening' this issue again as I still have not found any way to auto-hide a tooltip after a given time. What I want to achieve is:

The user touches a chart, and the chart displays a tooltip, just as it should. I then want the tooltip to hide itself _after X seconds_. **All** the above code samples do **NOT** work.

Is there any tested and working sample code? Thanks.

**Comment by ihnatmoisieiev** [comment]
@skuske 

we have found a solution. Please try

```
let chart = HIChart()
chart.events = HIEvents()
chart.events.load = HIFunction(jsFunction: "function () { var chart = this; Highcharts.addEvent(this.tooltip, 'refresh', function () { chart.tooltip.hide(X); }); }")
options.chart = chart
```
Just replace hiding time `X` to your own in milliseconds. 

We hope it will work for you.

**Comment by skuske** [comment]
@ihnatmoisieiev 

COOL! Many, many thanks! That works just brilliant! :o)

**Comment by AAChartModel** [comment]
@ihnatmoisieiev how to hide the crosshair after x seconds
