### ISSUE TITLE
HIXAxis glich the text UI

### ISSUE THREAD

**Issue by vnanaware** [highcharts/highcharts-ios#99]
![simulator screen shot - iphone 6s - 2018-05-23 at 17 43 05](https://user-images.githubusercontent.com/16416191/40423812-4c0b190e-5eb1-11e8-810c-f10e157504b9.png)

**Comment by vnanaware** [comment]
In Above screenshot HIXAxis Bottom bar title glich the UI 
is there any solution for this?

**Comment by ihnatmoisieiev** [comment]
@vnanaware try to change font size:
```
xAxis.labels = HILabels()
xAxis.labels.style = HIStyle()
xAxis.labels.style.fontSize = "10px"
```

**Comment by vnanaware** [comment]
added font but my text too much longs so they are mixing each other, How to resolve this?

**Comment by ihnatmoisieiev** [comment]
Using `formatter`:

```
xAxis.labels = HILabels()
xAxis.labels.formatter = HIFunction(jsFunction: "function(){ if (this.value.length > 10) { return this.value.substr(0,10) + '...'; } else { return this.value; } }")
```

**Comment by vnanaware** [comment]
Okay thanks its worked..
